### ISSUE TITLE
The server should not allow you to delete a non-existent collection, instead an HTTP error should be returned

### ISSUE THREAD

**Issue by illagrenan** [qdrant/qdrant#100]
I think the server should be stricter to the client and an attempt to delete a non-existent collection should return an error (preferably error 404).

This is related to https://github.com/qdrant/qdrant/issues/99

```
> POST /collections HTTP/2
> Host: ***
> content-type: application/json
> accept: */*
> content-length: 54
| {
|     "delete_collection": "non_existent_collection"
| }


< HTTP/2 200 
< date: Fri, 24 Sep 2021 11:05:15 GMT
< content-type: application/json
< content-length: 46
```

**Comment by generall** [comment]
Qdrant follows the idempotency property - meaning that executing same request multiple times will result in exactly the same result as executing it once. Having this idea I would like to preserve the current behavior of remove method - so that removing collection twice won't create an error report.
