### ISSUE TITLE
Allow to perform exact search even if vector index is built

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1042]
**Is your feature request related to a problem? Please describe.**
Currently, if vector index is build, it is not possible to disable approximate search, 
but it might be useful to have this option to tune the accuracy of ANN search.

**Describe the solution you'd like**
Add `exact` flag to the `SearchParams` which is false by default

**Comment by orion512** [comment]
This would be very useful

**Comment by agourlay** [comment]
shipped in [0.11.0](https://github.com/qdrant/qdrant/releases/tag/v0.11.0)
