### ISSUE TITLE
Allow reindex current vectors and change some collections parameters (hnsw parameters for example)

### ISSUE THREAD

**Issue by raulcarlomagno** [qdrant/qdrant#1044]
**Is your feature request related to a problem? Please describe.**
when i create my collection i set indexing_threshold to a high value so it does not index while uploadin, after uploading i set it for example to 5000 and it starts indexing, until here everything is ok
but, i would like to tune some hnsw parameters , so as upload records process takes approximately 4 hours, i would like to reindex vectors with the previous uploaded data

**Describe the solution you'd like**
as collection optimizer parameters can be changed on the fly. it would be good to modify hnsw parameters as well and be able to reindex vectors. For example to test m and ef_construct with different values but avoid uploading data again

**Comment by guxingke** [comment]
> to test m and ef_construct with different values but avoid uploading data again

This feature is required for testing before going online , can provide some way to get there ?

**Comment by IvanPleshkov** [comment]
Fixed in `v1.4.x`. Now it's possible to change hnsw params and trigger reindexing. Look at an example on bulk upload with example of changing parameters request
https://qdrant.tech/documentation/tutorials/bulk-upload/

**Comment by timvisee** [comment]
This section in the documentation shows more clearly how to update HNSW/quantization parameters: https://qdrant.tech/documentation/concepts/collections/#update-collection-parameters
