### ISSUE TITLE
Allow optional vectors when using named vectors

### ISSUE THREAD

**Issue by raulcarlomagno** [qdrant/qdrant#1045]
**Is your feature request related to a problem? Please describe.**
Suppose i have configured a collection with 2 named vectors. When uploading points, not all my points contain both vectors, some of them contain just one. Right now, qdrant complains about point not having both vectors when adding points. I tried sending None as well

**Describe the solution you'd like**
It would be good to be able to add points with optional named vectors

![image](https://user-images.githubusercontent.com/2282315/191748950-4b95f854-91cd-4d8d-ac18-6e3799381322.png)

**Comment by findmyway** [comment]
This requirement is quite common in real-world projects. The only workaround I can think of is just as mentioned in #1132

> For now we re-create a new collection, but this duplicated the payload of our entities by the number of vector type we have.

I'm wondering that is it possible to be supported in the near future?

**Comment by MrBeeMovie** [comment]
> This requirement is quite common in real-world projects. The only workaround I can think of is just as mentioned in #1132
> 
> > For now we re-create a new collection, but this duplicated the payload of our entities by the number of vector type we have.
> 
> I'm wondering that is it possible to be supported in the near future?

I second this. Would be extremely useful.

**Comment by HridayM25** [comment]
Hi! 
Can I try to work on this?

**Comment by msayan-vcbs** [comment]
Hey, I also have a need for this. Not all my entities have the data for vectors and it makes testing different model variations a bit difficult.

**Comment by timvisee** [comment]
Good news! I've started work on implementing this.

**Comment by generall** [comment]
released in https://github.com/qdrant/qdrant/releases/tag/v1.2.0
