### ISSUE TITLE
Support Object Storage such as s3

### ISSUE THREAD

**Issue by Michael-Jing** [qdrant/qdrant#1060]
**Is your feature request related to a problem? Please describe.**
I'm considering have a qudrant deployment on k8s, I not sure whether persistent volume is safe to use, so I think object storage support might be good to have.

**Describe the solution you'd like**
support store persistent data on external object storage system such as s3.
**Describe alternatives you've considered**
no
**Additional context**
no

**Comment by generall** [comment]
Hi @Michael-Jing, it is theoretically possible to mount S3 as a File System, we do not recommend to do it for a primary storage, only for the snapshot directory. There are many scenarios where using s3 as a primary storage could seriously impact the performance on the engine

**Comment by generall** [comment]
I am closing this issue for now, please feel free to open it back again if you have any suggestions of how s3 could be used to improve qdrant workflow
