### ISSUE TITLE
Search results are not ordered, the order is random(?)

### ISSUE THREAD

**Issue by dluc** [qdrant/qdrant#1077]
Search results are returned in random order. Am I missing something in the request or is it a bug?

Request:
```
POST collections/testcollection/points/search
```
```json
{
    "vector": [ 0.0, 5.5, 1.1, 2.2, 3.3 ],
    "limit": 0,
    "offset": 0,
    "with_payload": false,
    "with_vector": true
}
```

Response:
```json
{
    "result": [
        {
            "id": "61aaced9-e942-4211-a4ee-c57683492395",
            "version": 5,
            "score": 0.8274851,
            "payload": null,
            "vector": [ 0.21621937, 0.9729871, 0.021621937, 0.043243874, 0.06486581 ]
        },
        {
            "id": "d09e0808-f824-4aa5-83fd-037f47361f21",
            "version": 3,
            "score": 0.99999994,
            "payload": null,
            "vector": [ 0.0, 0.80064076, 0.16012816, 0.32025632, 0.48038447 ]
        },
        {
            "id": "e33d6be1-b3ec-4d73-a224-b9a2bdb5c833",
            "version": 4,
            "score": 0.98957,
            "payload": null,
            "vector": [ 0.14405274, 0.7922901, 0.15845802, 0.31691605, 0.47537404 ]
        }
    ],
    "status": "ok",
    "time": 0.000213675
}
```

Scores are correct, but records are randomly ordered. The order also changes with no reason when tweaking with_vector, with_payload, filter, etc.

Versions tested: 
* qdrant/qdrant:latest, id 804209bc1310, Sept 19
* qdrant/qdrant:dev, id afbf73b83458, Sept 29 (today)

**Comment by dluc** [comment]
Given that the order is incorrect, I don't even know if I can trust the `limit` parameter to return the closest vectors, or N random vectors.

**Comment by agourlay** [comment]
Hi @dluc 

did you observe this on a distributed deployment or on a single node?

**Comment by agourlay** [comment]
Thank you for the report, I was actually able to reproduce the issue on a single node deployment.

The issue appears when `limit` is set to 0. You could try using a high value as a workaround for the time being.

**Comment by agourlay** [comment]
After internal discussions we have decided to not enable users to fetch the entire result data set using `limit=0`.

First this feature is not properly documented and definitely looks like a bug.

Secondly, it represents a danger for the qdrant API and for downstream consumers to retrieve very large result sets all at once.

The proposed [fix](https://github.com/qdrant/qdrant/pull/1083) is to always return an empty result sets when the limit parameter is equal to zero.

In general, it is a good practice to use the [pagination API](https://qdrant.tech/documentation/search/#pagination) to iteratively traverse the results.

Thanks again for bringing up this issue!
