### ISSUE TITLE
Search endpoint with filters returns values outside the filter

### ISSUE THREAD

**Issue by sebastian-montero** [qdrant/qdrant#1086]
## Current Behavior
When I submit a query to the search endpoint with filters, the query returns the ranked search results but does not consider the filtering criteria.

## Steps to Reproduce
1. Create a collection
```
curl -X 'PUT' \
  'http://localhost:6333/collections/profiles_db' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "profiles_db",
    "vectors": {
      "size": 768,
      "distance": "Cosine"
    }
}'
```
2. Create an index
```
curl -X 'PUT' \
  'http://localhost:6333/collections/profiles_db/index' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "field_name": "customer_id",
    "field_schema": "keyword"
}'
```
3. Ingest data (ingesting individual points with a `for loop` in Python and the variables `profile_id`, `customer_id` and `profile_vector`)
```
url = 'http://localhost:6333/collections/profiles_db/points?wait=true'
headers = {"accept":"application/json","Content-Type":"application/json"}
data = {
    'points': [
        {
            "id": profile_id,
            "payload": {
                "customer_id": customer_id
                        },
            "vector": profile_vector
        }
    ]
}

        r = requests.put(url, data = json.dumps(data), headers=headers)
```

4. Submit search request
```
curl -X 'POST' \
  'http://localhost:6333/collections/profiles_db/points/search' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
        "filters":{
            "must" : [
                { "key": "customer_id", "match": { "value": value } }
            ]
        },
        "vector": [1,2,3,4,5,6],
        "limit": 5,
        "with_payload": true,
        "with_vector": false
  }'
```
## Expected Behavior
Return search results that contain values that match the filter parameters.

## Possible Solution
Not applicable

## Context (Environment)
We are testing Qdrant under the scenario of having different customers under the same vector database. During search, want to surface points for individual customers instead of points for all customers. 

## Detailed Description
Not applicable 

## Possible Implementation
Not applicable

**Comment by azayarni** [comment]
Please make sure to use "filter" instead of "filters".
```
        "filter":{
            "must" : [
                { "key": "customer_id", "match": { "value": value } }
            ]
        },
```

**Comment by sebastian-montero** [comment]
Thank you @azayarni. This has solved the issue. It was an error from my side.
