### ISSUE TITLE
Search endpoint returns vector of Null as first matches

### ISSUE THREAD

**Issue by sebastian-montero** [qdrant/qdrant#1087]
## Current Behavior
Points will all `zero` elements will default to a vector with all `null` elements. When performing a search, these vectors will surface as the top matches with a `null` value in the `score` field.

## Steps to Reproduce
1. Create a collection with vectors of size N
2. Insert points with vectors of size N with all 0 elements
3. Insert points with vectors of size N with non-zero elements
4. Run a vector search query

## Expected Behavior
Expected behaviour is to surface the closest points in the vector space instead of the `null` vectors. 

## Possible Solution
Filter out vectors whose sum equals 0

## Context (Environment)
I am creating vectors from role titles. Sometimes role titles can't be vectorised due to the language, misspelling, unseen tokens, etc. So we default the vectors to size N with all zero elements. 

## Detailed Description
Update how the search endpoint returns results

## Possible Implementation
Not applicable

**Comment by generall** [comment]
Hi @sebastian-montero, if you are using Cosine distance, it is impossible to normalize 0 vector. Please consider using Dot product as a distance measure if you really need to store vectors with all zeros.

**Comment by sebastian-montero** [comment]
Thank you @generall
