### ISSUE TITLE
Cosine score `1.0000001`

### ISSUE THREAD

**Issue by dluc** [qdrant/qdrant#1100]
Cosine similarity for this vector to itself returns `"score": 1.0000001`. Probably just a rounding error.

attachment: [vector.txt](https://github.com/qdrant/qdrant/files/9710941/vector.txt)

**Comment by generall** [comment]
https://0.30000000000000004.com/

**Comment by raulcarlomagno** [comment]
i detected it sometimes, so just in case, i do this after retrieving 
scores= np.clip(scores, .0, 1.)
