### ISSUE TITLE
[replication] Start a sync again if peer detects that a shard was deactivated

### ISSUE THREAD

**Issue by e-ivkov** [qdrant/qdrant#1128]
When a shard on a peer is deactivated - it means there were replication failures. In that case a peer:

1. Gets recent updates from consensus
2. Detects that a shard on it is deactivated
3. Requests a new sync from another peer (we need an API for this)
4. Peer 2 starts transfer with `StartTransfer {sync: true}`
5. ... Follows as in replication add new peer scenario

**Comment by agourlay** [comment]
Closing due to https://github.com/qdrant/qdrant/pull/1145.
Feel free to reopen if there is actually more to do.

**Comment by e-ivkov** [comment]
Yes, should be completed I think
