### ISSUE TITLE
[feature request]sparse vectors support

### ISSUE THREAD

**Issue by HaveF** [qdrant/qdrant#1135]
**Is your feature request related to a problem? Please describe.**
When I create some points or search point by hand. It looks a little clumsy when the vector contains lots of zero.
like:
```
"vector": [0.9, 0.1, 0.1, ... (200 zeros)..., 0.3]
```

**Describe the solution you'd like**
I have no idea what is the best solution to describe sparse vector.
I have one:
```
"vector": [(0, 0.9), (1, 0.1), (2, 0.1), (203, 0.3)]

or

"vectors": [
    [(0, 0.9), (1, 0.1), (2, 0.1), (203, 0.3)],
    [(0, 0.9), (2, 0.1), (203, 0)],  // if right padding are all 0, just write the last index, and zero
    [(2, 0.1), (203, 0.9)]
]
``` 

**Describe alternatives you've considered**
Use another field to describe is also works. But I suppose the solution above seems has more consistency.

**Additional context**

**Comment by generall** [comment]
Hi @HaveF, could you please elaborate on the use-case where you need to create vectors like this?

**Comment by HaveF** [comment]
Hi, @generall thanks for your reply!

I'm not sure if I can make it clear. Like [the use case you listed](https://qdrant.tech/use-cases/)

Medical Diagnostics, but search **only** by symptoms:

If we have a patient database, have some symptoms features(like 600), and related successful treatment.
We just simply quantify the symptoms to 4 level, like 0, 0.25, 0.5, 1, and successful treatment as vector's payload.

When new patient comes, we can quickly examine the most obvious symptoms(like 10 symptoms), and want to get the possible treatments. We can use the current vector format,  `"vector": [0, 0.25, 0.5, ... (595 zeros)..., 1]`, but it is hard to read, debug and transport. If we have sparse vector format, that would be better.

In most case, the vector is created by other program(like NLP's token, CV's feature), but in some case, we may try to create vector by hands, and want more readability.

**Comment by generall** [comment]
It seems to me that this view of the vectors could be easily done on the client side.

**Comment by HaveF** [comment]
ok, that's fine
Thanks for your input 🤝
