### ISSUE TITLE
Track performance to detect potential regressions

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#1167]
**Is your feature request related to a problem? Please describe.**
When a PR is merged, it is unclear how it affects the existing performance characteristics of the system.  

**Describe the solution you'd like**
Automatically run benchmarks on all PRs. 

This could be achieved with https://github.com/benchmark-action/github-action-benchmark

It supports Rust with `criterion.rs` for benchmarks https://github.com/benchmark-action/github-action-benchmark/blob/master/.github/workflows/criterion-rs.yml

Additionally its track performance over time by hosting previous runs in a dedicated repo. which can be configured to serve the results statically.

https://github.com/benchmark-action/github-action-benchmark#charts-on-github-pages

**Comment by llogiq** [comment]
On CI, criterion is a mixed bag, because you can never know how much compute you actually get at any given moment. That said, [iai](https://github.com/bheisler/iai) is a good replacement in this case, and I've used it for benchmarks in CI before with good success.
