### ISSUE TITLE
Optimize memory consumption of SimpleIdTracker

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1175]
**Is your feature request related to a problem? Please describe.**
It is suspected that SimpleIdTracker uses too much memory.

**Describe the solution you'd like**
SimpleIdTracker uses HashMaps and it looks like in some cases it might be more optimal to switch to Vec

**Describe alternatives you've considered**
Do not store ID mapping and versioning in RAM (need to measure potential perf. impact)

**Additional context**
```
With top I got 2GB ram usage. Almost all data used by segment - 1.9GB. List of segment parts with estimated ram usage:
* RocksDB doesn’t use a lot of ram. About 10MB per column family for parsing data while segment loading.
* Simple vector storage as expected, 730MB
* HNSW 630MB
* SimplePayloadStorage uses more than 120MB for containing empty payloads. That’s unexpected for a single hashmap
* SimpleIdTracker uses almost 400MB. That’s unexpected too, SimpleIdTracker contains only 3 maps
```

**Comment by IvanPleshkov** [comment]
Done in https://github.com/qdrant/qdrant/pull/1176
