### ISSUE TITLE
Validate that vector is non-zeroed in case of cosine 

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1195]
**Is your feature request related to a problem? Please describe.**
Cosine distance can not be computed with vectors of all zeros. 

**Describe the solution you'd like**
Make validation before inserting vector, return 400 in case of zero vector

**Describe alternatives you've considered**
Skip normalization and store vector as-is, in this case if will have 0 score with all other vectors

**Comment by agourlay** [comment]
Alternative solution implemented in https://github.com/qdrant/qdrant/releases/tag/v0.11.2
