### ISSUE TITLE
Running on Windows - issue with WAL

### ISSUE THREAD

**Issue by dluc** [qdrant/qdrant#1220]
I built the latest code from the main branch, for Windows, the service starts correctly with the default configuration from the repo, but the service is throwing errors.

## Current Behavior
API call fails.

## Steps to Reproduce
1. build on Windows 11, target release
2. copy exe and config folder to an installation path
3. run as admin (or not, no difference)
4. try to create a collection using PUT

## Expected Behavior
The collection should be created and the HTTP API should return success

## Detailed Description

<img width="790" alt="image" src="https://user-images.githubusercontent.com/371009/202108672-5c9ee79d-18f3-438b-ac99-62e80945f1bb.png">

Notice this line:

```
[2022-11-16T06:52:48.630Z WARN  qdrant::actix::helpers] error processing request: ServiceError { description: "Can't init WAL: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }" }
```

which I think is the cause of the 500 error in the following line

```
[2022-11-16T06:52:48.630Z INFO  actix_web::middleware::logger] 127.0.0.1 "PUT /collections/demo?wait=true HTTP/1.1" 500 164 "-" "-" 0.203398
```

Note: the same client code works fine when running qdrant via a docker image.

**Comment by dluc** [comment]
Test with 0.11.3

Folders:
```
├───config
├───snapshots
│   └───testcollection
└───storage
    ├───aliases
    └───collections
        └───testcollection
            └───0
                ├───segments
                │   ├───9f123455-c8fc-4aea-a628-2741152a385a
                │   │   └───payload_index
                │   └───d52686df-d008-4edc-8d50-c279c781da05
                │       └───payload_index
                └───wal
```

Error on collection creation:
```
[2022-11-16T09:01:42.990Z WARN  qdrant::actix::helpers] error processing request: ServiceError { description: "Can't init WAL: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }" }
```

```
PUT http://127.0.0.1:6333/collections/testcollection

{
  "vectors": {
    "size": 5,
    "distance": "Cosine"
  }
}
```
```
{
    "result": null,
    "status": {
        "error": "Service internal error: Can't init WAL: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }"
    },
    "time": 0.2035886
}
```

**Comment by lyolik1234** [comment]
Version 0.11.6 has the same problem:
![image](https://user-images.githubusercontent.com/122362585/211540306-5c80df14-48ff-4488-b59e-e7517481affb.png)

**Comment by lyolik1234** [comment]
No.
I compiled under Windows.

**Comment by generall** [comment]
it looks like windows doesn't support some file locking features used in WAL implementation. 
@lyolik1234 could you please try to run `cargo test --all` in the https://github.com/qdrant/wal repo.

**Comment by lyolik1234** [comment]
![image](https://user-images.githubusercontent.com/122362585/211565242-04172657-2a13-44f8-8b04-0f3f42e48f76.png)

**Comment by lyolik1234** [comment]
Finished test [unoptimized + debuginfo] target(s) in 3m 18s
warning: the following packages contain code that will be rejected by a future version of Rust: winapi v0.2.8
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running unittests src\lib.rs (target\debug\deps\wal-15ac3b9ad9c81b28.exe)

running 23 tests
test segment::test::test_create_dir_path ... ok
test segment::test::test_entries ... ok
test segment::test::test_open ... ok
test segment::test::test_open_nonexistent ... ok
test segment::test::test_overwrite ... ok
test segment::test::test_pad_len ... ok
test test::check_clear ... FAILED
test test::check_last_index ... FAILED
test test::check_prefix_truncate ... FAILED
test test::check_reopen ... FAILED
test test::check_truncate ... FAILED
test test::check_wal ... FAILED
test test::test_append ... FAILED
test test::test_exclusive_lock ... FAILED
test test::test_offset_after_open ... FAILED
test test::test_record_id_preserving ... FAILED
test test::test_segment_creator ... FAILED
test test::test_truncate ... FAILED
test test::test_truncate_flush ... FAILED
test test_utils::test::entry_generator_distribution ... ok
test test_utils::test::entry_generator_size ... ok
test test_utils::test::test_seed ... ok
test segment::test::test_append ... ok

failures:

---- test::check_clear stdout ----
thread 'test::check_clear' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:694:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test::check_clear' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:694:14
thread 'test::check_clear' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (0)
Error: "called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }"', C:\Users\owner\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-1.0.3\src\tester.rs:165:28

---- test::check_last_index stdout ----
thread 'test::check_last_index' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:660:14
thread 'test::check_last_index' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:660:14
thread 'test::check_last_index' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (0)
Error: "called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }"', C:\Users\owner\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-1.0.3\src\tester.rs:165:28

---- test::check_prefix_truncate stdout ----
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:831:14
thread 'test::check_prefix_truncate' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (0, 0)
Error: "called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }"', C:\Users\owner\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-1.0.3\src\tester.rs:165:28

---- test::check_reopen stdout ----
thread 'test::check_reopen' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:728:18
thread 'test::check_reopen' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:728:18
thread 'test::check_reopen' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (0)
Error: "called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }"', C:\Users\owner\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-1.0.3\src\tester.rs:165:28

---- test::check_truncate stdout ----
thread 'test::check_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:783:14
thread 'test::check_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:783:14
thread 'test::check_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:783:14
thread 'test::check_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:783:14
thread 'test::check_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:783:14
thread 'test::check_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:783:14
thread 'test::check_truncate' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (0, 0)
Error: "called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }"', C:\Users\owner\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-1.0.3\src\tester.rs:165:28

---- test::check_wal stdout ----
thread 'test::check_wal' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:625:14
thread 'test::check_wal' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:625:14
thread 'test::check_wal' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (0)
Error: "called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: \"Access is denied.\" }"', C:\Users\owner\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-1.0.3\src\tester.rs:165:28                                                                                                                                                                                              15:11                                                                                                                                                                                                                   ---- test::test_append stdout ----                                                                                                                                                                                 thread 'test::test_append' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:853:45                                                                                                                                                                                                                                                         ---- test::test_exclusive_lock stdout ----                                                                                                                                                                         thread 'test::test_exclusive_lock' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:1007:41                                                                                                                                                                                                                                                ---- test::test_offset_after_open stdout ----                                                                                                                                                                      thread 'test::test_offset_after_open' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:1080:67                                                                                                                                                                                                                                             ---- test::test_record_id_preserving stdout ----                                                                                                                                                                   thread 'test::test_record_id_preserving' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:1042:63                                                                                                                                                                                                                                          ---- test::test_segment_creator stdout ----                                                                                                                                                                        thread 'test::test_segment_creator' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:1028:42                                                                                                                                                                                                                                               ---- test::test_truncate stdout ----                                                                                                                                                                               thread 'test::test_truncate' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:873:10                                                                                                                                                                                                                                                       ---- test::test_truncate_flush stdout ----                                                                                                                                                                         thread 'test::test_truncate_flush' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\lib.rs:906:10                                                                                                                                                                                                                                                 
failures:                                                                                                                                                                                                              test::check_clear                                                                                                                                                                                                  test::check_last_index                                                                                                                                                                                             test::check_prefix_truncate                                                                                                                                                                                        test::check_reopen                                                                                                                                                                                                 test::check_truncate                                                                                                                                                                                               test::check_wal                                                                                                                                                                                                    test::test_append                                                                                                                                                                                                  test::test_exclusive_lock                                                                                                                                                                                          test::test_offset_after_open                                                                                                                                                                                       test::test_record_id_preserving                                                                                                                                                                                    test::test_segment_creator                                                                                                                                                                                         test::test_truncate                                                                                                                                                                                                test::test_truncate_flush                                                                                                                                                                                                                                                                                                                                                                                                         test result: FAILED. 10 passed; 13 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.36s                                                                                                                                                                                                                                                                                                                                   error: test failed, to rerun pass `--lib`

**Comment by lyolik1234** [comment]
Is the output text readable?
Or send it in some other way?

**Comment by generall** [comment]
> Is the output text readable? Or send it in some other way?

it is ok, seems like the WAL is not compatible with windows.

**Comment by generall** [comment]
Looking into it https://github.com/qdrant/wal/pull/39

**Comment by generall** [comment]
Idk, there is a strange behavior on the file removal on windows, which I can't efficiently debug without windows machine. @lyolik1234 could please try to look into it?

**Comment by generall** [comment]
Fixed with https://github.com/qdrant/qdrant/releases/tag/v1.0.0
