### ISSUE TITLE
Check endianness of user machine

### ISSUE THREAD

**Issue by IvanPleshkov** [qdrant/qdrant#1231]
Mmap for vector data doesn't check big-endian or little-endian for `f32`.  It may be a problem when the user takes a snapshot and uses it on a machine with different endianness. Need to add some flags of endianness to mmap vector data and check it while vector storage initialization. When fails, do convert or just report an error.
Also, it would be nice to add the endianness of the machine to the telemetry output.

**Comment by jofas** [comment]
Hi @IvanPleshkov,

I'd like to give this a try! Would be my first contribution to qdrant though, so would you or someone else from the core team be willing to provide mentorship in case I get stuck?

Rust provides a conditional compilation configuration option for checking the endianness of the target cpu [`target_endian`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_endian) that should probably be enough. Adding a field storing the endianness of the snapshot and match it to the endianness of the cpu at load time would enable us to convert or throw an error, I assume.

**Comment by IvanPleshkov** [comment]
Hi @jofas,
Thanks for being interested in Qdrant! Our team decided to skip this issue because of low priority. Try to look to another task. For instance, this task may be better for implementing https://github.com/qdrant/qdrant/issues/159
