### ISSUE TITLE
Allow multiple instances of the same vector per point.

### ISSUE THREAD

**Issue by Clockwork-Muse** [qdrant/qdrant#1251]
**Is your feature request related to a problem? Please describe.**
When building applications like image similarity search, it can be useful to search against multiple different instances of the same vector, that all link to the same payload.

**Describe the solution you'd like**
Instead of needing to upload different points with the same payload, or the point with multiple named vectors (which would currently require require defining all the views up front), add the ability to add multiple different versions of the same vector to search.  For example, being able to upload a point with something similar to this data:
```bash
PUT /collections/{collection_name}/points

{
    "points": [
        {
            "id": "5c56c793-69f3-4fbf-87e6-c4bf54c28c26",
            "payload": {"color": "red"},
            "some_vector": {
                "dark_red": [0.9, 0.1, 0.1],
                "light_red": [0.7, 0.1, 0.1]
            }
        }
    ]
}
```
The intention here is that searching is still performed as it is currently (and would return the same results):
```bash
POST /collections/{collection_name}/points/search

{
    "vector": {
        "name": "some_vector",
        "vector": [0.8, 0.1, 0.1]
    },
    "limit": 3
}
```

Note that the desired solution is inherently "jagged", in that no two points may have the same number of vector instances, and additionally that each vector instance would  be updateable independently.

**Describe alternatives you've considered**
Currently, the only way to approach this sort of feature is to upload points with duplicated payloads.  This is undesirable for two reasons:
 - If a payload needs to be updated, it must be updated for every point.  This immediately introduces a race condition against new points being added.
   - Alternatively, storing only an id for the payload and retrieving the payload from an external source means additional required infrastructure, and foregoing the ability to filter based on the payload from inside qdrant.
 - If there are multiple named vectors for the same payload data, updating one of the dimensions requires updating all the points, which is slow (and runs the same race condition concern).

**Comment by generall** [comment]
This is either group-by or optional vectors. Implemented in https://github.com/qdrant/qdrant/releases/tag/v1.2.0

(group-by lookup might be also related, but this is WIP)

**Comment by generall** [comment]
@Clockwork-Muse could you please maybe give more extensive example?

**Comment by Clockwork-Muse** [comment]
My real-world use for this is for image-similarity-search for searching for objects.  We have an undefined count of multiple images of the same object, from different angles (and possibly in different lighting conditions).  When we were doing this, we were storing things like item description and upc in the payload, which had to be duplicated for each image.

Obviously, group-by would allow us to (more easily) retrieve a single instance per upc, but the payloads would still have to be duplicated, which we were hoping to avoid.
Optional vectors would not be very helpful, since we have to search over every "column" essentially (ie, if there were "front view", "back view" vectors).

What I'm wanting here is a way to register multiple of the same ("image") vector with different values, ideally with some discriminator for update/delete purposes, that all point to the same point/payload object.

**Comment by OysterQAQ** [comment]
I have the same need. I am building a picture reverse search platform, where each id represents a painting, and each painting may have multiple pictures.

**Comment by generall** [comment]
> Obviously, group-by would allow us to (more easily) retrieve a single instance per upc, but the payloads would still have to be duplicated, which we were hoping to avoid.

I think this was addressed in https://github.com/qdrant/qdrant/releases/tag/v1.3.0 by introducing `Lookup in grouping requests`. With this feature it is possible to store only the minimal payload in the individual records, while the large global payload can be kept in the global objects in another collection

**Comment by Clockwork-Muse** [comment]
@generall - Yes, that is a much more usable form.  I don't see a way to be able to filter the looked up results, though?

**Comment by generall** [comment]
yes, the values used for filters should be included into records themselves. It's a limitation of effective scalability. Otherwise we would have to do a distributed join operation, that is very slow
