### ISSUE TITLE
Entire data was loaded in RAM even on_disk_payload=true (v0.11.4)

### ISSUE THREAD

**Issue by waclawthedev** [qdrant/qdrant#1258]
1. I added collection with "on_disk_payload":true, filled it with data.
2. Changed on_disk_payload: true in config.yaml
3. Restarted the server. RAM used increased to 3.16GB. My storage folder 3.25 GB now. Is it the bug or I misconfigured the server?

**Comment by generall** [comment]
Hi @waclawthedev! `on_disk_payload` option is related to the additional payload values you can store along the vectors. If you want to keep vectors on disk, please consider creating collection using custom https://github.com/qdrant/qdrant/blob/master/config/config.yaml#L59 `memmap_threshold` parameter.

This configuration option is also available with collection create API - https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/create_collection 
![image](https://user-images.githubusercontent.com/1935623/205606466-2dbebdd4-f8b0-4768-9151-9a66679651be.png)

Reasonable value for this param could be e.g. `20000` - same as the default value for `indexing_threshold`

**Comment by waclawthedev** [comment]
Thanks, I think it will be useful for newcomers.
