### ISSUE TITLE
Support non-searchable points as input for `recommend` method

### ISSUE THREAD

**Issue by eu9ene** [qdrant/qdrant#1265]
**Is your feature request related to a problem? Please describe.**
I can't use `recommend` method if my `positive` example should be excluded from the search index. This method is very convenient because it prevents round-trip loading vectors from another collection or storage and in combination with atomic collection/alias switching solves synchronization issues when a model is retrained and the vectors are updated. 

A workaround would be to put everything in one collection and have a filter but in my case, the number of points I don't want to index is significantly higher than the ones I want to search from. So it will be a waste of CPU to index everything and search in a huge collection when in fact I need a fraction of it.

**Describe the solution you'd like**
Either or both:
- Add an ability to explicitly exclude points from the search index on uploading.
- Add an argument to `recommend` method that defines what collection to use for `positive` and `negative` examples (we should be able to turn off indexing on this collection and swap aliases on both collections atomically after a model is retrained).

**Describe alternatives you've considered**
1. Store embeddings of non-searchable items somewhere else - complicates architecture, adds round-trip to retrieve vectors, complicates synchronization when the model is retrained.
2. Store embeddings in another collection in Qdrant and disable indexing - requires retrieving a vector first and then manually passing it to the search method. 

**Additional context**
I'm building a recommender of related items. I have a significantly smaller set of items to recommend than all existing items.

Also potentially Qdrant can be used for user embeddings that also shouldn't be a part of the index.

I think both are pretty common use cases in RecSys.

**Comment by generall** [comment]
released in https://github.com/qdrant/qdrant/releases/tag/v0.11.6
