### ISSUE TITLE
Try Advice::Random for vector storage & HNSW index mmap

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1308]
**Is your feature request related to a problem? Please describe.**
Currently, we do not specify the pattern of mmap usege, which means, that it operates in `MADV_NORMAL`.
Default behavior might invoke reading of multiple sequential pages, which might slow down the search in case low available RAM and\or slow disk.

**Describe the solution you'd like**
Make an experiment with `Advice::Random` ( `libc::MADV_RANDOM` ) on low ram usage, similar to what was described in this article: https://qdrant.tech/articles/memory-consumption/

(use of random vectors for comparison is fine, I think)

**Describe alternatives you've considered**
It might be possible, that random access will only benefit the search speed if RAM << Vectors Size.
If we will use mmap storage with enough ram, we are interested in faster filling of the disk cache.
Decision of enabling random access advice might require gathering additional parameters.

**Additional context**
Some users reported, that usage of swap instead of mmaps increased the speed. Might it be related to the read strategy of swap?

**Comment by ffuugoo** [comment]
Initial results available [here][https://github.com/qdrant/qdrant/pull/1312#issuecomment-1371079088].

**Comment by generall** [comment]
released in https://github.com/qdrant/qdrant/releases/tag/v0.11.7
