### ISSUE TITLE
Save integration test logs in case of failure on CI

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1318]
**Is your feature request related to a problem? Please describe.**
If test fails on CI, we should be able to check logs of each node, to investigate the issues, which is otherwise hard to reproduce

**Describe the solution you'd like**
maybe `on_failure` artifacts could help

**Comment by agourlay** [comment]
One quick fix could be to print the logs rendered with [logs-narrator](https://github.com/agourlay/logs-narrator) in case of failure with the ` on-failure`

**Comment by agourlay** [comment]
Tackled with https://github.com/qdrant/qdrant/pull/1335
