### ISSUE TITLE
When new image in docker hub 😊

### ISSUE THREAD

**Issue by Kavan72** [qdrant/qdrant#133]
Thanks for this awesome service. I'm using this service in production and the latest tag is not working somehow but if I build docker from the latest code so it's working. so, I just want to know when you guys is going to push the latest image to docker hub.

**Comment by generall** [comment]
Hi @Kavan72, thanks for feedback! Can you please provide more information regarding your issue with image from dockerhub? We push image each time we have a new version release, currently published is `v0.4.2` (same as `latest`), and there are no significant changes in master.

**Comment by Kavan72** [comment]
Sorry for the late reply, After reinstalling docker in my local system everything is working fine.
