### ISSUE TITLE
[0.9.1] Qdrant instance blinking while searching the vectors in collection

### ISSUE THREAD

**Issue by VitalyPetrov** [qdrant/qdrant#1358]
We faced a series of qdrant internal timeout errors while searching the vectors in certain collection. The process of search queries consists of `n` ETL tasks running in parallel, each operates with its own chunk of the data. 

## Current Behavior
Most of the ETL task runtime (99%) is stable but some unexpected timeout errors are crashing all the task runtime. The error is floating means after restart the same task on that particular chunk of data can be completed without any issues.

The error to be considered is as following:
```
Code: 503
Error message: upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

## Steps to Reproduce
1. Split the data (list of points ids i.e. list of lists) into `n` different pieces and broadcast them to corresponding `n`  ETL tasks.
2. Within each task divide your data into a series of small (`num_vectors=256`) batches. Then each the neighbours for given ids batch-wise I.e. sequentially.
3. Most of tasks will be completed successfully but another ones will crash due to internal timeout error while processing the batch.

## Expected Behavior
All the tasks should terminate successfully

## Possible Solution
Increase internal timeout threshold for incoming patch processing?

## Context (Environment)
Qdrant instance detail: standalone node, v0.9.1

We interact with our Qdrant instance through the RESTful API. The collection to be concerned has two field in payload, each with its index. Other collection config is as following:

```json
{
      "config" : {
         "hnsw_config" : {
            "ef_construct" : 100,
            "full_scan_threshold" : 10000,
            "m" : 16,
            "max_indexing_threads" : 0
         },
         "optimizer_config" : {
            "default_segment_number" : 5,
            "deleted_threshold" : 0.2,
            "flush_interval_sec" : 1,
            "indexing_threshold" : 20000,
            "max_optimization_threads" : 0,
            "max_segment_size" : 200000,
            "memmap_threshold" : 50000,
            "vacuum_min_vector_number" : 1000
         },
         "params" : {
            "distance" : "Dot",
            "on_disk_payload" : true,
            "shard_number" : 2,
            "vector_size" : 133
         },
         "wal_config" : {
            "wal_capacity_mb" : 32,
            "wal_segments_ahead" : 0
         }
      }
}
```

Would be very grateful if you provide with some ideas of to fix this type of errors

**Comment by azayarni** [comment]
Hi Vitaly. It seems to be a pretty old version since the current one is 0.11.7. Do you consider upgrading the version?

**Comment by VitalyPetrov** [comment]
We will do it in the nearest time. However, i`m not sure it should solve the issue (but at least we will be on the same page).

Have you ever faced that bag before the newest stable release?

**Comment by agourlay** [comment]
I do not recall seeing such a bug.

I see you are manually setting the number of segments to five. 
May I ask how many cores do you have on the machine running this deployment?

**Comment by VitalyPetrov** [comment]
```yaml
limits:
    cpu: 32
     memory: 64Gi
requests:
    cpu: 16
     memory: 32Gi
```

**Comment by generall** [comment]
@VitalyPetrov were you able to test on newest version?

**Comment by VitalyPetrov** [comment]
@generall  sure. We`re in progress with qdrant instance update and once its done we will check for bug to disappear
