### ISSUE TITLE
Possibility to delete snapshots

### ISSUE THREAD

**Issue by skeapskeap** [qdrant/qdrant#1360]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like for qdrant API to have endpoints for deleting stored snapshots. Since their size may be huge it would be great to be able to delete them without straight acces to file system.
For example:
`DELETE /collections/{collection_name}/snapshots/{snapshot_name}`
`DELETE /snapshots/{snapshot_name}`

**Describe alternatives you've considered**

**Additional context**

**Comment by agourlay** [comment]
Tackled in https://github.com/qdrant/qdrant/pull/1377

**Comment by agourlay** [comment]
will be part of the next release
