### ISSUE TITLE
Use as an embedded library, rather than as service

### ISSUE THREAD

**Issue by agg23** [qdrant/qdrant#137]
**Is your feature request related to a problem? Please describe.**
Allow use of `qdrant` on client devices, rather than as a hosted service

**Describe the solution you'd like**
Documentation and decoupling from `actix` and `grpc` in order to embed `qdrant` in client application code, rather than spawning as a separate process or service. This would detail management of the storage and search threads in a multithreaded application, with native API calls similar to a local DB API such as [rusqlite](https://github.com/rusqlite/rusqlite).

**Describe alternatives you've considered**
From a quick glance at the code, I imagine this is already possible, it just requires some documentation of how to properly set up.

**Comment by generall** [comment]
Hi, if you are looking for embedded libraries, please take a look at https://github.com/hora-search/hora
Support for stable low-level interfaces is outside of our capacity.
