### ISSUE TITLE
Re-try to recover a dead peer during local state sync

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1387]
**Is your feature request related to a problem? Please describe.**
Currently, we only request the shard replica recovery once, when the replica is reported dead.
But single request might not be enough, as e.g. the consensus might be in election phase, or the other transfers are blocking recovery.

**Describe the solution you'd like**
During the local state synchronization, check if replicas on current peer are dead.
If there is a dead peer and there are no other transfers blocking the recovery, request recovery again.

**Describe alternatives you've considered**
Additionally, make this check less regular by only checking dead peers 1 out of 10 (random) cycles.
Main concern here is that we don't want to spam consensus with requests which are just not yet processed.

**Additional context**
Situation might be reproduced if 2 out of 3 replicas go down and recover at the same time.

**Comment by agourlay** [comment]
Closed by https://github.com/qdrant/qdrant/pull/1391
