### ISSUE TITLE
Built-in unique ID support

### ISSUE THREAD

**Issue by azayarni** [qdrant/qdrant#1424]
**Is your feature request related to a problem? Please describe.**
Built-in unique ID support for data points

**Describe the solution you'd like**
(Optionally) Generate a UUID on the server instead of letting the client do it, like MongoDB and others. 

**Describe alternatives you've considered**
To leave it as it is and make adopters ask again and again

**Additional context**
Nope

**Comment by gautamprikshit1** [comment]
Additional help on this one?

**Comment by generall** [comment]
> Is this all there is to it, or am I missing something? Should uniqueness be checked against the dataset, even though it's an UUID?

I think it should be fine to rely just on random UUID. It is 128 bit, collision chance is astronomically small

**Comment by generall** [comment]
After some consideration I think we should move this functionality into clients.
The main reason is the property of idempotence, which will be broken by this change. Meaning that multiple duplicated requests from have same effect as just a single request (important for interaction with, e.g., external message brokers like Kafka or RabitMQ) 

Client-side implementation is also promise to be simpler in maintenance.
