### ISSUE TITLE
Update needed in documentation

### ISSUE THREAD

**Issue by Parthmadan-1** [qdrant/qdrant#1444]
https://qdrant.github.io/qdrant/redoc/index.html
Create Collection example in this link needs to be updated for **Windows OS**. On running the commands it generates errors like:

curl: URL using bad/illegal format or missing URL
curl: Could not resolve host: application
curl: unmatched close brace/bracket in URL position
"error":"Json deserialize error: key must be a string at line 1 column 2"

I was able to resolve the error after ever lasting internet search.

**Comment by Rajakavitha1** [comment]
Hi @Parthmadan-1 I tried the steps on Mac and they work as documented.
```
rkodhandapani@blr-mpqob ~ % curl -X PUT 'http://localhost:6333/collections/test_collection' \
    -H 'Content-Type: application/json' \
    --data-raw '{
        "vectors": {
          "size": 4,
          "distance": "Dot"
        }
    }'
{"result":true,"status":"ok","time":0.135997227}%                               rkodhandapani@blr-mpqob ~ % curl 'http://localhost:6333/collections/test_collection'
{"result":{"status":"green","optimizer_status":"ok","vectors_count":0,"indexed_vectors_count":0,"points_count":0,"segments_count":8,"config":{"params":{"vectors":{"size":4,"distance":"Dot"},"shard_number":1,"replication_factor":1,"write_consistency_factor":1,"on_disk_payload":true},"hnsw_config":{"m":16,"ef_construct":100,"full_scan_threshold":10000,"max_indexing_threads":0,"on_disk":false},"optimizer_config":{"deleted_threshold":0.2,"vacuum_min_vector_number":1000,"default_segment_number":0,"max_segment_size":null,"memmap_threshold":null,"indexing_threshold":20000,"flush_interval_sec":5,"max_optimization_threads":1},"wal_config":{"wal_capacity_mb":32,"wal_segments_ahead":0},"quantization_config":null},"payload_schema":{}},"status":"ok","time":0.rkodhandapani@blr-mpqob ~ %rkodhandapani@blr-mpqob ~ %rkodhandapani@blr-mpqob ~ %rkodhandapani@blr-rkodhandapani@blr-rkodhandapani@blr-rkodhandarkodhandarkodhandapani@blr-rkodhandapani@blr-mpqob ~ %rkodhandapani@blr-rkodhandapani@blr-rkodhandarkodhandarkodhandarkodhandarkodhandapani@blr-mpqob ~ % curl -L -X PUT 'http://localhost:6333/collections/test_collection/points?wait=true' \
    -H 'Content-Type: application/json' \
    --data-raw '{
        "points": [
          {"id": 1, "vector": [0.05, 0.61, 0.76, 0.74], "payload": {"city": "Berlin"}},
          {"id": 2, "vector": [0.19, 0.81, 0.75, 0.11], "payload": {"city": ["Berlin", "London"] }},
          {"id": 3, "vector": [0.36, 0.55, 0.47, 0.94], "payload": {"city": ["Berlin", "Moscow"] }},
          {"id": 4, "vector": [0.18, 0.01, 0.85, 0.80], "payload": {"city": ["London", "Moscow"] }},
          {"id": 5, "vector": [0.24, 0.18, 0.22, 0.44], "payload": {"count": [0] }},
          {"id": 6, "vector": [0.35, 0.08, 0.11, 0.44]}
        ]
    }'
{"result":{"operation_id":0,"status":"completed"},"status":"ok","time":0.024390065}%                              rkodhandapani@blr-mpqob ~ % curl -L -X POST 'http://localhost:6333/collections/test_collection/points/search' \
    -H 'Content-Type: application/json' \
    --data-raw '{
        "vector": [0.2,0.1,0.9,0.7],
        "top": 3
    }'
{"result":[{"id":4,"version":0,"score":1.362,"payload":null,"vector":null},{"id":1,"version":0,"score":1.273,"payload":null,"vector":null},{"id":3,"version":0,"score":1.208,"payload":null,"vector":null}],"status":"ok","time":0.001812972}%                                                                                                        rkodhandapani@blr-mpqob ~ % curl -L -X POST 'http://localhost:6333/collections/test_collection/points/search' \
    -H 'Content-Type: application/json' \
    --data-raw '{
        "vector": [0.2,0.1,0.9,0.7],
        "top": 3
    }'
{"result":[{"id":4,"version":0,"score":1.362,"payload":null,"vector":null},{"id":1,"version":0,"score":1.273,"payload":null,"vector":null},{"id":3,"version":0,"score":1.208,"payload":null,"vector":null}],"status":"ok","time":0.00208287}%                                                                                                         rkodhandapani@blr-mpqob ~ % {
  "result": [
    { "id": 4, "score": 1.362 },
    { "id": 2, "score": 0.871 }
  ],
  "status": "ok",
  "time": 0.000093972
}
```
You might want to condor these clients for windows:
The most popular Curl equivalents for Windows are:

Wget

[Wget](https://reqbin.com/req/c-ojpjkl15/wget-vs-curl) is a free command-line tool for downloading files using the HTTP, HTTPS, and FTP protocols. Wget is a non-interactive command-line tool that can be easily invoked from scripts, deferred commands, non-X-Windows terminals, etc.

VSCode Rest Client

VSCode Rest Client is an extension plugin for Microsoft VSCode Code Editor. It allows you to make HTTP calls by executing multiple curl-like commands. The most significant benefit of this extension is that you never have to leave your code editor to test endpoints and connections.

HTTPie

HTTPie is a command line-based HTTP client used for testing JSON-based APIs. Besides the simple language, HTTPie has colored terminal output with syntax highlighting, authentication capabilities, and built-in JSON support. It is the best command-line-based Curl replacement.

Postman API Client

Postman can provide everything you need to test your API, from simple HTTP requests to authentication, automated tests, and custom scripts.

RESTClient

The RESTClient is used to test various HTTP requests and RESTful web services. It has a user-friendly graphical interface and rich functionality.

**Comment by happynls** [comment]
from langchain.vectorstores import Qdrant
from langchain.embeddings import HuggingFaceBgeEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import PyPDFLoader

loader = PyPDFLoader("gpt.pdf")
documents = loader.load()
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500,
                                                   chunk_overlap=50)
texts = text_splitter.split_documents(documents)

# Load the embedding model 
model_name = "BAAI/bge-large-en"
model_kwargs = {'device': 'cpu'}
encode_kwargs = {'normalize_embeddings': False}
embeddings = HuggingFaceBgeEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)

url = "http://localhost:6333"
qdrant = Qdrant.from_documents(
    texts,
    embeddings,
    url=url,
    prefer_grpc=False,
    collection_name="vector_db_2",
)

print("Vector DB Successfully Created!")

I have added vectors to my collection with this code. Now, I want to implement an update functionality for individual words in my collection. The condition is that only the vectors corresponding to the changed word should be updated, while the vectors for other words remain unchanged.
I used docker.

**Comment by happynls** [comment]
![Screenshot_4](https://github.com/qdrant/qdrant/assets/155633884/149f37fc-e404-4a77-b128-83fed85e0b31)

Output of Above Code
