### ISSUE TITLE
serde_cbor is archived

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#147]
**Is your feature request related to a problem? Please describe.**

qdrant relies heavily on [serde_cbor](https://github.com/pyfisch/cbor) for handling data.
However the library is officially archived which represents a risk.

**Describe the solution you'd like**

The readme contains alternatives

- [ciborium](https://crates.io/crates/ciborium)
- [minicbor](https://crates.io/crates/minicbor)

**Describe alternatives you've considered**

Not proactively migrating until it becomes an urgent problem.

**Comment by generall** [comment]
It looks like alternatives are not yet there to be a drop-in replacement for [serde_cbor](https://github.com/pyfisch/cbor).

I suggest we use it as-is and fork if some issues are discovered
