### ISSUE TITLE
Upsert to a collection returns timeout error

### ISSUE THREAD

**Issue by thanos91** [qdrant/qdrant#1470]
Try to upload to a collection in a kubernetes deployed cluster version of Qdrant and i am getting a lot of timeouts. I am using the python api client. Batch size of points uploading is 256. 
![image](https://user-images.githubusercontent.com/1743311/218697887-4d5f7f9d-9798-4467-a59e-3522c3ff3d6d.png)

**Comment by generall** [comment]
Hi @thanos91, we would need a bit more details about your setup to find the problem.
Like what is the hardware, how much data you upload, what is the vector size

**Comment by thanos91** [comment]
Hi @generall, hardware is 8 cpu cores, 64GB of RAM on a netapp volume of ~800MB/s r/w speed, vector size is 384, the payload is saved on disk. I upload a batch of 128 or 256 vectors at the time. The initial setup of the collection was to save everything in RAM, so the memmap was null, but right now i am experimenting with memmap threshold 200_000.

**Comment by generall** [comment]
> netapp volume of ~800MB/s r/w speed

Do you mean it's a network-mounted disk? It might be a bottleneck, especially with mmap-based setup

**Comment by snayan06** [comment]
will it matter if u have efs (burstable ) or to have ebs is better ?

**Comment by xyzkk3** [comment]
I have the same problem,Did you solve it?

**Comment by generall** [comment]
you can increase timeout on the client. If you are uploading a large batch of data & you have slow disks - high latency is expected.


If you think that this is a bug, we would have to ask for more details about the setup

**Comment by xyzkk3** [comment]
> you can increase timeout on the client. If you are uploading a large batch of data & you have slow disks - high latency is expected.
> 
> If you think that this is a bug, we would have to ask for more details about the setup

I set batch_size =1, It's still out of time, what details do I need to provide

**Comment by agourlay** [comment]
@thanos91 What is the current status of your deployment? Are you still facing issues? Have you been able to upgrade to the latest versions?

**Comment by generall** [comment]
Closing the issue, as it requires as there are not enough details to reproduce.

**Comment by eze1376** [comment]
I had the same problem, when I want to `upsert` batch points more than 3000 points, it causes timeout error!
So, I split my data into some mini-batches with the code below and then fed it into `upsert` function:
```
step_size = 3_000
pionts_size = embeddings.shape[0] # number of all points

for i in range(0, int(pionts_size/step_size) + 1):
    start = i * step_size
    end = (i + 1) * step_size if (i + 1) * step_size < pionts_size else pionts_size
    print(start, end)
    qdrant_client.upsert(
        collection_name="{collection_name}",
        points=models.Batch(
            ids=index[start:end],
            vectors=embeddings.tolist()[start:end],
            payloads=payload_list[start:end],
        ),
    )
    print("Upserted!")
```
