### ISSUE TITLE
Dockerfile not Building from Source on Windows

### ISSUE THREAD

**Issue by HRITIKAKOLKAR** [qdrant/qdrant#1477]
Error In Line 27 of [qdrant/Dockerfile](https://github.com/qdrant/qdrant/blob/master/Dockerfile)

**Comment by generall** [comment]
Hi @HRITIKAKOLKAR , what is the error?

**Comment by HRITIKAKOLKAR** [comment]
executor failed running [/bin/sh -c rustup target add $(bash target_arch.sh)]: exit code: 1

**Comment by HRITIKAKOLKAR** [comment]
=> [builder  5/10] RUN apt-get update && apt-get install -y gcc-multilib && apt-get install -y clang cmake gcc-aarch64-linux-gnu g++-aar  182.8s 
 => ERROR [builder  6/10] RUN rustup target add $(bash target_arch.sh)

**Comment by generall** [comment]
It works on CI :confused: Are there any other logs? How do you run it?

**Comment by HRITIKAKOLKAR** [comment]
I ran it using the normal build command.
![qdrant01](https://user-images.githubusercontent.com/48088844/219316567-ceae64d6-18aa-4923-bff8-f9441170d42c.png)
![qdrant02](https://user-images.githubusercontent.com/48088844/219316597-61643c66-2236-405a-9c40-dd2e4731ad10.png)

**Comment by generall** [comment]
What is your environment, operation system?

**Comment by generall** [comment]
It looks like you are building with `buildx`, actually

**Comment by HRITIKAKOLKAR** [comment]
Windows 11, 64-bit operating system, x64-based processor

**Comment by HRITIKAKOLKAR** [comment]
No I am not using `buildx` command. I am using `docker build . --tag=qdrant/qdrant`

**Comment by generall** [comment]
I see, windows. I never tested docker builds on windows. You would probably need to update this file to select proper target https://github.com/qdrant/qdrant/blob/01807d5cf3eaa0ec3348d755a3875db49591aa91/tools/target_arch.sh

But what is your use-case?

**Comment by HRITIKAKOLKAR** [comment]
Actually I am just trying to see how this neural search work and also want to  implement it on some use-case.
I read the book _deep learning for search_. I want to write a blog related to it.

**Comment by generall** [comment]
> I read the book deep learning for search. I want to write a blog related to it.

That sounds very cool! There are several tested options for you:

- you can run ready-made docker
- you can build binaries without docker - it will give you .exe file you can run on windows
- you can start with a free-tier on our cloud

**Comment by HRITIKAKOLKAR** [comment]
### Issue Solved
Open this file [ tools/target_arch.sh 
(https://github.com/qdrant/qdrant/blob/01807d5cf3eaa0ec3348d755a3875db49591aa91/tools/target_arch.sh) in your Editor.

![qdrant03](https://user-images.githubusercontent.com/48088844/219324603-6ad26640-afdc-4086-9d9c-c16298fc1ca4.png)
]

And change "Select End of Line Sequence" this `CRLF` to `LF`

Now to know why this happens read this [thread](https://stackoverflow.com/a/58614733/11206399) on Stackoverflow
