### ISSUE TITLE
Logging to files

### ISSUE THREAD

**Issue by ChangyouSiom** [qdrant/qdrant#1481]
Is there any options to log to files? 

Thanks a lot!

**Comment by generall** [comment]
Hi @ChangyouSiom, we are using https://docs.rs/env_logger/latest/env_logger/ and there is no built-in option for this. But if you are running qdrant in container environment, docker or k8s should take care about it for you.

Could you please describe your requirements in a bit more details?

**Comment by snayan06** [comment]
have deployed qdrant as a container, and in docker logs I am just able to see the access logs, like internal logs of the qdrant not able to see, have tried updating the value of debug -> INFO in config. still was not able to see.

Thanks a lot !

**Comment by bikeshedder** [comment]
> we are using https://docs.rs/env_logger/latest/env_logger/ and there is no built-in option for this. (...)

It looks like the information about `env_logger` is no longer true. Looking at the code I can see that the tracing is set up like so:
```rs
    let settings = Settings::new(args.config_path)?;
    // (...)
    tracing::setup(&settings.log_level)?;
```

For that reason setting the `RUST_LOG` environment variable doesn't have any effect whatsoever.

**Comment by timvisee** [comment]
You're right. This has changed since.

You could set `QDRANT__LOG_LEVEL` instead, which would have the same effect.

**Comment by justinrmiller** [comment]
@timvisee Can you provide some background and guidance on this issue? I’d like to try implementing a fix.

**Comment by timvisee** [comment]
Hi @justinrmiller. In the current version we already support logging to a file on disk. I'm afraid this wasn't closed by accident, partially because it's not well documented.

You can specify the following:

```yaml
logger:
  on_disk:
    enabled: true
    log_file: path/to/log/file.log
    log_level: debug
```

This can also be done through `GET` or `POST` at `/logger`.
