### ISSUE TITLE
Is there an way for increasing throughput of cluster?

### ISSUE THREAD

**Issue by ed-park-kr** [qdrant/qdrant#1488]
Hey team!
I recently using qdrant for searching vectors.
I'm trying to organize vectordb with qdrant cluster and I expected expanding shard might increase our search throughput.

Like this:
- test A:
  - Each node size: 16 cpu
  - Pre requisite: 3 node
  - Collection setting: 3 shard 1 replica
  - Vectors: ~= 3_000_000
- test B:
  - Each node size: 16 cpu
  - Pre requitsite: 6 node
  - Collection setting: 6 shard 1 replica
  - Vectors: ~= 3_000_000

I thought test B's throughput would 2 times better than test A's.
But my expectation was wrong, throughput was same.

I think the main factor of performance is related with "segment number" of collection and "cpu" count (such as: segment_number / cpu, the more segment need more computing power)

So, keep my question simple is:
`How can I increase search throughput of collection by scaling out`

**Comment by generall** [comment]
Hi @ed-park-kr ! For higher throughput you need to keep the number of shards the same, but increase replication factor

**Comment by ed-park-kr** [comment]
Thank you for helping me! I'll try it!

**Comment by ed-park-kr** [comment]
Hey @generall ! I tried your solution like:
- test C:
  - Each node size: 16 cpu
  - Pre requitsite: 6 node
  - Collection setting: 3 shard 3 replica
  - Vectors: ~= 3_000_000
 
I expected 3 replicas can increase throughput over 3 times faster but I can't get the result of querying random vectors for unit time (Actually it takes over x4 more times to receive result than 1 replica)
Is there any cluster config or collection's optimizer config I should do? (Did I missed something?)

**Comment by generall** [comment]
> Actually it takes over x4 more times to receive result than 1 replica

Usually by throughput we understand the number of requests per second (RPS) the system can handle.
But it seems you are trying to measure latency of a single request, is it correct?

Latency and RPS are somewhat opposite sides of the balance. 
In your case it seems like the network latency is more expensive than the vector search itself.
If you want lower latency I would recommend to ideally use only one shard. In this case there will be no internal network communication inside the cluster. 

There are other possible configuration options you might tune, but I would need more info about your case scenario

**Comment by generall** [comment]
> Start 6 client machines for querying concurrently

Are you querying same qdrant node each time? In this setup you should see more QPS simply because different machines should handle different queries.

**Comment by ed-park-kr** [comment]
Oh I think that you just caught really great point!
Yes I'm just querying to same node for all time and I think client side connection balancing is needed. (I think it can be the solution)
Thank you! @generall  :)
