### ISSUE TITLE
Built-in authentication mechanism

### ISSUE THREAD

**Issue by azayarni** [qdrant/qdrant#1499]
**Is your feature request related to a problem? Please describe.**
Qdrant should provide an optional built-in authentication mechanism 

**Describe the solution you'd like**
Possibility to enable authentication via configuration

**Describe alternatives you've considered**
Using some external solution

**Additional context**
nope

**Comment by do-me** [comment]
+1
See also https://github.com/qdrant/qdrant/discussions/1418

**Comment by sbusso** [comment]
As an alternative, I use Kong as a gateway and authentication. This is also a preferred architecture in a production environment, not exposing the database to the internet. Here is an example of a simple setup for a standalone database and  can be extended to handle a cluster or on Kubernetes: https://medium.com/@stephane.busso/setting-up-qdrant-with-kong-for-authentication-a-step-by-step-guide-91c206a913f8

**Comment by do-me** [comment]
Very nice, thanks for writing the tutorial!

**Comment by DengYiping** [comment]
Link it here as well. mTLS authentication is already supported: https://github.com/qdrant/qdrant/pull/1663

**Comment by generall** [comment]
https://github.com/qdrant/qdrant/releases/tag/v1.2.0
