### ISSUE TITLE
`wait` param for all snapshotting API

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1532]
**Is your feature request related to a problem? Please describe.**
Snapshot API is long-running, so it might make sense to make it all async and do not require to keep connection while process is doing it's job

**Describe the solution you'd like**
Add an ability to tell the recovery process, that it can be dropped. E.g. `wait=false`, in this case API should answer immediately and recover should continue in background.

**Comment by SainiAditya1** [comment]
@generall please assign this to me , I want to work on this ..

**Comment by amab8901** [comment]
I also wanna work on this :yum:

**Comment by monatis** [comment]
@SainiAditya1 @amab8901 Guys, you are supposed to make your application at the GSoC website, not on GitHub issues. Please [our guide](https://qdrant.to/gsoc23) and keep the communications in the dedicated GSoC channel at [Discord](https://qdrant.to/discord).

**Comment by hbina** [comment]
I see that you've already implemented some of them here https://github.com/qdrant/qdrant/pull/1534
Do you want to add --wait to things like delete and create snapshots as well?
A problem that I've faced when trying to add one for creating is that it returns an Object, so I am not sure what to return in the case of early return or is it even worth to changing the API response.
