### ISSUE TITLE
Failed to create batch

### ISSUE THREAD

**Issue by Barney241** [qdrant/qdrant#1552]
## Current Behavior
When i try to create batch of items with 3 field indexes in payload. I figured out its happening because of one integer index. i am storing there int64 which can contain duplicit values in batch.

if i remove this integer index it starts to work. Its weird because i have other integer index with duplicit values that doesnt cause any problems.

I found out that batch size doesn't matter only think that i think is causing this is that particular integer index when i add it to the collection.

[2023-03-13T09:43:17.007Z ERROR qdrant::startup] Panic occurred in file lib/segment/src/index/field_index/histogram.rs at line 512: assertion failed: `(left == right)`
      left: `10`,
     right: `0`

## Expected Behavior

Creates batch successfully

## Context
I am using this go client  https://github.com/qdrant/go-client

**Comment by generall** [comment]
Hi @Barney241 could you please add some more details of how to reproduce that?

**Comment by Barney241** [comment]
@generall i added some more informations

**Comment by generall** [comment]
@Barney241 is there any chance you could share values stored in this faulty index? Maybe in private channel. It would be very helpful, and in this case we would be able to fix the problem ASAP.

**Comment by Barney241** [comment]
Our db entities have unique ids in this format `104230171086686139` its postgres bigint sequence. And i am indexing associated files so i need a reference to original entity. One entity can have multiple files so i added this entity id to payload and added index. If it helps and there is an easy way how to get all index values from qdrant i can send it to you

**Comment by generall** [comment]
@Barney241, you can use this command:

```
curl -L 'http://localhost:6333/collections/test_collection/points/scroll' -H 'Content-Type: application/json' -d '{ "limit": 1000000000, "with_payload": ["pd_id"], "with_vector": false }' > ids.json
```
It will export only the field `pd_id` from payloads. Just replace it with your field name and `test_collection` with your collection name

**Comment by Barney241** [comment]
@generall 
[ids.json.zip](https://github.com/qdrant/qdrant/files/10956682/ids.json.zip)

**Comment by generall** [comment]
@Barney241 thanks a lot, I was able to reproduce the issue! Will prepare fix soon!

**Comment by Barney241** [comment]
Thanks thats great
