### ISSUE TITLE
API endpoint to upload snapshot as a file

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1567]
**Is your feature request related to a problem? Please describe.**
Currently, it is only possible to apply snapshot if it is stored somewhere qdrant have access to. But in some cases (e.g. security-wise) it might make sense to only allow incoming connection.

**Describe the solution you'd like**
API which could accept uploaded file, save it to snapshots directory and recover collection from it.
(use get params to specify required config options, similar to https://qdrant.github.io/qdrant/redoc/index.html#tag/snapshots/operation/recover_from_snapshot )

**Describe alternatives you've considered**
Upload snapshot data first, store it, and apply recovery with second API call by simply specifying local path to the just uploaded file.

**Comment by SainiAditya1** [comment]
@generall I would like to work on this.

**Comment by muhib-siddique** [comment]
i want to work on this issue plese assign me this issue
