### ISSUE TITLE
Kubernetes deployment fails to restore collection or snapshot

### ISSUE THREAD

**Issue by zmtbnv** [qdrant/qdrant#1575]
## What works:
1. Qdrant Kuberntes deployment works via https://github.com/qdrant/qdrant-helm#tldr. 
2. Creating collection and uploading vectors - no issues

## What doesn't work
1. Restarting Qdrant Pod fails to restore collection leading to infinite **CrashLoopBackOff** with following message:
```bash
│ Access web UI at https://ui.qdrant.tech/?v=v1.0.3                                                                                                                               │
│                                                                                                                                                                                 │
│ [2023-03-17T06:20:42.325Z INFO  storage::content_manager::consensus::persistent] Loading raft state from ./storage/raft_state                                                   │
│ [2023-03-17T06:20:42.325Z INFO  storage::content_manager::toc] Loading collection: demo                                                                                         │
│ Stream closed EOF for default/qdrant-0 (qdrant)  
```

2. Restoring snapshot into new collection in Kuberenes environment fails with:
```bash
ERROR qdrant::startup] Panic occurred in file lib/storage/src/content_manager/consensus/consensus_wal.rs at line 22: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
```

## Steps to Reproduce
1. Create GKE cluster
2. Deploy QDrant with helm https://github.com/qdrant/qdrant-helm#tldr
3. Create new collection using Python Client and upload vectors
4. Restart the cluster and qdrant reuses same PV (which has collection/snapshots) and PVC. --> **Fails to restore existing collection** with following:
 ```bash
ERROR qdrant::startup] Panic occurred in file lib/storage/src/content_manager/consensus/consensus_wal.rs at line 22: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
```
6. Create new collection and try to restore snapshot following https://qdrant.tech/documentation/snapshots/#restore-snapshot or https://github.com/qdrant/qdrant-helm#snapshot-restoration. **Both cases fail with:**

```bash
ERROR qdrant::startup] Panic occurred in file lib/storage/src/content_manager/consensus/consensus_wal.rs at line 22: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
```

Is there any working solution to either of these in Kubernetes context?

Thanks.

**Comment by generall** [comment]
Hi @zmtbnv , I am no expert on GKE, but it looks like one PVC is used by multiple qdrant instances

**Comment by zmtbnv** [comment]
@generall Thank you for getting back on this. I solved the issue by disabling following. Seems in single node deployment, it fails if `livenessProbe` and `readinessProbe` are set `true`. Disabling it makes it work without any issues.
```bash
livenessProbe:
  enabled: false

readinessProbe:
  enabled: false
```
