### ISSUE TITLE
Incorrect version reported

### ISSUE THREAD

**Issue by RJKeevil** [qdrant/qdrant#1582]
## Current Behavior
When running Qdrant 1.1.0 or 1.0.3, the terminal in the container and a call to HealthCheck GetVersion returns v1.0.2

## Steps to Reproduce
1. Start the qdrant/qdrant:v1.1.0 docker container
2. Open a terminal for this container
3. Observe the message Access web UI at https://ui.qdrant.tech/?v=v1.0.2
![qdrant](https://user-images.githubusercontent.com/10771606/226275703-5f71fd48-5d4f-4cdd-9453-8c05192d2e7d.png)

## Expected Behavior
It returns the correct version v1.1.0

**Comment by generall** [comment]
Can't reproduce :man_shrugging: 

![image](https://user-images.githubusercontent.com/1935623/226290741-1ee636b5-3528-4ace-bd18-94f2002a4bc0.png)

**Comment by RJKeevil** [comment]
Apologies, wiping the image caches in docker fixed this.  Still confused how this happened tbh
