### ISSUE TITLE
Optimize memory consumption of the Inverted Index

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1604]
Optimize memory consumption of the Inverted Index

**Is your feature request related to a problem? Please describe.**
The full-text index uses inverted index to perform filtering and retrieval fast.
But the implementation of inverted index is naive and consumes a lot of memory.
Especially when the number of documents is large, and we use prefix tokenization.

It can quickly consume lots of memory for even a medium-sized dataset.

Inverted index is located here:
https://github.com/qdrant/qdrant/tree/master/lib/segment/src/index/field_index/full_text_index

Instructions how to use it in qdrant:
https://qdrant.tech/documentation/indexing/#full-text-index

**Describe the solution you'd like**

Optimize the in-memory representation of inverted index.
Avoid using `String` as a key in the hash set.
Use a more compact representation of the inverted index.

Ideally, the new implementation should be able to use the exising persistent storage format, but build the inverted index in a more compact way.

**Describe alternatives you've considered**
It might be required to change the persistent storage format as well, to make it more compact.
If you find it necessary, it will be required to also implement a migration logic for the existing storage.

**Additional context**

Acceptance criteria:

- At least 2x memory consumption reduction for the inverted index, actually it should be possible to reduce it 5x or more
- Search performance should not be affected (at least not significantly)
- Build time should not be affected (at least not significantly)
- Functionalities of the inverted index should be preserved

Experimental data:

- Feel free to use this snapshot for testing: https://storage.googleapis.com/qdrant-common-shared/startups-8476456695034750907-2023-03-25-09-41-29.snapshot.gz

```
gzip -d startups-8476456695034750907-2023-03-25-09-41-29.snapshot.gz

cargo run -r --bin qdrant -- --snapshot path/to/startups-8476456695034750907-2023-03-25-09-41-29.snapshot:startups
```

**Comment by Weijun-H** [comment]
This is an interesting issue, I will try to work on it : )

**Comment by Weijun-H** [comment]
My intuitive idea to optimize the in-memory representation of the inverted index is to use a `trie` data structure instead of a `String` key. Using a `trie` can reduce memory usage by avoiding storing redundant prefixes in memory, resulting in a more compact representation of the inverted index.

In terms of search performance, the use of a `trie` may require more time for exact match search, especially for large datasets. To mitigate any potential slowdown, we can employ path compression techniques. Path compression reduces the depth of the `trie` by compressing long paths into single nodes, which can significantly improve search performance for exact matches. However, for prefix search, the performance of a `trie` should still be fast.

Does this idea work?

**Comment by generall** [comment]
I would try to do following things:

- make sure Strings are not used in posting list. I would use vocab to convert all known words into u32.
- in this case posting lists will be `Vec<Vec<DocID>>`, which should be already more compact
- vocab can be hashmap or `trie`. I think we can make it generic, depending on the tokenizer type
- Documents are stored as `Vec<BTreeSet<String>>` - quite inefficient. It can be Vec<Vec<TokenId>>, it can also be sorted for faster checks
- Some tokens might be so frequent, that `Vec<DocID>` will be larger than `BitVec`. We can dynamically switch between those

Unfortunately, storing everything in a contiguous piece of memory is difficult, because we need to update everything dynamically.

**Comment by Weijun-H** [comment]
Hi @generall, do you know of an accessible method to measure memory consumption? I want to evaluate the current implementation. Thank you.

**Comment by Shubham8287** [comment]
Hi, Is this still active or someone working on it? else Issue looks too interesting, I would love to take it. I have some ideas to start with.

**Comment by generall** [comment]
> Hi, Is this still active or someone working on it? else Issue looks too interesting, I would love to take it. I have some ideas to start with.

there were two attempts, but they look inactive. Please feel free to suggest you version

**Comment by ibrahim-akrab** [comment]
My PR is almost complete and implements all the suggested points that @generall provided, but it has a couple bugs that I'm still trying to debug offline.

**Comment by generall** [comment]
> My PR is almost complete and implements all the suggested points that @generall provided, but it has a couple bugs that I'm still trying to debug offline in my free time.

please let me know if you need any help from my side

**Comment by ibrahim-akrab** [comment]
the problem that is the most confusing to me is that the test
https://github.com/qdrant/qdrant/blob/5e0e1b82faf88b917c136a3877c0a9156d10080e/openapi/tests/openapi_integration/test_fts.py#L230
fails with the index returning different results each time it runs. Do you think this can have something to do with cardinality estimation (since it's the mysterious black box to me) or should I just keep looking into the index code?

**Comment by Weijun-H** [comment]
> the problem that is the most confusing to me is that the test
> 
> https://github.com/qdrant/qdrant/blob/5e0e1b82faf88b917c136a3877c0a9156d10080e/openapi/tests/openapi_integration/test_fts.py#L230
> 
> 
> fails with the index returning different results each time it runs. Do you think this can have something to do with cardinality estimation (since it's the mysterious black box to me) or should I just keep looking into the index code?

@ibrahim-akrab Did you monitor the memory usage by htop? I am curious about the result of your implementation because the memory usage did not change in my version.

**Comment by ibrahim-akrab** [comment]
@Weijun-H I did use htop to measure memory usage alongside another utility called `psrecord` which monitors both memory and cpu usage and gives a generate a nice-looking plot for both.

The memory usage reduction came from reimplementing the document structure and using a vocabulary dictionary shared between all documents which I guess got rid of tokeb repetition in documents.
I didn't notice any significant memory optimization after using the radix-trie even though the index used in the sample snapshot uses a prefix tokenizer.

**Comment by Weijun-H** [comment]
> @Weijun-H I did use htop to measure memory usage alongside another utility called `psrecord` which monitors both memory and cpu usage and gives a generate a nice-looking plot for both.
> 
> The memory usage reduction came from reimplementing the document structure and using a vocabulary dictionary shared between all documents which I guess got rid of token repetition in documents. I didn't notice any significant memory optimization after using the radix-trie even though the index used in the sample snapshot uses a prefix tokenizer.

Also I noticed there is no memory usage reduction when running `cargo run -r --bin qdrant` without `--snapshot`.

**Comment by ibrahim-akrab** [comment]
I think that's because after restoring a snapshot, it is saved in a storage folder in the working directory, and automatically restored on startup.
For good measure, I just delete the storage folder before every measurement.

**Comment by Govthub** [comment]
Hello you got issues to fixed . Please drop your telegram or WhatsApp number so we can fixed it sir
