### ISSUE TITLE
Does the mode of cluster distribution support for grpc?

### ISSUE THREAD

**Issue by ainilian** [qdrant/qdrant#1605]
Does the mode of cluster distribution support for grpc? If not, does the team have a plan to do that.

**Comment by ainilian** [comment]
Hi @generall  
like this example of http:
     POST /collections/{collection_name}/cluster

   {
       "move_shard": {
       "shard_id": 0,
       "from_peer_id": 381894127,
      "to_peer_id": 467122995
    }
  }

I didn't find codes or doc about that example for grpc in Qdrant client

**Comment by generall** [comment]
got it. No, unfortunately cluster management api is only available on REST endpoint now. Eventually we will move it to gRPC as well, contributions are welcome!
