### ISSUE TITLE
Explicit `isNull` condition for payload filter

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1609]
**Is your feature request related to a problem? Please describe.**
Currently, there is `isEmpty` condition, which is passed when
either `"key": []` or `key` does not exist.  

But it is not triggered if `"key": null`.

**Describe the solution you'd like**
A new condition, that can check for `null`.

**Describe alternatives you've considered**
Allow `isEmpty` to match with `"key": null`. 

**Additional context**

Would require:

- Unit tests to check that the new condition works
- OpenAPI integration tests to make sure schema is updated properly

**Comment by ibrahim-akrab** [comment]
This looks like an easy fix. I'll look into it to see if I am missing something.

**Comment by ibrahim-akrab** [comment]
Thanks for the clarification. It makes sense now :)
