### ISSUE TITLE
Allow `indexing_threshold_kb: null` in config to disable indexing

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1621]
**Is your feature request related to a problem? Please describe.**
Currently, it is recommended to set some large value to disable indexing, but it looks ugly.

**Describe the solution you'd like**
Allow `indexing_threshold_kb: null`, which should be considered as disabled indexing

**Comment by RashulChutani** [comment]
Hi @generall I would be happy to work on this if possible? Thanks.

**Comment by RashulChutani** [comment]
Sure, Can you please assign the issue to me? Thanks.

**Comment by coszio** [comment]
Not seeing a PR yet, self-assigning :)

**Comment by coszio** [comment]
In the end the solution was to use 0 as the `disabled` setting, to avoid conflicts vs not setting it, see #1824
