### ISSUE TITLE
Data persistence for k8s deployment

### ISSUE THREAD

**Issue by junwang-wish** [qdrant/qdrant#1640]
**Is your feature request related to a problem? Please describe.**
I want to deploy qdrant to production using k8s, it is not feasible to compute and reindex all 200M items' embedding when new pod spawns, how to persist already indexed data?

**Describe the solution you'd like**
Load persisted data from S3 during pod spawn.

**Describe alternatives you've considered**
Serve without k8s using a metal server, which is not ideal

**Describe alternatives you've considered**
I have a weekly Kron job that runs ML model to populate the embeddings

**Comment by generall** [comment]
Data is usually persisted with PVC, check out https://github.com/qdrant/qdrant-helm

**Comment by junwang-wish** [comment]
Thanks for the pointer
