### ISSUE TITLE
Windows CI broken by OpenSSL on dev branch

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant#1643]
The Windows CI on the `dev` branch suddenly broke, causing PRs to fail.

Maybe this is due to an OpenSSL version change, not sure.

## Current Behavior
Windows builds on CI break for the `dev` branch.

## Steps to Reproduce
1. Start action on `dev` branch.
2. Wait for Windows action to fail.

## Expected Behavior
Windows action should complete successfully.

## Detailed Description
Linking on Windows fails due to OpenSSL errors, then this is spammed:

```
d1c57ff55ec93d69.rlib(ssl_lib.obj) : warning LNK4099: PDB '' was not found with 'libopenssl_sys-d1c57ff55ec93d69.rlib(ssl_lib.obj)' or at ''; linking object as if no debug info
2023-04-03T08:26:41.0975742Z [0m
2023-04-03T08:26:41.0976371Z [0m          libopenssl_sys-d1c57ff55ec93d69.rlib(ocsp_cl.obj) : warning LNK4099: PDB '' was not found with 'libopenssl_sys-d1c57ff55ec93d69.rlib(ocsp_cl.obj)' or at ''; linking object as if no debug info
2023-04-03T08:26:41.0976835Z [0m
2023-04-03T08:26:41.0977436Z [0m          libopenssl_sys-d1c57ff55ec93d69.rlib(ocsp_vfy.obj) : warning LNK4099: PDB '' was not found with 'libopenssl_sys-d1c57ff55ec93d69.rlib(ocsp_vfy.obj)' or at ''; linking object as if no debug info
```

- Failed run: https://github.com/qdrant/qdrant/actions/runs/4594147927/jobs/8113279617
- Full log: https://pastebin.com/3aUVxxfC

**Comment by timvisee** [comment]
Updating OpenSSL (<https://github.com/qdrant/qdrant/pull/1644>) doesn't fix this. Investigating further...

**Comment by agourlay** [comment]
In the past, I got rid of Windows build issues by deleting all our caches on GA.
It can sometimes be in a corrupted state.

I will give it a try again here :crossed_fingers:

**Comment by timvisee** [comment]
@agourlay Could you then trigger the build for [this](https://github.com/qdrant/qdrant/pull/1644) PR again to see if it works?

**Comment by timvisee** [comment]
Fixed by clearing caches!

**Comment by agourlay** [comment]
Happy to hear!

FYI  the caches can be cleaned up here https://github.com/qdrant/qdrant/actions/caches
