### ISSUE TITLE
Include "last queried" param into telemetry API

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1660]
**Is your feature request related to a problem? Please describe.**
In some case it might be interesting to know when the qdrant instance was requested last time.

**Describe the solution you'd like**

Include "last-request-time" into `/telemetry` endpoint, which should display the date and time (optionally, a timestamp) when the last call of any API (rest or gRPC) happened, except for `/`. If there were no queries after restart - the time of restart should be displayed.

**Describe alternatives you've considered**

Create separated fields for gRPC and REST

**Comment by coszio** [comment]
I don't think the `/` endpoint should be treated any differently from the other endpoints. Another solution I find is to add a "uptime" field to the `"app"` object, which would display the age of the latest boot. Alternatively, add a "last_boot" in the same "app" field, displaying the time of the last server boot.

**Comment by coszio** [comment]
Included in v1.1.1
