### ISSUE TITLE
May I ask, if I want to create 1 million collections, and the minimum number vector in each collection is 1000, and the maximum number is 5 million, may I ask what configuration I need

### ISSUE THREAD

**Issue by eliassama** [qdrant/qdrant#1690]
May I ask, if I want to create 1 million collections, and the minimum number vector in each collection is 1000, and the maximum number is 5 million, may I ask what configuration I need.

qdrant Whether to support?

**Comment by generall** [comment]
That might be relevant https://qdrant.tech/documentation/how_to/#serve-vectors-for-many-independent-users

**Comment by eliassama** [comment]
> 这可能是相关的https://qdrant.tech/documentation/how_to/#serve-vectors-for-many-independent-users

有个问题：payload_m 具体是用来做什么的？我看官方示例是 16，我不确定我需不需要做更改？
![image](https://user-images.githubusercontent.com/79587688/231145697-6253433d-ae67-41b5-8bdb-695d9dbfb599.png)

**Comment by eliassama** [comment]
我看注释是 Number of additional payload-aware links per node in the index graph. If not set - regular M parameter will be used.

那就是可以理解为相邻索引数量？

**Comment by generall** [comment]
> That's the number of adjacent indexes, right?

That is a number of edges per node in HNSW graph, yes

**Comment by eliassama** [comment]
> > That's the number of adjacent indexes, right?
> 
> That is a number of edges per node in HNSW graph, yes

ok, thanks.
