### ISSUE TITLE
My grpc link always breaks after 10 seconds

### ISSUE THREAD

**Issue by eliassama** [qdrant/qdrant#1695]
## Steps to Reproduce

When you use a go-client link, it always breaks after 10 seconds
report: rpc error: code = Internal desc = Service internal error: Waiting for consensus operation commit failed. Timeout set at: 10 seconds

## Expected Behavior

Depending on the grpc time I set

## Possible Solution

I think it started here
https://github.com/qdrant/qdrant/blob/de93c75bf3abb81c076d90a380d46ee3627f7704/lib/api/src/grpc/transport_channel_pool.rs#L15

**Comment by eliassama** [comment]
> @eliassama Are you able to perform any operation? Listing all the collections should not take 10 seconds. That may indicate some networking issues.

This is mostly when I create collections.

like this:

```
{
    "vectors":{
        "size":1,
        "distance":"Euclid"
    },
    "shard_number":3,
    "replication_factor":1,
    "write_consistency_factor":1,
    "on_disk_payload":true,
    "hnsw_config":{
        "m":0,
        "ef_construct":0,
        "full_scan_threshold":100,
        "max_indexing_threads":0,
        "on_disk":true,
        "payload_m":16
    },
    "wal_config":{
        "wal_capacity_mb":32,
        "wal_segments_ahead":0
    },
    "optimizers_config":{
        "deleted_threshold":0.2,
        "vacuum_min_vector_number":1000,
        "default_segment_number":0,
        "max_segment_size":null,
        "memmap_threshold":20000,
        "indexing_threshold":20000,
        "flush_interval_sec":5,
        "max_optimization_threads":1
    },
    "init_from":null,
    "quantization_config":null
}
```

**Comment by eliassama** [comment]
By the way, I use a Ceph-based network disk with a bandwidth of 50M/s

**Comment by eliassama** [comment]
Let me explain the parameters that I used to create the collection

1. My vectors are all 512 dimensional.
2. I use the Euclidean distance for the calculation.
3. I have three distributed nodes. Each machine has 16 CPU 32 Memory 1.2 T Disk.
4. I don't have a lot of memory, but I have a lot of data around a billion, so I need all the data on disk.
5. I have multi-tenant isolation requirements, minimum 1000 vectors per tenant, maximum 10000000 vectors per tenant.

**Comment by generall** [comment]
> By the way, I use a Ceph-based network disk with a bandwidth of 50M/s

This might be a reason for slow operations. When you create collection, it creates some amount of initial files, which might be overwhelming for this types of disks (IOPS is more relevant, rather than bandwidth, though).

There is a timeout param in collection creation API - https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/create_collection

It should fix your API call if the hypothesis is correct.
But working with disk that slow might be problematic. Even if you only load portions of data into RAM, the process of loading might be critically slow. So each time you query a cold part of the collection, you are going to wait 10+ seconds for a query because of the disk.

Using local SSD type of disk if highly recommended

**Comment by eliassama** [comment]
> > By the way, I use a Ceph-based network disk with a bandwidth of 50M/s
> 
> This might be a reason for slow operations. When you create collection, it creates some amount of initial files, which might be overwhelming for this types of disks (IOPS is more relevant, rather than bandwidth, though).
> 
> There is a timeout param in collection creation API - https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/create_collection
> 
> It should fix your API call if the hypothesis is correct. But working with disk that slow might be problematic. Even if you only load portions of data into RAM, the process of loading might be critically slow. So each time you query a cold part of the collection, you are going to wait 10+ seconds for a query because of the disk.
> 
> Using local SSD type of disk if highly recommended

if i want set timeout 60s,  like: url?timeout=60

right?

timeout |  
-- | --


<br class="Apple-interchange-newline">

**Comment by timvisee** [comment]
> if i want set timeout 60s, like: url?timeout=60
> 
> right?

Correct!

**Comment by eliassama** [comment]
In addition, I have a question, according to the above set to create parameters, a billion 512 dimensional vectors if stored roughly how much space will take up?

Because I'm considering using SSDS, but I need to get enough disk space first

**Comment by timvisee** [comment]
> In addition, I have a question, according to the above set to create parameters, a billion 512 dimensional vectors if stored roughly how much space will take up?

As a rule of thumb you can use `memory_size = 1.5 * number_of_vectors * vector_dimension * 4 bytes
` ([via](https://qdrant.tech/articles/scalar-quantization/)).

Qdrant cloud also has a calculator to estimate this: https://cloud.qdrant.io/calculator

**Comment by eliassama** [comment]
> > In addition, I have a question, according to the above set to create parameters, a billion 512 dimensional vectors if stored roughly how much space will take up?
> 
> As a rule of thumb you can use `memory_size = 1.5 * number_of_vectors * vector_dimension * 4 bytes` ([docs](https://qdrant.tech/documentation/cloud/capacity/#basic-configuration)).
> 
> Qdrant cloud also has a calculator to estimate this: https://cloud.qdrant.io/calculator
> 
> These will let you calculate the amount of memory required. That is a good indicator of the amount of disk space you'll need.

It looks like 500 million vector data requires around 1.5 terabytes of SSD, and 1 billion pieces of data requires around 3 terabytes of SSD.

Thank you for your information.
