### ISSUE TITLE
[docs] can't create test_collection

### ISSUE THREAD

**Issue by melekes** [qdrant/qdrant#170]
Hi 👋 I'm going through the [QUICK_START](https://github.com/qdrant/qdrant/blob/master/QUICK_START.md) tutorial right now and can't seem to add `test_collection`.

## Current Behavior

Server returns

```
[2022-01-02T11:45:04Z INFO  actix_web::middleware::logger] 172.17.0.1:60782 "PUT /collections/test_collection HTTP/1.1" 404 0 "-" "curl/7.64.1" 0.000051
```

## Steps to Reproduce

1. docker pull generall/qdrant
2. `docker run -p 6333:6333 \
  -v $(pwd)/qdrant_storage:/qdrant/storage \
  generall/qdrant`
3. curl -X PUT 'http://localhost:6333/collection/test_collection' \
    -H 'Content-Type: application/json' \
    --data-raw '{
        "vector_size": 4,
        "distance": "Dot"
    }'

## Expected Behavior

According to the docs the expected response should be:
```
{
    "result": true,
    "status": "ok",
    "time": 0.031095451
}
```

## Possible Solution
Did the API endpoint get changed?

## Context (Environment)
qdrant: v0.4.2

---

Also, I think it would be wise to put info on how to run qdrant inside the QUICK_START guide. From reading readme, it wasn't clear to me what config I should use and what should be the path to data? Does the data has to exist before I start the QUICK_START guide? I assumed no. Then the example in README (docker run ... /path/to/data ... /path/to/config) is not the best for QUICK_START. I would add something like:

```
Given you've already built or downloaded the Docker image, run this in your terminal window:

docker run -p 6333:6333 \
  -v $(pwd)/qdrant_storage:/qdrant/storage \
  generall/qdrant
  
Now that qdrant is running, let's create a collection with dot-production metric. In another terminal window run:

...
```

**Comment by generall** [comment]
Is it resolved?

**Comment by generall** [comment]
OpenAPI docs are currently updated for `master` and there are some changes related to `create collection` API which are not released yet

**Comment by melekes** [comment]
yeah, I was using QUICK_START from master w/ qdrant 0.4.2 (not master).

**Comment by generall** [comment]
Added a version selector to the OpenAPI Redoc page: https://github.com/qdrant/qdrant/pull/171

**Comment by generall** [comment]
Added version selector https://github.com/qdrant/qdrant/pull/171
