### ISSUE TITLE
Retrieve 1000 from 1 million took > 3 seconds with in-memory client

### ISSUE THREAD

**Issue by junwang-wish** [qdrant/qdrant#1704]
```
client = QdrantClient(":memory:", prefer_grpc=True)
client.recreate_collection(
    collection_name="clip_image_product",
    vectors_config=VectorParams(size=512, distance=Distance.COSINE),
)
# insert 1 million points
for chunk in tqdm(range(10000)):
    vectors = np.random.rand(100, 512)
    client.upsert(
        collection_name="clip_image_product",
        points=[
            PointStruct(
                id=idx+chunk*100,
                vector=vector.tolist(),
                payload={"color": ["red", "yellow", "blue"][idx%3], "rand_number": idx % 10}
            )
            for idx, vector in enumerate(vectors)
        ]
    )
# this took >3 seconds
query_vector = np.random.rand(512)
hits = client.search(
    collection_name="clip_image_product",
    query_vector=query_vector,
    limit=1000  # Return 5 closest points
)
```
This is far slower than the benchmarks, is it expected?

**Comment by generall** [comment]
Hi @junwang-wish! The local mode version is not optimized for performance, please consider switching to the server

**Comment by junwang-wish** [comment]
Thanks @generall so in my case I am deploying vectorDB along side Nvidia triton inference server with custom embedding models (deployed as single-node inference server via k8s). Due to internal infra constraints, it is nontrivial to setup a sidecar container in my k8s config, thus it'd be really convenient to use qdrant via a startup script / in-memory client instead of docker. Example would `python start.sh &` to start qdrant in the background. Is that possible?

**Comment by generall** [comment]
it is possible to just use qdrant as a binary file without docker.

**Comment by junwang-wish** [comment]
Thanks @generall it'd be great to have a shell script that downloads, installs and runs the binary. But I understand it could be relatively lower priority for your team.

**Comment by timvisee** [comment]
> Thanks @generall it'd be great to have a shell script that downloads, installs and runs the binary. But I understand it could be relatively lower priority for your team.

Qdrant currently doesn't have binary releases. That makes this a lot harder than a simple pull-and-execute.

**Comment by generall** [comment]
@timvisee do you have experience of making those binary releases?

**Comment by timvisee** [comment]
> @timvisee do you have experience of making those binary releases?

Yes, but mostly on GitLab CI, not GitHub.

**Comment by agourlay** [comment]
Took the liberty to put a minimal version together https://github.com/qdrant/qdrant/pull/1723
