### ISSUE TITLE
RocksDB Service Internal Error during ingest

### ISSUE THREAD

**Issue by suciokhan** [qdrant/qdrant#1725]
## Current Behavior
While attempting to create a database of Arxiv embeddings on a _remote server_ using the Python client after ingesting ~8000 records, I received the following error:
```
"error":"Service internal error: RocksDB put_cf error: IO error: While open a file for appending: ./storage/collections/arxiv_metadata_oai_db/0/segments/5ce2a7a0-13f4-48fe- ...'
```
After this, I'm unable to connect to the collection using the Python client, receiving `ResponseHandlingException: timed out` error.

## Steps to Reproduce

1. Create conda environment for python 3.10.10 on Ubuntu 20.04 for holding source data and executing the Python client to upcert data into the database.
2. Use a separate server with Ubuntu 20.04 to host the database.
2. Pull qdrant docker `docker pull qdrant/qdrant` on the server.
3. Run docker `sudo docker run -p 6333:6333  -v $(pwd)/qdrant_storage:/qdrant/storage  qdrant/qdrant`
4. Create a collection configured to quantize vectors using the Ubuntu client like this:  
```
# Create an new collection
client.recreate_collection(
    collection_name = new_database_name,
    vectors_config = VectorParams(size=768, distance=Distance.COSINE),
    optimizers_config = OptimizersConfigDiff(memmap_threshold=20000),
    quantization_config = ScalarQuantization(
        scalar=ScalarQuantizationConfig(
            type = ScalarType.INT8,
            always_ram = False)
            )
)
```
5. Iteratively, single-threaded, upsert records like this:
```
operation_info = client.upsert(
    collection_name=new_database_name,
    wait=True,
    points=[
        PointStruct(id=this_uuid,
                    vector=this_vector,
                    payload={"arxiv_id":arxiv_id,
                             "authors": authors,
                             "title":title,
                             "journal_ref":journal_ref,
                             "categories": categories,
                             "abstract":abstract,
                             "doi":doi},
                    )
            ]
        )
```

## Expected Behavior
All points get created in the database.

## Possible Solution
Unknown...perhaps it has to do with Docker configuration? I know next-to-nothing about Docker.

## Context (Environment)
If more RAM is needed, I have a good amount to spare.

## Detailed Description
Recommend troubleshooting guidance to help other users who might run into this issue.

## Possible Implementation
Perhaps add a troubleshooting section to the documentation on your website? Thanks for your attention- other than this I've been super happy with your documentation and how easy the client is to use.

**Comment by suciokhan** [comment]
After shutting down the docker and restarting, I'm able to curl and see the status of the database:

```
{"result":{"status":"green","optimizer_status":"ok","vectors_count":8179,"indexed_vectors_count":0,"points_count":8179,"segments_count":8,"config":{"params":{"vectors":{"size":768,"distance":"Cosine"},"shard_number":1,"replication_factor":1,"write_consistency_factor":1,"on_disk_payload":true},"hnsw_config":{"m":16,"ef_construct":100,"full_scan_threshold":10000,"max_indexing_threads":0,"on_disk":false},"optimizer_config":{"deleted_threshold":0.2,"vacuum_min_vector_number":1000,"default_segment_number":0,"max_segment_size":null,"memmap_threshold":20000,"indexing_threshold":20000,"flush_interval_sec":5,"max_optimization_threads":1},"wal_config":{"wal_capacity_mb":32,"wal_segments_ahead":0},"quantization_config":{"scalar":{"type":"int8","always_ram":false}}},"payload_schema":{}},"status":"ok","time":0.000057445}
```

It appears to be up again, but how do I prevent it from crashing during ingest?

**Comment by suciokhan** [comment]
Monitoring qdrant console logging- more details when I ran it again:

```
ai_db/points?wait=true HTTP/1.1" 200 93 "-" "python-httpx/0.23.3" 0.004012
[2023-04-13T16:36:29.603Z INFO  actix_web::middleware::logger] 192.168.xxx.xxx "PUT /collections/arxiv_metadata_oai_db/points?wait=true HTTP/1.1" 200 93 "-" "python-httpx/0.23.3" 0.002953
[2023-04-13T16:36:29.640Z ERROR segment::segment] Segment "./storage/collections/arxiv_metadata_oai_db/0/segments/0acd4bfc-be89-4f35-b5bf-40e0f5284995" operation error: Service runtime error: RocksDB put_cf error: IO error: While open a file for appending: ./storage/collections/arxiv_metadata_oai_db/0/segments/0acd4bfc-be89-4f35-b5bf-40e0f5284995/000305.sst: Too many open files
[2023-04-13T16:36:29.640Z ERROR collection::collection_manager::collection_updater] Update operation failed: RocksDB put_cf error: IO error: While open a file for appending: ./storage/collections/arxiv_metadata_oai_db/0/segments/0acd4bfc-be89-4f35-b5bf-40e0f5284995/000305.sst: Too many open files
```
It repeats those errors over and over.

**Comment by suciokhan** [comment]
I suspect this is relevant to my problem:

https://github.com/facebook/rocksdb/issues/4089

**Comment by suciokhan** [comment]
Unfortunately this did not resolve my issue. It's still dying at a little over 8000 insertions, even though I have my open file limit set to `64000` when it was previously `1024`.

**Comment by generall** [comment]
On some systems the default limit for opened files is too low. please try to increase it using https://docs.docker.com/engine/reference/commandline/run/#ulimit

For example you can set it to 65535

**Comment by generall** [comment]
Hi @suciokhan, did it work for you?

**Comment by suciokhan** [comment]
Sorry just got back to my PC- I will try it and report how it works asap.
