### ISSUE TITLE
This project violated Github TOS

### ISSUE THREAD

**Issue by selckin** [qdrant/qdrant#1732]
Andrey Vasnetsov scraped github for emails and send out a spam campaign promoting the project violating github TOS

Hi Thomas,

I came across your profile during scouring through GitHub. I assumed that you are proficient in similarity learning, so I thought to reach out.

We've developed an open-source vector search engine with advanced features https://github.com/qdrant/qdrant 
If it's a topic of your interest, I'll be happy to hear your feedback on it. Any insights, suggestions, criticism, or feature requests are very welcome.

Look forward to hearing back from you.

Best regards,
Andrey Vasnetsov
Co-founder & CTO at Qdrant

**Comment by azayarni** [comment]
Thanks for reporting! We will look into this and fix it as soon as possible.

**Comment by fbarbe00** [comment]
Please stop sending unsolicited spam emails about your GitHub projects

**Comment by azayarni** [comment]
Resolved for good. Thanks for your help.
