### ISSUE TITLE
Provide executable binaries in releases

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#1733]
**Is your feature request related to a problem? Please describe.**

Provide executable binaries when cutting releases.
This would lower the barrier of entry for new users who do not use Docker for some reason.

With such binaries we could provide scripts that download the latest release and start it locally with very low friction.

**Describe the solution you'd like**

The minimal set of targets could be:
- Linux x86
- Windows x86
- Mac x86
- Mac arm

There are two step required, the build for each target and then the upload to Github.

There are several Github actions available to produce binaries and upload them on a given event.

One example is https://github.com/taiki-e/upload-rust-binary-action which would require additional setup to install our build dependencies.

Otherwise we could separate the build step from the upload step manually.

**Comment by agourlay** [comment]
For inspiration I would recommend having a look at what the awesome folks at Quickwit did for their release pipeline.

It seems very similar to what I described previously.

e.g https://github.com/quickwit-oss/quickwit/releases/tag/v0.5.0

from https://github.com/quickwit-oss/quickwit/blob/main/.github/workflows/publish_release_packages.yml

**Comment by Shubham8287** [comment]
I have some experience to use [upload-rust-binary-action](https://github.com/taiki-e/upload-rust-binary-action) and CIs in past, Would love to take this issue. Can you assign it to me?

**Comment by edgerunnergit** [comment]
Don't have any prior experience with the suggested github action, but still interested in taking a shot at this. 

Also could you please clarify whether for "bounty" tagged issues, whether you plan to assign users based on first come first serve basis or whoever sends a PR first?

**Comment by generall** [comment]
If there will be 2 PRs, we will chose the best one. We can assign task only if you have a time estimation for this task to complete

**Comment by Shubham8287** [comment]
Actually, I started working on it https://github.com/Shubham8287/qdrant/pull/1 :). I also want to spend time reading the Contribution doc and proper testing instead of doing things in too hurry

**Comment by Shubham8287** [comment]
@generall I will Raise the PR for it by today. I have already started working on it as per the above comment.

**Comment by agourlay** [comment]
Please be advised that it is not simply a matter of **using** the aforementioned GA.

There are system dependencies required at build time that can be found in our [Docker file](https://github.com/qdrant/qdrant/blob/master/Dockerfile#L24-L26).

I have already tested a vanilla setup myself https://github.com/qdrant/qdrant/pull/1723 :smiling_face_with_tear: 

The build and upload phase will most likely have to be separated like in my recommendation comment above.

**Comment by Shubham8287** [comment]
thanks for more clarification to build separately, I see that's necessary. I do expect to improvise my workflow a few times before making a final PR.

**Comment by Shubham8287** [comment]
@agourlay Since system dependencies can vary in version between different environments, this may cause issues. Would you like me to pin the dependencies to specific major versions or use the default versions for each OS

**Comment by generall** [comment]
@Shubham8287 if you mean the protobuf version e.t.c. I think latest available for each platform will do. Otherwise we need a place where dependabot can monitor those versions

**Comment by Shubham8287** [comment]
You may like to review the PRs, It is generating binaries for macos and linux :)

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/qdrant/releases/tag/v1.2.0
