### ISSUE TITLE
Batch Search is too slow and does not call qdrant in parallel?

### ISSUE THREAD

**Issue by junwang-wish** [qdrant/qdrant#1734]
Batch search with batch size of 10 is almost 10x slower than Batch search with batch size of 1. Shouldn't Batch search send requests to qdrant in parallel for speedup? This is my code
```
from qdrant_client import QdrantClient
from qdrant_client.http.models import SearchRequest
from qdrant_client.models import Distance, VectorParams, PointStruct, OptimizersConfigDiff
import numpy as np
from tqdm import tqdm

ann_client = QdrantClient(url="http://localhost:6334", prefer_grpc=True)

# batch search with bsize=1
search_queries = [
    SearchRequest(
        vector=np.random.random(512).tolist(),
        limit=1000,
        with_payload=False
    ) for ind in range(1)
]

for i in tqdm(range(100)):
    res = ann_client.search_batch(
        collection_name="dummy",
        requests=search_queries

# batch search with bsize=10
search_queries = [
    SearchRequest(
        vector=np.random.random(512).tolist(),
        limit=1000,
        with_payload=False
    ) for ind in range(10)
]

for i in tqdm(range(100)):
    res = ann_client.search_batch(
        collection_name="dummy",
        requests=search_queries
```
here are the tqdm bar
```
# batch size with bsize=1 --> 71 iters/s --> 71 searches /s since bsize=1
100%|████████████████████████████████| 100/100 [00:01<00:00, 71.39it/s]

# batch size with bsize=10 --> 9 iters/s --> 90 searches /s since bsize=10
100%|████████████████████████████████| 100/100 [00:11<00:00,  8.99it/s]
```
Based on the tqdm bars above, there isn't significant speed up by using Batch search, which defeats the purpose of Batching? My experience of using async calls is that it should improve speed by an order of magnitude, i.e. using for loop to call openai api for ten times is ~10x slower than using async for loop then await.

Therefore, what is the proper way to parallelize requests so they are truly sent to qdrant backend in parallel and processed concurrently ? Assuming it might involve use of asyncio ? This is related to https://github.com/qdrant/qdrant-client/issues/155

**Comment by agourlay** [comment]
Thanks for reaching out!

Reading your snippet, I am not sure  where the 10x slowdown is visible.

The following snippet generates 100 search_batch containing each a single search query.
Each iteration of the benchmark processes a single query.

```python
# batch search with bsize=1
search_queries = [
    SearchRequest(
        vector=np.random.random(512).tolist(),
        limit=1000,
        with_payload=False
    ) for ind in range(1)
]

for i in tqdm(range(100)):
    res = ann_client.search_batch(
        collection_name="dummy",
        requests=search_queries
```

Whereas the following snippet 100 search_batch containing each 10 search query.
Each iteration of the benchmark processes 10 queries.

```python
# batch search with bsize=10
search_queries = [
    SearchRequest(
        vector=np.random.random(512).tolist(),
        limit=1000,
        with_payload=False
    ) for ind in range(10)
]

for i in tqdm(range(100)):
    res = ann_client.search_batch(
        collection_name="dummy",
        requests=search_queries
```

100 times a single requests represents 10x less of work than 100 times with batch of 10.

My understanding is that you should compare instead either:
- 100 non batched requests vs 1 batched requests with 100 elements
- 100 non batched requests vs 10 batched requests with 10 elements

Am I getting this right?

**Comment by junwang-wish** [comment]
Thanks @agourlay so there might be some misunderstanding. 

Essentially I would like to call qdrant in an async way and process multiple requests in parallel, similar to how I call OpenAI api async, as below. With the script below, getting 10 responses from OpenAI takes approx the same time as getting 1 response from OpenAI, and thus batching 10 requests to OpenAI in this async way creates a 10x speedup.

I was expecting the same type of speedup when sending qdrant a batch of 10, but based on the script I shared, it did not enable a 10x speedup.

I want to know if there is a way to start 10 async calls to qdrant and get 10 responses that takes similar time as 1 call to qdrant, just like how I dealt with OpenAI api.
```
import asyncio
import aiohttp
import logging
import os 
OPENAI_KEY = os.environ['OPENAI_KEY']
headers = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {OPENAI_KEY}"
}

async def call_oai(session, data):
    try:
        async with session.post(
            'https://api.openai.com/v1/chat/completions',
            headers=headers,
            json=data
        ) as response:
            res = await response.json()
        return data, res
    except Exception as e:
        logging.error(f"{data} failed due to {e}")
        return data, None

async def call_oais(datas):
    async with aiohttp.ClientSession() as session:
        tasks = []
        for data in datas:
            task = asyncio.ensure_future(call_oai(session, data))
            tasks.append(task)
        reses = await asyncio.gather(*tasks)
        return reses
```

**Comment by generall** [comment]
>  With the script below, getting 10 responses from OpenAI takes approx the same time as getting 1 response from OpenAI, and thus batching 10 requests to OpenAI in this async way creates a 10x speedup

I guess the reason here is that in OpenAI you are paying for each embedding separately, so they are happy to throw whatever resources they have to complete your query as fast as possible.

In qdrant, batch request allows to spare some resources on establishing network connection / re-using filters, but it is still limited by the resources of the machine you are running it on.

**Comment by junwang-wish** [comment]
Thanks @generall , I understand, and want to work with you and your team to utilize qdrant in production. 
So in this specific case (posted above) I over-allocated resources with
```
cpu: 20 vCPU
memory: 100 Gb
instance: g4dn.12xlarge
```
I am only testing 1M 512-dim vectors in the above example, and retrieving 1000 items, and the QPS is ~100, latency is >100ms. With the hardware allocated, I would really hope to support
```
retrieve 1000 vectors from 10-50 Million 512-dim vectors, QPS ~1000, latency < 50ms
```
I do believe the hardware allocated has enough resources to achieve the goal above (correct me if wrong), but what caused the bottleneck such that even with 1 Million vectors, the QPS << 1000 and latency >> 50ms? 

I'd love to work with the team to fix the bottleneck to demonstrate the ROI for vector search.

**Comment by generall** [comment]
@junwang-wish, of course, would be glad to help you!

We would need some more information about your case to do so. Could you please reach us our on discord https://qdrant.to/discord , we can answer your questions in more convenient way
