### ISSUE TITLE
"Service internal error: Failed to flush id_tracker versions: Service runtime error: RocksDB flush_cf error: IO error: While open a file for appending: /var/lib/qdrant/storage/collections/gc_first_test/0/segments/3a8d5b7d-fc41-492e-91aa-7770e8900832/000036.sst: Too many open files"

### ISSUE THREAD

**Issue by happysalada** [qdrant/qdrant#1736]
here is the error I'm running into
"Service internal error: Failed to flush id_tracker versions: Service runtime error: RocksDB flush_cf error: IO error: While open a file for appending: /var/lib/qdrant/storage/collections/gc_first_test/0/segments/3a8d5b7d-fc41-492e-91aa-7770e8900832/000036.sst: Too many open files"

## Steps to Reproduce
I'm not sure how to reproduce this, I've got about 4 million datapoints in that collection, I don't know if it's related or not
I'm running qdrant 1.1.0
1.
2.
3.
4.

**Comment by generall** [comment]
check out https://github.com/qdrant/qdrant/issues/1725

**Comment by generall** [comment]
hi @happysalada, did `--ulimit nofile=65535:65535` solution helped?

**Comment by happysalada** [comment]
When running a systemd service there is a particular setting for that, ulimit is not global and doesnt permanently change settings.
I dont remember off the top of my head which setting it was, but that solved the problem.
