### ISSUE TITLE
Panic occurred in file /build/cargo-vendor-dir/actix-server-2.1.1/src/worker.rs at line 425: called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: \"Too many open files\"

### ISSUE THREAD

**Issue by happysalada** [qdrant/qdrant#1737]
getting the following error
Panic occurred in file /build/cargo-vendor-dir/actix-server-2.1.1/src/worker.rs at line 425: called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: \"Too many open files\"

## Steps to Reproduce
with version 1.1.0
I've got a script running at 3000 rpm uploading datapoints to qdrant while it's starting. 
I'm guessing the service needs to be fully started before properly being able to handle files
1.
2.
3.
4.

**Comment by happysalada** [comment]
I also get a related error when trying to shut down the node after a panic

2023-04-15T02:56:11.477Z ERROR collection::update_handler] Failed to flush: Service runtime error: Failed to flush id_tracker mapping: Service runtime error: RocksDB flush_cf error: IO error: While open a file for appending: /var/lib/qdrant/storage/collections/gc_first_test/0/segments/f9e7d195-3dd3-44a2-857b-09e6442a9e22/000024.sst: Too many open files

**Comment by eliassama** [comment]
First, you need to make sure the service is running on SSDS
Second, you can refer to the https://qdrant.tech/documentation/how_to/#bulk-upload-a-large-number-of-vectors

**Comment by generall** [comment]
https://github.com/qdrant/qdrant/issues/1725

**Comment by saurabhmj11** [comment]
The error message "Too many open files" indicates that the application has reached the limit of the maximum number of open files allowed by the operating system. This can happen if the application is opening too many files and not closing them properly, or if the system's limit is too low.

To resolve this issue, you can try increasing the maximum number of open files allowed by the operating system. On Linux, you can use the ulimit command to increase the limit temporarily or permanently. For example, to set the limit to 100000 files, you can use the command:

bash
Copy code
ulimit -n 100000
If you are running the application in a Docker container, you can set the ulimit using the --ulimit option when starting the container.

Alternatively, you can try reducing the number of open files used by the application by closing files when they are no longer needed or by using file descriptors more efficiently.

If the issue persists, it's possible that there is a bug in the application that is causing it to open too many files. You can try debugging the application to identify the source of the issue and fix it.

Regarding the issue of the service needing to be fully started before properly handling files, it's possible that the application is trying to access files before they are available or before they have been fully initialized. You can try adding some delay or retry logic to the application to ensure that files are available before accessing them.

Without more information about your specific environment and application, it's difficult to provide a more detailed solution or implementation.

**Comment by happysalada** [comment]
Hey thanks ! Im running this as a systemd service and increasing the number of open file resolved the problem
