### ISSUE TITLE
Built in api-key auth

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1739]
**Is your feature request related to a problem? Please describe.**
As a follow-up for https://github.com/qdrant/qdrant/issues/1499

In some scenarios it is desirable to have basic protection from the external connections. For example, when serving Qdrant to the Internet or local corp network, where you don't trust your own co-workers.

**Describe the solution you'd like**
Implement api-key-based authentication, which should follow the same pattern as authentication in qdrant cloud (so clients should be compatible out of the box):

If configured, header `api-key: <API-KEY>` should be checked in both REST and gRPC interfaces. If api key doesn't match, the 403 error with explanation should be returned.

API key should be configurable via the `config.yaml` and by default it is None, so no auth is required.

Api key could be an arbitrary string.

**Describe alternatives you've considered**
Delegate authentication to external service.
Even though, it is generally preferable and more flexible solution, in some cases the added complexity is too high.

**Additional context**
There is another useful scenario of limiting access to only the read-only API. As well fine-grained access control. This scenario should be addressed in further tasks.

**Comment by paulotten** [comment]
I'll take a stab at this.

**Comment by dentroai** [comment]
yes, multiple API Keys are very important indeed! 
Also creating API Keys per project that can't access other projects would be important.

**Comment by coszio** [comment]
@dentroai Qdrant Cloud has an API Key builder for ease of use, but it can be used in open-source as well like this:

https://qdrant.tech/documentation/guides/security/#granular-access-control-with-jwt

**Comment by timvisee** [comment]
Also note that [Qdrant Cloud](https://qdrant.to/cloud) offers this out of the box. It allows you to easily create and manage multiple API keys from the Cloud dashboard.
