### ISSUE TITLE
unable to restore from full snapshot

### ISSUE THREAD

**Issue by suciokhan** [qdrant/qdrant#1747]
## Current Behavior
When I attempt to restore from a full snapshot, I receive the following error:

```
[2023-04-18T12:25:25.851Z INFO  storage::content_manager::consensus::persistent] Loading raft state from ./storage/raft_state
[2023-04-18T12:25:25.856Z ERROR qdrant::startup] Panic occurred in file src/snapshots.rs at line 91: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

## Steps to Reproduce
1. Created full-snapshot on remote server running Docker of Qdrant.
2. Copy snapshot to other computer.
3. Copy the snapshot onto the local Qdrant docker: `docker cp full-snapshot-2023-04-17-17-25-00.snapshot dockerid:/qdrant/snapshots/`
4. Confirm local Qdrant sees the snapshot with Python client: `client.list_full_snapshots()`
5. Access local Qdrant container: `docker exec -it dockername bash`
6. Execute the restore command: `./qdrant --storage-snapshot /snapshots/full-snapshot-2023-04-17-17-25-00.snapshot`

Unfortunately the data is an 11 GB snapshot- not something I can easily share here :(

## Expected Behavior
Restoration of collections in a fresh Qdrant docker instance on local computer which were created on a different Qdrant instance on a separate computer.

## Possible Solution
Unknown. 

## Context (Environment)

This is impacting mobility of the database. I used a server I'm unable to move or remotely-access to create the database due to its processing power, but now that I have it built I'd like to keep it on my laptop so I can take it with me.

When I attempt to perform a restoration from a full-snapshot on a fresh Qdrant docker image, it fails.

## Detailed Description

If I'm simply doing something wrong that is easily-fixable, please add more detailed instructions in the Documentation to help others in the future.

## Possible Implementation
See above

**Comment by generall** [comment]
Based on your mount path,
the command should be `./qdrant --storage-snapshot /qdrant/snapshots/full-snapshot-2023-04-17-17-25-00.snapshot`

**Comment by generall** [comment]
Also, instead of "Copy the snapshot onto the local Qdrant docker"  it might be better to mount directory as a volume

**Comment by suciokhan** [comment]
> 

Ah, that did the trick- I thought it was relative to the directory I was in, since I was calling ./qdrant inside of the /qdrant/ directory.  This appears to have loaded the collections successfully:

```
print(collection_info.status)
print(collection_info.vectors_count)
```
Results in:
```
CollectionStatus.GREEN
2231517
```

Thanks very much for your help.
