### ISSUE TITLE
filter qdrant searching by score

### ISSUE THREAD

**Issue by ainilian** [qdrant/qdrant#1748]
Hi, Can qdrant filter the searching results by score. like the example:
POST http://7.xx.xx.xx:6333/collections/{collection_name}/points
{
   "filter":
    {
        "should":[{
            "key":"score",
            "range":{
                "gte":0.01
            }
    }]
},
    "vector":[0.030077174305915833,0.03349129855632782,...]
}

**Comment by generall** [comment]
there is score_threshold

https://qdrant.tech/documentation/search/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uOm50aC1vZi10eXBlKDIpID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIHA6bnRoLW9mLXR5cGUoMjIp#filtering-results-by-score
