### ISSUE TITLE
Wrong input: Vector inserting error: expected dim: 1, got 1536

### ISSUE THREAD

**Issue by james-ok** [qdrant/qdrant#1752]
The Upsert points interface encountered an exception

Wrong input: Vector inserting error: expected dim: 1, got 1536

**Comment by generall** [comment]
Hi @james-ok, could you please describe how to reproduce your issue?

**Comment by generall** [comment]
@james-ok I am closing this issue, as there is not enough context to provide any assistance. Please feel free to re-open the issue with additional info
