### ISSUE TITLE
Custom PointIdType

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#1756]
**Is your feature request related to a problem? Please describe.**
Qdrant supports point type num and uuid
I have an unique custom string id.
Can You add a new type of point id as String?

Thanks.

**Comment by generall** [comment]
We decided to not support arbitrary string IDs - here is a reasoning behind this https://github.com/qdrant/qdrant/issues/810#issuecomment-1183549781
If you need custom IDs, you can store it as payload - there are almost every function available with filters. so you can delete, update and retrieve based on payload value

**Comment by ava57r** [comment]
Thanks.
