### ISSUE TITLE
Expose async GRPC request for Python client

### ISSUE THREAD

**Issue by junwang-wish** [qdrant/qdrant#1760]
Roughly, the Latency/throughput-wise for >50 concurrent request of >1000 vector retrieval:
`async grpc > async http > grpc > http`
Can we expose `async grpc` so that 1000 QPS retrieval of 1000 vectors per request on 10-20M 512-dim vectors can be achievable with 20 vCPUs and 100Gb RAM? 

Currently I am having 400 QPS doing retrieval of 1000 vectors per request on 1M 512-dim vectors, seem a bit slow, or is it expected?

Assuming P95 latency < 100ms of course

**Comment by generall** [comment]
https://github.com/qdrant/qdrant-client/pull/159
