### ISSUE TITLE
Store the same pointId multiple times in the same collection. Does qdrant keep only the latest copy or will it keep the one that was previously stored?

### ISSUE THREAD

**Issue by eliassama** [qdrant/qdrant#1761]
Store the same pointId multiple times in the same collection. Does qdrant keep only the latest copy or will it keep the one that was previously stored?

**Comment by generall** [comment]
yes, ids should be unique, otherwise it will overwrite the point. But you can put your custom ids into payload and do pretty much everything with it - retrieve, update, delete, e.t.c.

**Comment by eliassama** [comment]
> yes, ids should be unique, otherwise it will overwrite the point. But you can put your custom ids into payload and do pretty much everything with it - retrieve, update, delete, e.t.c.

ok, thanks
