### ISSUE TITLE
Implement `order_by` functionality in scroll API

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1763]
**Is your feature request related to a problem? Please describe.**
There is a number of use-cases where it might be convenient to have a way to retive points, ordered by some specific payload key.

For example, there is a e-commerce search, but instead of searching similar products, we want to retrieve products by price.
Usually, we would be done by some SQL database, but if we already have Qdrant in place, it should be possible to cover this functionality as well, just to avoid additional database.

**Describe the solution you'd like**

One solution is to introduce `order_by` parameter to `scroll` method, which will be used to sort results by some payload key.
Functionality should be working like this:

- User creates a scroll with `order_by` parameter, which is a key in payload.
- Payload key should be have a numerical index.
- Qdrant will read the index sorted by payload key, and will return results sorted by combination of (paylaod_value, id).
- Additionally, reasults should be filtered by `offset` id parameter, so that we won't duplicate results, even if some point has multiple values for the same payload key.

Reading of the next page in this scenario should be done by passing `offset` parameter, which is a `next_page_offset` from the previous response + filtering by `order_by` key.

Alternatively, it might be more convenient if in addition to `order_by` parameter, we could also pass `offset` param into this field. So it looks like this:

Example of the request:

```
POST /collections/collection_name/points/scroll
{
    "order_by": {
        "key": "price",
        "direction": "asc/desk", <-- optional, default is "asc"
        "offset/min/max": 100 <-- optional, required if we want the next page 
    },
    "offset": "123e4567-e89b-12d3-a456-426614174000"
}
```

**Describe alternatives you've considered**

In addition to `order_by` parameter into search request and use it to sort top-k results.
But it might be not efficient, because we will need to read all the points, and then sort them. 
And it might also be done by the client with minimal additional effort.

**Additional context**

Acceptance criteria:

- [ ] `order_by` parameter is added to `scroll` method
- [ ] `order_by` parameter is optional
- [ ] there are tests for this functionality
- [ ] implementation is efficient, meaning that it doesn't require to full-scan the collection if we want to retrieve points with high offset/min/max values

**Comment by roxanne-mackinnon** [comment]
Could someone please elaborate on the type and usage of the 'offset/min/max' parameter? My understanding is that in the example, if 'direction' is 'asc', and 'offset' is 100, the API should return at most 'limit' points in the range starting with the offset ID, with price <= 100. It this understanding correct?

**Comment by bmanturner** [comment]
No, offset is used for pagination of data. Offset of 100 means you skip 100 items. Example: if you fetch 10 items at a time, you would set offset to 0 for the first ten, 10 for the NEXT ten, 20 for the ten after that, etc.

Min, used in conjunction with direction of "asc" would indicate the id of the first item to return.
Max, used in conjunction with direction of "desc" would indicate the id of the first item to return.

Disclaimer: I've never worked in this codebase. I'm just explaining basic sort/pagination schemes. Someone from qdrant should clarify what they want.

**Comment by generall** [comment]
In our understanding - `offset` is the ID of the point, to start scroll from. It works, if we have scroll ordered by IDs. But if we introduce sorting by some other field - next page is not going to be offset-ted by id anybore (except for the cases, where all payload values are the same and we need to scroll over the page with those equal values). As a result - we need to specify 2 parameters for process in scrolling if we want to to be ordered by payload value.

**Comment by midepeter** [comment]
@generall Is this issue still open and can i still shoot my shot at it.. Thank you

**Comment by iho** [comment]
@roxanne-mackinnon do you have any progress? I can take this task

**Comment by roxanne-mackinnon** [comment]
@iho Yes, I'm almost done. I had to put it on pause while I was finishing my final exams, but I'm almost finished.

**Comment by kfernandez31** [comment]
@roxanne-mackinnon can I take over or will you be submitting a PR soon?

**Comment by BabaBert** [comment]
I also started looking into this, but I don't know if I'll be able to finish it. For the record though /attempt #1763

**Comment by lecoqjacob** [comment]
@BabaBert if you need assistance or someone to take over the work let me know! Looks like you have a good bit of the implementation down

**Comment by BabaBert** [comment]
@generall what exactly do you mean by "implementation is efficient, meaning that it doesn't require to full-scan the collection if we want to retrieve points with high offset/min/max values"?
Correct me If I'm wrong but if I want to read the index sorted by payload key, well, I have to at least one sort the index requiring a full scan.
You could cash the result for further paginations but, I don't, see how this can be achieved differently.

**Comment by zaidsasa** [comment]
Will this feature be implemented in Search API as well ?

Thanks
