### ISSUE TITLE
Is it possible to create collection without vectors?

### ISSUE THREAD

**Issue by snarb** [qdrant/qdrant#1782]
I want to have collection of texts with access by ID, with key value behavior like redis. 
To not have both redis and qdrant. Is it possible in qdrant only?

**Comment by generall** [comment]
yes, it is!
You can do it like this:

```
curl -L -X PUT 'http://localhost:6333/collections/no-vectors' \
-H 'Content-Type: application/json' \
-d '{
    "vectors": {}
}'
```
