### ISSUE TITLE
Qdrant Cloud: In the case of `memmap_threshold=20000`, the QPS is very low on a 5 million 768-dimensional dataset.

### ISSUE THREAD

**Issue by MochiXu** [qdrant/qdrant#1789]
## Current Behavior
I want to use [vector-db-benchmark](https://github.com/qdrant/vector-db-benchmark) to test the performance of a dataset containing **5 million 768-dimensional vectors** on qdrant cloud's **Storage optimized** mode. However, the final QPS obtained is very low.

**Please help me to set the index creation parameters of HNSW for the above 5 million 768-dimensional vector data in Storage optimized mode, to achieve the goal of minimizing memory usage while maintaining a relatively high QPS.**

## Steps to Reproduce
1. Create a cluster on qdrant cloud with a configuration of `2 CPUs`, `16GB RAM`, and `1 node`. The service provider is AWS `us-east-1`.
2. Deploy `vector-db-benchmark` on an AWS `us-east-1` virtual machine with a resource configuration of `4 cores` and `8GB` RAM.
3. Here is my qdrant `HNSW` vector index configuration
```json
"collection_params": {
      "optimizers_config": {
        "memmap_threshold": 20000
      },
      "hnsw_config": {
        "m": 16,
        "ef_construct": 128
      }
    }
```
4. Here is search result.json, when search parallel=1, the QPS is 0.309.
<img width="590" alt="e4212927-ca6b-475b-9ee4-90b6ebc163c0" src="https://user-images.githubusercontent.com/42711279/234621202-076a87f7-fa69-4a7e-b895-1eca1da82f0c.png">

5. Here is qdrant cloud metric
<img width="1154" alt="f179d652-2ed3-41ce-89fc-743c49fbc592" src="https://user-images.githubusercontent.com/42711279/234621766-d3bd2d6f-b46f-4ad8-9f25-e32eecdc71fc.png">

**Comment by timvisee** [comment]
> We will look into options of how to improve this initial timings

Doing [`madvice(MADV_WILLNEED)`](https://man7.org/linux/man-pages/man2/madvise.2.html) on the memory mapped pages may be one approach. But I'm not sure what effect this has when the dataset is huge.

**Comment by MochiXu** [comment]
I have another question to ask. After version v1.1.0, qdrant can use quantization_config to create an index. Below is the index configuration I used. The dataset used is still 5 million vectors of 768 dimensions, but the QPS can only reach around 1-2.

**Comment by MochiXu** [comment]
When I disable the `optimizers_config` option, qdrant consumes 22GB of memory for a 5 million 768-dimensional vector datasets with only the `quantization_config` configuration. Is this expected?

```json
"quantization_config": {
        "type": "int8",
        "quantile": 0.99,
        "always_ram": true
      }
```

**Comment by generall** [comment]
yes, it is about right:

```
5000000 x 768 x 4 - original vectors
+ 
5000000 x 768 - quantized
+
~30% indexes
```

Qdrant always keeps the original vectors, you can put them on disk, by configuring the optimizer.

**Comment by generall** [comment]
ToDo: bechmark the cloud with advanced configuration - io_uring + hybrid disks
