### ISSUE TITLE
Cluster peer_id larger than Javascript Int max value

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#1796]
The peer_id returned in the `/cluster`API  cannot be safely used as it has been rounded during the serialization process.

## Current Behavior

Examples with a cluster of two nodes

`10679558528704629386` turns into `10679558528704629000`

```json
{
  "result": {
    "status": "enabled",
    "peer_id": 10679558528704629000,
    "peers": {
      "4155833442222845257": {
        "uri": "http://127.0.0.1:6345/"
      },
      "10679558528704629386": {
        "uri": "http://localhost:6335/"
      }
    },
    "raft_info": {
      "term": 1,
      "commit": 3,
      "pending_operations": 0,
      "leader": 10679558528704629000,
      "role": "Leader",
      "is_voter": true
    },
  }
}
```

`4155833442222845257` turns into `4155833442222845400` 

```json
{
  "result": {
    "status": "enabled",
    "peer_id": 4155833442222845400,
    "peers": {
      "4155833442222845257": {
        "uri": "http://127.0.0.1:6345/"
      },
      "10679558528704629386": {
        "uri": "http://localhost:6335/"
      }
    },
    "raft_info": {
      "term": 1,
      "commit": 3,
      "pending_operations": 0,
      "leader": 10679558528704629000,
      "role": "Follower",
      "is_voter": true
    },
  }
}
```

## Steps to Reproduce

Create a cluster with two nodes and call `curl localhost:6343/cluster | jq .`

## Expected Behavior

The peer_id should not be altered by the serialization.

## Possible Solution

This issue is due to the difference in size between Rust u64 and Javascript Integer which is 53-bit wide.

This is visible when parsing a peer_id in Javascript

```javascript
> parseInt("10679558528704629386")
10679558528704629000
```

A naive solution would be to represent the peer_id as Strings in the API.
But it would be a breaking change, introducing a new field `peer_id_str` could mitigate the issue.

**Comment by generall** [comment]
I think it is a JS bug, not Qdrant.

**Comment by agourlay** [comment]
tackled in https://github.com/qdrant/qdrant/pull/1813
