### ISSUE TITLE
Issue creating Full Snapshots

### ISSUE THREAD

**Issue by epicshardz** [qdrant/qdrant#1802]
Current Behavior
When calling client.create_full_snapshot(), a TimeoutError is raised with the message "The read operation timed out".

Steps to Reproduce
Call client.create_full_snapshot().
Wait for the operation to time out.
Expected Behavior
The operation should complete successfully and return a full snapshot.

Possible Solution
One possible solution is to increase the timeout period for the operation, or to improve the server connection to reduce the likelihood of timeouts occurring.

Context (Environment)
This issue is affecting users who are trying to create full snapshots using the client library. The TimeoutError is preventing the operation from completing, which is causing frustration for users who need access to their snapshots.

Detailed Description
The issue appears to be related to a network timeout that is occurring during the operation. This could be due to a slow or unreliable network connection, or a problem with the server that is being accessed. Increasing the timeout period for the operation may help to resolve the issue, or improving the network connection could also be beneficial.

Possible Implementation
To implement a solution, the timeout period for the operation could be increased in the client library. Alternatively, users could be advised to check their network connection and try the operation again at a later time if they continue to experience timeouts.

(ChatGPT to the bug and made that report ^^^  following the format)

The error code is as follows:
```
TimeoutError                              Traceback (most recent call last)
File [~\AppData\Roaming\Python\Python310\site-packages\httpcore\_exceptions.py:10](https://file+.vscode-resource.vscode-cdn.net/d%3A/Downloaded/CodeBuddy/CodeBuddy/~/AppData/Roaming/Python/Python310/site-packages/httpcore/_exceptions.py:10), in map_exceptions(map)
      9 try:
---> 10     yield
     11 except Exception as exc:  # noqa: PIE786

File [~\AppData\Roaming\Python\Python310\site-packages\httpcore\backends\sync.py:28](https://file+.vscode-resource.vscode-cdn.net/d%3A/Downloaded/CodeBuddy/CodeBuddy/~/AppData/Roaming/Python/Python310/site-packages/httpcore/backends/sync.py:28), in SyncStream.read(self, max_bytes, timeout)
     27 self._sock.settimeout(timeout)
---> 28 return self._sock.recv(max_bytes)

File [c:\Python310\lib\ssl.py:1258](file:///C:/Python310/lib/ssl.py:1258), in SSLSocket.recv(self, buflen, flags)
   1255         raise ValueError(
   1256             "non-zero flags not allowed in calls to recv() on %s" %
   1257             self.__class__)
-> 1258     return self.read(buflen)
   1259 else:

File [c:\Python310\lib\ssl.py:1131](file:///C:/Python310/lib/ssl.py:1131), in SSLSocket.read(self, len, buffer)
   1130     else:
-> 1131         return self._sslobj.read(len)
   1132 except SSLError as x:

TimeoutError: The read operation timed out
...
     96 except Exception as e:
---> 97     raise ResponseHandlingException(e)
     98 return response

ResponseHandlingException: The read operation timed out
```

I am also getting varying snapshot size, for the same unchanged cluster.

**Comment by agourlay** [comment]
How big is the snapshot being created?
Maybe it is simply too big to be created within the `timeout`.

Also it is possible to use the snapshot API in an asynchronous fashion by setting the `wait` param. to false https://qdrant.github.io/qdrant/redoc/index.html#tag/snapshots/operation/create_full_snapshot

I assume the option is available in the Python driver.

**Comment by generall** [comment]
Please feel free to re-open this issue if there is any more context for reproduction
