### ISSUE TITLE
How to perform searches with index on disk

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#1807]
Hi,

1. I create a collection 
client = QdrantClient("localhost", port=6333)

client.recreate_collection(
    collection_name="test_collection",
    vectors_config=VectorParams(size=1024, distance=Distance.DOT),
)
2. I search against that collection
print(client.search(
        collection_name="test_collection",
        query_vector=v,
        limit=3,
    ))
 This works. 
3. But when I save the index to disk 

client.recreate_collection(
    collection_name="test_collection",
    vectors_config=models.VectorParams(size=1024, distance=models.Distance.COSINE),
    optimizers_config=models.OptimizersConfigDiff(memmap_threshold=20000),
    hnsw_config=models.HnswConfigDiff(on_disk=True)
)

My search results are blank/empty.

Do I have to modify my search query or possibly change the way Im creating the index on disk??
Thanks in advance

Ajay

**Comment by generall** [comment]
`client.recreate_collection` deletes your existing collection with all data. You need to create a collection with proper params before you insert your data

**Comment by nairajay2k** [comment]
How do I add an on_disk index after inserting data?

**Comment by generall** [comment]
https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/update_collection

**Comment by nairajay2k** [comment]
> 

Doesnt look like  a vector index. Its asking for a field_name which I dont think is present for vector. Im a newbie so maybe I have misunderstood.
Thanks

**Comment by generall** [comment]
Try something like this:

```
curl -L -X PATCH 'http://localhost:6333/collections/<collection-name>' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
  "optimizers_config": {
    "memmap_threshold": 10000
  }
}'
```

**Comment by nairajay2k** [comment]
I disabled the indexing during insert of 10 M points as follows
client = QdrantClient("localhost", port=6333)

client.recreate_collection(
    collection_name="{collection_name}",
    vectors_config=models.VectorParams(size=768, distance=models.Distance.COSINE),
    optimizers_config=models.OptimizersConfigDiff(
        indexing_threshold=1000000000,
    ),
)
I followed your steps, with the following body
{

    "optimizers_config": {
        "memmap_threshold": 20000,
        "indexing_threshold": 20000
    },
    "hnsw_config": {
        "on_disk": true
    }
}
The search is still not working even after the curl ended (quickly in about 0.009 sec). But I notice my CPU is very active now. Could it be the indexing which is running in the background causing this?

**Comment by generall** [comment]
yes, indexing works in the background. But what do you mean by search not working? it should return some results, even without index. It might be slow, though

**Comment by nairajay2k** [comment]
the search was timing out. It worked after a few minutes though and my cpu utilization came down to normal.

**Comment by nairajay2k** [comment]
Is it possible to do "Group By" kind of aggregation with qdrant? If yes, pl provide a sample code. If not, is it on the roadmap, and when can it be expected?

**Comment by generall** [comment]
it is currently in development

**Comment by nairajay2k** [comment]
Some of my bulk upserts of points are failing due to timeout. What is the default and how can I change the default timeout for upsert? Please provide some python code.
Thanks in advance
Ajay

**Comment by coszio** [comment]
Hi @nairajay2k, are you still having this issue? 

It looks like you might be using `wait=true`, in which case doing smaller batches will help. Alternatively you can [make the http request](https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/upsert_points) separately and specify a longer timeout like [this](https://reqbin.com/code/python/3zdpeao1/python-requests-timeout-example)

**Comment by nairajay2k** [comment]
No I was using wait=false AFAIK but anyway the issue got resolved by setting a higher timeout.
Thank you
