### ISSUE TITLE
Appendable MMAP vector storage

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1818]
**Is your feature request related to a problem? Please describe.**
Right now it is only possible to build MMAP vector storage once (which is usually done by optimizer).
That prevents users from starting with MMAP vector storage right away. The main limitation for this was the impossibility to resize mmaped file. 

**Describe the solution you'd like**
Implement chunked MMAP storage, similar to `ChunkedVectors`: https://github.com/qdrant/qdrant/blob/842e86434e35ac9eb44a6c858165534a89180614/lib/segment/src/vector_storage/chunked_vectors.rs#L17

Chuncked MMAP storage should support all the same functions as `ChunkedVectors`, but should operate with mmap-ed memory instead of `Vec<T>`. 

**Additional context**

Would also like to understand the performance cost of this implementation. Is there a pitfalls of having 10-100 mmap files instead of one?
Also what might be the optimal chunk size? Can we make the first chunk smaller than all other? Ideally, we don't want to pre-allocate 128Mb of disk for an empty collection.

**Comment by timvisee** [comment]
An initial version of this is implemented in <https://github.com/qdrant/qdrant/pull/1838>.

**Comment by generall** [comment]
https://github.com/qdrant/qdrant/releases/tag/v1.2.0
