### ISSUE TITLE
Updating specific fields without overwriting the whole document

### ISSUE THREAD

**Issue by LiahimRatman** [qdrant/qdrant#1828]
Hi!

As I saw from documentation, at this moment Qdrant doesn't support partial document update, you can only overwrite the whole document. It could be very convenient to have an option to update only a part of a document, especially if it is big. It could be also useful if you have separate services indexing each field of the document that do not possess the whole document information in it (the only way now is to get the whole document from Qdrant, change it and index back OR to make a service, creating the document and indexing it as a whole, which could be not convenient in certain cases).

An example of such update in Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_update_part_of_a_document

Anyway, thank you for a nice instrument!

**Comment by generall** [comment]
https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/set_payload - does partial update
https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/overwrite_payload - does full update

**Comment by LiahimRatman** [comment]
Nice! My fault. Thank you for response!
