### ISSUE TITLE
too many replicas returned an error

### ISSUE THREAD

**Issue by carl10086** [qdrant/qdrant#1831]
## Current Behavior

1. After inserted 1_800_000 points to collection, search failed with error: ` too many replicas returned an error`
2. server error log
```
[2023-05-04T06:18:12.958Z ERROR qdrant::startup] Panic occurred in file lib/segment/src/vector_storage/chunked_vectors.rs at line 50: range end index 8190976 out of range for slice of length 8189952
[2023-05-04T06:18:13.728Z WARN  qdrant::actix::helpers] error processing request: Failed to complete read operation: too many replicas returned an error
```
3. version: `qdrant 1.1.1` ;
4.  virtual machine is restarted when inserting data , before it was success;

## Steps to Reproduce

python client:

```python
    resp = client.search(
        collection_name=collection_name,
        search_params=models.SearchParams(
            hnsw_ef=128,
            # exact=False
        ),
        query_vector=vec,
        limit=8
    )
```

collection information:

```json
{
	"result": {
		"status": "green",
		"optimizer_status": "ok",
		"vectors_count": 1252192,
		"indexed_vectors_count": 1132155,
		"points_count": 1252192,
		"segments_count": 6,
		"config": {
			"params": {
				"vectors": {
					"size": 1024,
					"distance": "Dot"
				},
				"shard_number": 1,
				"replication_factor": 1,
				"write_consistency_factor": 1,
				"on_disk_payload": true
			},
			"hnsw_config": {
				"m": 32,
				"ef_construct": 100,
				"full_scan_threshold": 10000,
				"max_indexing_threads": 0,
				"on_disk": true
			},
			"optimizer_config": {
				"deleted_threshold": 0.2,
				"vacuum_min_vector_number": 1000,
				"default_segment_number": 0,
				"max_segment_size": null,
				"memmap_threshold": 20000,
				"indexing_threshold": 20000,
				"flush_interval_sec": 5,
				"max_optimization_threads": 1
			},
			"wal_config": {
				"wal_capacity_mb": 32,
				"wal_segments_ahead": 0
			},
			"quantization_config": {
				"scalar": {
					"type": "int8",
					"always_ram": true
				}
			}
		},
		"payload_schema": {}
	},
	"status": "ok",
	"time": 0.00003289
}
```

**Comment by agourlay** [comment]
Thank you for reporting this issue, we are looking into it :+1: 

In the meantime could you please elaborate regarding your setup more specifically details about:

1. the virtual machine type
2. the file system persisting the data
3. how the service is restarted, gracefully or crashed

**Comment by carl10086** [comment]
Thank you for your reply. Qdrant is an amazing vector database, especially for high-dimensional vectors.

Here are more details about the issue:

1. Virtual Machine System: `Ubuntu 22.04 LTS with kernel version 5.15.0-54-generic`. ;
2. Filesystem: XFS with mount options: `xfs defaults,noatime,nodiratime 0 0` ;
3. The service restarted with crashed ;

@agourlay

**Comment by agourlay** [comment]
Thanks for details and the kind words!

Got a few more questions to make sure I understand the setup properly.

4. How did you install qdrant?
5. Did the qdrant process crashed before the VM restart OR only after the restart?
6. Do you still have the logs before the VM restart?

**Comment by timvisee** [comment]
@carl10086 You mention using a VM. Are you indeed using a VM, or just a Docker container. Could you clarify this a bit? That is an important difference that would help us debugging.

**Comment by carl10086** [comment]
@agourlay 
4. How did you install qdrant?
- I compiled qdrant from source code in ubuntu22.04
```bash
$rustc --version
rustc 1.69.0 (84c898d65 2023-04-16)
$ cargo --version
cargo 1.69.0 (6e9a83356 2023-04-12)
```
5. Did the qdrant process crashed before the VM restart OR only after the restart?
- the restart is unexpected because the billing is not enough in the cloud service  ~
6. Do you still have the logs before the VM restart?
- No

@timvisee 
I'm using a VM without docker with a configuration only changed `storage-path`

**Comment by generall** [comment]
Hi @carl10086, we might have found reason for the problem you are experiencing. Could you please try run https://github.com/qdrant/qdrant/releases/tag/v1.1.3

**Comment by carl10086** [comment]
1. I've tried v1.1.3 and it's works fine;
2. Thank you very much for your help, I'm migrating from elasticsearch 8.5 to qdrant for the high dim vectors, it's significant improve our latency,  lOL

@generall
