### ISSUE TITLE
Implement a disk based vector index 

### ISSUE THREAD

**Issue by gvelo** [qdrant/qdrant#185]
**Is your feature request related to a problem? Please describe.**
Currently the HNSW index reside on main memory. The current memory usage model is `num_collections * hnsw_index_size`

**Describe the solution you'd like**
Vector index should reside on disk.

**Describe alternatives you've considered**
https://github.com/microsoft/DiskANN

**Additional context**
https://proceedings.neurips.cc/paper/2019/file/09853c7fb1d3f8ee67a61b6bf4a7f8e6-Paper.pdf

**Comment by aldentepasta** [comment]
This would be incredibly helpful. I'm surprised sharding is on the roadmap but this isn't. The limits imposed by RAM would bite much earlier than anything else.

**Comment by generall** [comment]
Might be a part of https://github.com/qdrant/qdrant/pull/1171
