### ISSUE TITLE
Try to use faster `lto` for CI builds

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1858]
**Is your feature request related to a problem? Please describe.**
Continuation of https://github.com/qdrant/qdrant/issues/1812

One thing we still didn't try is to disable `lto=fat` on CI builds of docker. It supposedly should speed-up compile of the final binary. 
And In combination with `mold` in should be even faster https://github.com/qdrant/qdrant/pull/1811

**Describe the solution you'd like**

- Use some kind of build flag, which is only enabled on CI builds, which overwrites default `lto=fat`.
(alternatively, we can only set lto=fat on production build)
- enable mold same as in this PR  - https://github.com/qdrant/qdrant/pull/1811
- make sure that CI builds became faster

**Describe alternatives you've considered**

- previous attempt of using mold failed, probably because of `lto`
- we are not going to use external services for builds and not going to change logic of build (all should happen inside docker)

**Additional context**

Expected time of builds with cache should go down to ~10mins (currently 16mins)

**Comment by Jesse-Bakker** [comment]
I did some measurements:
In CI, docker builds take about 5x longer than non-docker builds (10 vs 2 minutes).

Build time is decreased by 2x by using LTO=false instead of lto=fat, and decreased by 2x by setting opt-level=0 instead of opt-level=3. Mold saves about 10% on top of the other improvements.

**Comment by generall** [comment]
Thanks @Jesse-Bakker !
