### ISSUE TITLE
cannot cargo run on mac M2?

### ISSUE THREAD

**Issue by spursy** [qdrant/qdrant#1884]
```bash
cargo run --bin qdrant


...............

    Finished dev [unoptimized + debuginfo] target(s) in 15.37s
     Running `target/debug/qdrant`
[1]    95033 bus error  cargo run --bin qdrant

```

**Comment by spursy** [comment]
```bash
cargo run --bin qdrant


...............

    Finished dev [unoptimized + debuginfo] target(s) in 15.37s
     Running `target/debug/qdrant`
[1]    95033 bus error  cargo run --bin qdrant

```

**Comment by generall** [comment]
We tested on m1, not sure what is the difference in arch there

**Comment by Jesse-Bakker** [comment]
There are many different possible reasons for a bus error. It might happen when running through rosetta, if the binary is changed while running, through a failed mmap, etc.

@spursy does the error happen after running `cargo clean` and then `cargo run --bin qdrant` again? 
What is the output of running `file target/debug/qdrant`?

**Comment by spursy** [comment]
first step: cargo clean

**Comment by generall** [comment]
google said it might be simply out-of-memory problem. Could you please check if you have enough to compile (I don't know how much it is required to have on mac)

**Comment by spursy** [comment]
I have save the problem by process 

```bash
cargo run --target=aarch64-apple-darwin  --bin qdrant
```

**Comment by Jesse-Bakker** [comment]
So, the problem might have been that the default target was x86 and the binary was running through rosetta
