### ISSUE TITLE
Possible loss of payload index configuration 

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1890]
It might be possible, that if service is killend in a specific moment, segment might loose it's configuration for payload indexes.

## Current Behavior

There are 2 conditions:

- WAL should not contain create-index operation (it might be too old and truncated)
- Service should stop between temp segment created and payload indexes transferred from optimized segment

## Steps to Reproduce

1. Go to branch `payload-index-config-persistence`
2. Run bfb with `docker run --rm -it --network=host qdrant/bfb ./bfb -d 512 -n 10000 --quantization scalar --indexing-threshold 5000 --segments 2 --keywords 10`
3. Service should crash with planned panic
4. Reboot service

Now we will have 3 segments one of which have empty payload index configuration

## Expected Behavior

All segments should have payload index configuration

## Possible Solution

* Introduce `payload_index` into create segment function, so segment won't be marked as ready before correct index is created.

or

* Adjust conversion from temp segment to working segment

or

* Do sanity check on load 

## Context (Environment)

Might be related to https://discord.com/channels/907569970500743200/1106610540492619949

**Comment by sunisdown** [comment]
is `payload-index-config-persistence` in this repo? can't find it.

**Comment by generall** [comment]
forgot to push. It is now

**Comment by timvisee** [comment]
A hotfix for this has been implemented in <https://github.com/qdrant/qdrant/pull/1913>.

Leaving this open because we probably want to improve it a bit later.

**Comment by generall** [comment]
Also related fix: https://github.com/qdrant/qdrant/pull/1936

Should be resolved with https://github.com/qdrant/qdrant/releases/tag/v1.2.0
