### ISSUE TITLE
Test  storage compatibility for quantized collections

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#1891]
**Is your feature request related to a problem? Please describe.**
There is a mechanism to detect breaking changes at the storage level.

See  https://github.com/qdrant/qdrant/blob/master/tests/storage-compat/README.md

**Describe the solution you'd like**
I would like the compatibility test  to also cover the case of quantization.

The data generator may need to refactored to handle a multi collections setup.

**Comment by coszio** [comment]
Added in #2040
