### ISSUE TITLE
Allow to clear payload with filters

### ISSUE THREAD

**Issue by kacperlukawski** [qdrant/qdrant#1892]
**Is your feature request related to a problem? Please describe.**
It is possible to set, overwrite and delete payload with filters, not point ids only. However, clearing the payload accepts only the ids. I'd like it to be consistent with the other endpoints.

**Describe the solution you'd like**
I want the "Clear payload" endpoint to accept filters in the same way as the "Set payload" or "Delete payload" methods.

**Additional context**
https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/clear_payload

**Comment by kacperlukawski** [comment]
@agourlay Yes, my bad! This is just being rendered differently in the Redoc compared to the other endpoints:
![image](https://github.com/qdrant/qdrant/assets/2649301/f83ee638-590c-40cf-b766-5f8374ec0360)

**Comment by AbdelrahmanAbounida** [comment]
but how can I delete it without providing a list of points (I wanna use filter only)

**Comment by AbdelrahmanAbounida** [comment]
```
client.delete_payload(
        collection_name=settings.qdrant_collection_name,
        keys=["company_id"],
        points=models.Filter(
        must=[
            models.FieldCondition(
                key="company_id",
                match=models.MatchValue(value="asd213frt45rwed"),
            )
        ]
    )
    )
```
