### ISSUE TITLE
Possible limit for internal gRPC response size

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1901]
In cluster mode: points select requests with large amount of large vectors (2000 points, 1536d) fails with

```
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 500 (Internal Server Error)
Raw response content:
b'{"status":{"error":"Service internal error: 1 of 1 shards failed with: Service internal error: Tonic status error: Operation was attempted past the valid range"},"time":0.460266307}'
```

## Steps to Reproduce

1. Have a cluster of 3 nodes, 1 collection, 1536d, 3 shards, 1 replica
2. Make a 
```
client.retrieve(
        collection_name=collection_name, ids=ids, with_payload=False, with_vectors=True
    )
```

where `ids` have about 2000 values of existing IDs

3. observe 500 error

## Expected Behavior

result returns fine

## Possible Solution

Possibly, there are some gRPC limits we overlooked

**Comment by timvisee** [comment]
We assume this is fixed with <https://github.com/qdrant/qdrant/pull/1906>.
