### ISSUE TITLE
Configurable location for the tmp snapshot files.

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1905]
**Is your feature request related to a problem? Please describe.**
Currently, we write tmp files for snapshots in the `/storage` directory. It is suboptimal for the following reasons:

- `/storage` is limited in disk size
- writing lot's of data to `/storage` may affect the performance as it consumes bandwidth
- `/storage` is usually a network-mounted disk, so it might be slow  

**Describe the solution you'd like**

Make a parameter, which defines folder, that qdrant can use for temporary files, like snapshots. 

(optionally, also tmp segments, but this require additional consideration)
If option is not specified, use default as it is right now.

**Describe alternatives you've considered**
Write directly to `/snapshot`. But, by design, we assume that `/snapshot` might be even slower than `/storage`

**Additional context**
Required to optimize cloud performance

**Comment by AllMight2099** [comment]
Hi there!
I was looking to contribute to qdrant and was hoping I could work on this issue.

**Comment by AllMight2099** [comment]
Oh, that's alright. I just started work on mine. I'll pick up a different issue

**Comment by generall** [comment]
https://github.com/qdrant/qdrant/releases/tag/v1.3.0
