### ISSUE TITLE
Handshake failed with API_KEY

### ISSUE THREAD

**Issue by eek** [qdrant/qdrant#1930]
I've just recently deployed a Qdrant docker file, all worked well until I added an `api_key` to the config. Once I did that, I could no longer connect to the DB: 

```
qdrant httpx.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

>>> E0519 12:24:27.693696812   27580 ssl_transport_security.cc:1420]       Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
```

Even though I didn't change anything else. And I'm going with everything basic:

```qdrant_custom_config.yaml
debug: true
log_level: INFO

service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  api_key: 38ad1c3a-1c4b-4f2f-83d8-da3aabfff88a
```
(the API key from the above is just an example to show the format - generated GUID)

```
docker run -d --restart unless-stopped -p 6333:6333 -p 6334:6334 -v $(pwd)/qdrant_storage:/qdrant/storage -v $(pwd)/qdrant_custom_config.yaml:/qdrant/config/production.yaml qdrant/qdrant
```

I then tried to generate a self-signed certificate and enabled TLS, but then it errors with the fact that it's a self-signed certificate:
```
ResponseHandlingException: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate
```

Any thoughts, or it's maybe something fishy on my side? (the docker itself is being run by an Amazon Linux 2 AMI)

**Comment by generall** [comment]
Hi @eek, if you are using python qdrant client, it will prefer https to be used with API key. If you still want to use plain un-encrypted channel with API key (which is highly not recommended), you can set `https=False` in client configuration.

Could you please share the code you are using to connect to qdrant?

**Comment by DengYiping** [comment]
With regards to self-signed certificate, I think you have to add those certificates somehow to your truststore in the client.

**Comment by eek** [comment]
Hi @generall, I've tried now to give it another try following the latest documentation (which btw, would be great to also give examples on how to run the docker container with the tls self-signed by mkcert - basically a full step by step tutorial would be great).

My config file:
```
debug: false
log_level: INFO

service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  api_key: 38ad1c3a-1c4b-4f2f-83d8-da3aabfff88a

tls:
  # Server certificate chain file
  cert: ./tls/cert.pem
  # Server private key file
  key: ./tls/key.pem
```

I've generated self-signed pem files with `mkcert` as in the documentation.

I've launched the docker using the following:

```
docker run -d --restart unless-stopped -p 6333:6333 -p 6334:6334 -v $(pwd)/qdrant_storage:/qdrant/storage -v $(pwd)/qdrant_custom_config.yaml:/qdrant/config/production.yaml -v $(pwd)/mydomain.com+6.pem:/qdrant/tls/cert.pem -v $(pwd)/mydomain.com+6-key.pem:/qdrant/tls/key.pem qdrant/qdrant
``` 

I've checked if the key.pem and cert.pem files are the ones that I generated inside the container and they are.

Now when I try to connect:

```
client = QdrantClient(
    host="172.25.13.52", //fake IP
    port=6333,
    prefer_grpc=True,
    api_key="38ad1c3a-1c4b-4f2f-83d8-da3aabfff88a"
)
```

I get the following error:

```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: 
ipv4:172.25.13.52:6334: Ssl handshake failed: SSL_ERROR_SSL: error:100000f7:SSL 
routines:OPENSSL_internal:WRONG_VERSION_NUMBER"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last 
error: UNKNOWN: ipv4:172.25.13.52:6334: Ssl handshake failed: SSL_ERROR_SSL: 
error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER 
{grpc_status:14, created_time:"2023-05-31T15:20:13.299311647+03:00"}"
>
Exception ignored in: <function QdrantRemote.__del__ at 0x7f64fc19f6d0>
Traceback (most recent call last):
  File "/home/eek/.local/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 133, in __del__
  File "/home/eek/.local/lib/python3.10/site-packages/grpc/_channel.py", line 1750, in close
  File "/home/eek/.local/lib/python3.10/site-packages/grpc/_channel.py", line 1732, in _close
AttributeError: 'NoneType' object has no attribute 'StatusCode'
```

any idea why it says my OpenSSL has the WRONG_VERSION_NUMBER? I'm on the Amazon Linux 2 AMI

**Comment by timvisee** [comment]
@eek This could be related to Python internally not trusting your certificate.

What happens when using REST (rather than gRPC)? I believe the internal HTTP client is more successful picking up the self signing certificate authority.

```python
client = QdrantClient(
    host="172.25.13.52", //fake IP
    port=6333,
    prefer_grpc=False,
    api_key="38ad1c3a-1c4b-4f2f-83d8-da3aabfff88a"
)
```

**Comment by generall** [comment]
```
client = QdrantClient(
    host="172.25.13.52", //fake IP
    port=6333,
    prefer_grpc=True,
    api_key="38ad1c3a-1c4b-4f2f-83d8-da3aabfff88a"
)
```

This code here will use https - https://github.com/qdrant/qdrant/issues/1930#issuecomment-1555873920

**Comment by coszio** [comment]
Hi @eek! did this solve your issue?

**Comment by Wamy-Dev** [comment]
I am also having a problem with this using my domain. Any solution?
