### ISSUE TITLE
Failed to complete read operation: too many replicas returned an error when doing a search batch

### ISSUE THREAD

**Issue by Siyer2** [qdrant/qdrant#1933]
Can't run a batch search.

I've tried this with the [the JS client](https://www.npmjs.com/package/@qdrant/qdrant-js) and [Swagger](https://ui.qdrant.tech/?v=v1.1.0) with Qdrant binaries (binaries identical to [this](https://github.com/BloopAI/bloop/tree/main/apps/desktop/src-tauri/bin)).

## Current Behavior
When I run a batch search, I get the following error:
```
Failed to complete read operation: too many replicas returned an error
```

## Steps to Reproduce

1. Run Qdrant locally with binaries like [this](https://github.com/BloopAI/bloop/tree/main/apps/desktop/src-tauri/bin) (I'm using qdrant-aarch64-apple-darwin)
2. Create a collection with the following config:
```
vectors: {
  size: 1536,
  distance: 'Cosine',
},
```

2. Run a batch search in [the Swagger UI](https://ui.qdrant.tech/?v=v1.1.0#/points/search_batch_points) with a payload like this (removed vectors payload to make more readable):
```
{
  "searches": [
    {
      "vectors": [...], 
      "limit": 3,
      "with_vector": false,
      "with_payload": true
    },
    {
      "vectors": [...], 
      "limit": 3,
      "with_vector": false,
      "with_payload": true
    }
  ]
}
```

Error logs:
```
[2023-05-20T02:53:51.890Z ERROR qdrant::startup] Panic occurred in file /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-1.0.1/src/slice/api.rs at line 2594: index 7 out of bounds: 7

[2023-05-20T02:53:52.957Z WARN  qdrant::actix::helpers] error processing request: Failed to complete read operation: too many replicas returned an error
```

## Expected Behavior
The batch search should work and return the relevant points.

## Context (Environment)
Output from http://localhost:6333/ in a browser:
```
{"title":"qdrant - vector search engine","version":"1.1.0"}
```

Run a batch search with embedded Qdrant in a desktop app.

Any help would be appreciated!

**Comment by generall** [comment]
hi @Siyer2 , please try the latest version of qdrant

**Comment by Siyer2** [comment]
> hi @Siyer2 , please try the latest version of qdrant 

Thanks for the reply @generall 

Do you know where I can find these prebuilt binaries or will I need to build them myself?

**Comment by generall** [comment]
we will publish binaries on the next release
