### ISSUE TITLE
Panics on `cargo bench` in `lib/segment`

### ISSUE THREAD

**Issue by hatoo** [qdrant/qdrant#1934]
## Current Behavior

`cargo bench` in `lib/segment` panics.

```
...
Benchmarking scoring-vector/score-point: Warming up for 3.0000 sthread 'main' panicked at 'internal error: entered unreachable code: FakeMetric::distance', lib/segment/benches/hnsw_build_asymptotic.rs:113:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: bench failed, to rerun pass `--bench hnsw_build_asymptotic`
```

## Steps to Reproduce

```bash
cd lib/segment
cargo bench --bench hnsw_build_asymptotic
```

## Expected Behavior

No panic.

## Possible Solution

Because it panics on https://github.com/qdrant/qdrant/blob/5837460cfbac237f13facc9ffd51b8a6c71c2c6c/lib/segment/benches/hnsw_build_asymptotic.rs#L111-L114 , I've confirmed that it runs without panic if we make `distance()` returns some `Distance` but I'm not sure it's the best solution.

## Context (Environment)

WSL2, dev branch

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/qdrant/pull/2754
