### ISSUE TITLE
Benchmark on billion scale dataset

### ISSUE THREAD

**Issue by yusufani** [qdrant/qdrant#1947]
Hi, 

I couldn't find any reference on how Qdrant performs on a vector dataset with 1 billion records. Are there any record limits? Can you give information about the search time?

**Comment by andy1xx8** [comment]
We have a dataset of ~ 800k points of 2048 dim vectors and config with on disk only =>it took 8GB of ram

**Comment by raghavsonavane** [comment]
@andy1xx8 Hi, Can you please share the configuration used for this, I have tried to benchmark this but it's going OOM

**Comment by timvisee** [comment]
> @andy1xx8 Hi, Can you please share the configuration used for this, I have tried to benchmark this but it's going OOM

You'd normally use `on_disk: true` for this on vectors, the indexes and on your payload. That way you don't require 100% physical memory to achieve this.
