### ISSUE TITLE
Collections containing / in its name are not loaded on restart

### ISSUE THREAD

**Issue by volkerstampa** [qdrant/qdrant#1956]
If a collection containing a '/' (slash) in its name is created it seems to disappear after a restart.

## Current Behavior
If a collection containing a / in its name is created, the creation is successful and metadata of the collection can be retrieved through a GET request. However if qdrant is restarted it seems the collection cannot be "found" and instead an WARN is logged 

`WARN  storage::content_manager::toc] Collection config is not found in the collection directory: "./storage/collections/test", skipping`

Retrieving metadata for this collection though GET after a restart is answered with HTTP Status 404 Not Found.

## Steps to Reproduce

```bash
$ curl -X PUT 'http://localhost:6333/collections/test%2Fdemo' --verbose -H 'Content-Type: application/json' --data-raw '{ "vectors": { "size": 4, "distance": "Dot" } }'
*   Trying 127.0.0.1:6333...
* Connected to localhost (127.0.0.1) port 6333 (#0)
> PUT /collections/test%2Fdemo HTTP/1.1
> Host: localhost:6333
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 47
> 
< HTTP/1.1 200 OK
< content-length: 48
< content-type: application/json
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< date: Wed, 24 May 2023 09:30:08 GMT
< 
* Connection #0 to host localhost left intact
{"result":true,"status":"ok","time":0.207046592}

$ curl 'http://localhost:6333/collections/test%2Fdemo'
{"result":{"status":"green","optimizer_status":"ok","vectors_count":0,"indexed_vectors_count":0,"points_count":0,"segments_count":8,"config":{"params":{"vectors":{"size":4,"distance":"Dot"},"shard_number":1,"replication_factor":1,"write_consistency_factor":1,"on_disk_payload":true},"hnsw_config":{"m":16,"ef_construct":100,"full_scan_threshold":10000,"max_indexing_threads":0,"on_disk":false},"optimizer_config":{"deleted_threshold":0.2,"vacuum_min_vector_number":1000,"default_segment_number":0,"max_segment_size":null,"memmap_threshold":null,"indexing_threshold":20000,"flush_interval_sec":5,"max_optimization_threads":1},"wal_config":{"wal_capacity_mb":32,"wal_segments_ahead":0},"quantization_config":null},"payload_schema":{}},"status":"ok","time":0.00006342}

# restart qdrant

$ curl 'http://localhost:6333/collections/test%2Fdemo' --verbose
*   Trying 127.0.0.1:6333...
* Connected to localhost (127.0.0.1) port 6333 (#0)
> GET /collections/test%2Fdemo HTTP/1.1
> Host: localhost:6333
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< content-length: 89
< content-type: application/json
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< date: Wed, 24 May 2023 09:33:12 GMT
< 
* Connection #0 to host localhost left intact
{"status":{"error":"Not found: Collection `test/demo` doesn't exist!"},"time":0.00002139}
```

## Expected Behavior
If a collection was created successfully it should remain retrievable after a restart.

## Possible Solution
- Either prevent/forbid creation of collections with '/' in its name 
- or properly encode '/' before storing them on the filesystem
- or load collections even if they are stored in sub-directories of the collections-folder 

## Context (Environment)

In our application we want to support the concept of a namespace in addition to the concept of a collection. When storing data in qdrant we just joined namespace and collection separated by a / to build a collection-name for qdrant. Unfortunately with this approach the collection does not survive restarts.

## Detailed Description

See possible solution

**Comment by sunisdown** [comment]
I submitted a PR that validates the collection name when creating the collection.

**Comment by timvisee** [comment]
Thank you for bringing this to our attention!

There may be more problems than just the one you've described here. For example, I'm unsure how our client libraries handle this with regards to URL encoding.

Though I do like to support a `/` in collection names, it may be better to just ban this (and some other) characters all together. I'm afraid other problems may arise later when depending on this.

> In our application we want to support the concept of a namespace in addition to the concept of a collection. When storing data in qdrant we just joined namespace and collection separated by a / to build a collection-name for qdrant. Unfortunately with this approach the collection does not survive restarts.

You might want to use a different separator for the time being until we get this fixed. Using `namespace_collection` may be an option.

**Comment by sunisdown** [comment]
> Though I do like to support a / in collection names, it may be better to just ban this (and some other) characters all together. 

Agree. It would be simpler and more straightforward to just ban these characters. No complex implementations are introduced to support these characters.

**Comment by sepal** [comment]
Just ran into this as well. The main problem is, that the API server doesn't recognize such names for certain operations like get or delete a collection. Upsert on the other hand seems to work.

**Comment by generall** [comment]
https://github.com/qdrant/qdrant/releases/tag/v1.3.0
