### ISSUE TITLE
Read-only API key

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1959]
**Is your feature request related to a problem? Please describe.**
Sometimes it is useful to be able to expose Qdrant instance for read/search queries.
Some use-case could be: search for web-sites backend-less. 

**Describe the solution you'd like**
Introduce API Key which only allows read operations on Qdrant instance.

API key should work for both: gRPC and REST endpoints, should only allow read subset of APIs.

API to allow:

- search (+batch), scroll, get-point, recommend, group-by inside collections
- list collections
- get collection info

**Describe alternatives you've considered**
 - Reverse proxy stuff
- Make API list configurable API to allow (this is too much work)

**Additional context**

- Should be implemented as a middle-ware (similar to how current API key works)
- Disabled by default, middleware should be only enabled if API key specified
- Read-only API key should be specified in the config 
- PR Should include tests

**Comment by BabaBert** [comment]
@generall Should the middleware's check for different request headers or use the same one? If so, should the read only resources be ambiguous in regard to the used key?

**Comment by timvisee** [comment]
> Should the middleware's check for different request headers or use the same one?

We want to reuse the same API key header.

> If so, should the read only resources be ambiguous in regard to the used key?

I'm not entirely sure what you mean, but if API key usage is enabled:

- A user uses either a full API key, read-only API key or no API key in the request header
- With both API keys, all read-only operations as listed in the first comment should work as normal, otherwise return an authentication error
- With the full API key, all other operations should work as normal, otherwise return an authentication error

Does that clear things up?

**Comment by amrhassan** [comment]
Hi. I've made an attempt [here](https://github.com/qdrant/qdrant/pull/2010) with some dubious design decisions. Happy to discuss and take it further if necessary.

**Comment by timvisee** [comment]
> but I assume the read only key would then be disabled too.

Good question.

No I think, if only a read key is set, only read operations should be allowed. That could be useful if some instance has a static dataset.

**Comment by BabaBert** [comment]
Quick question, what is the status of this issue? I postponed my attempt as I assumed @amrhassan had a working solution.

**Comment by amrhassan** [comment]
@BabaBert Yes the PR has a working solution, pending merging.

**Comment by ologbonowiwi** [comment]
/attempt #1959

hey @amrhassan, if you don't mind, I'll take up from what you did

**Comment by ologbonowiwi** [comment]
Hey @ttejas123, a PR to it is already open. 

I'm only waiting the contributors review.
