### ISSUE TITLE
Maybe we can use `poem-openapi` without handwritten spec, what do you think?

### ISSUE THREAD

**Issue by sunli829** [qdrant/qdrant#196]
**Is your feature request related to a problem? Please describe.**

Maintaining this [file](https://github.com/qdrant/qdrant/blob/master/openapi/openapi-main.ytt.yaml) is painful, and it is difficult to ensure that the code behaves as described in this file.

**Describe the solution you'd like**
I recommend using [poem-openapi](https://github.com/poem-web/poem), which automatically generates `spec.json` from the code.

**Describe alternatives you've considered**

**Additional context**
If you want I can open a PR to help you with this. 🙂

**Comment by generall** [comment]
Hi @sunli829 that is a great project! If it existed when I chose a web framework, I would definitely try it!
At this point, I am afraid it could be too painful to switch. On the other hand, if it is not as hard as I expect it to bee, I would like to give it a hit;)

**Comment by sunli829** [comment]
I can provide a PR for assessing the difficulty of the migration. 😁
