### ISSUE TITLE
non vector query

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#1969]
This is one search result corresponding to schema.
ScoredPoint(id='ef72218e-c3a0-4177-87cd-92d7c715e12b', version=49618, score=539.0775, payload={'claim_number': '00001', 'dependent_on': None, 'file_name': 'check.XML.out', 'is_dependent': 'false', 'snippet': '1. such that', 'score': 539.0775}, vector=[0.1,0.2,0.1])
And this is how Im retrieving the count
count = client.count(
collection_name=coll_name,
must=[
models.FieldCondition(
key="is_dependent",
match=models.MatchValue(value="true")
),
],
exact=True,
)
However the count is constant and doesnt seem to depend on what key and value I specify in match condition. What am I doing wrong??

**Comment by generall** [comment]
The correct usage of `count` method should look like this:
![image](https://github.com/qdrant/qdrant/assets/1935623/7868304e-1d13-4160-a9ca-25e7f9da5339)

note the `count_filter=Filter` part
