### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by hyhanyan** [qdrant/qdrant#1970]
After inserting our trajectory dataset, the memory usage of Qdrant stabilized at a certain level after a few minutes. However, after restarting Qdrant, the memory usage dropped significantly again. For example, when we stored both the data and index (a total of 614.27MB of trajectories) on disk, the memory usage stabilized at around 1.67GB. However, after restarting Qdrant, the memory usage dropped to 529MB. We would like to raise this issue to the Qdrant team.

**Comment by timvisee** [comment]
That is unfortunate. Would you mind to share your collection information? Maybe some configuration may result in this.

To get your collection information, you can sue the following URL and rename `test` to your collection name:

```bash
curl http://localhost:6333/collections/test
```

**Comment by generall** [comment]
Hi @hyhanyan, it might be not a memory leak, but caching and memory fragmentation. This is an expected behavior, as allocator does not necessary return memory to the OS if it is freed inside the program.

You can validate this hypothesis limiting the allowed memory to the point below maximal usage you observed and see that it will not crash

**Comment by hyhanyan** [comment]
this is my conf :{"result":{"status":1,"optimizer_status":{"ok":true},"vectors_count":7933101,"segments_count":3,"config":{"params":{"shard_number":1,"on_disk_payload":true,"vectors_config":{"Config":{"Params":{"size":30,"distance":2}}},"replication_factor":1,"write_consistency_factor":1},"hnsw_config":{"m":16,"ef_construct":100,"full_scan_threshold":10000,"max_indexing_threads":0,"on_disk":false},"optimizer_config":{"deleted_threshold":0.2,"vacuum_min_vector_number":1000,"default_segment_number":2,"memmap_threshold":20000,"indexing_threshold":20000,"flush_interval_sec":5,"max_optimization_threads":1},"wal_config":{"wal_capacity_mb":32,"wal_segments_ahead":0}},"points_count":7933101,"indexed_vectors_count":7933101},"time":0.000557084}

**Comment by hyhanyan** [comment]
Memory changes 
<img width="1279" alt="2F083BC9-18D8-4BA6-B93A-9EBDBCBA8069" src="https://github.com/qdrant/qdrant/assets/11550403/5a15751e-2264-4a4a-b9d2-278b2d343f14">
<img width="1276" alt="CA015975-3A73-4D81-95F2-D2C2C7062D68" src="https://github.com/qdrant/qdrant/assets/11550403/8b8670fb-d594-4c5d-9959-0983444156f4">

**Comment by hyhanyan** [comment]
This code can reproduce stably

**Comment by hyhanyan** [comment]
If the memory limit is set to 2GB, the temporary memory usage will exceed 2GB when inserting data, and it will crash. Therefore, I believe that when the data is 600M, its temporary memory will rise to over 2GB at one point. After about 5 minutes of inserting the data, the memory will begin to decrease and stabilize before dropping to 3.6G. If it does not restart, it will remain at this value, but if I restart at this time, At this point, the memory will drop to 1.1GB. If it is not a memory leak, what parameters should I set to achieve

**Comment by timvisee** [comment]
Thanks for giving that a test.

According to your configuration you're using memmap. When restarting Qdrant, none of this data is in memory and is still on disk, keeping memory usage low. When using Qdrant and accessing specific vectors, the data will slowly be pulled in memory again increasing the usage.

In any case, what you're describing is no weird or exceptional case at all. Memory usage like this can be expected in some cases.

Out of curiosity. Are you running a Linux host, or are you using a different OS?

**Comment by hyhanyan** [comment]
I ran qdrant on the MacOs M2 chip

**Comment by timvisee** [comment]
> I ran qdrant on the MacOs M2 chip

Docker does not run natively on macOS, instead containers run in a Linux VM. 

That isn't a problem of course, it's just that the memory usage counter can be very unreliable. IIRC it even includes things like kernel disk cache in a setup like this. It can give a bad impression of how much memory is actually used.

**Comment by generall** [comment]
I am going to close this issue, as this is not a memory leak. Please feel free to open another issue or re-open this one if you will find other behavior you find incorrect
