### ISSUE TITLE
API key support breaks `/metrics` endpoint

### ISSUE THREAD

**Issue by kylemclaren** [qdrant/qdrant#1980]
API Key Support Breaks /metrics Endpoint for Prometheus Scrapers

## Current Behavior

After the [recent addition of API key support](https://github.com/qdrant/qdrant/pull/1745), the `/metrics` endpoint is broken for Prometheus scrapers that are unable to authenticate with the new method. Instead of the expected metrics data, an authentication error message is returned. 

## Steps to Reproduce

1. [Enable](https://qdrant.tech/documentation/security/#authentication) API key support in the configuration.
2. Set up a Prometheus scraper without API key authentication.
3. Attempt to access the `/metrics` endpoint.
4. Observe the returned authentication error.

## Expected Behavior

Even with API key support enabled, the `/metrics` endpoint should remain accessible to Prometheus scrapers that can't authenticate using the API key. The expected behavior is for the endpoint to return the relevant metrics data instead of an authentication error.

## Possible Solution

A possible fix could involve creating an exception or a separate, unauthenticated endpoint for Prometheus scrapers, allowing them to bypass the API key authentication. 

## Context (Environment)

This issue has made it impossible to collect metrics from the `/metrics` endpoint using Prometheus, thereby hindering our system monitoring and performance analysis efforts. 

## Detailed Description

The API key support addition is a welcome feature for enhancing security, but it has inadvertently caused an issue with Prometheus scrapers' access to the `/metrics` endpoint. A solution is needed that allows these scrapers to access the endpoint as before, while keeping the new security measures intact.

## Possible Implementation

One possible implementation could involve setting up a configuration flag that allows specific endpoints like `/metrics` to bypass the API key authentication. This flag could be toggled on for systems that use Prometheus scrapers or similar tools which can't authenticate using API keys. Alternatively, a separate endpoint could be set up specifically for these tools, which would not require API key authentication.

**Comment by timvisee** [comment]
Thank you for bringing this to our attention!

> Even with API key support enabled, the `/metrics` endpoint should remain accessible to Prometheus scrapers that can't authenticate using the API key.

I'm not sure I agree with this. The idea of the API key is to secure the whole instance. Metrics could leak information.

> One possible implementation could involve setting up a configuration flag that allows specific endpoints like `/metrics` to bypass the API key authentication. This flag could be toggled on for systems that use Prometheus scrapers or similar tools which can't authenticate using API keys.

We want to minimize access control features in the core Qdrant product, because that can make a lot of things difficult.

---

I wonder if we could easily provide the API key in a different manner from Prometheus. Through a query parameter for example. That way we could easily support both.

**Comment by kylemclaren** [comment]
Hey @timvisee 

>The idea of the API key is to secure the whole instance. Metrics could leak information.

Actually, you are 100% correct and I didn't fully think that through.

>I wonder if we could easily provide the API key in a different manner from Prometheus

So my issue is that with a platform like Fly.io for instance, [custom metrics](https://fly.io/docs/reference/metrics/#custom-metrics) can be automatically scraped by a hosted Prometheus, however, there is not much room for configuration:

```toml
[metrics]
port = 9091 # default for most prometheus clients
path = "/metrics" # default for most prometheus clients
```

**Comment by timvisee** [comment]
No worries!

Would it be possible to use this?

```toml
[metrics]
port = 6333
path = "/metrics?api_key=my_super_secret_key_here"
```

**Comment by kylemclaren** [comment]
Ah, clever solution. I just tested and the configuration is accepted as valid, however, this might pose an issue as it is unclear if a secret/env variable can be used there. Which is a problem as of course, it's not a great idea to hardcode that value.

What about having the endpoint reachable only via a configurable port? That way, we can decouple the endpoint from anything that is publicly accessible (and therefore safely remove auth)?

**Comment by kylemclaren** [comment]
Related [discussion](https://community.fly.io/t/authenticated-requests-for-health-checks-and-prometheus-metric-scraping/7909/2) with some workarounds

**Comment by wodka** [comment]
As I'd like to do a similar thing now - in a lot of tools the metrics endpoint is exposed on a different port (default could be the same as the regular REST interface.

Because then we could expose /metrics without it being exposed to the public

**Comment by vitali-ipquants** [comment]
Hi @timvisee ,
I just tried to configure the ServiceMonitor object via the qdrant helm chart and observed the 403 error in our Promethues.

Is there any suggestion on how to run qdrant cluster with API key and collect its metrics from Promethues?

Thank you!

**Comment by timvisee** [comment]
Yes, we now support HTTP Bearer authentication for `/metrics`. Prometheus supports this form of authentication.

https://github.com/qdrant/qdrant/pull/2855
