### ISSUE TITLE
{"status":{"error":"Wrong input: Vector inserting error: expected dim: 1, got 3"},"time":0.000749279}

### ISSUE THREAD

**Issue by laiweijiemu** [qdrant/qdrant#1993]
when add points , use  params  = '{
    "points": [
        {
            "id": 12,
            "payload": {"color": "red"},
            "vector": [0.9, 0.1, 0.1]
        }
    ]
}'   retrurn  {"status":{"error":"Wrong input: Vector inserting error: expected dim: 1, got 3"},"time":0.000749279}, for why.

**Comment by zarkone** [comment]
I can reproduce this error. I think it is expected behavior if your vector size doesn't match collection's size. You can check your collection size by `curl 'http://localhost:6333/collections/<collection_name>' `: 

in my case I see 

```json
...
"config": {
      "params": {
        "vectors": {
          "size": 4,
          "distance": "Dot"
        },
```

which means that vectors to be inserted should have 4 numbers

**Comment by generall** [comment]
I assume this is resolved, please feel free to re-open if three is anything else
