### ISSUE TITLE
Can't delete collection when RAM on Cluster is used up

### ISSUE THREAD

**Issue by JanMP** [qdrant/qdrant#2031]
I just added a collection to the free tier cluster and now it won't start up because it has run out of RAM. I have a collection on it, that I could delete, but since the container does not spin up I can't access the api. Is there a way around this (I would rather not want to delete the entire cluster)?

**Comment by azayarni** [comment]
You can (re)start the cluster in recovery mode. https://qdrant.tech/documentation/guides/administration/#recovery-mode

**Comment by timvisee** [comment]
I assume that using recovery mode as linked should be enough, so I'm closing this.

Feel free to open this again if the issue persists :smiley:
