### ISSUE TITLE
Remove dependency on Sled

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#204]
The [sled](https://github.com/spacejam/sled) database is only used to persist configuration data.

The dependency could be entirely removed by unifying the persistence system on `rocksdb` to:
- decrease the code base complexity
- decrease binary size
- decrease compilation time

**Comment by agourlay** [comment]
It is also worth exploring a solution using simply a flat file to hold the configuration to avoid adding a dependency on `rocksdb` at the top level.

Better reach consensus on the solution before starting.

**Comment by generall** [comment]
> Something like https://crates.io/crates/config ?

no, sled is not used for user-defined configuration. It currently used for alias persistance.

**Comment by agourlay** [comment]
We have decided to first remove Sled by saving the aliases in a json file.
Once we go distributed, we will move those aliases into the globally shared state.
