### ISSUE TITLE
How to update index if memmap was used?

### ISSUE THREAD

**Issue by chouife** [qdrant/qdrant#2044]
Hi,now I use memmap to upload a large scale of vectors and disable indexing during upload.I revise the indexing_threshould by counting the uploaded vectors after the process of uploading is finished.I want to insert some new vectors right now,I just know how to insert data through the function of upload_collection.But I don't know how to update the index of the new data, could you give me some suggestions about it.By the way,the process of updating index is applied to the total data or the data I just inserted if there have some methods can handle the problem.
My English is poor,maybe some formulations are incomprehensible.
Thanks!

**Comment by generall** [comment]
> But I don't know how to update the index of the new data

It will be updated automatically according to the configured thresholds.
After you configured `indexing_threshould` to the default value - you don't need to care about enabling index anymore.
Disabling index only make sense during the initial upload

**Comment by chouife** [comment]
Thanks for your reply.
