### ISSUE TITLE
Add curl and jq in the Docker image?

### ISSUE THREAD

**Issue by sebastien-prudhomme** [qdrant/qdrant#2058]
**Is your feature request related to a problem? Please describe.**

In Kubernetes context: I'd like to access the state of the cluster to correctly register/unregister peers in it

**Describe the solution you'd like**

In the Docker image: having curl to access the API and jq to analyze the JSON result

**Describe alternatives you've considered**

Improve the arguments of the qdrant binary?

For instance consider this is the first peer in the cluster if the URL of the --bootstrap option is not reachable

Also an an argument to unregister the peer working in the container from the cluster by calling the good API call. Like "consul leave" if I take inspiration from another product that is using the Raft protocol (https://developer.hashicorp.com/consul/commands/leave)

**Additional context**

**Comment by generall** [comment]
Hi @sebastien-prudhomme, thanks for the suggestions!

> Also an an argument to unregister the peer working in the container from the cluster by calling the good API call. 

We have https://qdrant.github.io/qdrant/redoc/index.html#tag/cluster/operation/remove_peer API, isn't it the same thing?

> For instance consider this is the first peer in the cluster if the URL of the --bootstrap option is not reachable

This can potentially create an ambiguity, if the network blinks, can potentially create a state which is hard to recover.

> In the Docker image: having curl to access the API and jq to analyze the JSON result

In the next release we are planning to include [web-ui](https://github.com/qdrant/qdrant-web-ui) with console, it will took like this:

![image](https://github.com/qdrant/qdrant/assets/1935623/ca561f96-fb02-4157-81ac-9efd1da1f28e)


Will this cover the requirement for curl + jq in your oppinion?

**Comment by sebastien-prudhomme** [comment]
H @generall, my context is Kubernetes where I can scale up and down a statefulset (like the one in https://github.com/qdrant/qdrant-helm).

One problem I have s that when I scale it down, the container should unregister itself from the cluster.

Currently it's not possible to do it because there is no qdrant command to do it and no curl/jq in the container to call the API through the shell.

**Comment by generall** [comment]
web ui is released in https://github.com/qdrant/qdrant/releases/tag/v1.3.0
