### ISSUE TITLE
Incorrect API validation: hnsw_config.max_indexing_threads: value 8 invalid, must be 1000.0 or larger

### ISSUE THREAD

**Issue by ArthurMelin** [qdrant/qdrant#2069]
Hi,

There seem to be an incorrect validation of the `hnsw_config.max_indexing_threads` property for the create collection API, I suspect this isn't intentional and was a copy/paste mistake from the rule for `full_scan_threshold` here:

https://github.com/qdrant/qdrant/blob/b13df2272cb351986d2a47844127a5280dfbc3cb/lib/collection/src/operations/config_diff.rs#L59

**Comment by timvisee** [comment]
Thank you for the report!

This appears to have been fixed in <https://github.com/qdrant/qdrant/pull/2021>.

It is not part of any release however. Would you desire a patch release for this?

**Comment by ArthurMelin** [comment]
Oh sorry I only checked the master branch. No it's ok I just used a PATCH to update the setting after, thanks!

**Comment by timvisee** [comment]
Sorry about this. We'll make sure to have the fix included in our next release. :smile:
