### ISSUE TITLE
Individual endpoints for points operation

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#208]
Follow up on #32 which handled the `collections` operations.

The goal of this issue is to discuss the design of the new update API for points.

The current update API is:

 `POST /collections/{col_name}` with different commands possible:

- PointOperations
  - "upsert_points" : array of points OR batch
  - "delete_points": array of ids
- PayloadOps
  - "set_payload": payload object AND array of points
  - "delete_payload": keys AND array of points
  - "clear_payload": array of points
- FieldIndexOperations
  - "create_index": index name
  - "delete_index": index name

One possible solution is to deprecate the current endpoint and introduce 7 new specialized endpoints

1. update points

`PUT /collections/{col_name}/points/`
 - array of points OR batch as body

2. delete points

`DELETE /collections/{col_name}/points/`
 - array of ids as query parameters
  
3. set payload

`POST  /collections/{col_name}/points/{name}/payload`
 - payload object AND array of points as body

4. delete payload  

`PUT /collections/{col_name}/points/{name}/payload`
- keys AND array of points as body

5. clear payload

`PUT /collections/{col_name}/points/{name}/payload`
- array of ids as query parameters

6. create index

`POST /collections/{col_name}/index/`
  - index name as body

7. delete index

`DELETE /collections/{col_name}/index/{index_name}`

**Comment by agourlay** [comment]
@generall Could you please review this design? 

In general I am not sure about the usage of query parameters for the ids as the list could be long.
And I am unsure about the design of `delete` payload due to existence of a complex object to target the payload.

**Comment by agourlay** [comment]
The review showed that the proposed solution is problematic and contains some typos :sweat_smile: 

The main take away is that DELETE should be modeled as POST with `delete` (or similar verb) in the URL if a body is necessary.

Here is the latest proposal.

1. update points

`PUT /collections/{col_name}/points/`
 - array of points OR batch as body

2. delete points

`POST /collections/{col_name}/points/delete`
 - array of ids as query parameters
  
3. set payload

`POST  /collections/{col_name}/points/payload`
 - payload object AND array of points as body

4. delete payload  

`POST /collections/{col_name}/points/payload/delete`
- keys AND array of points as body

5. clear payload

`POST /collections/{col_name}/points/payload/clear`
- array of ids as query parameters

6. create index

`POST /collections/{col_name}/index/`
- index name as body

7. delete index

`DELETE /collections/{col_name}/index/{index_name}`

**Comment by generall** [comment]
:+1:

**Comment by agourlay** [comment]
Just a thought for 6.

What about simply passing the index name as in URL?

`POST /collections/{col_name}/index/{index_name}`

Also it seems we use PUT to create collections using the same scheme.

Should we use PUT here as well?

**Comment by Kavan72** [comment]
@agourlay I guess you did some mistake 
![image](https://user-images.githubusercontent.com/19048640/150749566-c3a78873-470c-41fd-b0d9-801e652ed2f1.png)

**Comment by Kavan72** [comment]
and also I would prefer to use the get method for get the points and the delete method to delete items something like this 
![image](https://user-images.githubusercontent.com/19048640/150750544-814f3e37-1d65-4cdb-b30e-186c537e6e94.png)

**Comment by generall** [comment]
Hi @Kavan72, thanks for noticing the error! Will fix it ASAP.

Regarding HTTP methods - we, unfortunately, could not make them GET or DELETE, since those are batch operations and require to have a payload.

We were considering related public discussions regarding the possible approach:

* https://peterdaugaardrasmussen.com/2020/11/14/rest-should-you-use-a-body-for-your-http-delete-requests/
* https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request/299696
* https://github.com/OAI/OpenAPI-Specification/issues/1801

And decided that using POST is a safe alternative.

**Comment by agourlay** [comment]
@Kavan72 thank you very much for validating the spec, I learned something :+1:

**Comment by Kavan72** [comment]
@agourlay @generall got it, Thank you guys for great open source tools. Also, one more question is how we can store uuid as a id? I guess it's possible if you can increase the id size u64 to i128 🤔 (convert uuid to int and save as a int)

**Comment by generall** [comment]
@Kavan72 Thanks!

> Also, one more question is how we can store uuid as a id? I guess it's possible if you can increase the id size u64 to i128 thinking (convert uuid to int and save as a int)

At some point we would need to allow any string as a key. Current plan is to do it before v1.0

**Comment by Kavan72** [comment]
@generall nice, is there any issue or PR's draft ? Actually, I want to use qdrant in our product but this id limitation is blocking us.

**Comment by generall** [comment]
Hi @Kavan72, no PR yet, but I have created an issue for tracking the progress https://github.com/qdrant/qdrant/issues/255

As an alternative approach - have you considered using `keyword` payload for storing your IDs and assigning random numerical ids for records? I should still be able to retrieve points by ID using `scroll` API with filter. Just make sure that your payload field is indexed.
https://qdrant.github.io/qdrant/redoc/index.html#operation/scroll_points

The downside is that you would require 2 request in order to update existing point

**Comment by Kavan72** [comment]
@generall problem is if I generate a random id (basically just a random int) then I have to store the last id in order to generate the next id when inserting new data and we can't do this

**Comment by generall** [comment]
Why do you need to store it? There is a pretty small chance of collision even for 64-bit numbers https://stackoverflow.com/questions/22029012/probability-of-64bit-hash-code-collisions

**Comment by Kavan72** [comment]
@generall hmm, you are right but still for update need to find random id and after I can update data with that id

**Comment by generall** [comment]
@Kavan72 exactly, that is a downside - you would either need to delete by filter and then insert again, or find random id by payload filter and then update with this id. In each case 1 extra request required. So it is not an ideal workaround.

I will try to fit this issue into v0.5.x, but unfortunately can not guarantee the timeline

**Comment by Kavan72** [comment]
@generall I can understand about the timeline, for the moment if you can convert u64 to u128 that is also fine bcoz normal uuid can store in u128.

**Comment by generall** [comment]
released in https://github.com/qdrant/qdrant/releases/tag/v0.5.0
