### ISSUE TITLE
Enhance Point Counting by Introducing `score_threshold` Support 

### ISSUE THREAD

**Issue by gregpriday** [qdrant/qdrant#2091]
Context: https://qdrant.tech/documentation/concepts/points/#counting-points

## Description:

I'm working on a [Qdrant driver](https://github.com/gregpriday/laravel-scout-qdrant) for Laravel Scout. To enhance the search feature, I implemented support for `score_threshold`. This functionality works as expected.

However, an issue arises when attempting to count the number of points that meet or exceed the `score_threshold`. Currently, there's no built-in way in the Qdrant API to count the number of points that pass the given score_threshold, which is a necessary operation for accurate pagination.

## Feature Request:

I would like to propose the addition of `score_threshold` support to the point counting function. This feature would provide the capability to count the number of points that are above the given score threshold, enhancing the existing point-counting functionality.

## Impact:

The addition of this feature would greatly benefit users implementing pagination with search operations that use `score_threshold`. It will make the count of points more flexible and dynamic according to the varying score threshold set by the user, thereby leading to more accurate pagination results.

## Potential Solution:

Ideally, the solution would allow for an optional `score_threshold` parameter in the point counting method. When this parameter is provided, the method should only count points that meet or exceed this score threshold.

**Comment by amankrx** [comment]
Hello, I'm interested in taking on this issue. Could someone kindly confirm if it's available for me to work on? 
Thank you!

**Comment by generall** [comment]
I don't know what method could be used to get this count without an exhaustive search of the vectors. I am not sure if the usable method even exists. 

With an exhaustive search, this feature will be even more computationally complex than the search itself. 
Moreover, it will be the performance of this feature will be unstable and unpredictable, cause score is not linear and small change in the `score_threshold` may change the result size by order of magnitudes. 


I might overlook something, so please let me know if the method exists, I will be happy to give is a try. Feel free to open this issue if there any additional context
