### ISSUE TITLE
How to limit client permissions?

### ISSUE THREAD

**Issue by yurux-mineral** [qdrant/qdrant#2099]
Hi, I want to use one client(from python) to handle create, update and delete, the other(from js) can only search. What configurations can I set? Or is there any way to achieve this?

**Comment by timvisee** [comment]
This is not natively possible at this time.

Work is being made on a read-only API key feature which would achieve what you're requesting. You can find more about it here: https://github.com/qdrant/qdrant/issues/1959

Qdrant has a global _write lock_ feature as described [here](https://qdrant.tech/documentation/guides/administration/#locking). But this should not be used for this purpose, as user requests would be able to unlock it again.

**Comment by yurux-mineral** [comment]
Got it.
Thanks~Looking forward to more flexible features💐
