### ISSUE TITLE
How to search the keyword in payload without vector

### ISSUE THREAD

**Issue by Andision** [qdrant/qdrant#2113]
First I would like to thank for all the people contribute to this great work. I would like to know are there any methods that I can search the raw keyword in the payload instead of vector. I find that in the [official tutorial](https://qdrant.tech/articles/neural-search-tutorial/) we have to use the `startups.sqlite3` database to solve this issue. I think maybe we can have some more "elegant" way , instead of scorlling all of the points and hit the keyword in payload one by one, to solve this issue :-)

**Comment by andy1xx8** [comment]
You can check the scroll api
