### ISSUE TITLE
`devcontainer` configuration

### ISSUE THREAD

**Issue by BabaBert** [qdrant/qdrant#2117]
**Is your feature request related to a problem? Please describe.**

Since the deployment and development of this repository is tightly integrated with Linux, it would be very beneficial to have a `devcontainer` setup to get started up contributing more easily. This is especially important for people, who don't have a native Linux distribution running (MacOS is not sufficient).

**Describe the solution you'd like**

`devcontainer`-configuration with all the necessary extension like *protoc*, *rust*, etc. 

**Describe alternatives you've considered**

MacOS and Windows scripts

**Additional context**

none

**Comment by generall** [comment]
To whoever looking for VScode configuration of dev container: https://gist.github.com/BabaBert/8fa83d51431be28babe16db551edcf91

I am not particularly sure about introducing it into repo readme, cause it will require maintenance (making sure the config actually work for newer versions).
