### ISSUE TITLE
How much will the accuracy of the search drop

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#2120]
Hello
How much will the accuracy of the search drop for 
- Product 
- compression x64
- m = 16
- ef_connstruct  = 100

I tried to search the same vector in index and I got `score` ~ `0.59`.
I expect score ~ `0.99` - `0.9`

Thanks.

**Comment by generall** [comment]
that depends on your data, there is no universal answer

**Comment by ava57r** [comment]
I didn't say that. I am trying to perform a search on the same vector that is in the index. 
I set `exact: true` in search request and I got expected score `1`.
Could you explain how the `exact` flag works?

**Comment by timvisee** [comment]
> Could you explain how the `exact` flag works?

To elaborate on this:

Normally we search through an index, this is very fast and finds us the approximate result.

With `exact: true` we go over each vector one-by-one, this can become very slow and should be used with care, but it does give you an exact answer.
