### ISSUE TITLE
Use configurable tmp_path for uploading snapshots

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2126]
**Is your feature request related to a problem? Please describe.**
Currently path for uploading snapshots is hard-coded. It lacks flexibility for cloud and k8s deployments

**Describe the solution you'd like**
Use tmp_direcory introduced in https://github.com/qdrant/qdrant/issues/1905

**Comment by timvisee** [comment]
Fixed by <https://github.com/qdrant/qdrant/pull/2156>
