### ISSUE TITLE
Use configurable tmp_path for recovering snapshots

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2127]
Is your feature request related to a problem? Please describe.
Temp path for recovering collection is hard-coded. It lacks flexibility for cloud and k8s deployments

https://github.com/qdrant/qdrant/blob/0ca6c647e1f27fab9e57727823e6af4ecf952468/src/snapshots.rs#L50

Describe the solution you'd like
Use tmp_direcory introduced in https://github.com/qdrant/qdrant/issues/1905

**Comment by agourlay** [comment]
@timvisee can be closed?
