### ISSUE TITLE
Issue with Azure File Share and Qdrant Docker Image

### ISSUE THREAD

**Issue by rliberoff** [qdrant/qdrant#2129]
## Current Behavior
We are experiencing random errors with the Qdrant Docker image deployed in an Azure Container App (a service equivalent to a managed Azure Kubernetes Service). These errors renders the Azure Container App (ACA) unusable, because it never starts.

The Qdrant data is stored in an Azure File Share and connected to the container with a mounted volume.

We really appreciate any help with this issue. Full error trace is provided below in the «Detailed Description» section.

## Steps to Reproduce
There are no specific steps to reproduce. The error happens randomly from time to time.

## Expected Behavior
This should not happen. Or at least the Qdrant database should be able to start not considering the corrupted collection.

## Context (Environment)
We're using Qdrant latest Docker image deployed into an Azure Container App (ACA) in an Azure Container Environment (ACE) with a Consumption plan, and having at least one replica always running. The scale configuration is set from 1 to 10 replicas, with a minimum of 1 replica always running.

Collections are stored in an Azure File Share, and mounted as a volume in the ACA.

The issue affects us because our AI system stops working since the database never starts.

## Detailed Description
The following is the full error trace:

```
[2023-06-21T21:26:23.183Z INFO storage::content_manager::consensus::persistent] Loading raft state from ./storage/raft_state
[2023-06-21T21:26:23.200Z INFO storage::content_manager::toc] Loading collection: DocumentQnA_DashTest
[2023-06-21T21:26:25.510Z INFO storage::content_manager::toc] Loading collection: DocumentQnA_ENCAMINA
[2023-06-21T21:26:27.275Z INFO storage::content_manager::toc] Loading collection: DocumentQnA_JoseluisDengraTest
[2023-06-21T21:26:27.669Z ERROR qdrant::startup] Panic backtrace:
    0: qdrant::startup::setup_panic_hook::{{closure}}
    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call 
        at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
    2: std::panicking::rust_panic_with_hook
        at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
    3: std::panicking::begin_panic_handler::{{closure}}
        at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
    4: std::sys_common::backtrace::__rust_end_short_backtrace
        at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
    5: rust_begin_unwind at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
    6: core::panicking::panic_fmt at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
    7: collection::collection::Collection::load::{{closure}}
    8: storage::content_manager::toc::TableOfContent::new
    9: qdrant::main
    10: std::sys_common::backtrace::__rust_begin_short_backtrace
    11: main
    12: __libc_start_main
    13: _start

[2023-06-21T21:26:27.669Z ERROR qdrant::startup] Panic occurred in file /qdrant/lib/collection/src/shards/replica_set.rs at line 501: Failed to load local shard "./storage/collections/DocumentQnA_JoseluisDengraTest/0": Service internal error: RocksDB open error: Corruption: Corruption: IO error: No such file or directory: While open a file for random read: ./storage/collections/DocumentQnA_JoseluisDengraTest/0/segments/03743b58-5f6d-4cbd-9af3-8ee1aac12164/000017.ldb: No such file or directory in file ./storage/collections/DocumentQnA_JoseluisDengraTest/0/segments/03743b58-5f6d-4cbd-9af3-8ee1aac12164/MANIFEST-000029
[2023-06-21T21:26:27.672Z ERROR collection::collection] Collection `before_drop` was not called.
[2023-06-21T21:26:27.672Z ERROR collection::shards::local_shard] Collection `before_drop` was not called.
[2023-06-21T21:26:27.672Z ERROR collection::collection] Collection `before_drop` was not called.
[2023-06-21T21:26:27.672Z ERROR collection::shards::local_shard] Collection `before_drop` was not called.
```

**Comment by suryaa62** [comment]
facing the same issue

**Comment by rliberoff** [comment]
@suryaa62 I was told by the Qdrant Team in Discord that it might be due to the Azure Container Applications (ACA) itself and Azure File Shares. That We should use Azure Kubernetes Service (AKS) or something like Web Apps for Containers.

So far, We'd changed some configurations on the ACA. If those changes fail, We're going to move the Qdrant instance into a Web App for Containers.

**Comment by piotrek-appstream** [comment]
Having the same issue. Have you managed to solve this?

**Comment by nilleb** [comment]
I have a similar issue, surely related to Azure File Share
```
{  "result": {    "status": "red",
    "optimizer_status": {      "error": "Service internal error: Can't remove segment data at ./storage/collections/sentences/0/segments/cc12d213-4616-4ee3-b7ba-b7289a88e5a6.deleted, error: Resource temporarily unavailable (os error 11)"    },
    "vectors_count": 642236,
    "indexed_vectors_count": 641740,
    "points_count": 642235,
    "segments_count": 11,
    "config": {    },
    "payload_schema": {      "authors[].documentRole": {        "data_type": "keyword",
        "points": 640776      },
      "published_at": {        "data_type": "integer",
        "points": 642235      },
      "authors[].uid": {        "data_type": "keyword",
        "points": 640776      }
    }
  },
  "status": "ok",
  "time": 5.33e-05}
```

**Comment by rliberoff** [comment]
Ok, so after many months working wiht Qdrant and Azure services, I found that the most stable results are with AKS and Azure Web Apps for Containers.

So, if you are struggling with Azure Container Apps or Azure Container Instances and Qdrant, I would suggest to move to an Azure Web App for Containers and configure to point to your current Azure File Share. So far this approach has fixed my issues.

**Comment by generall** [comment]
Going to close this issue for now.

Also, qdrant cloud is rolling out azure region, so feel free to try that as well

**Comment by nilleb** [comment]
I'd like to add that I've not experienced anymore the problem putting in place a periodic health check, asking qdrant to count the records every 5 minutes....

**Comment by rliberoff** [comment]
Hey @nilleb,

Could you please share how did you configured the periodic health check to ask Qdrant to count the records?

Thank you!

**Comment by nilleb** [comment]
In python it's easy to call the `QdrantClient.count(collection_name)` [endpoint](https://python-client.qdrant.tech/qdrant_client.qdrant_client)

Then you can wrap it in a [repeat_every](https://fastapi-utils.davidmontague.xyz/user-guide/repeated-tasks/) or call it from a DataDog Browser test...
