### ISSUE TITLE
Is it possible to compare two 3D objects like .obj files in Qdrant? 

### ISSUE THREAD

**Issue by AminMemariani** [qdrant/qdrant#2133]
I have to compare two 3D objects from two different 3D scanners. 
They scan the same object and I want to find the similarities between these two.

So far, I am doing the comparison using software called CloudCompare. The problem with it is that I have to align these two objects manually (Position, Rotation, Scale). Is it possible to compute the standard deviation and mean distance of two 3D objects using Qdrant?

**Comment by coszio** [comment]
I don't think qdrant is the tool you're looking for, unless any of [these metrics](https://qdrant.tech/documentation/concepts/search/#metrics) to compare vectors are useful to you 😄

**Comment by AminMemariani** [comment]
> I don't think qdrant is the tool you're looking for, unless any of [these metrics](https://qdrant.tech/documentation/concepts/search/#metrics) to compare vectors are useful to you 😄

Is it possible to find the correlation between two vectorized 3D objects using Qdrant?

**Comment by coszio** [comment]
If by correlation you mean distance, yes. It will, however, depend on the quality of your model that generates such embeddings.
