### ISSUE TITLE
deadlock on collection creation

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2141]
## Current Behavior
In some rare cases service hangs and stops responding to APIs.
Usually it is associated with creating many collections or heavy optimization work.

## Steps to Reproduce

1. Start a service
2. create a lot of collectons
3. Upload some points to the collections
4. make scroll (any read?) requests to collections 

With some small probability the service can stop responding

**Comment by ffuugoo** [comment]
I've been able to repro this by simply creating a 10k points collections in a loop.

- E.g., `for iter in $(seq 250); do bfb --collection-name whatever-$iter -d 1280 -n 10000 --no-wait-index; done`.
- `1280` is vector length used by the person who initially reported the bug.
- It repros both with and without `--no-wait-index`, but it's just faster _with_ the option.
- If/when `bfb` requests starts timing out suddenly, that's it.

On my machine it usually repro at around 150-180 collections.

**Comment by ffuugoo** [comment]
Also, I think that this "lock" can happen not only on collection creation, but during points upsert as well. _IIRC_, in some of my tests `bfb` started timing out in the middle of points upload (i.e., after collection was created).

**Comment by agourlay** [comment]
Are you hitting the memory limit of the host machine when it happens?
My 32Gb RAM machine can create 200 collections without any issues.

**Comment by ffuugoo** [comment]
@agourlay I'm not 100% sure if this is RAM related, tbh. I run this in Docker with 16GB memory allocated to Docker VM. With 16GB RAM it seems I can create 200 or so 10k points collections. (Though previously with 12GB RAM it did OOM around 150-180 collections.)

**Comment by generall** [comment]
fixed in 1.3.1
