### ISSUE TITLE
The seed server cannot re-join cluster after restarting.

### ISSUE THREAD

**Issue by itechbear** [qdrant/qdrant#2147]
In distributed mode, if the seed server gets restarted, it cannot re-join the cluster.

## Current Behavior

The seed server cannot re-join the cluster after restarting.

## Steps to Reproduce

1. start three servers, by running command `./qdrant --uri host-0`, `./qdrant --bootstrap host-0 --uri host-1`, `./qdrant --bootstrap host-0 --uri host-2`
2. The cluster works normally. 
3. restart the seed server without any states kept (e.g. the container gets recreated), re-join the cluster by command   `./qdrant --bootstrap host-2 --uri host-0`,

Following is the logs from the first container.
```
[2023-06-24T11:39:27.919Z INFO storage::content_manager::consensus::persistent] Initializing new raft state at ./storage/raft_state
[2023-06-24T11:39:37.930Z ERROR qdrant::startup] Panic backtrace:
0: qdrant::startup::setup_panic_hook::{{closure}}
1: as core::ops::function::Fn>::call
at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
2: std::panicking::rust_panic_with_hook
at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
3: std::panicking::begin_panic_handler::{{closure}}
at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
4: std::sys_common::backtrace::__rust_end_short_backtrace
at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
5: rust_begin_unwind
at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
6: core::panicking::panic_fmt
at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
7: core::result::unwrap_failed
at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
8: qdrant::main
9: std::sys_common::backtrace::__rust_begin_short_backtrace
10: main
11:
12: __libc_start_main
13:

[2023-06-24T11:39:37.930Z ERROR qdrant::startup] Panic occurred in file src/main.rs at line 277: Can't initialize consensus: Failed to initialize Consensus for new Raft state: Failed to add peer to known: status: Internal, message: "Failed to add peer: Service internal error: Failed to propose operation: leader is not established within 10 secs", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sat, 24 Jun 2023 11:39:37 GMT", "content-length": "0"} }

```

## Expected Behavior

The seed server should join the cluster successfully.

**Comment by generall** [comment]
Hi @itechbear, could you please check that 2-nd and 2-rd node re-elect leader properly after the first node was disabled?

Aslo, since you are removind state of the node, it might be required to explicitly remove node from the consensus before re-attaching node with the same URL

**Comment by generall** [comment]
I think I have an idea how this might have happened:

- Originally there were only 2 nodes in the cluster
- first node died
- Third node tried to join cluster only after the first one was already dead

That might explain why 

```
    "raft_info": {
      "term": 1,
      "commit": 0,
```

happens on the third node. (as if it never was in consensus)

In this situation there are not enough nodes to attach the third node.

**Comment by generall** [comment]
@itechbear does this scenario matches your situation?

**Comment by timvisee** [comment]
@itechbear Could you please make sure that your `storage` directory (for each instance) is properly persisted? It contains an important `raft_state.json` file which is needed to rejoin the cluster.

In other words: you cannot simply wipe the storage directory for a node, restart it and expect it to join the cluster again.

**Comment by timvisee** [comment]
> Some other distributed systems do work in this scenario. For example, Apache Cassandra, if I remember it right. I'd expect qdrant to work too. Thanks for letting me know the limitation.

Happy to see that clarifies what's going on. I assume that fixed the problem.

Currently this is required to make sure the same node (machine) gets the same peer ID assigned. Maybe there's something we can improve upon here, but we haven't planned anything like that.

Closing this now, feel fee to open it if you have further questions.

**Comment by pschichtel** [comment]
this has been a nice surprise after trying to migrate a pod with local storage. I currently have the issue that 2 out of 3 nodes lost their state file and it seems that the remaining node doesn't become leader because it needs at least one more member to get a quorum.

Any recommendations to fix this situation?

**Comment by pschichtel** [comment]
Ok we managed to recover that cluster by removing the peers from the first node (so it becomes leader of a single node cluster) and then fabricating raft_state.json files for the other nodes that contain their original peer ID in "this_peer_id", but no other peers anywhere.
