### ISSUE TITLE
Memory structure on Runtime

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#2150]
Hello.

I tried to set some params `on_disk*`
`hnsw_config.on_disk = true`
`on_disk_payload = true`
`quantization_config.always_ram = true`
`vectors_config.on_disk = false`

How can I predict the memory size of indexes?
What internal structures affect memory consumption?

**Comment by timvisee** [comment]
> What internal structures affect memory consumption?

The `on_disk` parameter usually means that memory mapped files will be used. All memory mapped data primarily persists on disk, but may still all be loaded in memory.

To give two examples on what that would mean:

If using a machine with a huge amount of RAM and memory mapped files: all memory mapped data may eventually end up in RAM. So if you'd have 32 GB of RAM, and your vector data is 10 GB, you may end up consuming 10-15 GB of RAM eventually.

If using a machine with a limited amount of RAM and memory mapped files: it is likely that all available RAM will be used to make best use of the system resources. So if you'd have 4 GB of RAM, and your vector data is 10GB, it will probably end up using all 4 GB of RAM. Without using `on_disk` we would crash, with it we won't crash.

In short, when using memory mapped data, all available RAM will still be used if necessary.
So, using memory mapped files doesn't necessarily decrease RAM usage when there's a lot available. Instead it makes it possible to still use Qdrant if we don't have enough RAM for everything; it then prevents out-of-memory crashes and tries to use RAM efficiently.

You should know that modern operating systems are quite smart with managing this. For example, if all RAM is used for memory mapped data and a different application needs more memory, your kernel automatically drops some of this memory mapped data to make room for it. Using a lot of RAM is good for the best performance, don't forget: unused RAM is wasted RAM.

> How can I predict the memory size of indexes?

I don't have a good estimation for the size of the index specifically, but a good rule of thumb for everything would be 1.5 times the size of your vectors. [Documentation](https://qdrant.tech/documentation/cloud/capacity/#basic-configuration).

Forgive me for the long explanation. I hope this clarifies and answers your question. Please let me know if you have any further questions!

**Comment by ava57r** [comment]
I read documentation more 3 month ago. 
This link is really useful.
Thanks.
