### ISSUE TITLE
Recall is difference for a small index and a huge index 

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#2155]
Hello
I try to check recall for difference indexes and I can not get the same vector from Index.

## Current Behavior
qdrant version: v1.2
I use
scalar quantizer
m 16
ef 128

I can not find the same vector 6 times from  100 times with score 0,9 in index with 200 millions vectors.
I tried set `limit = 1000` and response did not contain my `uid`.

## Steps to Reproduce
1. create index with 1 million vectors
2. search some vectors in index which contains their. score will be OK (1.0 - 0.98)
3. create index with 200 millions vectors
4.  search some vectors in index which contains their. Some responses will not contain uid with limit 1000.

## Expected Behavior
all of vectors are in response with score ~ 0.9

**Comment by ava57r** [comment]
I use `quantile = 0.99` from link [quantile](https://qdrant.tech/documentation/guides/quantization/#setting-up-scalar-quantization)

**Comment by generall** [comment]
Qdrant is using ANN search, A stands for Approximate.
You can tune precision of the search by adjusting `m` and `ef` params

**Comment by timvisee** [comment]
Note that you can also use `exact=true` for exact results. That is extremely expensive/slow however, as it skips the index all together.

**Comment by ava57r** [comment]
Thanks
