### ISSUE TITLE
Documentation: Bulk Upload Vectors

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#2160]
Hello

I read it early
[Bulk Upload Vectors](https://qdrant.tech/documentation/tutorials/bulk-upload/)

and recommendation was "set indexing_threshold as 1_000_000 "

Now set "indexing_threshold: 0"

Does It depend on the version of Qdrant?

**Comment by generall** [comment]
yes, is was change in one of the recent versions

**Comment by ava57r** [comment]
I am testing v1.2.2 now
1_000_000 or 0 ?

**Comment by ava57r** [comment]
I found this PR
https://github.com/qdrant/qdrant/pull/1824

**Comment by ava57r** [comment]
I think I've found the answer. Thanks
