### ISSUE TITLE
Potential deadlock in HNSW indexer

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#2163]
Running [lockbud](https://github.com/BurtonQin/lockbud) on our codebase shows a new potential deadlock.

Disclaimer: running the tool is not straightforward and requires a very long compile time cycle. 

```json
{
  "DoubleLock": {
    "bug_kind": "DoubleLock",
    "possibility": "Possibly",
    "diagnosis": {
      "first_lock_type": "ParkingLotRead(std::vec::Vec<u32>)",
      "first_lock_span": "lib/segment/src/index/hnsw_index/graph_layers_builder.rs:342:29: 342:43 (#0)",
      "second_lock_type": "ParkingLotRead(std::vec::Vec<u32>)",
      "second_lock_span": "lib/segment/src/index/hnsw_index/graph_layers_builder.rs:55:13: 55:18 (#0)",
      "callchains": [
        [
          [
            "lib/segment/src/index/hnsw_index/graph_layers_builder.rs:344:25: 350:26 (#0)"
          ],
          [
            "lib/segment/src/index/hnsw_index/graph_layers.rs:107:9: 107:92 (#0)"
          ],
          [
            "lib/segment/src/index/hnsw_index/graph_layers.rs:81:13: 85:15 (#0)"
          ]
        ]
      ]
    },
    "explanation": "The first lock is not released when acquiring the second lock"
  }
} 
```

It needs to be investigated to assess if there is a real issue and ideally fix it.

**Comment by generall** [comment]
The double read can't actually happen in this case, as the point locked in 

> `lib/segment/src/index/hnsw_index/graph_layers_builder.rs:344:25`

is the one being inserted, while at

> lib/segment/src/index/hnsw_index/graph_layers.rs:81:13: 85:15

We lock candidates to be inserted.

Going to make a PR to fix warning anyway

**Comment by agourlay** [comment]
Tackled in https://github.com/qdrant/qdrant/pull/2167
