### ISSUE TITLE
`Can't send Raft message over channel` when adding new peer

### ISSUE THREAD

**Issue by kylemclaren** [qdrant/qdrant#2166]
## Current Behavior

I am running Qdrant v1.3.0 on a distributed three-node cluster on Fly.io Machines in one single region. When a new peer node is added in a different region, Raft error messages occur:

```
2023-06-28T13:49:08Z app[148e722b75d789] jnb [info][2023-06-28T13:49:08.932Z DEBUG hyper::client::connect::dns] resolving host="6e82d379c04d58.vm.qdrant-6pn.internal"
2023-06-28T13:49:08Z app[148e722b75d789] jnb [info][2023-06-28T13:49:08.933Z DEBUG hyper::client::connect::http] connecting to [fdaa:1:3dbe:a7b:172:1b46:2567:2]:6335
2023-06-28T13:49:09Z app[6e82d379c04d58] lhr [info][2023-06-28T13:49:09.196Z ERROR qdrant::tonic::logging] gRPC /qdrant.Raft/Send unexpectedly failed with Internal error "Can't send Raft message over channel" 0.000053
```

Although the peer seems to be added to the cluster, the consensus thread status shows as "stopped_with_err" due to a failure to apply a configuration change entry:

```json
    "consensus_thread_status": {
      "consensus_thread_status": "stopped_with_err",
      "err": "Failed to apply committed entries: Failed to apply configuration change entry"
    },
```

## Steps to Reproduce

1. Set up a three-node Qdrant cluster in a single Fly region using https://github.com/kylemclaren/qdrant-on-fly
2. Create a collection and ingest some vector data.
3. Add a new peer node in a different region using `flyctl machine clone --region <NEW_REGION>`.

## Expected Behavior

The peer should be added without error, and the cluster should function seamlessly across regions.

## Possible Solution

Relevant code: https://github.com/qdrant/qdrant/blob/master/src/tonic/api/raft_api.rs#L40

## Context (Environment)

Attempting to create a globally distributed Qdrant cluster, I want to scale out my cluster to different regions by adding new peers.

**Comment by generall** [comment]
Hi @kylemclaren, we can't really maintain fly.io deployments, would you consider using our cloud instead?

**Comment by kylemclaren** [comment]
This has been suggested to me in a number of places and it is kind of missing the point, I feel. I don't really have a use-case for Qdrant Cloud (though it looks great!). My experiment is more to create an distributed cluster on a platform such as Fly, but really could be anything like AWS or DigitalOcean

If I had said this was on AWS, would the response be the same?

**Comment by generall** [comment]
I would say use our helm chart

**Comment by kylemclaren** [comment]
So I would be forced to use k8s to run a distributed deployment? Are you saying that you won't be accepting bug reports based on what platform someone is trying to run Qdrant on?

**Comment by generall** [comment]
well, you can also do it on pure VMs, like EC2 or whatever. But I am no expect in fly.io, never used it. There might be some hidden pitfalls you didn't consider

**Comment by generall** [comment]
in other words, I can't follow your `Steps to Reproduce` as they invoke some third-party non-standard service

**Comment by kylemclaren** [comment]
Yep, and I opened an issue to try and flesh out those pitfalls. Not really looking for anyone to support or "maintain" my deployment, rather to discuss something that is potentially broken and try get it running on my platform of choice.

**Comment by kylemclaren** [comment]
Anyways, let me rather try `pg_vecor` on Supabase
