### ISSUE TITLE
Auto increment Point IDs or support ULID

### ISSUE THREAD

**Issue by sevenjay** [qdrant/qdrant#2219]
Currently the database lacks an auto-increment functionality for Point IDs both in `upload_collection` and `upsert`. This means that when inserting new points into the database, we need to manually assign unique IDs.

```python
client.upload_collection(
                collection_name=collection_name,
                ids=None,
                vectors=vectors,
                payload=payloads
            )
```
Once executed, the system will automatically increment the Point IDs. Subsequently, next 
`upload_collection` function will start overwriting from 0.

```python
client.upsert(
                collection_name=self._collection_name,
                points=models.Batch(
                    ids=None,
                    payloads=payloads,
                    vectors=vectors
                ),
            )
```
for `upsert` error for Batch ids none is not an allowed value

**Describe the solution you'd like**
I would like to have an auto-increment feature for Point IDs in the database. This means that whenever a new point is inserted into the database, the system should automatically assign a unique ID to it, without the need for manual intervention. The auto-increment should ensure that each new point receives a higher ID than the previous one, maintaining a consistent and sequential ordering.

**Describe alternatives you've considered**
One alternative solution could be to generate unique IDs by a custom algorithm. Needs to find the last ID first.

Automating the ID assignment would improve efficiency and reduce the likelihood of errors.

**Comment by sevenjay** [comment]
In the end, I used ULID to solve it, although it's a bit ugly.
```python
import time
from ulid import monotonic as monotonic_ulid

    ts = time.time()
    for result_batch in iter_batch(embedding_results, self._batch_size):
        for result in result_batch:
            ...
            node_ids.append(monotonic_ulid.from_timestamp(ts).uuid.hex)
            vectors.append(result.embedding)
            payloads.append(metadata)

        self._client.upsert(
            collection_name=self._collection_name,
            points=models.Batch(
                ids=node_ids,  # ids=node_ids,
                vectors=vectors,
                payloads=payloads,
            ),
        )
```
at least, support ulid in Point IDs?
https://github.com/ahawker/ulid

**Comment by coszio** [comment]
I am curious, what made you choose ULID instead of UUIDs?

**Comment by sevenjay** [comment]
If you have a collection of different items and you want to ensure uniqueness, it's not an issue since each item will be unique by UUID or a counter number.

However, if you need to sort the items in a specific order and also handle scenarios where new items may be added or existing ones may be deleted, finding the maximum count or scrolling through the entire collection can be inefficient.

To address this, you can use ULID to make the items both unique and sortable. ULID is a type of identifier that combines a timestamp and a random component, resulting in a value that can be sorted lexicographically.

**Comment by timvisee** [comment]
We've worked on unique ID generation before but decided to stop our efforts on it: https://github.com/qdrant/qdrant/pull/1535

What about using [`uuid.uuid4()`](https://docs.python.org/3/library/uuid.html#uuid.uuid4) on the client for unique IDs and adding a timestamp as [payload](https://qdrant.tech/documentation/concepts/payload/). That would allow both uniqueness and time-based sorting.

**Comment by sevenjay** [comment]
I think it is sufficient for the server to accept ULIDs, while allowing the client to generate ULIDs is acceptable. UUIDs generated by the client do not have any inherent order. Only ULIDs generated within the same millisecond (with different seeds) cannot be sorted, but we will not generate ULIDs with different seeds within the same millisecond.

**Comment by timvisee** [comment]
I understand that ULIDs may be helpful in this situation, but we want to prevent adding all kinds of ID types to the core product as this can be very expensive. We'd therefore like to keep the ID types to the minimum possible.

Doesn't adding a timestamp as payload solve the issue? It would allow sorting as you described, with arguably better control. This would require no Qdrant changes at all.

**Comment by sevenjay** [comment]
We have already included a timestamp in the payload, but it is only for recording purposes and not for ordering. The implementation of the "order_by" feature has not been completed yet. https://github.com/qdrant/qdrant/issues/1763

**Comment by sevenjay** [comment]
It's ok with `monotonic_ulid.from_timestamp(ts).uuid.hex`, convert ulid to uuid string.
just a suggestion for you to consider
