### ISSUE TITLE
Is it ok to copy collections files in /storage to another machine and run docker directly ? 

### ISSUE THREAD

**Issue by jarheadjoe** [qdrant/qdrant#2220]

**Comment by coszio** [comment]
Recommended way is via snapshots https://qdrant.tech/documentation/concepts/snapshots/#snapshots-for-the-whole-storage

**Comment by jarheadjoe** [comment]
@coszio How to use the restore command on Docker?

**Comment by timvisee** [comment]
> Is it ok to copy collections files in /storage to another machine and run docker directly?

As @coszio noted, using snapshots is recommended.

Other than that, copying the directory is possible. We currently have no guarantees for file compatibility across different systems though. So you should only give that a shot when copying to a machine running the same OS and same CPU architecture. Or better, only copy on the very same machine.

> How to use the restore command on Docker?

This is tricky, but can be done:

```bash
docker run -p 6333:6333 \
    -v $(pwd)/qdrant_storage:/qdrant/storage \
    -v $(pwd)/my_snapshot.snapshot:/qdrant/my_snapshot.snapshot \
    qdrant/qdrant \
    ./qdrant --snapshot ./my_snapshot.snapshot:my_snapshot
```

This mounts the snapshot file into the container and rewrites the startup command to include `--snapshot`. Be sure to change the `my_snapshot` occurrences in the above command to what you're using.

**Comment by jarheadjoe** [comment]
@jarheadjoe Thx for your answers. I tried MacOS to Centos7, and failed.

**Comment by do-me** [comment]
For me it fails too: 

```
docker run -p 6333:6333 -v $(pwd)/test_collection_qdrant.snapshot:/qdrant/test_collection_qdrant.snapshot     qdrant/qdrant     ./qdrant --snapshot ./test_collection_qdrant.snapshot:test_collection_qdrant
           _                 _
  __ _  __| |_ __ __ _ _ __ | |_
 / _` |/ _` | '__/ _` | '_ \| __|
| (_| | (_| | | | (_| | | | | |_
 \__, |\__,_|_|  \__,_|_| |_|\__|
    |_|

Access web UI at https://ui.qdrant.tech/?v=v1.1.0

[2023-09-12T13:39:46.875Z INFO  storage::content_manager::consensus::persistent] Initializing new raft state at ./storage/raft_state
[2023-09-12T13:39:46.887Z INFO  qdrant::snapshots] Recovering snapshot test_collection_qdrant from ./test_collection_qdrant.snapshot
[2023-09-12T13:39:46.887Z INFO  qdrant::snapshots] Collection path: ./storage/collections/test_collection_qdrant
[2023-09-12T13:39:46.919Z ERROR qdrant::startup] Panic occurred in file src/snapshots.rs at line 67: Failed to recover snapshot test_collection_qdrant: Service internal error: File IO error: failed to iterate over archive
```

Adding the flag `-v $(pwd)/qdrant_storage:/qdrant/storage` throws the same error.

Apparently it fails to read the snapshot it so I suppose it has something to do with the way the file is passed from my host to the Docker image.
