### ISSUE TITLE
Service internal error: IO Error: Function not implemented (os error 38)

### ISSUE THREAD

**Issue by jarheadjoe** [qdrant/qdrant#2226]
build collection on centosOS

{
    "result": {
        **"status": "red",
        "optimizer_status": {
            "error": "Service internal error: IO Error: Function not implemented (os error 38)"
        },**
        "vectors_count": 1707184,
        "indexed_vectors_count": 0,
        "points_count": 1707184,
        "segments_count": 16,
        "config": {
            "params": {
                "vectors": {
                    "size": 1024,
                    "distance": "Cosine",
                    "on_disk": true
                },
                "shard_number": 2,
                "replication_factor": 1,
                "write_consistency_factor": 1,
                "on_disk_payload": true
            },
            "hnsw_config": {
                "m": 16,
                "ef_construct": 100,
                "full_scan_threshold": 10000,
                "max_indexing_threads": 0,
                "on_disk": true
            },
            "optimizer_config": {
                "deleted_threshold": 0.2,
                "vacuum_min_vector_number": 1000,
                "default_segment_number": 8,
                "max_segment_size": null,
                "memmap_threshold": 20000,
                "indexing_threshold": 20000,
                "flush_interval_sec": 5,
                "max_optimization_threads": 1
            },
            "wal_config": {
                "wal_capacity_mb": 32,
                "wal_segments_ahead": 0
            },
            "quantization_config": null
        },
        "payload_schema": {}
    },
    "status": "ok",
    "time": 0.000565007
}

**Comment by jarheadjoe** [comment]
[2023-07-06T23:49:35.433Z ERROR qdrant::startup] Panic occurred in file lib/collection/src/update_handler.rs at line 243: Optimization error: Service internal error: IO Error: Function not implemented (os error 38)
[2023-07-06T23:49:44.177Z ERROR collection::update_handler] Optimization error: Service internal error: IO Error: Function not implemented (os error 38)
[2023-07-06T23:49:44.177Z ERROR qdrant::startup] Panic backtrace: 
       0: qdrant::startup::setup_panic_hook::{{closure}}
       1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
       2: std::panicking::rust_panic_with_hook
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
       3: std::panicking::begin_panic_handler::{{closure}}
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
       4: std::sys_common::backtrace::__rust_end_short_backtrace
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
       5: rust_begin_unwind
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
       6: core::panicking::panic_fmt
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
       7: tokio::runtime::task::raw::poll
       8: std::sys_common::backtrace::__rust_begin_short_backtrace
       9: core::ops::function::FnOnce::call_once{{vtable.shim}}
      10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      12: std::sys::unix::thread::Thread::new::thread_start
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
      13: <unknown>
      14: clone
    
[2023-07-06T23:49:44.177Z ERROR qdrant::startup] Panic occurred in file lib/collection/src/update_handler.rs at line 243: Optimization error: Service internal error: IO Error: Function not implemented (os error 38)

**Comment by jarheadjoe** [comment]
system: centos 7.6 x64
operation: 
1)create collection, upload ~1 million points, with
client.recreate_collection(
      collection_name=collection_name,
      vectors_config=rest.VectorParams(
          size=vector_size,
          distance=rest.Distance[distance_func],
          on_disk=True
      ),
      optimizers_config=rest.OptimizersConfigDiff(
          **indexing_threshold=0**, default_segment_number=8,
          memmap_threshold=20000
      ),
      hnsw_config=rest.HnswConfigDiff(on_disk=True),
      shard_number=2,
      on_disk_payload=True
  )
2) Then begin indexing with 
client.update_collection(
      collection_name=COLLECTION_NAME,
      optimizer_config=rest.OptimizersConfigDiff(
          **indexing_threshold=20000**
      )
  )

**Comment by agourlay** [comment]
Thank you for the report!

Which version of Qdrant are you using?
Are you getting this error systematically?

**Comment by jarheadjoe** [comment]
Qdrant docker :latest
I reinstall my operate system to centos8, this error dose not occour.

**Comment by generall** [comment]
Thanks for reporting @jarheadjoe! We will check the minimal kernel requirement and update documentation accordingly

**Comment by vkras** [comment]
We are also seeing it ""you tested on 2 different os versions other than centos 7, you've tested on Rocky 8 and Rocky 9,  on 2 different types of vm hosts as well,  and you've tested it on both physical and virtual hardware, it is a downstream of RHEL running the RHEL kernal, kernel  5.14.XXXX"

**Comment by generall** [comment]
@chenbt-hz we test on 5.4, I don't yet have information about minimal version below that

**Comment by joyzho** [comment]
we have the same issue
