### ISSUE TITLE
[2023-07-08T18:20:18.892Z ERROR collection::update_handler] Optimization error: Service internal error: IO Error: Function not implemented (os error 38)

### ISSUE THREAD

**Issue by leonardlin** [qdrant/qdrant#2236]
logs show:

[2023-07-08T18:20:18.892Z ERROR collection::update_handler] Optimization error: Service internal error: IO Error: Function not implemented (os error 38)

![image](https://github.com/qdrant/qdrant/assets/5815009/c26b2927-c773-42a0-8fb3-b15d60b55d4f)

## Current Behavior
using v 1.3.1
python qdrant client 1.3.1

I import a lot of records 768dim 
into a collection that is created with the following parameters:
qclient.recreate_collection(
    collection_name=collectionName,
    vectors_config=VectorParams(size=self.embeddingService.dimensions, distance=Distance.COSINE),
    on_disk_payload=True,
    optimizers_config=OptimizersConfigDiff(memmap_threshold=20000),
    quantization_config=ScalarQuantization(
    scalar=ScalarQuantizationConfig(
        type=ScalarType.INT8,
        always_ram=True,
    ),

every 1-2 hours I get the error shown above

## Expected Behavior
no error

## Context (Environment)
not sure what the error means.
Are there now records missing?

**Comment by generall** [comment]
resolved in discord. The problem was related to the old kernel version

**Comment by leonardlin** [comment]
@generall do you mean the problem with kernel 2.4 and that rust only supports 2.6.18+?

I'm using the official qdrant docker, running on
Amazon Linux 2  4.14.301-224.520.amzn2.x86_64

Kernel 4.14

Or do I need a newer kernel?
