### ISSUE TITLE
Improve handling of timed-out search requests

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2273]
**Is your feature request related to a problem? Please describe.**

Currently, there are no limitation of how long the search query could be executed. That might cause the problem, that abandoned queries may still continue to execute for a long time. 
Query delay may be caused by either querying the instance with very slow disk, no cache, or just huge wave of requests.

**Describe the solution you'd like**
Internally, we already have a timeout for communication between shards - 1 minute.
As a first step, we can enforce the same timeout on segment-level query execution.

Implementation can consist of 2 parts:

- tokio:select in async part of the code which will track the time spent and if timeout happens - return appropriate error message + trigger cancellation atomic bool
- modification to the RawScorer, which will atomic take into account and will execution if timeout reached.  

**Describe alternatives you've considered**

- Make everything async
- Use tokio cancellation token (will require segment to depend on tokio)
- 

**Additional context**

The issue requires experimental setup before implementing changes

**Comment by timvisee** [comment]
Fixed in <https://github.com/qdrant/qdrant/pull/2293>.
