### ISSUE TITLE
java client.searchPoints response payload is null

### ISSUE THREAD

**Issue by daizhanchao** [qdrant/qdrant#2291]
![image](https://github.com/qdrant/qdrant/assets/33017467/29639d92-f0f3-4cf4-875b-9ebd822a1a48)

**Comment by generall** [comment]
Hi @daizhanchao java client is supposed to have `with_payload` param in the search request. Are you using it?

**Comment by daizhanchao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by daizhanchao** [comment]
> 

I would like to retrieve the stored data from the returned results. Currently, this portion of the data is empty, and only the relevant ID, vector values, and scores are provided. The "setPayload" value in PointStruct is missing.

**Comment by sunzhongshan1988** [comment]
yes I have the same problem， version 1.3.0

**Comment by daizhanchao** [comment]
Thank you very much ！！！
