### ISSUE TITLE
How to gracefully upgrade the currently running stand-alone/cluster version

### ISSUE THREAD

**Issue by zjy282** [qdrant/qdrant#2298]
As in the title, currently running version 1.1.1, if you want to upgrade to >1.2.0, you will be prompted that the version is incompatible through snapshot recovery

**Comment by agourlay** [comment]
You should be able to upgrade one minor version at the time.

Can you please add more details regarding the target version and the exact error.

**Comment by zjy282** [comment]
> You should be able to upgrade one minor version at the time.
> 
> Can you please add more details regarding the target version and the exact error.

Thank you for your help. I have learned from Discord that services deployed through Docker can be upgraded sequentially from 1.1.1-"1.2.x-"1.3.2 by using shared data files. It is recommended that you write the upgrade-related method instructions into official documents or Readme.

**Comment by agourlay** [comment]
Added to the official documentation with https://github.com/qdrant/landing_page/pull/253
