### ISSUE TITLE
Filters don't function properly when only the key attribute is specified 

### ISSUE THREAD

**Issue by BabaBert** [qdrant/qdrant#2299]
## Current Behavior
When you only specify a filter key but not a match or a range, the filter will always return an empty set.
It seems like the filter tries to match against `null` which would explain the result for specified payloads. 

## Expected Behavior
I would expect empty rules to be ignored if not specified, so that the filter ambiguously returns every point that contains the key.

## Steps to Reproduce

openapi/tests/openapi_integration/helpers/collection_setup.py:
```suggestion path=openapi/tests/openapi_integration/helpers/collection_setup.py
                {
                    "id": 1,
                    "vector": [0.05, 0.61, 0.76, 0.74],
                    "payload": {"city": "Berlin", "population": 4500000}
                },
```

openapi/tests/openapi_integration/test_filter.py:
```suggestion path=openapi/tests/openapi_integration/test_filter.py
def test_match_key():
    response = request_with_validation(
        api='/collections/{collection_name}/points/search',
        method="POST",
        path_params={'collection_name': collection_name},
        body={
            "vector": [0.2, 0.1, 0.9, 0.7],
            "limit": 3,
            "filter": {
                "must": [
                    {
                        "key": "population",
                    }
                ]
            }
        }
    )
    assert response.ok

    print(response.json())

    json = response.json()
    assert len(json['result']) == 1

    ids = [x['id'] for x in json['result']]
    assert 1 in ids
```

**Comment by agourlay** [comment]
Thanks for the report :+1: 

I understand that the current behavior can be surprising.
I have created a small fix to discuss with the team https://github.com/qdrant/qdrant/pull/2305

**Comment by generall** [comment]
I think I would rather expect this query to be invalid at all

**Comment by agourlay** [comment]
Introducing a validation for field condition is also a valid approach :+1: 

Maybe a good use case for our new derived payload validation infrastructure.

**Comment by agourlay** [comment]
It is difficult to attribute semantic to a filter which is missing the action part.

IMHO it is either an illegal state or a pass through like in my draft PR.

Given the confusion it generates, I believe making it an illegal state by returning an explicit error to the user would be the most sensible way forward.

**Comment by varshneydevansh** [comment]
can I pick this?

**Comment by russcam** [comment]
I vote for this being an illegal state. The semantics of a filter on `null` and empty values are covered by [`is_null`](https://qdrant.tech/documentation/concepts/filtering/#is-null) and [`is_empty`](https://qdrant.tech/documentation/concepts/filtering/#is-empty), respectively.

**Comment by agourlay** [comment]
@varshneydevansh Sure go for it, I am not aware of anyone working on this.

@russcam Thanks for the vote :+1:

**Comment by varshneydevansh** [comment]
Okay, I'll work on this. =)

**Comment by varshneydevansh** [comment]
Which file should I start working with and do I have to work on the UI part https://github.com/qdrant/qdrant-web-ui/tree/master/src ?

**Comment by agourlay** [comment]
No need to touch. the web UI :)

Look for the type `FieldCondition` and try to use our validation infrastructure  to return a client side error if only the key attribute is specified.

**Comment by amit-62** [comment]
Hello @agourlay, can I work on this issue? Do I have to validate e.g. [go client.](https://github.com/qdrant/go-client) as well as other clients.

**Comment by agourlay** [comment]
@amit-62 Feel free to give it a try, we usually do not assign issues.

This is a pure server side change, no need to modify any clients.

Check my previous comment about `FieldCondition` to get started.

**Comment by varshneydevansh** [comment]
Apologies, everyone, I wasn't able to do this as I had a little pending work of my book writing which I am trying to complete and will join soon. =)

**Comment by amit-62** [comment]
Hello @agourlay, at the place of returning [this](https://github.com/qdrant/qdrant/pull/2305/files#diff-88aa83be35b3797966ba5c957cce57d559935090b93e80d62f549644779aecf9R30) closure, can I return an error will it work?

**Comment by agourlay** [comment]
@varshneydevansh @amit-62 

I started typing a longer explanation to guide you through a implementation when I realized that I basically done it myself.

I decided to push my solution instead to streamline this issue has we had having many back and forth already.

Hopefully there will be issues which are more amenable for new contributors :+1: 

https://github.com/qdrant/qdrant/pull/2745

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/qdrant/releases/tag/v1.6.0
