### ISSUE TITLE
Storage upgrade tool

### ISSUE THREAD

**Issue by Jesse-Bakker** [qdrant/qdrant#2306]
**Is your feature request related to a problem? Please describe.**
When updating qdrant to a newer version that's more than one minor version newer, this requires one upgrade by one minor version step at a time. This is time consuming, manual, and error-prone

**Describe the solution you'd like**
A tool like pg_upgrade, included with the qdrant distribution, which detects the version of the storage pointed to, and upgrades the storage (step by step) automatically up to the version that the tool was bundled with.

**Comment by generall** [comment]
So far we keep all the migration scripts in the core, but storage compatibility is not the only criteria. We also need to maintain compatibility of the internal gRPC requests. So having storage upgrade tool won't resolve one-by-one version upgrade requirement
