### ISSUE TITLE
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)

### ISSUE THREAD

**Issue by developeriopinion** [qdrant/qdrant#2312]
Raw response content:
b'{"status":{"error":"Wrong input: Vector inserting error: expected dim: 768, got 1536"},"time":0.000203256}'

the upload python program snippet:
vectors_config = qdrant_client.http.models.VectorParams(
    size=768,
    distance=qdrant_client.http.models.Distance.COSINE
)

**Comment by joein** [comment]
Hello @developeriopinion 

you’ve created a collection with vector dimension equals to 768, but trying to upload vectors with dimensionality of 1536

**Comment by hu372197979** [comment]
I also encountered the same error, but I used 1536 when I created the document and 768 when I updated or queried it

**Comment by agourlay** [comment]
I think the issue has been addressed, feel free to reopen a new one if it is not the case.
