### ISSUE TITLE
Test HTTP API

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#232]
**Is your feature request related to a problem? Please describe.**

The HTTP API is currently not tested which represents a risk in terms of introducing regressions.

The only safety net present is having developers execute locally `./tests/basic_api_test.sh` before submitting PRs.

The current situation presents several issues:
- many features are not tested via the bash script
- it is not enforced in the development workflow
- increasing the test coverage is not part of the development worklow
- using a bashscript is not super ergonomic

**Describe the solution you'd like**

1) HTTP tests that are executed as part of the CI pipeline to catch regressions
2) pick a testing strategy (see next paragraph)
3) make HTTP testing part of the requirements to merge new features 

**Describe alternatives you've considered**

Concerning the testing strategy, there are 2 main approaches.

1) self contained tests
- tests are spawning servers https://actix.rs/docs/testing/
- pro: have everything contained in the core project
- contra: Rust is not necessarily the best language to express complex tests

2) black box testing:
- spawn a server and execute tests written in a DSL such as [cucumber](https://cucumber.io/) or [cornichon](https://github.com/agourlay/cornichon) (shameless plug :sweat_smile:)
- pro: more readable and easier for non dev to add tests
- contra: spawing a server makes things more complicated & introducing additional non Rust tooling

**Comment by generall** [comment]
API tests should involve usage of the client, generated from OpenAPI definitions. In this case we would be able to check correctness of the definitions.

**Comment by e-ivkov** [comment]
I think even before we have extensive HTTP API tests, it would be better to add a step to CI to run the bash script.

**Comment by agourlay** [comment]
I am trying to get our integration tests bash scripts to run on CI as a first step :+1:

**Comment by e-ivkov** [comment]
[OpenAPI Generator npm package](https://github.com/OpenAPITools/openapi-generator) supports generating Rust clients. This might be useful for testing our API from the Rust unit tests.

There is also a Rust crate [paperclip](https://github.com/paperclip-rs/paperclip) that should be able to generate Rust clients, but it seems less finished.

**Comment by agourlay** [comment]
We now have a safety net provided by https://github.com/qdrant/qdrant/pull/279

The next step is to investigate the Rust client generator and some basic actix-web testing.

**Comment by agourlay** [comment]
Here is the outcome of the first try at generating a Rust client in https://github.com/qdrant/qdrant/pull/287

- [https://github.com/OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator) does not generate valid code of `anyOf` types (see https://github.com/qdrant/qdrant/pull/287#issuecomment-1031322763)
- [paperclip](https://github.com/paperclip-rs/paperclip) looks promising but does not support openapi spec V3

Where can we go from there?

If generating a Rust client is currently difficult, we could focus on our Python [client](https://github.com/qdrant/qdrant_client) which is actually used.

The plan would be to:
- add more tests to the Python client
- add a Github action to the Python client to run the tests against a local qdrant service (as CI)
- modifying the openapi spec on the qdrant repo should trigger the regeneration of the python client and run its tests

**Comment by e-ivkov** [comment]
Recently found another generator from Oxide computer https://github.com/oxidecomputer/progenitor

It seems to support 3.0.x version

**Comment by generall** [comment]
> Recently found another generator from Oxide computer https://github.com/oxidecomputer/progenitor

tried, crashes on our spec =(

**Comment by e-ivkov** [comment]
> > Recently found another generator from Oxide computer https://github.com/oxidecomputer/progenitor
> 
> tried, crashes on our spec =(

Maybe let's submit an issue to them for the future? I think it's actively maintained.

**Comment by generall** [comment]
I am going to close this issue - for gRPC there should be a different one once required.
