### ISSUE TITLE
Website Documentation and example has wrong schema in "with_lookup"

### ISSUE THREAD

**Issue by keotic** [qdrant/qdrant#2325]
## Current Behavior

in https://qdrant.tech/documentation/concepts/search/#lookup-in-groups
the "with_lookup" schema on the website has "collection_name" key.
While the OpenApi schema has a "collection" key:

  "WithLookup": {
        "type": "object",
        "required": [
          "collection"
        ],
        "properties": {
          "collection": {
            "description": "Name of the collection to use for points lookup",
            "type": "string"
          },
          "with_payload": {
            "description": "Options for specifying which payload to include (or not)",
            "default": true,
            "anyOf": [
              {
                "$ref": "#/components/schemas/WithPayloadInterface"
              },
              {
                "nullable": true
              }
            ]
          },
          "with_vectors": {
            "description": "Options for specifying which vectors to include (or not)",
            "default": null,
            "anyOf": [
              {
                "$ref": "#/components/schemas/WithVector"
              },
              {
                "nullable": true
              }
            ]
          }
        }
      },

## Expected Behavior

Examples and documentation should match the lates API schemas

**Comment by kacperlukawski** [comment]
@keotic Thanks for pointing this out!

**Comment by timvisee** [comment]
Thanks!

Fixed in <https://github.com/qdrant/landing_page/pull/230>.
