### ISSUE TITLE
Add API for points distance calculations by ids

### ISSUE THREAD

**Issue by keotic** [qdrant/qdrant#2334]
**Is your feature request related to a problem? Please describe.**
Currently, to get the distance between sets of points given their ids we need to retrieve the points vectors and perform the 
distance calculations on the retrieved vectors (Dot, Cosine etc..)

When the sets of points ids is large large payloads of vectors needs to be retrieved and handled.

For example:
Assume dim size of 1024, and 2 sets of points ids of size 10,000 that their dot product needs to be calculated.

1. 10,000 *2 ids needs to be sent to the server in order to fetch their vectors
2. A payload of 10,000 * 2 * 1024 vectors needs to be loaded from the server (over 800MB for fp32)
3. Dot product calculation on the client yielding a matrix of 10,000^2 ( about 400MB )

**Describe the solution you'd like**
Add API to get the distances given the points ids.
It will remove the unnecessary 2 & 3 steps, saving a lot of client, server and networking resources.

**Comment by agourlay** [comment]
Can you please describe your use case, it is not clear to me why you need the actual distance between points.

**Comment by keotic** [comment]
Thanks for the quick reply.
Calculating distances by points ids is useful for scenarios of dynamic interactions received from front-end apps that only hold the points ids.
For example, consider an app with 2 long documents (each is chunked to many chunks, the app holds the chunks point ids)
if we want to find common / similar chunks between the 2 documents, we need to get the distance matrix between the chunks of the 2 documents.

This functionality can be achieved in a cumbersome way by using the current API of recommend  + lookup + filters

**Comment by fenss** [comment]
Maybe sth. like this, I need it also: [Calculate Distance Between Vectors](https://milvus.io/docs/v2.1.x/calculate_distance.md)

**Comment by espdev** [comment]
It would be nice to have an API something like [pdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html#scipy.spatial.distance.pdist) function from scipy - pairwise distances between observations, where the input is a list of point IDs in the database and the output is a distance matrix.

I was actually surprised that such functionality is not available in Qdrant.

**Comment by generall** [comment]
It feels like it could be done with just filters and batch recommendation request.

**Comment by generall** [comment]
I am going to close this task, as it looks to me that it requests a functionality that already exists.
Please feel free to prove me wrong and re-open the issue
