### ISSUE TITLE
Expose HNSW search paths 

### ISSUE THREAD

**Issue by keotic** [qdrant/qdrant#2335]
**Is your feature request related to a problem? Please describe.**
The query paths on the hierarchical graph hold valuable information that may be used in pair with the queries results ( nearest vectors).
An option to retrieve the graph search paths with the query results will be appreciated. 

**Describe the solution you'd like**
Add an optional flag to all search & recommend APIs to retrieve the graph search paths. 

**Additional context**
This is an advanced feature and not for the faint-hearted : )

**Comment by IvanPleshkov** [comment]
Hi! Thanks for your proposal. The original HNSW algorithm doesn't provide a search path, it's more like to BSF search than DFS (don't use that comparison pls in practice, I'm just trying to explain why HNSW search don't have paths). Maybe as a path you mean the list of the search result for each level. But I cannot get any idea why someone needs this info.
Can you please share ideas of situations where such paths are applicable?

**Comment by keotic** [comment]
Hi
Yes indeed by paths I mean the search results (points and distance) for each layer.
I can't elaborate much on the usage, but I can say that this info holds valuable information.

**Comment by IvanPleshkov** [comment]
Because there are no applications for this proposal, I'm going to close it. I find supporting the feature that nobody uses is too expensive for us
