### ISSUE TITLE
Allow using nested keys in `with_payload` selector

### ISSUE THREAD

**Issue by kacperlukawski** [qdrant/qdrant#2336]
Both search and scroll endpoints allow specifying payload keys to be retrieved in the results. Right now, we only allow top-level keys to be used. Ideally, we could use nested keys to extract any property we want, similar to the indexes that might be created at any level.

## Usage

```python
from qdrant_client import QdrantClient

client = QdrantClient(...)
client.scroll("collection", with_payload=["properties.nested_key"])
```

### Related links
https://discord.com/channels/907569970500743200/1112631958158196747/1133294963392786486

**Comment by agourlay** [comment]
This seems like a good first issue.

The scope is pretty narrow and it can be tested locally.

**Comment by Doordashcon** [comment]
Hello @agourlay, currently looking into this.

**Comment by Doordashcon** [comment]
On navigating the codebase.

This change should ideally alter the filtering endpoints as well? 

i.e
```python
...
fake_something = Faker()

payload = []

data = np.random.uniform(low=-1.0, high=1.0, size=(1_000, 100))

for i in range(len(data)):
    payload.append(
        {
            "user": [
                {
                    "name": fake_something.name(),
                    "posts": [
                        {
                            "xp": fake_something.random_int(0, 10),
                            "comments": [fake_something.word(), fake_something.word()],
                        }
                    ],
                },
            ],
            "universeInfo": {
                "galaxy": fake_something.word(),
                "spaceTimeContinuum": fake_something.word(),
                "dominantSpecies": fake_something.word(),
                "interstellarCommunication": fake_something.word(),
            },
        }
    )
    
hits = client.search(
    collection_name="my_collection",
    query_vector=query_vector,
    query_filter=Filter(
        must=[  # These conditions are required for search results
            FieldCondition(
                key='user.post.xp',  # Condition based on a user's experience.
                range=Range(
                    gte=5  # Select only those results where `xp` >= 5
                )
            )
        ]
    ),
    with_payload=["user.post.comments"], #Get the comments
    limit=5  # Return 5 closest points
)    
...
```

**Comment by agourlay** [comment]
The change should apply everywhere the `payload_selector `is exposed :+1:

**Comment by sofiyanpathan** [comment]
can i work on this?

**Comment by Doordashcon** [comment]
> The change should apply everywhere the `payload_selector` is exposed 👍

Would like to clarify if this signifies that a new field be added to the `payload_selector` to account for the `rest_path`?

**Comment by agourlay** [comment]
There is no need for an additional field, the change is to interpret differently the payload selector payload key if it contains a JSON path.

Check how the payload_selector is handled when retrieving points

https://github.com/qdrant/qdrant/blob/dev/lib/collection/src/collection_manager/segments_searcher.rs#L295-L300

Then follow the selector's implementation

https://github.com/qdrant/qdrant/blob/dev/lib/segment/src/types.rs#L1704-L1715

You will see that it simply filters by top level key in the payload.

What we want is to filter by a JSON path string.

We have several methods to extract JSON based on a path in https://github.com/qdrant/qdrant/blob/dev/lib/segment/src/common/utils.rs#L204

**Comment by Doordashcon** [comment]
`PayloadSelector.process` can be configured to take in an additional argument and then pass that to `get_value_from_json_map`.

**Comment by Doordashcon** [comment]
The `Payload` method `process` returns `Payload` which is a `Map<String, Value>`.

Take this nested structure
```python
payload.append({"level1": {"level2": {"level3": {"level4": "deep_value"}}}})
```

For searches on "level4" there is only a `Value` type. Should results allow for retrieval up to this level?

**Comment by Doordashcon** [comment]
Hello @agourlay, about ready for review. Would a comprehensive test for this change be needed?

**Comment by agourlay** [comment]
@Doordashcon Great to hear.

It would be great to have a few unit tests with happy paths and edge cases.
Then a new integration test in `openai_integration` to validate that everything is wired properly.

**Comment by agourlay** [comment]
I decided to take over the feature to speed things up a bit https://github.com/qdrant/qdrant/pull/2756

https://github.com/qdrant/qdrant/pull/2669#issuecomment-1742912596

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/qdrant/releases/tag/v1.6.0
