### ISSUE TITLE
Error during indexing

### ISSUE THREAD

**Issue by camdencheek** [qdrant/qdrant#2338]
My collection status is `red` with the error `Service internal error: Removing proxy segment which is still in use:`.

## Current Behavior
I ingested ~20 million vectors in a collection with indexing enabled (config below). `indexed_vectors_count` climbed to ~9 million before stalling out, then a couple of hours later the status changed to `red` with the error `Service internal error: Removing proxy segment which is still in use: <my_collection_name>/0/segments/<uuid>`

Interestingly, CPU usage for qdrant is still pretty high, even after the optimizer failed and seems to be doing no additional work.

<details>
<summary>
Collection details
</summary>

```json
{
  "result": {
    "status": "red",
    "optimizer_status": {
      "error": "Service internal error: Removing proxy segment which is still in use: \"./storage/collections/repos.openai.text-embedding-ada-002.indexed/0/segments/c6e8ab8f-2f9c-416c-8ccc-10c8cb99434c\""
    },
    "vectors_count": 20649073,
    "indexed_vectors_count": 9781948,
    "points_count": 20649073,
    "segments_count": 71,
    "config": {
      "params": {
        "vectors": {
          "size": 1536,
          "distance": "Cosine",
          "on_disk": true
        },
        "shard_number": 1,
        "replication_factor": 1,
        "write_consistency_factor": 1,
        "on_disk_payload": true
      },
      "hnsw_config": {
        "m": 8,
        "ef_construct": 100,
        "full_scan_threshold": 10,
        "max_indexing_threads": 8,
        "on_disk": true,
        "payload_m": 8
      },
      "optimizer_config": {
        "deleted_threshold": 0.2,
        "vacuum_min_vector_number": 1000,
        "default_segment_number": 0,
        "max_segment_size": null,
        "memmap_threshold": null,
        "indexing_threshold": 20000,
        "flush_interval_sec": 0,
        "max_optimization_threads": 8
      },
      "wal_config": {
        "wal_capacity_mb": 1,
        "wal_segments_ahead": 0
      },
      "quantization_config": {
        "scalar": {
          "type": "int8",
          "quantile": 0.95,
          "always_ram": false
        }
      }
    },
    "payload_schema": {
      "repoID": {
        "data_type": "integer",
        "points": 20649073
      }
    }
  },
  "status": "ok",
  "time": 0.100324209
}

```

</details>

## Steps to Reproduce
I have not attempted to reproduce yet. Even if I'm unable to reproduce, I'm mostly looking for a "why" the error might've occurred so I can be more confident in indexing in general. 

## Expected Behavior
After ingesting 20 million vectors, `indexed_vectors_count` should grow over time to rougly match `vectors_count` and the status should change to `green`. 

## Context (Environment)
I am trying to evaluate qdrant's indexing at scale. I am running qdrant in a docker container on a Debian VM with 16GB memory and 4 CPUs. Vectors, payloads, and HNSW are all configured to be on-disk.

**Comment by camdencheek** [comment]
I started from a fresh instance and re-ran the ingestion job. This time, I was able to ingest the full set, but indexing seems to have stalled at ~5 million vectors indexed (of ~20 million). I restarted the container, and after restart, status was reporting as "green" (rather than "yellow" before the restart).


Is there any way to gain visibility into why indexing has stalled?

**Comment by timvisee** [comment]
While I have no clear idea at this time on how this might occur, I do want to add some pointers to maybe clear this up a bit.

The error you mentioned points to:

https://github.com/qdrant/qdrant/blob/7164ac4a5987d28f1c93f5712aef8e09e7d93555/lib/collection/src/collection_manager/holders/segment_holder.rs#L79-L87

It basically tries to drop segment data which it is done optimizing with. This operation requires exclusive access; it fails because there is some other long running task or _thing_ that keeps a reference to it. This should of course, not happen. It waits for up to [one hour](https://github.com/qdrant/qdrant/blob/7164ac4a5987d28f1c93f5712aef8e09e7d93555/lib/collection/src/collection_manager/holders/segment_holder.rs#L22) after which it fails with the error.

This timeout is the reason you aren't seeing the error status immediately.

Thank you for sharing your collection status and for confirming you've been seeing this a second time. I'll do some testing locally in the hopes I reach the same breakpoint.

**Comment by generall** [comment]
It might be related to https://github.com/qdrant/qdrant/issues/2273

If you are using on-disk option and make search requests to un-indexed colletion, it might get stuck for quite a long period. This behavior will be fixed in the next release

**Comment by timvisee** [comment]
@camdencheek Are you by any chance doing any searches on the collection while indexing is happening? And, are these searches potentially timing out?

As @generall mentioned, long running searches (that aren't cancelled) may be the reason for segments to be occupied for a long while.

**Comment by timvisee** [comment]
> I did run a search against the instance while indexing was in progress.

> I think I canceled it before it finished.

The problem in the current release is that the searches don't stop internally when you cancel them.

That problem is fixed in the next release and is already in our `dev` branch. So situation should not be problematic in the future.

> Would this also explain the second time I attempted where there is no error? Collection status is still green, but only 5m/20m vectors are indexed, and hasn't increased for over 24h.

Do you see any (significant) CPU/disk activity?

**Comment by camdencheek** [comment]
> The problem in the current release is that the searches don't stop internally when you cancel them.

Got it, thanks for the explanation!

> Do you see any (significant) CPU/disk activity?

`iotop` is reporting zero activity and `htop` is reporting ~0.5% CPU usage from qdrant

**Comment by camdencheek** [comment]
I'm happy to collect any debugging information that would be useful while it's in this state, otherwise I can try to re-run the ingestion and refrain from running any searches 🙂

**Comment by camdencheek** [comment]
Another maybe relevant tidbit I realized I missed before: this collection has a single payload index.

**Comment by timvisee** [comment]
Hi @camdencheek. We've just released [v1.4.0](https://github.com/qdrant/qdrant/releases/tag/v1.4.0) which includes <https://github.com/qdrant/qdrant/pull/2293> being the probable fix for this.

Could you upgrade and see whether the same issue comes up again?

**Comment by camdencheek** [comment]
Thanks for the update! I re-ran the job with the new version, and cancelling a search no longer causes indexing to stall. However, I was still not seeing the entire collection being indexed (only getting ~50% of the way there). I increased the memory allocated to qdrant (from 16GB to 32GB) and indexing started completing successfully. I did not see any log messages indicating there was a problem. Is it expected that indexing will stall with insufficient memory? And if it is, is there a way to determine that's the problem?

**Comment by timvisee** [comment]
> and cancelling a search no longer causes indexing to stall.

Fantastic! Thanks for confirming.



> However, I was still not seeing the entire collection being indexed (only getting ~50% of the way there). I increased the memory allocated to qdrant (from 16GB to 32GB) and indexing started completing successfully. I did not see any log messages indicating there was a problem. Is it expected that indexing will stall with insufficient memory? And if it is, is there a way to determine that's the problem?

Interesting. Thanks for giving that a shot. I don't think we have any logic that _blocks_ indexing when there's not enough free memory, but I'd have to dive into the codebase to confirm that.

Since you mention low memory availability, could the culprit be very heavy swapping? Where indexing is stalled because it is constantly page faulting?

**Comment by camdencheek** [comment]
> could the culprit be very heavy swapping?

I did not look into this super closely since increasing memory unblocked me, but anecdotally, indexing seemed to keep up with ingestion until it suddenly stopped. If swapping were to blame, I would expect indexing speed to slowly degrade rather than suddenly stopping entirely. 

Going to close this since the original issue is solved, but I will likely dig into this again at some point and let ya know if I find anything interesting. Thanks for the help!
