### ISSUE TITLE
Support for binary vectors

### ISSUE THREAD

**Issue by AmineDiro** [qdrant/qdrant#2349]
Hello there qdrant community !

**Is your feature request related to a problem? Please describe.**
As an ML engineer, I usually need to store binary vectors (generated from perceptual hash for example). 

**Describe the solution you'd like**
Support binary vectors Vec<u8>. I took a look at the code base and found that vector type definition is done via type aliasing 
```rust
pub type VectorElementType = f32;
```
I also so that supporting binary vectors is in the current roadmap, how advanced is the development of this feature? I would love to contribute to this issue 😃 ! If the issue is still open, I have some questions regarding the current implementation:
- Adding [`hamming distance`](http://huonw.github.io/hamming/hamming/fn.distance_fast.html) crate for distance computation
- To have a generic `VectorType<T: VecType>` where `VecType` is some defined trait implemented for `f32` and `u8` for now 🤔 ? Of course, also changing all dependent methods
-  Having a `VecType` enum wrapper: 
```rust
pub enum VecType{
  Float(f32)
  Binary(u8)
}
```

**Describe alternatives you've considered**
`qdrant` is my go-to vector store solution and the current answer I found is to store the binary vector as an f32 vector of {0,1} representing the binary data. L2 distance is used as it mirrors the hamming distance.

**Comment by IvanPleshkov** [comment]
Hi! Thanks for your proposal. At this moment we don't have any plans to change vector types. But you can continue using vector of {0, 1}. You can also use scalar quantization to reduce memory usage and increase search speed. For models with binary data we are thinking about binary quantization. But now we didn't include this feature to our roadmap

**Comment by jamiechoi1995** [comment]
As for the hamming distance, I think this link may help
https://qdrant.tech/documentation/guides/quantization/#binary-quantization-as-hamming-distance
