### ISSUE TITLE
Unable to delete collection snapshot via REST API

### ISSUE THREAD

**Issue by zhangzf875** [qdrant/qdrant#2389]
_Rough translation by Google:_

I want to delete all the snapshots of a certain collection through the command on the client, but the execution of the statement does not report an error, but there is no way to delete the snapshot. The
specific statement 

```bash
curl -X DELETE "http://localhost:6333/collections/69169_bak/snapshots" \
    -H "accept: application/json" \
```

<details>

<summary>Original content: 无法通过http命令删除集合快照</summary>

我在客户端上面通过命令想要删除某一个集合的所有快照，但是语句执行也没有报错，但是快照没有办法删除
具体语句
curl -X DELETE "http://localhost:6333/collections/69169_bak/snapshots" \
-H "accept: application/json" \

</details>

**Comment by timvisee** [comment]
Excuse me for responding in English, I don't speak Chinese.

Snapshots can currently only be deleted one-by-one.

- To delete one: https://qdrant.tech/documentation/concepts/snapshots/#delete-snapshot
- To list all snapshots: https://qdrant.tech/documentation/concepts/snapshots/#list-snapshot

Are you requesting support for an endpoint to delete all current snapshots?

**Comment by zhangzf875** [comment]
您好，请问一下要是想要展示一个集合的所有点的向量数据，命令应该怎么写

**Comment by timvisee** [comment]
> > 您好，请问一下要是想要展示一个集合的所有点的向量数据，命令应该怎么写
>
> Hello, if you want to display the vector data of all points in a set, how should the command be written?

You can use the scroll API to list (and paginate) all points: https://qdrant.tech/documentation/concepts/points/#scroll-points
