### ISSUE TITLE
Extreme load average after changing collection params "on_disk"

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#2390]
qdrant v1.4 adds feature "change the parameters in an existing collection"

I tried
I changed a param `hnsw.on_disk` true => false
I got an extreme load average on my server 
My server has 24 cores only. =)

![extreme-LA-2023-08-07 11-18-17](https://github.com/qdrant/qdrant/assets/20382553/387d8d78-3398-4af5-ab09-95e0ef9dc572)

Could You add some limits?

**Comment by timvisee** [comment]
At this time, changing any of these parameters will result in the index and quantization data to be rebuilt.

The process of rebuilding this is why you're seeing this load.

This is noted in the documentation, and it is why it is not recommended to use on a production instance:

> Calls to this endpoint may be blocking as it waits for existing optimizers to finish. It is not recommended to use this in a production database as it may introduce huge overhead due to rebuilding the index.


We'll eventually optimize this to skip rebuilding for simple changes such as `on_disk`, but we haven't worked on this improvement yet.
