### ISSUE TITLE
systemctl systemd .service unit file example

### ISSUE THREAD

**Issue by Andrew-MK** [qdrant/qdrant#2398]
**Please provide example of systemctl .service unit file** to run qdrant as daemon on ubuntu/debian linux. For example, [elasticsearch.service](https://github.com/elastic/elasticsearch/blob/main/distribution/packages/src/common/systemd/elasticsearch.service) where the recommended system daemon settings are listed - LimitNOFILE, KillSignal, restart policy, etc...

**Comment by marco-sacchi** [comment]
@Andrew-MK why was this issue closed without a reference to a possible configuration for systemd .service unit file?

If you have one could you share it?
