### ISSUE TITLE
Support k8s liveness and readiness probes when using `api_key`

### ISSUE THREAD

**Issue by TonySkorik** [qdrant/qdrant#2401]
Currently when using the `api_key` server setting, the healthcheck endpoint `/` is also getting secured, which leads to k8s being unable to start pods, since it gets `403 Unauthorized` when performing healthcheck and shuts down the pod as not ready after some time.

To mitigate this issue the `/` API path should not perform authorization checks.

Also current ck8s convention [states](https://kubernetes.io/docs/reference/using-api/health-checks/) that liveness and readiness probes should be exposed on unsecured `/livez` and `/readyz` endpoints respectively. 

Please remove authorization from `/` and add `/livez` and `/readyz` endpoints.

This also should be supported in the official Qdrant helm chart.

**Comment by timvisee** [comment]
Fixed in <https://github.com/qdrant/qdrant/pull/2407>. This will be part of the next patch release.

**Comment by cedenilla** [comment]
I am getting `403 Unauthorized` also from `/metrics` endpoint. Can be also related to this?
