### ISSUE TITLE
TimeoutError: The read operation timed out

### ISSUE THREAD

**Issue by agoor97** [qdrant/qdrant#2405]
client.search(collection_name='image-search-vgg19', query_vector=image_feats[0], 
                                     limit=10000, score_threshold=threshold, with_payload=False)

**Comment by timvisee** [comment]
Your command has `limit=10000` set. That is a very high number, and so it might take a very long time for the server to actually process the request.

It is definitely recommended to choose a lower number.

If that isn't possible, you can increase the timeout to a more fitting number:

```python
QdrantClient(
    ....,
    timeout=120, # timeout in seconds
)
```

**Comment by timvisee** [comment]
There are multiple places where `on_disk` is used. If you mean setting `on_disk=True` for HNSW, then yes, that will probably make it faster.

**Comment by agoor97** [comment]
I mean here 
## Collection Configuration
collection_config = VectorParams(
                        size=4096,                  ## The size of vgg19 convbase
                        distance=Distance.COSINE,   ## using cosine similarity
                        on_disk=True            
                    )

**Comment by timvisee** [comment]
That puts vector data on disk. No, I don't think setting that to `False` will make a significant difference.

**Comment by agoor97** [comment]
Thank you

**Comment by timvisee** [comment]
@agoor97 on second thought, that actually will make a difference.

I'm not sure if it'll reduce the request time to be within the default timeout, but it's definitely worth a try.
