### ISSUE TITLE
web UI password

### ISSUE THREAD

**Issue by amilkov3** [qdrant/qdrant#2413]
**Is your feature request related to a problem? Please describe.**

doesn't appear to be a way via the config to set a password for the web UI

**Describe the solution you'd like**

allow for a hard-coded config password

**Describe alternatives you've considered**

**Additional context**

**Comment by amilkov3** [comment]
oh i guess you can set one via a dialog with NGINX config

**Comment by generall** [comment]
Hi @amilkov3! Web-ui itself (static files) is not protected by API-key indeed, but it won't be able to retrieve any information from Qdrant if the API key is configured

**Comment by amilkov3** [comment]
hmm yea now im having the problem where i serve the dashboard under `/dashboard/` in nginx to the qdrant container but the web UI needs to have a `serve_from_subpath: <path>` configuration like grafana cause itll send requests to `/collections` for example to `/dashboard/collections` instead. so i went ahead and just opened up port 6333 but now im back to the original problem which is that its not password protected 

the Api-key is just a static config for rest/grpc clients though. i need to secure access to the web UI itself

**Comment by generall** [comment]
With API-key enabled, dashboard will look like this:

![Screenshot from 2023-08-17 11-06-18](https://github.com/qdrant/qdrant/assets/1935623/ec884fae-fa1d-4d31-9a88-9b6f50ed9b45)

It is not just a static config for rest/grpc clients

**Comment by amilkov3** [comment]
@generall ah cool thanks, closing
