### ISSUE TITLE
Docker cannot up

### ISSUE THREAD

**Issue by hscspring** [qdrant/qdrant#2423]
## Steps to Reproduce

[root@iZ2zedepakssxcq57n5bdzZ docker_storage]# docker run --rm  qdrant/qdrant:latest
           _                 _
  __ _  __| |_ __ __ _ _ __ | |_
 / _` |/ _` | '__/ _` | '_ \| __|
| (_| | (_| | | | (_| | | | | |_
 \__, |\__,_|_|  \__,_|_| |_|\__|
    |_|

Access web UI at http://localhost:6333/dashboard

[2023-08-12T02:56:08.626Z INFO  storage::content_manager::consensus::persistent] Initializing new raft state at ./storage/raft_state.json
[2023-08-12T02:56:08.637Z ERROR qdrant::startup] Panic backtrace:
       0: qdrant::startup::setup_panic_hook::{{closure}}
       1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                 at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1999:9
       2: std::panicking::rust_panic_with_hook
                 at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:709:13
       3: std::panicking::begin_panic_handler::{{closure}}
                 at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:597:13
       4: std::sys_common::backtrace::__rust_end_short_backtrace
                 at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
       5: rust_begin_unwind
                 at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
       6: core::panicking::panic_fmt
                 at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
       7: tokio::runtime::builder::Builder::build
       8: qdrant::main
       9: std::sys_common::backtrace::__rust_begin_short_backtrace
      10: main
      11: <unknown>
      12: __libc_start_main
      13: _start

[2023-08-12T02:56:08.637Z ERROR qdrant::startup] Panic occurred in file /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs at line 447: OS can't spawn worker thread: Operation not permitted (os error 1)
thread panicked while processing panic. aborting.
./entrypoint.sh: line 25:     6 Aborted                 (core dumped) ./qdrant $@

**Comment by generall** [comment]
Hi @hscspring, what kind of OS are you using?

**Comment by hscspring** [comment]
@generall 


sorry, here is the environment:

```bash
$ uname -a
Linux iZ2zedepakssxcq57n5bdzZ 4.19.91-21.al7.x86_64 #1 SMP Wed Sep 2 19:47:49 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a

LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	AlibabaCloud(AliyunLinux)
Description:	Alibaba Cloud Linux (Aliyun Linux) release 2.1903 LTS (Hunting Beagle)
Release:	2.1903
Codename:	HuntingBeagle

$ cat /etc/os-release
NAME="Alibaba Cloud Linux (Aliyun Linux)"
VERSION="2.1903 LTS (Hunting Beagle)"
ID="alinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.1903"
PRETTY_NAME="Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

$ hostnamectl
   Static hostname: iZ2zedepakssxcq57n5bdzZ
         Icon name: computer-vm
           Chassis: vm
        Machine ID: <id>
           Boot ID: <id>
    Virtualization: other
  Operating System: Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle)
            Kernel: Linux 4.19.91-21.al7.x86_64
      Architecture: x86-64

```

i've never met this issue before... this os seems like a customed virtual machine.

**Comment by generall** [comment]
it might be worth trying with a newer version of the kernel

**Comment by hscspring** [comment]
> it might be worth trying with a newer version of the kernel

thanks for your reply.

i agree with that.

**Comment by timvisee** [comment]
This is probably related: https://github.com/qdrant/qdrant/issues/2149

This is likely due to a constrained Docker environment with missing capabilities.

You should provide the necessary capabilities. You can also use `--privileged` when starting the container, though this is definitely not recommended for production use.

**Comment by hscspring** [comment]
@timvisee  it works, thanks very much.
