### ISSUE TITLE
Update the local disk to cloud

### ISSUE THREAD

**Issue by axz91** [qdrant/qdrant#2443]
When using llama_index with storage_context = StorageContext.from_defaults(persist_dir='./storage'), how to upload the local disk index to your database, thanks.

**Comment by generall** [comment]
Related PR: https://github.com/qdrant/qdrant-client/pull/243

**Comment by axz91** [comment]
Could you provide an example, where to find the function

**Comment by generall** [comment]
> Could you provide an example, where to find the function

It was not yet merged

**Comment by joein** [comment]
@axz91  There is an example to show the idea

You can adjust it based on your needs

https://github.com/qdrant/qdrant-client/issues/202

**Comment by agourlay** [comment]
@axz91 Please give the migration tool a try and give feedback on the qdrant-client repo :pray:
