### ISSUE TITLE
The state of the collection is always in yellow

### ISSUE THREAD

**Issue by yesletgo** [qdrant/qdrant#2463]
## Current Behavior

When the index vector count remains stable and there is no increase in data, but the state of the set does not change to green, the CPU remains under high load.

## Steps to Reproduce

**1.create collection**

```json
{
    "vectors": {
      "size": 1024,
      "distance": "Dot",
      "on_disk": false
    },
	"on_disk_payload": false,
    "optimizers_config": {
        "memmap_threshold": 20000
    },
    "quantization_config": {
        "scalar": {
            "type": "int8",
            "always_ram": true
        }
    },
     "hnsw_config": {
        "on_disk": false
    }
}
```

**2. create index**
```json
{
     "field_name": "group_id",
    "field_schema": "keyword"
}
```

**3.upload  batchs**

After uploading  80 million data, the status of collection is always yellow 

### Server info
qdrant version is 1.4.1 and is cluster mode
kernel: 5.4.248-1.el7.elrepo.x86_64
k8s version: 1.23.5
data: 80 million vector. Each vector has 1024 dimensions

### Collection info
```json
{
    "result": {
        "status": "yellow",
        "optimizer_status": "ok",
        "vectors_count": 82696100,
        "indexed_vectors_count": 82696100,
        "points_count": 82696100,
        "segments_count": 144,
        "config": {
            "params": {
                "vectors": {
                    "size": 1024,
                    "distance": "Dot",
                    "on_disk": false
                },
                "shard_number": 18,
                "replication_factor": 1,
                "write_consistency_factor": 1,
                "on_disk_payload": false
            },
            "hnsw_config": {
                "m": 16,
                "ef_construct": 100,
                "full_scan_threshold": 10000,
                "max_indexing_threads": 0
            },
            "optimizer_config": {
                "deleted_threshold": 0.2,
                "vacuum_min_vector_number": 1000,
                "default_segment_number": 0,
                "max_segment_size": null,
                "memmap_threshold": 20000,
                "indexing_threshold": 20000,
                "flush_interval_sec": 5,
                "max_optimization_threads": 1
            },
            "wal_config": {
                "wal_capacity_mb": 32,
                "wal_segments_ahead": 0
            },
            "quantization_config": {
                "scalar": {
                    "type": "int8",
                    "always_ram": true
                }
            }
        },
        "payload_schema": {
            "group_id": {
                "data_type": "keyword",
                "points": 82696100
            }
        }
    },
    "status": "ok",
    "time": 3.896181817
}
```

**Comment by timvisee** [comment]
A collection is yellow when Qdrant is optimizing it. Indexing and quantization can take a very long time.

Looking at your collection info snippet, it seems that 100% of the vectors is indexed. I'd therefore expect the optimization process to be done, unless you changed index/quantization parameters in the meanwhile.

Can I ask, how long have you been waiting for?

Also, could you share the logs of your instance, as it might point us to something.

**Comment by yesletgo** [comment]
> A collection is yellow when Qdrant is optimizing it. Indexing and quantization can take a very long time.
> 
> Looking at your collection info snippet, it seems that 100% of the vectors is indexed. I'd therefore expect the optimization process to be done, unless you changed index/quantization parameters in the meanwhile.
> 
> Can I ask, how long have you been waiting for?
> 
> Also, could you share the logs of your instance, as it might point us to something.

After waiting for more than 10 hours, the status was still yellow, and then I deleted the cluster. This situation did not occur in version 1.2.2.
On the other hand,  what are the most compatible kernel and k8s versions for the 1.4 version of the qdrant cluster？

**Comment by generall** [comment]
Hi @yesletgo have you seen high CPU usage / Disk IO during this yellow status after 10 hrs?

**Comment by yesletgo** [comment]
> Hi @yesletgo have you seen high CPU usage / Disk IO during this yellow status after 10 hrs?

Yea,i have seen

**Comment by generall** [comment]
@yesletgo what hardware re you using?

**Comment by yesletgo** [comment]
@generall 
master：1 *  4cores/8G
datanode： 6 *  64cores/192G

**Comment by generall** [comment]
what do you mean by master? As of now Qdrant doesn't make a difference between node types

**Comment by yesletgo** [comment]
@generall The master is the master of K8S. Datanode is the datnode of K8S.
The shared disk of nfs is a high-performance disk, approaching the performance of solid-state disks.

**Comment by yesletgo** [comment]
Can I ask, which kernel version is recommended？

**Comment by generall** [comment]
latest, is possible. We test on 5.15

**Comment by generall** [comment]
> The shared disk of nfs is a high-performance disk

nfs might be not the best choice in combination with mmaps.

Could you please measure the IOPS of those disks?
You can find instructions and estimations here: https://qdrant.tech/articles/memory-consumption/

**Comment by yesletgo** [comment]
@generall read: IOPS=62.0k, BW=246MiB/s (258MB/s)(8192MiB/33299msec).
By the way,, would you recommend Centos 7 or Centos 8？

**Comment by yesletgo** [comment]
I found a strange phenomenon. When I tried the following configuration and uploaded the data, the status changed to green for a while.
{
"vectors": {
**"on_disk": true**
},
**"on_disk_payload": true,**
"quantization_config": {
"scalar": {
"always_ram": true
}
},
"hnsw_config": {
"on_disk": true or false
}
}

**Comment by PtttCode** [comment]
# Current Behavior
When I upsert more vectors to one collection which has over 10 millions of the length of 2048 vector, Qdrant will produce lots of  **Timeout error**.

Also the specific collection's status is **Yellow**.

## Different kinds of error
```
2024-04-19T09:46:16.420405Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/Upsert unexpectedly failed with Unknown error "h2 protocol error: error reading a body from connection: connection reset" 0.105189    
2024-04-19T09:46:16.430406Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/Upsert unexpectedly failed with Unknown error "h2 protocol error: error reading a body from connection: connection reset" 0.146256  
2024-04-19T09:25:30.885151Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Client specified an invalid argument "Bad request: Empty update request" 0.000059    
2024-04-19T09:25:58.150360Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Client specified an invalid argument "Bad request: Empty update request" 0.000049    
2024-04-19T09:27:02.173016Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Client specified an invalid argument "Bad request: Empty update request" 0.000212    
2024-04-19T09:34:09.003136Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Deadline expired before operation could complete "Timeout: Timeout error: Deadline Exceeded: status: DeadlineExceeded, message: \"Healthcheck timeout 2000ms exceeded\", details: [], metadata: MetadataMap { headers: {} }" 9.379868    
2024-04-19T09:34:09.430080Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Deadline expired before operation could complete "Timeout: Timeout error: Deadline Exceeded: status: DeadlineExceeded, message: \"Healthcheck timeout 2000ms exceeded\", details: [], metadata: MetadataMap { headers: {} }" 9.414219    
2024-04-19T09:22:09.624810Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Deadline expired before operation could complete "Timeout: 1 out of 3 shards failed to apply operation. First error captured: Timeout error: Deadline Exceeded: status: DeadlineExceeded, message: \"Healthcheck timeout 2000ms exceeded\", details: [], metadata: MetadataMap { headers: {} }" 9.465554    
2024-04-19T09:22:10.447050Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Deadline expired before operation could complete "Timeout: 1 out of 3 shards failed to apply operation. First error captured: Timeout error: Deadline Exceeded: status: DeadlineExceeded, message: \"Healthcheck timeout 2000ms exceeded\", details: [], metadata: MetadataMap { headers: {} }" 9.357179   
2024-04-19T08:50:06.520025Z  WARN storage::content_manager::consensus_manager: Failed to send message to http://qdrant-cluster-2.qdrant-cluster-headless:6335/ with error: Error in closure supplied to transport channel pool: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }    

```

# Machine Configuration

**Kernal Version**: 5.4.0

**CPU**: strong enough

**Disk**: SSD but use NFS driver

**Qdrant(v1.8.4)** deploy on **Kubernetes** with 3 shards By helm.

Here is the production.yaml:
```yaml

cluster:
  consensus:
    tick_period_ms: 100
  enabled: true
  p2p:
    port: 6335
service:
  enable_tls: false
```


# Steps to Reproduce

**1. Create collection and upsert lots of vectors into it.
Here is the collection config:**
```yaml
{
    "result": {
        "status": "yellow",
        "optimizer_status": "ok",
        "vectors_count": 15485372,
        "indexed_vectors_count": 15350828,
        "points_count": 15485372,
        "segments_count": 17,
        "config": {
            "params": {
                "vectors": {
                    "size": 2048,
                    "distance": "Cosine"
                },
                "shard_number": 3,
                "replication_factor": 1,
                "write_consistency_factor": 1,
                "on_disk_payload": true
            },
            "hnsw_config": {
                "m": 16,
                "ef_construct": 100,
                "full_scan_threshold": 10000,
                "max_indexing_threads": 0,
                "on_disk": false
            },
            "optimizer_config": {
                "deleted_threshold": 0.2,
                "vacuum_min_vector_number": 1000,
                "default_segment_number": 2,
                "max_segment_size": null,
                "memmap_threshold": 200000,
                "indexing_threshold": 20000,
                "flush_interval_sec": 5,
                "max_optimization_threads": 1
            },
            "wal_config": {
                "wal_capacity_mb": 32,
                "wal_segments_ahead": 0
            },
            "quantization_config": null
        },
        "payload_schema": {}
    },
    "status": "ok",
    "time": 0.001245324
}
```
**2. Upsert vectors continusly. In the beginnng, there is nothing happen, but errors will will continue to occur after a while**



# Wish
**Please tell me how to fix it?**  @generall  @timvisee 

Or 
**@yesletgo  If you had resolved it, please tell me how to  do.**

**Comment by PtttCode** [comment]
> # Current Behavior
> When I upsert more vectors to one collection which has over 10 millions of the length of 2048 vector, Qdrant will produce lots of **Timeout error**.
> 
> Also the specific collection's status is **Yellow**.
> 
> ## Different kinds of error
> ```
> 2024-04-19T09:46:16.420405Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/Upsert unexpectedly failed with Unknown error "h2 protocol error: error reading a body from connection: connection reset" 0.105189    
> 2024-04-19T09:46:16.430406Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/Upsert unexpectedly failed with Unknown error "h2 protocol error: error reading a body from connection: connection reset" 0.146256  
> 2024-04-19T09:25:30.885151Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Client specified an invalid argument "Bad request: Empty update request" 0.000059    
> 2024-04-19T09:25:58.150360Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Client specified an invalid argument "Bad request: Empty update request" 0.000049    
> 2024-04-19T09:27:02.173016Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Client specified an invalid argument "Bad request: Empty update request" 0.000212    
> 2024-04-19T09:34:09.003136Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Deadline expired before operation could complete "Timeout: Timeout error: Deadline Exceeded: status: DeadlineExceeded, message: \"Healthcheck timeout 2000ms exceeded\", details: [], metadata: MetadataMap { headers: {} }" 9.379868    
> 2024-04-19T09:34:09.430080Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Deadline expired before operation could complete "Timeout: Timeout error: Deadline Exceeded: status: DeadlineExceeded, message: \"Healthcheck timeout 2000ms exceeded\", details: [], metadata: MetadataMap { headers: {} }" 9.414219    
> 2024-04-19T09:22:09.624810Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Deadline expired before operation could complete "Timeout: 1 out of 3 shards failed to apply operation. First error captured: Timeout error: Deadline Exceeded: status: DeadlineExceeded, message: \"Healthcheck timeout 2000ms exceeded\", details: [], metadata: MetadataMap { headers: {} }" 9.465554    
> 2024-04-19T09:22:10.447050Z  INFO qdrant::tonic::logging: gRPC /qdrant.Points/Upsert failed with Deadline expired before operation could complete "Timeout: 1 out of 3 shards failed to apply operation. First error captured: Timeout error: Deadline Exceeded: status: DeadlineExceeded, message: \"Healthcheck timeout 2000ms exceeded\", details: [], metadata: MetadataMap { headers: {} }" 9.357179   
> 2024-04-19T08:50:06.520025Z  WARN storage::content_manager::consensus_manager: Failed to send message to http://qdrant-cluster-2.qdrant-cluster-headless:6335/ with error: Error in closure supplied to transport channel pool: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }    
> ```
> 
> # Machine Configuration
> **Kernal Version**: 5.4.0
> 
> **CPU**: strong enough
> 
> **Disk**: SSD but use NFS driver
> 
> **Qdrant(v1.8.4)** deploy on **Kubernetes** with 3 shards By helm.
> 
> Here is the production.yaml:
> 
> ```yaml
> cluster:
>   consensus:
>     tick_period_ms: 100
>   enabled: true
>   p2p:
>     port: 6335
> service:
>   enable_tls: false
> ```
> 
> # Steps to Reproduce
> **1. Create collection and upsert lots of vectors into it. Here is the collection config:**
> 
> ```yaml
> {
>     "result": {
>         "status": "yellow",
>         "optimizer_status": "ok",
>         "vectors_count": 15485372,
>         "indexed_vectors_count": 15350828,
>         "points_count": 15485372,
>         "segments_count": 17,
>         "config": {
>             "params": {
>                 "vectors": {
>                     "size": 2048,
>                     "distance": "Cosine"
>                 },
>                 "shard_number": 3,
>                 "replication_factor": 1,
>                 "write_consistency_factor": 1,
>                 "on_disk_payload": true
>             },
>             "hnsw_config": {
>                 "m": 16,
>                 "ef_construct": 100,
>                 "full_scan_threshold": 10000,
>                 "max_indexing_threads": 0,
>                 "on_disk": false
>             },
>             "optimizer_config": {
>                 "deleted_threshold": 0.2,
>                 "vacuum_min_vector_number": 1000,
>                 "default_segment_number": 2,
>                 "max_segment_size": null,
>                 "memmap_threshold": 200000,
>                 "indexing_threshold": 20000,
>                 "flush_interval_sec": 5,
>                 "max_optimization_threads": 1
>             },
>             "wal_config": {
>                 "wal_capacity_mb": 32,
>                 "wal_segments_ahead": 0
>             },
>             "quantization_config": null
>         },
>         "payload_schema": {}
>     },
>     "status": "ok",
>     "time": 0.001245324
> }
> ```
> 
> **2. Upsert vectors continusly. In the beginnng, there is nothing happen, but errors will appear after a while**
> 
> # Wish
> **Please tell me how to fix it?** @generall @timvisee
> 
> Or **@yesletgo If you had resolved it, please tell me how to do.**
> 
> ** If anything else need to offer, just tell me **

It seems disk problem. Let me fix it and I will give the response as soon as possible

**Comment by timvisee** [comment]
It could definitely be a disk problem. We normally measure its performance in terms of IOPS.

Note that we recommend against using NFS. It is not reliable enough for database/search engine use, and have seen issues with it before.
