### ISSUE TITLE
Load local collection data into memory

### ISSUE THREAD

**Issue by FeiyangW** [qdrant/qdrant#2464]
I create a collection in local db by following command.
client = QdrantClient(path="path/to/db")
client.create_collenction(XXX)

Later, Is there any way for the following client to load the above collection into memory?
client = QdrantClient(":memory:")
client.load_from_local(xxxxxxx) # need this.

**Comment by agourlay** [comment]
I do not think this use case is currently supported.

You better ask directly on the [Python client repository](https://github.com/qdrant/qdrant-client/).
