### ISSUE TITLE
extract nested payload as original

### ISSUE THREAD

**Issue by JoanFM** [qdrant/qdrant#25]
With the introduction of #15 , nested payload is unwrapped to have filtrable payload.

For instance:

```json
{ "metadata": {"hello": "world"}}
```

is expanded to a flat key:
```json
"metadata__hello": "world"
```

and now if I try to check the payload of this specific point I will get this flattened point. 

It would be nice to get the original input back.

I think there could be 2 ways.
- Convert it at extracting type, doing some sort of grouping by common prefixes and so on (like with a Trie)
- What I think could be more mantainable, but at space cost, to store original Payload along with the filtrrable fields.
- Some intermediate, keep duplicated payloads but JUST for the nested fields

What is your opinion on this? I could try to help a bit on this.

**Comment by generall** [comment]
I also can't see the ideal no-cost solution here, but from my perspective nested flattening is a form of syntax sugar. And syntax sugar should not affect the storage. Right now it is only possible to use nested object with json interface of the `Segment`, so it might be easier to implement de-flattening in the segment wrapper you use for bindings. REST API relies now on pure serde which handles a lot of things including API Schema, and I would like to keep it there until some better solution found.

**Comment by JoanFM** [comment]
Right now flattening does affect the storage, so it is more than just syntax sugar. It affects the way points are filtered and stored.

**Comment by generall** [comment]
Storage does not know anything about nesting - it treats nested fields exactly the same way as other fields, they only have a different name. Query might look different, but the payload indexing is same. That is what I mean by syntax sugar.

**Comment by generall** [comment]
Elastic, for example, treats nested lists of objects `{"a": [{"x": 1, "y": "3"}, {"x": 2, "y": 4}]}`  as `{"a.x": [1,2], "a.y": [3, 4]}`. So grouping information is lost. In this case nesting also only a syntactic sugar. ES was a special *nested* structures in this case, but it requires completely different implementation

**Comment by generall** [comment]
Full JSON support is released in https://github.com/qdrant/qdrant/releases/tag/v0.7.0
