### ISSUE TITLE
How to index and search for elements part of an array

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#2511]
for the payload,
[
  {
    "id": 1,
    "country": {
      "name": "Germany",
      "cities": [
        {
          "name": "Berlin",
          "population": 3.7,
          "sightseeing": ["Brandenburg Gate", "Reichstag"]
        },
        {
          "name": "Munich",
          "population": 1.5,
          "sightseeing": ["Marienplatz", "Olympiapark"]
        }
      ]
    }
  },
  {
    "id": 2,
    "country": {
      "name": "Japan",
      "cities": [
        {
          "name": "Tokyo",
          "population": 9.3,
          "sightseeing": ["Tokyo Tower", "Tokyo Skytree"]
        },
        {
          "name": "Osaka",
          "population": 2.7,
          "sightseeing": ["Osaka Castle", "Universal Studios Japan"]
        }
      ]
    }
  }
]
How do I index and search the country.cities.name and country.cities.sightseeing?? Please provide python code snippet .
The use case is "suppose if we want to retrieve records with sightseeing value as Reichstag"

Thanks
Ajay

**Comment by generall** [comment]
Hi @nairajay2k, have you seen this: https://qdrant.tech/documentation/concepts/filtering/#nested-key ?

**Comment by nairajay2k** [comment]
Yes, thank you so much Andrey.

**Comment by timvisee** [comment]
I assume this is resolved. Please open it again if you're still having trouble with this.

**Comment by bbkgh** [comment]
Hi. Can we introduce index on nested keys for using in filter?
sth like:
create_payload_index(
                collection_name=collection_name,
                field_name="country.cities[].name",
                field_schema="keyword",
            )
