### ISSUE TITLE
How to create non vector indexes on disk

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#2512]
Hi,

Please let me know how to create a non vector index on disk. I have seen documentation on vector indexes only for this so far.
Issue Im facing is a lot of RAM consumption when I create a non vector index. I have around 1 million records and 2 non vector indexes on arrays in the records(total elements would still be of the order of 1 million). I have an ubuntu machine with 16 GB RAM but the docker qdrant process gets OOMed out due to high RAM consumption.

Thanks
Ajay

**Comment by generall** [comment]
Payload index can only be created in RAM currently. There are WIP improvements for memory consumption for payload indexes - https://github.com/qdrant/qdrant/pull/2453, will be released with the next version.

**Comment by generall** [comment]
>  Will it degrade performance by a lot?

Depends on how fast your disk is

**Comment by timvisee** [comment]
If you'd still like this index, it may be better to _offload_ your vector data to disk by using memory mapped vectors. It may prevent OOMs for the time being. I think that is better than enabling SWAP where you may experience huge latency surprise spikes.

You can enable this by setting `on_disk=true` on the vectors.
