### ISSUE TITLE
Add recovery mode status into `/metrics` API

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2535]
**Is your feature request related to a problem? Please describe.**
Currently it is only present in telemetry, but for some use-case it might be useful to also have Prometheus-compatible format.

**Comment by varshneydevansh** [comment]
Can I look into this? @agourlay I was actually applying for the job but after reading about `qdrant` over the JD I followed the GH link and seems like an interesting project, can I work on this? If you can ping the initial files where to begin, that would be great.

**Comment by agourlay** [comment]
Sure, you can start by having a look at the `/metrics` API [here](https://github.com/qdrant/qdrant/blob/dev/src/actix/api/service_api.rs#L48)

Check how it works and then look at the `/telemetry` endpoint and how it reports the recovery mode status.

**Comment by agourlay** [comment]
@varshneydevansh sorry, the issue has been worked on already https://github.com/qdrant/qdrant/pull/2549

**Comment by varshneydevansh** [comment]
I can work on another issue that is more beginner-friendly.

**Comment by agourlay** [comment]
https://github.com/qdrant/qdrant/pull/2549
