### ISSUE TITLE
Increase JSON payload size limit

### ISSUE THREAD

**Issue by genrry** [qdrant/qdrant#2537]
Hello, I'm trying to fill my collection 

```
client.upsert(
    collection_name='my-collection',
    points=models.Batch(
        ids=index,
        vectors=vectors
        payloads=payload
    )
)
```

and I get the following error:

---------------------------------------------------------------------------
UnexpectedResponse                        Traceback (most recent call last)
Cell In[7], line 1
----> 1 client.upsert(
      2     collection_name='candidates',
      3     points=models.Batch(
      4         ids=list(candidates_data),
      5         vectors=list([candidate['index'] for candidate in candidates_data.values()]),
      6         payloads=list([candidate['metadata'] for candidate in candidates_data.values()])
      7     )
      8 )

File [c:\Users\usuario\documents\dockerized\cv_parser_venv\lib\site-packages\qdrant_client\qdrant_client.py:757](file:///C:/Users/usuario/documents/dockerized/cv_parser_venv/lib/site-packages/qdrant_client/qdrant_client.py:757), in QdrantClient.upsert(self, collection_name, points, wait, ordering, **kwargs)
    733 """Update or insert a new point into the collection.
    734 
    735 If point with given ID already exists - it will be overwritten.
   (...)
    753     Operation result
    754 """
    755 assert len(kwargs) == 0, f"Unknown arguments: {list(kwargs.keys())}"
--> 757 return self._client.upsert(
    758     collection_name=collection_name,
    759     points=points,
    760     wait=wait,
    761     ordering=ordering,
    762     **kwargs,
    763 )

File [c:\Users\usuario\documents\dockerized\cv_parser_venv\lib\site-packages\qdrant_client\qdrant_remote.py:1123](file:///C:/Users/usuario/documents/dockerized/cv_parser_venv/lib/site-packages/qdrant_client/qdrant_remote.py:1123), in QdrantRemote.upsert(self, collection_name, points, wait, ordering, **kwargs)
   1120 if isinstance(points, rest_models.Batch):
   1121     points = rest_models.PointsBatch(batch=points)
-> 1123 http_result = self.openapi_client.points_api.upsert_points(
   1124     collection_name=collection_name,
   1125     wait=wait,
   1126     point_insert_operations=points,
   1127     ordering=ordering,
   1128 ).result
   1129 assert http_result is not None, "Upsert returned None result"
   1130 return http_result

File [c:\Users\usuario\documents\dockerized\cv_parser_venv\lib\site-packages\qdrant_client\http\api\points_api.py:1179](file:///C:/Users/usuario/documents/dockerized/cv_parser_venv/lib/site-packages/qdrant_client/http/api/points_api.py:1179), in SyncPointsApi.upsert_points(self, collection_name, wait, ordering, point_insert_operations)
   1169 def upsert_points(
   1170     self,
   1171     collection_name: str,
   (...)
   1174     point_insert_operations: m.PointInsertOperations = None,
   1175 ) -> m.InlineResponse2006:
   1176     """
   1177     Perform insert + updates on points. If point with given ID already exists - it will be overwritten.
   1178     """
-> 1179     return self._build_for_upsert_points(
   1180         collection_name=collection_name,
   1181         wait=wait,
   1182         ordering=ordering,
   1183         point_insert_operations=point_insert_operations,
   1184     )

File [c:\Users\usuario\documents\dockerized\cv_parser_venv\lib\site-packages\qdrant_client\http\api\points_api.py:604](file:///C:/Users/usuario/documents/dockerized/cv_parser_venv/lib/site-packages/qdrant_client/http/api/points_api.py:604), in _PointsApi._build_for_upsert_points(self, collection_name, wait, ordering, point_insert_operations)
    602 if "Content-Type" not in headers:
    603     headers["Content-Type"] = "application/json"
--> 604 return self.api_client.request(
    605     type_=m.InlineResponse2006,
    606     method="PUT",
    607     url="/collections/{collection_name}/points",
    608     headers=headers if headers else None,
    609     path_params=path_params,
    610     params=query_params,
    611     data=body,
    612 )

File [c:\Users\usuario\documents\dockerized\cv_parser_venv\lib\site-packages\qdrant_client\http\api_client.py:74](file:///C:/Users/usuario/documents/dockerized/cv_parser_venv/lib/site-packages/qdrant_client/http/api_client.py:74), in ApiClient.request(self, type_, method, url, path_params, **kwargs)
     72 url = (self.host or "") + url.format(**path_params)
     73 request = self._client.build_request(method, url, **kwargs)
---> 74 return self.send(request, type_)

File [c:\Users\usuario\documents\dockerized\cv_parser_venv\lib\site-packages\qdrant_client\http\api_client.py:97](file:///C:/Users/usuario/documents/dockerized/cv_parser_venv/lib/site-packages/qdrant_client/http/api_client.py:97), in ApiClient.send(self, request, type_)
     95     except ValidationError as e:
     96         raise ResponseHandlingException(e)
---> 97 raise UnexpectedResponse.for_response(response)

UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Payload error: JSON payload (1224959171 bytes) is larger than allowed (limit: 33554432 bytes)."},"time":0.0}'

How can I increase the JSON payload limit so it will let me insert the data?

**Comment by genrry** [comment]
nevermind, found the solution

**Comment by timvisee** [comment]
Could you elaborate on what you did to make this work?

**Comment by genrry** [comment]
Turns out I was trying to add to many records in the same request, so I added them in batches instead

**Comment by SametOzenc** [comment]
Can you share the working code?
