### ISSUE TITLE
Geo Filter Optimization by merging filters

### ISSUE THREAD

**Issue by zzzz-vincent** [qdrant/qdrant#2539]
**Is your feature request related to a problem? Please describe.**
Presently, it's seems that Qdrant evaluates each individual Geo Filter in conjunction with the geo points within a given query. To illustrate, in a scenario where there are N geo filters and all points intersect with every filter, we would need to process all points N times. Moreover, in common use cases, the number of filters is expected to be significantly lower than the number of points.

**Describe the solution you'd like**
There are potential optimizations available, such as the consolidation of geo filter geometries prior to processing (eg. merging overlapping polygons). This approach could potentially reduce the overall iterations over the geo hashes and geo points. However, it's important to conduct further investigation and perform performance testing to ensure the effectiveness of this strategy.

**Comment by agourlay** [comment]
Thanks for keeping track of this.

While looking at code I found something missing.

When running a query, we first analyze its filters and try the find the filter that will decrease the most the number of points to scan.

To do so, we estimate the cardinality of each filters.

It looks like we forgot to handle geo polygons `estimate_cardinality` for the geo index.

https://github.com/qdrant/qdrant/blob/0f102a5575ac33df03f06563844198f3ea26136b/lib/segment/src/index/field_index/geo_index.rs#L571C8-L591

Adding the geo polygon case and make sure the filters are being optimized would be a food first step :+1:
