### ISSUE TITLE
 Does Qdrant not support deleting all matched points using a payload?

### ISSUE THREAD

**Issue by Friedrich-hue** [qdrant/qdrant#2545]
我想使用payload来删除符合条件的数据，但是没有找到接口，只能先查询符合条件的数据，再删除数据

**Comment by agourlay** [comment]
You can delete points which are matching a filter.

See https://qdrant.tech/documentation/concepts/points/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIGgzOm50aC1vZi10eXBlKDIp#delete-points

e.g.

```http
POST /collections/{collection_name}/points/delete
{
    "filter": {
        "must": [
            {
                "key": "color",
                "match": {
                    "value": "red"
                }
            }
        ]
    }
}
``` 

Is this what you are looking for?
