### ISSUE TITLE
Upserting point with wrong vector size does not return an error

### ISSUE THREAD

**Issue by timdhughes** [qdrant/qdrant#2557]
When upserting point with the wrong vector size for a collection, the vector is not added to the collection as expected, but there is no error returned from the API.

## Current Behavior
The HTTP status code returned is 200.

## Steps to Reproduce
1.  Create a new collection
```json
PUT collections/test
{
  "vectors": {
    "size": 10,
    "distance": "Cosine"
  }
}
```
2.  Try to upsert points with the wrong vector size.  In the example below, the vector has 3 elements instead of 10.
```json
PUT collections/test/points
{
  "points": [
    {
      "id": 1,
      "vector": [0.1, 0.2, 0.3]
    }
  ]
}
```
Qdrant response:
```json
{
  "result": {
    "operation_id": 0,
    "status": "acknowledged"
  },
  "status": "ok",
  "time": 0.000120771
}
```
## Expected Behavior
The API should return a 400 bad request status code.

## Possible Solution
Check the request to make sure the vector size matches the collection.

## Context (Environment)
When switching algorithms with a new vector size, it was not immediately clear what was wrong with the vector database.

**Comment by timvisee** [comment]
That's weird! That should not happen.

Could you elaborate a bit on what your setup looks like? Are you running Qdrant in a cluster, or is it just a single node deployment?

Also, do you see a proper error response when using `?wait=true`?

**Comment by timvisee** [comment]
I confirm that I see the same behavior without `?wait=true`.

**Comment by timvisee** [comment]
I confirm that I see the same behavior without `?wait=true`.

I took some time to dive into this to see whether we think this is problematic.

Requests without `?wait=true` are acknowledged here: https://github.com/qdrant/qdrant/blob/0f102a5575ac33df03f06563844198f3ea26136b/lib/collection/src/shards/local_shard_operations.rs#L25-L66

We do this to allow handling requests much quicker, that is useful when doing a bunch of operations at once. At this place, we currently don't do this validation. The requests will eventually be blocked further down the line though, so these invalid vectors won't end up in your collection.

I can look into adding this validation in this stage as well if desired.

For now I recommend to use `?wait=true` if an error response is needed.

**Comment by agourlay** [comment]
I think we should return HTTP code 202 if `wait=false` :thinking: 

But would that be a breaking change?

**Comment by timvisee** [comment]
> I think we should return HTTP code 202 if `wait=false` 🤔
> 
> But would that be a breaking change?

Yeah! We figured that before, but that would indeed be breaking.
