### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#2569]
## Current Behavior

[2023-09-02T12:21:05.057Z ERROR actix_server::accept] Error accepting connection: Too many open files (os error 24)

Got too many open files error on ubuntu 22. The main consumers of file handles seem to be qdrant and docker(qdrant is running off docker).
This happened pretty quickly without having much data flow into qdrant(Only a few thousand records at max)

(venv) gl@gl:~/huggingface$ sudo lsof | awk '{ print $1 " " $2; }' | sort -rn | uniq -c | sort -rn | head -15
[sudo] password for gl: 
lsof: WARNING: can't stat() fuse.portal file system /run/user/128/doc
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/128/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.portal file system /run/user/1000/doc
      Output information may be incomplete.
 197006 qdrant 46610
 194370 docker-pr 46513
   6670 python 53925

## Steps to Reproduce

1. Im using ubuntu 22(64 GB RAM and a 16 TB HDD)
2.
3.
4.
Please help solve this. I guess Im using a docker image thats a week or two old.

**Comment by generall** [comment]
https://qdrant.tech/documentation/guides/common-errors/#too-many-files-open-os-error-24
