### ISSUE TITLE
qdrant-client returns extra hyphens in document ids

### ISSUE THREAD

**Issue by Andrew-MK** [qdrant/qdrant#2570]
I'm using the latest version qdrant and qdrant-client under windows. My documents have an **id of the form "c9a52f5499c2d5b7bd1f61da14ebe68d"** (this is a string representation of the MD5 hash from the data from the document) but after call **qdrant.search has returned hit.id in the form with extra hyphens like "c9a52f54-99c2-d5b7-bd1f-61da14ebe68d"**.
Code for reproduce:
```python
#!pip install -U qdrant-client
from qdrant_client import models, QdrantClient

qdrant = QdrantClient("http://127.0.0.1:6333")

# Create collection
qdrant.recreate_collection(
    collection_name="test_collection",
    vectors_config=models.VectorParams(
        size=4,
        #distance=models.Distance.COSINE
        distance=models.Distance.DOT
    )
)

# documents with id = MD5 strings like c9a52f5499c2d5b7bd1f61da14ebe68d
# import hashlib
# documents[i]["id"] = hashlib.md5(str(RANDOM_TEXT).encode('utf-8')).hexdigest()
documents = [
    {'id': 'c9a52f5499c2d5b7bd1f61da14ebe68d', 'vector': [0, 0, 0, 0]},
    {'id': 'd84ea79c65cb1120dd3b84575f21796c', 'vector': [0, 0, 0, 0]},
    {'id': 'e542d826196f174feabb214b90bce300', 'vector': [0, 0, 0, 0]},
    {'id': '29a1d272cf36da946e56f4a9968a2a04', 'vector': [0, 0, 0, 0]},
    {'id': '9b237584654fe1ef24a81c77510b4492', 'vector': [0, 0, 0, 0]},
    {'id': '38bd01e5e83e1871245c68ea4ca0dae8', 'vector': [0, 0, 0, 0]},
    {'id': '90eb5ad56b20a58db6bea42b1722c1ee', 'vector': [0, 0, 0, 0]},
    {'id': '6029bf620139fb6d39d88ca615bab612', 'vector': [0, 0, 0, 0]},
    {'id': 'b366d11ab901128df5c5b2e72daea432', 'vector': [0, 0, 0, 0]},
    {'id': 'f9e99436909d6b8abdf186dcc461d9a9', 'vector': [0, 0, 0, 0]},
    {'id': 'cad87077ef9f0f4267b51002701c4d79', 'vector': [0, 0, 0, 0]},
    {'id': 'efecb3de92f3f0b68b2c1623401f0e65', 'vector': [0, 0, 0, 0]},
    {'id': '66c205fa667de4ccc549c65de400d888', 'vector': [0, 0, 0, 0]}
]

# upload documents to qdrant
qdrant.upload_records(
    collection_name="test_collection",
    records=[
        models.Record(
            id=doc["id"],
            vector=doc["vector"],
        ) for doc in documents
    ]
)

# search
hits = qdrant.search(
    collection_name="test_collection",
    query_vector=[0,0,0,0],
    limit=100
)

# Printed hit.id - must be without any hyphens:
for hit in hits:
    print("id:",hit.id)
    
'''
# Outputs on my system:
id: 38bd01e5-e83e-1871-245c-68ea4ca0dae8
id: 6029bf62-0139-fb6d-39d8-8ca615bab612
id: cad87077-ef9f-0f42-67b5-1002701c4d79
id: d84ea79c-65cb-1120-dd3b-84575f21796c
id: 66c205fa-667d-e4cc-c549-c65de400d888
id: 90eb5ad5-6b20-a58d-b6be-a42b1722c1ee
id: efecb3de-92f3-f0b6-8b2c-1623401f0e65
id: 9b237584-654f-e1ef-24a8-1c77510b4492
id: c9a52f54-99c2-d5b7-bd1f-61da14ebe68d
id: b366d11a-b901-128d-f5c5-b2e72daea432
id: f9e99436-909d-6b8a-bdf1-86dcc461d9a9
id: e542d826-196f-174f-eabb-214b90bce300
id: 29a1d272-cf36-da94-6e56-f4a9968a2a04
'''
```

**Comment by generall** [comment]
Hi @Andrew-MK, that's expected behavior, since Qdrant doesn't store text representation of IDs, but binary form of UUIDs instead.

**Comment by Andrew-MK** [comment]
But in [documentation](https://qdrant.tech/documentation/concepts/points/#point-ids) we can see:
![image](https://github.com/qdrant/qdrant/assets/136389593/08d7aa92-8112-4db8-903c-7fd2278d1c2e)
I just need hit.id to return to the text (simple) representation - maybe there is some kind of special flag for this?

**Comment by generall** [comment]
@Andrew-MK, there is no flag for that. Documentation says that it can parse all of those formats, but there is no information about the original format after the parsing.
If you need to store exact string representation, you can use payload instead

**Comment by Andrew-MK** [comment]
Thank you, this is a way out of the situation. I also use: hit.id.replace("-",""). 
Sorry for the issue, I just wanted to report the detected atypical behavior when we put one value into the database and get another (in a different format) without specifying such regular behavior in the documentation. 
Perhaps for greater compatibility with row IDs in relational db (oracle/mssql) or NoSQL (elasticsearch/solr/mongodb) or cache systems (redis/memcached) out of the box, the desired id format could be set in recreate_collection.

**Comment by Andrew-MK** [comment]
I also could not find ways to solve or mention the following questions in the documentation:
- How to use Qdrant without a disk (completely disable persistence, wal journal and other disk queries)? I tried to use QdrantClient(":memory:"), but for some unknown reason it works 10 times slower than working with the Qdrant gRPC server. Or maybe I can place qdrant on ramdisk for this and specify "on_disk": true in all create collection parameters (will qdrant then be completely on ramdisk without spending additional RAM to storing vectors or indexes without serious degradation of speed)? 
- How to connect to qdrant via unix socket (or gRPC is the fastest possible interaction with qdrant server on ramdisk)?
- How to run qdrant as daemon (linux service) on ubuntu/debian etc.
- Time-to-live (TTL) or expire points behavior for automatic removal of irrelevant (outdate) vectors as in [Elasticsearch](https://www.elastic.co/blog/ttl-documents-shield-and-found) or [Redis](https://redis.io/commands/ttl/)
- Maxmemory protection mechanisms or control methods (LRU, LFU) when the memory limit is reached as Eviction policies in [Redis](https://redis.io/docs/reference/eviction/)

**Comment by generall** [comment]
@Andrew-MK 

> Or maybe I can place qdrant on ramdisk for this and specify "on_disk": true 

Surprisingly, that might work.
Tested with:
```
docker run --rm -it --network=host --mount type=tmpfs,dst=/qdrant/storage  qdrant/qdrant:v1.4.1
```
and memory usage almost didn't change compared to just regular mounted volume.

> How to connect to qdrant via unix socket

We don't have this feature yet

> How to run qdrant as daemon (linux service) on ubuntu/debian etc.

There were a few people who did that, but we didn't do it ourselves.
I think there should be no problem to do so, but we don't have official instructions for this method yet

> Time-to-live (TTL) or expire points behavior for automatic removal of irrelevant (outdate) vectors 

there is a feature request for that - https://github.com/qdrant/qdrant/issues/1327

But from my perspective it looks like simple delete-by-filter request on CRON. Something that doesn't necessary have to be integrated into the search engine. Please feel free to correct me if you see why having this inside the DB could be beneficial except for the fact that you won't need to implement it yourself.

> Maxmemory protection mechanisms or control methods (LRU, LFU) when the memory limit is reached as Eviction policies in [Redis](https://redis.io/docs/reference/eviction/)

We don't have this. Full in-memory mode was not in the original consideration, so qdrant usually assumes that if memory is critical, it should used with on-disk option which utilizes disk cache instead of ram allocations

**Comment by Andrew-MK** [comment]
Thank you kindly for your response. 
- > docker run --rm -it --network=host --mount type=tmpfs,dst=/qdrant/storage  qdrant/qdrant:v1.4.1

  Is it supposed to be with this configuration (on_disk everywhere + memmap_threshold)?
  ```python
  qdrant.recreate_collection(
    collection_name="my_ondisk_collectiin",
    hnsw_config=models.HnswConfigDiff(on_disk=True),
    on_disk_payload=True,
    vectors_config=models.VectorParams(
        on_disk=True,
        size=1024,
        distance=models.Distance.DOT
    ),
    optimizers_config=models.OptimizersConfigDiff(memmap_threshold=20000)
  )
  ```

- Runing binary as daemon (linux service) really no problem to do ( [elasticsearch.service example](https://github.com/elastic/elasticsearch/blob/main/distribution/packages/src/common/systemd/elasticsearch.service) ), but it is necessary to correctly rewrite the logic of commands from "./entrypoint.sh"  into qdrant.service file (ExecStart, KillSignal, EXIT_CODE ... system limits (LimitAS=infinity) for systemctl start qdrant; systemctl stop qdrant; systemctl restart qdrant; systemctl status qdrant commands and journalctl -u qdrant for systemd logs). A lot of people may need a fast vector cache/database without unnecessary dependencies and a .service file is the way to it. With the .service file, it will be possible to make .deb and .rpm builds, place them in debian/centos repositories and give users the opportunity to install and administer qdrant in a standard way, like redis/memcached/nginx - apt install qdtrant. A lot of people don't use docker, a lot of people won't want to install docker for the one component, and the secured launch of docker containers is a [fairly long set of options ](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html) for the command you presented. Transferring docker containers to a backend server infrastructure without the Internet is also more difficult than transferring a binary or .deb or .rpm package.
- TTL, time filtering and [date math](https://solr.apache.org/guide/solr/latest/indexing-guide/date-formatting-math.html#date-math) may be needed in many cases, having this capability at the database level eliminates many problems. For example date math: the time on the quadrant server is 13:00, on the server from which the vectors for insertion come is 13:05, and on the clients from which the search is performed where 12:50, or the time zone is incorrectly set and -3 hours. Upload like PointStruct(id=1, vector=[0.05, 0.61], payload={"timestamp": "NOW"})
and client.search with query_filter=Filter(must=[FieldCondition(key="timestamp",match=NOW-1DAY/DAY)]), where NOW is the keyword always denoting the server time - solves the problems of time synchronization, time zones, etc.
- The TTL mechanism in my case is needed for the inverse of the anomaly detection task, well described by the [example of coffee bean defects detecting](https://youtu.be/bVihQRtPtn0?t=1902) - stream novelty checker/detection. I have to control that the vector representations of incoming data in a sufficiently large stream are unique within a certain time range (not the uniqueness of the data is an anomaly - for example: stream unique place visitors (anonymous faces vectors without long-term storage) scorer in shopping mall with many entrances/exits with cams or stream anti-plagiarism system or stream texts novelty scorrer etc), the time range shifts, days pass, vectors become irrelevant, a certain size of disk and RAM is allocated for qdrant, it is necessary to delete irrelevant vectors in time, otherwise resources will run out - without ttl assign ttl to third-party entities in relation to the database (range selection by date from client side (as described above); delete vectors by cron etc) taking into account the data flow - it may be suboptimal on the part of the database and cause various problems during long-term operation (for example, the administrator forgot to fix the cron after changing the IP of the database or transferring the software to another server). For vector cache and working with time series, this is a useful functionality, as well as the mentioned mechanisms to prevent the use of all memory/disk. Now in my case for each vector in the huge stream I have to do (and it works very slowly because of persistence, wal, which could not be disabled - it kills the disk, although RAM is not a problem, since the server is for streaming data processing without their long-term storage)
  ```python 
  #1 -  Search vector in DB 
  client.search(
    collection_name="{collection_name}",
    query_filter=models.Filter(
        must=[
            models.FieldCondition(
                key="timestamp",
				range=models.Range(
									gt=None,
									gte=CURRENT_TIMESTAMP-HOURS*SECONDS,
									lt=None,
									lte=None,
								),
							),
            )
        ]
    ),
    search_params=models.SearchParams(
        hnsw_ef=128,
        exact=False
    ),
    query_vector=VECTOR,
    limit=3,
  )
  #2 - Put vector into DB with wait=True if similar vector not in DB
   client.upsert(wait=True, payload={"timestamp": [CURRENT_TIMESTAMP]} ...)
  ```

Thank you for your work and qdrant (and separately for the mentioned podcast), all of the above are considerations of an individual user and by no means a lack of a database, but with the accumulation of users with similar needs, it is a way to improve qdrant and extensions of its applicability.
