### ISSUE TITLE
Add OCI compliant Labels

### ISSUE THREAD

**Issue by d3287t328** [qdrant/qdrant#2572]
**Is your feature request related to a problem? Please describe.**
```# OCI Image Spec annotations
LABEL org.opencontainers.image.title="Qdrant" \
      org.opencontainers.image.description="Official Qdrant image" \
      org.opencontainers.image.url="https://qdrant.com/" \
      org.opencontainers.image.documentation="https://qdrant.com/docs" \
      org.opencontainers.image.source="https://github.com/qdrant/qdrant" \
      org.opencontainers.image.version="1.0" \
      org.opencontainers.image.revision="$VCS_REF" \
      org.opencontainers.image.vendor="Qdrant"
```

add this or some variation of it to your Dockerfile. this helps metadata to the image with the docker inspect command and is a step towards red hat container certification.

**Comment by agourlay** [comment]
Thank you for the report!

The release [1.5.0](https://github.com/qdrant/qdrant/releases/tag/v1.5.0) ships a docker image with a few OCI labels.


Please open a new issue if there are any important labels missing!
