### ISSUE TITLE
Flaky test test_snapshot_collection

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#2574]
The test `test_snapshot_collection` turned flaky following the work on adding support for `tempdir`.

It fails for the moment only on CI. 

e.g. https://github.com/qdrant/qdrant/actions/runs/6050885786/job/16421718673?pr=2562#step:6:265

```
failures:

---- tests::snapshot_test::test_snapshot_collection stdout ----
thread 'tests::snapshot_test::test_snapshot_collection' panicked at 'called `Result::unwrap()` on an `Err` value: ServiceError { error: "File IO error: No such file or directory (os error 2)", backtrace: Some("   0: <collection::operations::types::CollectionError as core::convert::From<std::io::error::Error>>::from\n             at ./src/operations/types.rs:672:29\n   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual\n             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1961:27\n   2: collection::collection::Collection::create_snapshot::{{closure}}\n             at ./src/collection.rs:1594:9\n   3: collection::tests::snapshot_test::_test_snapshot_collection::{{closure}}\n             at ./src/tests/snapshot_test.rs:107:10\n   4: collection::tests::snapshot_test::test_snapshot_collection::
```

It fails either at `collection.rs:1594` or `collection.rs:1583`

**Comment by agourlay** [comment]
After two attempts with https://github.com/qdrant/qdrant/pull/2618 and https://github.com/qdrant/qdrant/pull/2621, it seems the issue is still present.

Here after rebase https://github.com/qdrant/qdrant/actions/runs/6147059931/job/16677683215#step:6:275

**Comment by agourlay** [comment]
The last patch splitting the test seems to have remove the flakiness.

I will wait a few more days to close this issue just to be sure.

Unfortunately there is no root cause clearly identified here.

**Comment by timvisee** [comment]
We reverted this (<https://github.com/qdrant/qdrant/pull/2683>) change to see if it resolves this issue. We have the suspicion that it is causing these issues. 

If it turns out to be unrelated and the issue pops up again, we can un-revert the commit again.

**Comment by timvisee** [comment]
We expect this to be fixed by <https://github.com/qdrant/qdrant/pull/2720>.
