### ISSUE TITLE
Search via PointID (and not a vector)

### ISSUE THREAD

**Issue by RJKeevil** [qdrant/qdrant#2575]
My application has an interesting pattern in that all document vectors are stored initally in Qdrant, and searches happen at a later point in their lifecycle.  This means that to perform a similarity search for a document, I need to query qdrant twice: once to fetch the stored vector for a given PointId, then once again as a cosine similarity search for that vector, to find other documents that are similar to this initial document.  I think there would be a performance and code simplicity improvement if I could just query in a single statement "what are the top N matches for the vector that is stored as point 123456".  Ideally, this would also have a batch interface for a list of starting vectors.

Apologies if this is already possible, but i could not see this in the documentation currently.

**Comment by generall** [comment]
check this out https://qdrant.tech/documentation/concepts/search/#recommendation-api

**Comment by RJKeevil** [comment]
Ah my bad, misread that, will try it out, thanks
