### ISSUE TITLE
Some kind of normalization possible??

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#2590]
We are currently persisting a payload with our embedding vectors in qdrant (1 payload per vector). However this payload is mostly redundant and copies of the order of 100x are made. The payload is pretty big(about 20kb) compared to the vector(about 4kb).  

Any foreign key kind of arrangement would be extremely useful from a storage optimization point of view.

It seems qdrant 1.3.x has this..? Pl provide a sample query in python with filters on the payload.

**Comment by generall** [comment]
duplication of https://github.com/qdrant/qdrant/issues/2592
