### ISSUE TITLE
Non vector collection

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#2600]
How do I create a collection without any vector? Python code would great.

**Comment by timvisee** [comment]
You simply create a collection, without providing any vectors:

```python
c = QdrantClient(host="localhost", port=6333)
c.create_collection(
    collection_name="my_collection",
    vectors_config={},
)
```

**Comment by nairajay2k** [comment]
How do I insert into such a collection?? I tried with a blank vector [] or empty list and it gives 
"error":"Wrong input: Not existing vector name error: "
If I skip the vector alltogether then it complains again. 
Please provide an insert example in python.

Thank you
Ajay

**Comment by nairajay2k** [comment]
This is how I created the collection
client.recreate_collection(
    collection_name=collection_name,
    vectors_config={},
    on_disk_payload=True,
)
