### ISSUE TITLE
getting a error inserting an int as an id

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#2601]
{"status":{"error":"Format error in JSON body: value 113416337936912160000000000000000000000 is not a valid point ID, valid values are either an unsigned integer or a UUID at line 1 column 56"}

def string_to_int(in_str):
    hex = in_str.encode("utf-8").hex()
    return int(hex, base=16)

What Im doing is the following. My actual keys are strings which I convert to hex string and then the hex string to int.
This int is what Im passing to the id required by a point.

How do I fix this??
Thanks
Ajay

**Comment by timvisee** [comment]
The number above is too large. IDs can be 64-bit integers. That means the largest number that can be used is `18446744073709551615` (`2^64-1`).

**Comment by timvisee** [comment]
The best approach is likely to generate a random ID, and attach the original key as payload data. That way you're still able to query based on that key using filiters.

**Comment by nairajay2k** [comment]
What I want is if I need to replay the insertions...then the existing data should be left alone..I was hoping if I had the same id ,the data would just be updated and not freshly inserted causing duplicates..How do I manage this with a random number or UUID?

**Comment by generall** [comment]
@nairajay2k, you can hash your original ID into UUID. That should ensure mapping of original -> uuid to be unique enough. Then you could use hash for updates

**Comment by nairajay2k** [comment]
I hope there are no hash collisions..I will have about 10 billion vectors

**Comment by timvisee** [comment]
If you're able to attach random IDs to all your data now, before inserting, that would be a lot better. That way you may be able to use the same IDs again.

> I hope there are no hash collisions..I will have about 10 billion vectors

If you want to be sure, you'll have to test this before hand with some script.

**Comment by russcam** [comment]
@nairajay2k if wishing to generate UUIDs from string IDs, take a look at [version 5 UUIDs](https://datatracker.ietf.org/doc/html/rfc4122#section-4.3), which use SHA-1 as the hash algorithm
