### ISSUE TITLE
Qdrant does not follow the gRPC health checking protocol

### ISSUE THREAD

**Issue by pnivlek** [qdrant/qdrant#2614]
Hi, gRPC defines a standard health check protocol [here](https://github.com/grpc/grpc/blob/master/doc/health-checking.md). Currently, the gRPC health check is under the [Qdrant service](https://github.com/qdrant/qdrant/blob/0c5f3f253541ffc01d25b4b0703c972a4446be38/lib/api/src/grpc/proto/qdrant.proto), not the Health service, and has the name HealthCheck instead of Check. It would be nice to update this to fit the standard, anything monitoring Qdrant's grpc ports doesn't have to treat it as a special case.

**Comment by timvisee** [comment]
Thank you for bringing this to our attention!

> It would be nice to update this to fit the standard, anything monitoring Qdrant's grpc ports doesn't have to treat it as a special case.

I'm afraid that we cannot easily change this due to compatibility reasons. It would require a careful migration and deprecation progress.

**Comment by generall** [comment]
> I'm afraid that we cannot easily change this due to compatibility reasons. It would require a careful migration and deprecation progress.

I think it won't be too much of a problem to keep both methods for some time

**Comment by kwkr** [comment]
Hey @pnivlek @generall ! I came up with some initial implementation of an additional method that would be compliant with the spec that you provided. Please have a look when you have some free time and let me know if there is anything else that I missed.
