### ISSUE TITLE
Migrate from async-channel to tokio channels

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#262]
**Is your feature request related to a problem? Please describe.**

The application uses [async-channel](https://github.com/smol-rs/async-channel) in the update pipeline.
The value of this library is to propose an async multi-producer multi-consumer channel (MPMC).
However our current usage does not require an MPMC, a regular MPSC would suffice as there is only one worker consuming messages for each of our channels.

**Describe the solution you'd like**

Migrate to [Tokio's MPSC](https://docs.rs/tokio/latest/tokio/sync/index.html#mpsc-channel).
The application already uses Tokio so we get to remove completely the `async-channel` dependency.

**Describe alternatives you've considered**

None come to my mind.

**Comment by e-ivkov** [comment]
Even if MPMC will be needed in the future it will be possible to use broadcast channel in tokio https://docs.rs/tokio/latest/tokio/sync/broadcast/index.html
