### ISSUE TITLE
Explicit timeout parameter for search requests.

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2623]
**Is your feature request related to a problem? Please describe.**
Currently we use globally-configured timeout of 60 seconds, 
but it is not always convenient.

**Describe the solution you'd like**
We explicit `timeout` parameter as a part of request in query arguments, as `&timeout=10` for rest
and top-level argument in gRPC.

The parameter should affect the timeout of internal RPC and and time after which the request is cancelled in local shard. 

**Describe alternatives you've considered**
Parameter in `params`

**Additional context**
Default value should be same as now - 60 sec

**Comment by coszio** [comment]
I believe including it in `params` is more fitting because it answers to the "how" of the request, rather than the "what"

**Comment by generall** [comment]
but timeout is not a parameter of search, but the whole request

**Comment by coszio** [comment]
implemented in #2748
