### ISSUE TITLE
Limit default max indexing threads for better performance on high CPU machines

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2627]
**Is your feature request related to a problem? Please describe.**
currently, qdrant will use all available (CPUs - 1) for indexing HNSW by default.
But on large machines with e.g. 128CPUs it is no longer efficient to utilize all CPUs.

 
**Describe the solution you'd like**
If the number of indexing threads is not defined explicitly, use not more than 16 (or even 8?) threads.

**Comment by timvisee** [comment]
Should we graph this behavior on a large machine to provide at least _some_ evidence to settle on a fixed number?

**Comment by agourlay** [comment]
seems to be tackled in https://github.com/qdrant/qdrant/pull/2869/files#diff-67293fc9a85ddf8661786df73c06a44b234be77f07712dcac739b659b340a952R18

**Comment by timvisee** [comment]
<https://github.com/qdrant/qdrant/pull/3115> attempts to improve on this further, by not only limiting HNSW building threads by by also trying to nicely saturate the CPU with all optimization tasks.
