### ISSUE TITLE
No panics in geo_hash.rs

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#2645]
Historically `geo_hash.rs` has been growing the occurrences of the following error handling pattern

```rust
        ...
        .take_while(|hashes| hashes.is_some())
        .last()
        .expect("no hash coverage for any precision")
        .expect("geo-hash coverage is empty")
``` 

Ideally those should be replaced by proper error handling and not panic the thread.

If it is really unexpected it should return a `ServiceError`.

**Comment by SrijanShovit** [comment]
Hi @agourlay !!  I am interested in working on this issue. Could you please assign it to me?

**Comment by timvisee** [comment]
@SrijanShovit Feel free to pick this up, I believe no one is working on this at this time. We don't assign issues in GitHub though.

**Comment by etolbakov** [comment]
I was eager to give a try addressing this change.
Could you please have a look and share your feedback?

**Comment by timvisee** [comment]
Resolved in <https://github.com/qdrant/qdrant/pull/2701>.
