### ISSUE TITLE
Expose the qdrant protocol buffers definitions into a separate repo

### ISSUE THREAD

**Issue by Tochemey** [qdrant/qdrant#2648]
**Is your feature request related to a problem? Please describe.**

There is no issue at the moment. I was reading the client doc and saw that Qdrant does offer a gRPC clients built in python. That is cool, however how long can the qdrant team supports that and also for those of us who are not python developers that can be an issue.

**Describe the solution you'd like**

The solution I am proposing is to expose the qdrant protocol buffer definitions into a separate repo that any developer can git submodule and generate the client interface to interact with qdrant.

**Describe alternatives you've considered**
The other alternate is to try generating the pbs in the various supported language by qdrant and expose it them into a repo. That way a dev team can just add those dependencies into their application.

**Additional context**
No

**Comment by generall** [comment]
Another alternative: sync proto files in client using sparse checkout function in git.

See example:

https://github.com/qdrant/rust-client/blob/master/tools/sync_proto.sh

**Comment by Tochemey** [comment]
@generall the approach is cool. However, it still does not scale well. Having a separate repo for the exposed proto definitions for qdrant is the best option. That way those definitions can be properly versioned with git tags.

**Comment by generall** [comment]
@Tochemey could you please elaborate what exactly doesn't scale well?

> That way those definitions can be properly versioned with git tags.

Right now definitions are also tagged with qdrant versions. 
E.g. you can use `--branch <tag_name>` to clone specific version of qdrant and hence specific version of proto files.

**Comment by Tochemey** [comment]
> https://github.com/qdrant/rust-client/blob/master/tools/sync_proto.sh

Ok that makes sense then. I did not know about the definitions being tagged.

**Comment by Tochemey** [comment]
@generall Thanks. closing the issue
