### ISSUE TITLE
Rest* and grpc* metrics lost when deployed by helm

### ISSUE THREAD

**Issue by derecknowayback** [qdrant/qdrant#2650]
When I deploy qdrant by helm, I visit the `/metrics` api and get the following response (comment removed): 
```plaintext
app_info{name="qdrant",version="1.5.0"} 1
app_status_recovery_mode 0
collections_total 0
collections_vector_total 0
cluster_enabled 1
cluster_peers_total 1
cluster_term 1
cluster_commit{peer_id="1303647246748565"} 1
cluster_pending_operations_total 0
cluster_voter 1
```
So where is the grpc and restful like metrics ?

PS: I haven't used the qdrant yet, just simply deployed it.

**Comment by agourlay** [comment]
If you have not performed any operations, it makes sense that no metrics are available.

Try to create a collection and interact with it, you will then see metrics.

Are you maybe expecting something else?

**Comment by derecknowayback** [comment]
Thanks!

**Comment by timvisee** [comment]
I'd like to add that we don't expose statistics for endpoints such as `/` or `/metrics` as we figured this would be useless information. So only metrics for "real" endpoints is shown.
