### ISSUE TITLE
Expose monitoring metrics

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#268]
**Is your feature request related to a problem? Please describe.**

Currently the system is a blackbox for users while it is running.
Improving observability would enable users to understand what the system is doing and how much traffic it is serving.
 
This would also improve the quality of the bug reports in the future.

**Describe the solution you'd like**

There are many tools available to capture metrics and expose those to a on-premise service or to a cloud provider.

The main philosophy choice is between capturing time-series (think [Prometheus](https://prometheus.io/) like) vs capturing traces (think [Jaegger](https://www.jaegertracing.io/) like) 

Here are a couples of examples for inspiration:
- https://www.elastic.co/guide/en/kibana/current/elasticsearch-metrics.html
- https://docs.mongodb.com/manual/administration/monitoring/
- https://www.postgresql.org/docs/9.1/monitoring.html

**Describe alternatives you've considered**

This issue merely scratches the surface of what is possible and provides a place to discuss the problem space.

**Comment by agourlay** [comment]
Sharing here for transparency the result of an experiment done with [OpenTelemetry](https://opentelemetry.io/) to push traces to Jaeger.

The resulting code can be found in this [commit](https://github.com/qdrant/qdrant/commit/e36fd9415c14c37fa1f88ae5b1ed81d71e27b11b).

It uses the following crates:

- [https://crates.io/crates/tracing](https://crates.io/crates/tracing)
- [https://crates.io/crates/tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry)
- [https://crates.io/crates/tracing-subscriber](https://crates.io/crates/tracing-subscriber)
- [https://crates.io/crates/opentelemetry](https://crates.io/crates/opentelemetry)
- [https://crates.io/crates/opentelemetry-jaeger](https://crates.io/crates/opentelemetry-jaeger)

With this setup I was query and analyze traces locally.

![jaeger-overview](https://user-images.githubusercontent.com/606963/204790762-e9e83d1e-0f45-48ac-b22d-97569d346dec.png)

![consensus-thread](https://user-images.githubusercontent.com/606963/204790944-8098d7e5-d238-428b-9b6e-8dffc790dc52.png)

This works really nicely but it has a couple drawbacks:

- not easy to setup due to the amount of moving pieces
- annotating manually the code to instrument is a bit cumbersome

**Comment by generall** [comment]
https://qdrant.tech/documentation/monitoring/
