### ISSUE TITLE
The replica set for shard 0 on peer 5392764864990243117 does not have enough active replicas

### ISSUE THREAD

**Issue by alenpaulvarghese** [qdrant/qdrant#2722]
## Current Behavior

Getting the following error.
`qdrant::actix::helpers] error processing request: The replica set for shard 0 on peer 5392764864990243117 does not have enough active replicas`

## Steps to Reproduce

1. Added data inside qdrant
2. Run `qdrant_client.count('collection_name')`

## Expected Behavior
The client should be returning the number of count.

## Context (Environment)

Running qdrant docker container on a Windows 11 machine.

**Comment by generall** [comment]
Hi @alenpaulvarghese, could you please provide more details of how to reproduce your issue?

- how do you deploy qdrant
- which version
- how you setup collection
- how reproducible is the issue

**Comment by alenpaulvarghese** [comment]
Sorry for not giving enough information early, to answer the question:

> how do you deploy qdrant

Using docker 
 - image from qdrant/qdrant:latest
 - hash `2451c27278fb389737adfc1b207ae3467b2f5ae351ed51a810d0878a1be03939`
> which version

qdrant 1.1.0
> how you setup collection

using qdrant client
 - config Cosine distance
 - size 512
 
 > how reproducible is the issue
 
I have no idea how to replicate the problem. If I run across it again, I'll update you.

**Comment by timvisee** [comment]
> qdrant 1.1.0

Please update to our latest version first.

Do you run just a single instance, or do you use multiple instances?

Could you share the code snippet that you use to create the collection?

**Comment by alenpaulvarghese** [comment]
sure I will try updating to the latest version. I haven't done any special configuration to run on multiple instance, I am only running one container.

Using the python client. here is the code I used to create the collection.
```
qdrant_client.create_collection(
     collection_name=self.collection_id,
     vectors_config=VectorParams(distance=Distance.COSINE, size=512)
)
```

**Comment by alenpaulvarghese** [comment]
After the update, I couldn't replicate the problem. If I run across the problem I will re-open the issue.
