### ISSUE TITLE
Bool payload index is not used during search.

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2743]
It looks like binary payload index doesn't speed up filtered search requests.

## Current Behavior

```
POST collections/benchmark/points/count
{
  "filter": {"must": [{"key": "b", "match": {"value": true}}]}
}
```

Takes a long time to execute - seconds, instead of expected microseconds

## Steps to Reproduce

1. Create collection with ~1M vectors and field with bool value
2. Create bool payload index for this value
3. Make a count request with bool filter
4. Check the execution speed.

## Expected Behavior

Request is very fast

## Possible Solution

It looks like binary index is not hooked up with the request condition.

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/qdrant/releases/tag/v1.6.0
