### ISSUE TITLE
GRPC 6334 container doesn't pull any dashboard

### ISSUE THREAD

**Issue by pauldintel** [qdrant/qdrant#2747]
When I am using : 
![image](https://github.com/qdrant/qdrant/assets/104393458/c1b5acdd-02d3-407e-b4b4-f6cfa3ce3d15)

the services up and we can access dashboard to see the collections and algorithms but when start above with 6334:6334 port the dashboard didn't spin up . 
How can we access UI dashboard on 6334 http port ? 

Also how can we stream the log from container to local directory to see the activities while vectordb is in action ? 
I tried attempting like below but it doesn't work :

![image](https://github.com/qdrant/qdrant/assets/104393458/ff3469a4-688b-4235-9ba1-f0b5335ba5e9)

## Expected Behavior
6334 port with dashboard access available

**Comment by generall** [comment]
6334 port is reserved for gRPC interface, it is not supposed to be accessible from browser
