### ISSUE TITLE
Why do queries always timeout and the proportion of CPUs running in the background is also very low.

### ISSUE THREAD

**Issue by nowtobe** [qdrant/qdrant#2773]
log: 
2023-10-07T15:14:32.857032Z DEBUG collection::shards::local_shard_operations: Search timeout reached: 60 seconds
2023-10-07T15:14:32.857059Z DEBUG collection::shards::replica_set: Read operation failed: Timeout error: Operation 'Search' timed out after 60 seconds
2023-10-07T15:14:32.857213Z  WARN qdrant::actix::helpers: error processing request: 1 of 1 shards failed with: Timeout error: Operation 'Search' timed out after 60 seconds
-- ------------------------------------------
1 server: 
cpu:32
mem:128G
os:ubuntu 20.04
cargo build --release --bin qdrant （source code base 1.5.1)
client sdk：rust-client 1.5.0
-- ------------------------------------------
q:
Why do queries always timeout and the proportion of CPUs running in the background is also very low.
When there are only a few hundred thousand pieces of data, there is no problem. If there is too much data, there will be problems. What configurations do I need to optimize? How should we find the problem?

GET collections/QcollectionA

{
  "result": {
    "status": "green",
    "optimizer_status": "ok",
    "vectors_count": 4627173,
    "indexed_vectors_count": 4627173,
    "points_count": 4627173,
    "segments_count": 37,
    "config": {
      "params": {
        "vectors": {
          "size": 10465,
          "distance": "Cosine",
          "on_disk": true
        },
        "shard_number": 1,
        "replication_factor": 1,
        "write_consistency_factor": 1,
        "on_disk_payload": true
      },
      "hnsw_config": {
        "m": 16,
        "ef_construct": 100,
        "full_scan_threshold": 10000,
        "max_indexing_threads": 0,
        "on_disk": false
      },
      "optimizer_config": {
        "deleted_threshold": 0.2,
        "vacuum_min_vector_number": 1000,
        "default_segment_number": 0,
        "max_segment_size": null,
        "memmap_threshold": 20000,
        "indexing_threshold": 20000,
        "flush_interval_sec": 10,
        "max_optimization_threads": 1
      },
      "wal_config": {
        "wal_capacity_mb": 32,
        "wal_segments_ahead": 0
      },
      "quantization_config": null
    },
    "payload_schema": {}
  },
  "status": "ok",
  "time": 0.000068921
}
-- ----------------------
thank you !

**Comment by generall** [comment]
Hi @nowtobe, it looks like you are using on-disk storage for your data. 
In this case the most likely bottleneck is the speed of disk you are using.


There are several things you can do to improve:

- Use faster disks. The most important factor is disk IOPS. You can read more about how to measure it and what impact on performance it has here: https://qdrant.tech/articles/memory-consumption/

- Use in-memory quantization. I see size of your vectors is quite high, so maybe even binary quantization will work. Here is how to configure it: https://qdrant.tech/documentation/tutorials/optimize/#prefer-low-memory-footprint-with-high-speed-search

**Comment by nowtobe** [comment]
> Hi @nowtobe, it looks like you are using on-disk storage for your data. In this case the most likely bottleneck is the speed of disk you are using.
> 
> There are several things you can do to improve:
> 
> * Use faster disks. The most important factor is disk IOPS. You can read more about how to measure it and what impact on performance it has here: https://qdrant.tech/articles/memory-consumption/
> * Use in-memory quantization. I see size of your vectors is quite high, so maybe even binary quantization will work. Here is how to configure it: https://qdrant.tech/documentation/tutorials/optimize/#prefer-low-memory-footprint-with-high-speed-search

thank you

I switched to memory, but when the data is only a few hundred thousand, using "recommend_datch()" and "recommend()" takes less time, and when the data is nearly five million, it takes longer.

When using "recommended batch ()" and "recommended ()", I checked the backend CPU usage of ubuntu (using the top command), with the maximum not exceeding 200%, but the maximum being 3200% (which should be due to CPU underutilization). Did I ignore the setting of a certain multi-threaded query parameter, which limited my performance

**Comment by timvisee** [comment]
> When using "recommended batch ()" and "recommended ()", I checked the backend CPU usage of ubuntu (using the top command), with the maximum not exceeding 200%, but the maximum being 3200% (which should be due to CPU underutilization). Did I ignore the setting of a certain multi-threaded query parameter, which limited my performance

I assume your question is whether you can utilize more CPU to search quicker?

The answer to that is no. Indexing is very CPU heavy, while searching through the data once the index is built is not. Searching is memory/disk heavy, so you're likely limited by the speed of either of them.

**Comment by nowtobe** [comment]
Now I understand. Thank you for your answers
