### ISSUE TITLE
points_count of Collection Info

### ISSUE THREAD

**Issue by digitalboy** [qdrant/qdrant#2775]
## Current Behavior
I am using Cloud, but the points_count was fixed 6477, even I have upserted new point.

{"status":"green","optimizer_status":"ok","vectors_count":6477,"indexed_vectors_count":0,"points_count":6477,"segments_count":2,"config":{"params":{"vectors":{"size":1536,"distance":"Cosine"},"shard_number":1,"replication_factor":1,"write_consistency_factor":1,"on_disk_payload":true},"hnsw_config":{"m":16,"ef_construct":100,"full_scan_threshold":10000,"max_indexing_threads":0,"on_disk":false},"optimizer_config":{"deleted_threshold":0.2,"vacuum_min_vector_number":1000,"default_segment_number":0,"max_segment_size":null,"memmap_threshold":null,"indexing_threshold":20000,"flush_interval_sec":5,"max_optimization_threads":1},"wal_config":{"wal_capacity_mb":32,"wal_segments_ahead":0},"quantization_config":null},"payload_schema":{}}

**Comment by timvisee** [comment]
The number of points exposed in the collection status is not very accurate. There are various reasons for it to show a different number than what you might expect.

Could you elaborate on what your upsertion looks like? Are you upserting a point with an ID that already exists?

**Comment by generall** [comment]
The documentation now includes the mention that those counters are approximate

**Comment by timvisee** [comment]
You can find it here: https://qdrant.tech/documentation/concepts/collections/#approximate-point-and-vector-counts
