### ISSUE TITLE
Update twitter logo

### ISSUE THREAD

**Issue by Ayush9026** [qdrant/qdrant#2786]
Twitter logo is old  marked in screenshot below replace with new one 'x'.

![qdrant front page](https://github.com/qdrant/qdrant/assets/114745463/77fddb4a-19b5-4783-b69f-51f7a0dda9c6)

**Comment by Ayush9026** [comment]
@monkCommits i am working on it.

**Comment by timvisee** [comment]
Thank you for noting this.

Please note that the page in the above screenshot is located in a different repository: https://github.com/qdrant/landing_page/

**Comment by Ayush9026** [comment]
@timvisee thanks for telling this i will rectify it.

**Comment by timvisee** [comment]
Reopened in https://github.com/qdrant/landing_page/issues/341
