### ISSUE TITLE
Fix quantization re-scoring for payload-first retrieval

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2787]
Currently, if the query is executed by the payload-index-first strategy, quantization re-scoring is not applied.
In case of binary quantization is may lead to poor results and unexpected scoring values.

## Current Behavior

re-scoring is ignored

## Steps to Reproduce

1. Create collection with fine-grained payload index. Random values are fine
2. Enable binary quantization
3. Make a search query with filter over payload value

Resulting scores are not re-scored even if re-scoring param is explicitly enabled. As a result, raw binary scores present in the result.

## Expected Behavior

Query should follow the re-scoring strategy in all scenarios

## Possible Solution

Implement missing re-scoring procedures in case of payload-index-based execution

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/qdrant/releases/tag/v1.6.1
