### ISSUE TITLE
Random vector being uploaded to collection when using upsert method

### ISSUE THREAD

**Issue by PraneethVasarla** [qdrant/qdrant#2788]
Current Behavior

When using the Qdrant Python client upsert method to upload a point with a vector to a collection, a random vector is uploaded instead of the specified vector.

I made sure that I am passing a list of floats to the upsert method. Here is the code snippet:

<img width="850" alt="image" src="https://github.com/qdrant/qdrant/assets/36670992/a006207c-4bc6-4f9c-bf20-71e1157d1d24">

<img width="904" alt="image" src="https://github.com/qdrant/qdrant/assets/36670992/866eac95-43f8-4af3-9f70-806f6c2b9acb">

As you can see from above, the payload and the ID are mapped correct but the vector has been completely changed. Is this an actual bug or am I just missing something silly here?

Steps to Reproduce

1. Install the Qdrant Python client version 1.6.0 (However, faced the issue with previous versions too. Updated to 1.6.0 only yesterday).
2. Create a new Qdrant client object.
3. Create a new PointStruct object with the desired ID, vector, and payload.
4. Call the upsert method on the Qdrant client object, passing in the PointStruct object.
5. Retrieve the point from the collection using the retrieve method.
6. Check the vector of the retrieved point.

Expected Behavior:

The vector of the retrieved point should be the same as the vector that was specified in the PointStruct object that was passed to the upsert method.

Possible Solution

Is there a part of code where random vectors are being generated? Probably they are being overwritten over my own vectors.

Context (Environment)

I am running this on MacOS 14.0.
Qdrant docker image: Latest
qdrant_client: 1.6.0 (Faced in older versions too)
Python: 3.11

Detailed Description

I am proposing to fix the bug in the Qdrant Python client that is causing random vectors to be uploaded to collections when using the upsert method.

**Comment by generall** [comment]
What's expected behaviour if you are using cosine distance. The vectors are not random, they are normalized. 

If you need to preserve original vectors, there are 2 options:

- use Dot instead of Cosine
- Save original vector to the payload

https://qdrant.tech/documentation/concepts/collections/#collections

**Comment by PraneethVasarla** [comment]
Ah! Had a feeling I was missing something silly. Earlier with other vector DBs that I have used, I had to normalize my vectors myself if I wanted to use cosine. That's pretty neat with qdrant. Thanks!!
