### ISSUE TITLE
In cases where the search conditions remain the same, the database will throw an error if there is no data matching the conditions. However, if the database has data that matches the conditions, it won't produce an error.在检索条件不变的情况下，数据库没有condition可匹配的数据会报错，如果数据库有可匹配到的condition的数据不报错

### ISSUE THREAD

**Issue by Friedrich-hue** [qdrant/qdrant#2816]
```python
def condition_to_filter(must_conditions: List[tuple] = None, should_conditions: List[tuple] = None, **kwargs):
    """
    must_conditions和should_conditions的参数应该是：
    [
        (‘key', 'value')
    ]
    """
    filter_options = {
    }

    def get_condition(key, value):
        return models.FieldCondition(
            key=f'metadata.{key}',
            match=models.MatchValue(value=value),
        )

    if must_conditions:
        conditions = []
        for must in must_conditions:
            # 创建单个条件
            condition = get_condition(*must)
            conditions.append(condition)
        filter_options['must'] = conditions
    if should_conditions:
        conditions = []
        for should in should_conditions:
            # 创建单个条件
            condition = get_condition(*should)
            conditions.append(condition)
        filter_options['should'] = conditions
    return filter_options


filter_options = condition_to_filter(**kwargs)
search_options = {
    'query': query,
    'k': max_return_amount,
    'filter': models.Filter(**filter_options)
}
docs = []
try:
    docs = self.vectordb.similarity_search(**search_options)
except Exception as e:
    self.logger.error(e)
```

在检索条件不变的情况下，如果数据有能匹配到的condition的数据不报错，数据库没有condition的数据会报错：

  File "E:\文件\programs\stars_customer_service-server\.venv\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\文件\programs\stars_customer_service-server\src\files\models.py", line 289, in pre_delete_folder
    smart.remove_data_by_metadata(must_conditions=[(('from', 'folder'), ('folder_id', instance.id))])
  File "E:\文件\programs\stars_customer_service-server\src\files\lib\smart\__init__.py", line 179, in remove_data_by_metadata
    filter_options = Base.condition_to_filter(**kwargs)
  File "E:\文件\programs\stars_customer_service-server\src\files\lib\smart\__init__.py", line 160, in condition_to_filter
    condition = get_condition(*must)
  File "E:\文件\programs\stars_customer_service-server\src\files\lib\smart\__init__.py", line 153, in get_condition
    match=models.MatchValue(value=value),
  File "E:\文件\programs\stars_customer_service-server\.venv\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for MatchValue

**Comment by coszio** [comment]
Looks the same as #2815
