### ISSUE TITLE
error processing request: Can't reach one of the workers

### ISSUE THREAD

**Issue by uahmad235** [qdrant/qdrant#2829]
I am running qdrant server on my own infrastructure. I need to upsert around 20M vectors to the index.
I am already halfway but suddenly facing connection issues.

**Qdrant client version: 1.6.0**

Here's the server side docker logs:
```
2023-10-16T10:44:42.323801Z  WARN qdrant::actix::helpers: error processing request: Can't reach one of the workers: channel closed    
2023-10-16T10:44:42.324271Z  INFO actix_web::middleware::logger: xx.xx.xx.xx "PATCH /collections/medquery-index HTTP/1.1" 500 118 "-" "python-httpx/0.25.0" 0.004187 
```
On the client side i am getting this:
```
   client.update_collection(
  File "/home/ubuntu/venv_p2/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1324, in update_collection
    return self._client.update_collection(
  File "/home/ubuntu/venv_p2/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 1688, in update_collection
    result: Optional[bool] = self.http.collections_api.update_collection(
  File "/home/ubuntu/venv_p2/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 1314, in update_collection
    return self._build_for_update_collection(
  File "/home/ubuntu/venv_p2/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 634, in _build_for_update_collection
    return self.api_client.request(
  File "/home/ubuntu/venv_p2/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
    return self.send(request, type_)
  File "/home/ubuntu/venv_p2/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 97, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 500 (Internal Server Error)
Raw response content:
b'{"status":{"error":"Service internal error: Can\'t reach one of the workers: channel closed"},"time":0.003659626}'
```

**Comment by uahmad235** [comment]
@generall I have a latest qdrant image running on EC2 instance (48CPUS) with TLS as mentioned in the docs.
I was doing upserts using two different clients and i realised that the amount of data is too much (9M vectors already inserted with 10M more to be inserted) and the re-indexing is too frequent which was choking the server and causing timeout erros on client side.

So i tried to increase the `indexing_threshold` like this following the official docs:
```python
client.update_collection(
    collection_name=INDEX_NAME,
    optimizer_config=models.OptimizersConfigDiff(
        indexing_threshold=100_000
    )
)
```
And  when i resumed my `upsert` process, i ran into the abovementioned issue. All the other operations such as `client.count`, `client.search` are working fine except `upsert`.

Please let me know if i am doing anything wrong here or you need further information. Thanks!

**Comment by generall** [comment]
Also, regarding

> the re-indexing is too frequent which was choking the server and causing timeout erros on client side.

If you need to search and upsert at the same time, you might want to look at [indexed_only](https://qdrant.tech/documentation/concepts/search/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIHVsOm50aC1vZi10eXBlKDMpID4gbGk6bnRoLW9mLXR5cGUoMyk%3D) param of the search requests, if eventual indexing is OK for your usecase

**Comment by uahmad235** [comment]
Thank you for the reply @generall 
I restarted the container but it did not help.
Also i am not doing search and upserts at same time. By choking, i meant that i was getting timeout on upserts at reindexing time (since i have two clients pushing data to the server). I noticed the resources of the server and all the CPUs were occupied. My assumption is that it it is due to re-indexing.

**Comment by generall** [comment]
Are there any more logs on the server side after restrart ?

**Comment by timvisee** [comment]
> So i tried to increase the `indexing_threshold` like this following the official docs:

Please note that during the upsertions you can set it to 0 to prevent indexing at all. Then you can revert it back to your preferred threshold once all data is upserted. That way indexing does not affect upsertions at all.

This is documented here: https://qdrant.tech/documentation/tutorials/bulk-upload/#disable-indexing-during-upload

**Comment by uahmad235** [comment]
@generall apparently the upsert issue fixed after i restarted the container once more.

@timvisee thank you so much. This is really helpful. I've also created more shards to improve throughput.
