### ISSUE TITLE
Search problem by payload value

### ISSUE THREAD

**Issue by ridvancakir-cop** [qdrant/qdrant#2832]
No matter how much I searched, I could not find out whether Qdrant has such a feature. 

I have 20 books of different genres. Since I cannot upsert each book at once, I divided each book into equal parts of 512. And I created PointStruct from them as follows:

`PointStruct(id = unique_id, payload={"book":book_index},
                           vector=sentence_embedding.tolist())`

But since I made each book into separate vectors and created PointStruct like that; book_index of some points in Qdrant is the same. But all points with the same book_index represent the same book.

I collected these points in an array and upsert them as follows:

```
points = [#PointStructs...]

client = QdrantClient("localhost", port=6333)

collection_name = "book_embedding"
client.recreate_collection(
    collection_name=collection_name,
    vectors_config=models.VectorParams(size=512, distance=models.Distance.COSİNE),
)

chunk_size = len(points) // 100
chunks = [points[i:i+chunk_size] for i in range(0, len(points), chunk_size)]

for chunk in chunks:
    operation_info = client.upsert(
        collection_name="book_embedding",
        wait=True,
        points=chunk
    )
    print(operation_info)
```

And I search as follows:

```
vector data = #vector form of a sentence
 search_result = client.search(
     collection_name="book_embedding",
     query_vector=vector_data, 
     limit=5
 )
```
My output is as follows:
```
id='01ae9e67-c1ea-47a2-a6a8-ec12e0c0a8ee' version=60 score=0.71703494 payload={'book': 12} vector=None
id='e30e098f-927b-4ede-a903-4a2f55e29c8d' version=51 score=0.71298337 payload={'book': 8} vector=None
id='22a336d0-6a7f-4214-976a-a927610ad438' version=1 score=0.7012645 payload={'book': 3} vector=None
id='bc30bc99-bf50-4167-9361-a65fbfc2bdce' version=2 score=0.70112646 payload={'book': 3} vector=None
id='c6c78d4f-6b38-44e1-af35-e5adcefa19e0' version=84 score=0.7006396 payload={'book': 1} vector=None
```

My main problem is as follows: speaking for the example above; some of the 5 results I receive have the same book_index value. 

As you can see, in the output above, there are two results for book number 3. But what I want to do is to find a score for each book, not for each point.

**Comment by generall** [comment]
https://qdrant.tech/documentation/concepts/search/#grouping-api - this might be related

**Comment by ridvancakir-cop** [comment]
I don't know how I missed that. I think that's what I'm looking for. Thank you.

**Comment by timvisee** [comment]
Closing this now. Feel free to open it again if it doesn't solve what you're looking for.
