### ISSUE TITLE
Add into segment logging a collection name, a shard, a segment id

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#2839]
Hello 
I read some logs about indexing process

```
DEBUG segment::index::hnsw_index::hnsw: finish main graph
DEBUG segment::index::hnsw_index::hnsw: building additional index for field field1
DEBUG segment::index::hnsw_index::hnsw: building additional index for field field2
DEBUG segment::index::hnsw_index::hnsw: building additional index for field field3
DEBUG segment::index::hnsw_index::hnsw: building additional index for field field4
DEBUG segment::index::hnsw_index::hnsw: building additional index for field field5
DEBUG segment::index::hnsw_index::hnsw: building additional index for field field6
DEBUG segment::index::hnsw_index::hnsw: building additional index for field field7
DEBUG segment::index::hnsw_index::hnsw: building additional index for field field8
DEBUG segment::index::hnsw_index::hnsw: finish additional payload field indexing
```

I would like to know here a collection name, a shard id, a segment id.

Thanks.

**Comment by generall** [comment]
hm, those are debug log, not really expected to be used for any kind of monitoring, as we are not going to guarantee format in the new versions. So it would require to apply modifications to log things you want

**Comment by ava57r** [comment]
> hm, those are debug log, not really expected to be used for any kind of monitoring, as we are not going to guarantee format in the new versions. So it would require to apply modifications to log things you want

I believe that such an addition will be useful at the time of debugging. No guarantees are needed. If this message is deleted in the process, it does not matter
