### ISSUE TITLE
Collection does not exist - Unexpected Response: 404 (Not Found) - Error in few hours after the collection has been created

### ISSUE THREAD

**Issue by skejriwal44** [qdrant/qdrant#2842]
I get an error in few hours after the collection is created that says that the Collection does not exist - Unexpected Response: 404 (Not Found). Then the collection needs to be recreated again using `recreate_collection` and data has to be upserted fort it to become accessible.

Error -
```
UnexpectedResponse: Unexpected Response: 404 (Not Found)
Raw response content:
b'{"status":{"error":"Not found: Collection `750k_noise_collection` doesn\'t exist!"},"time":8.929e-6}'
```
P.S - When this error comes, all other collections created also throw the same error.

**Comment by generall** [comment]
Hi @skejriwal44, could you please provide some more information about your setup and exact actions you were performing to get this result?

**Comment by generall** [comment]
To progress on this issue more info on how to reproduce is required

**Comment by timvisee** [comment]
@zadolbaloi Are you running a custom Qdrant setup within Docker? Are you sure all nodes are properly registered in consensus?

You can check `GET /cluster` on all peers to see if all peers are listed there.

**Comment by zadolbaloi** [comment]
> @zadolbaloi Are you running a custom Qdrant setup within Docker? Are you sure all nodes are properly registered in consensus?
> 
> You can check `GET /cluster` on all peers to see if all peers are listed there.

I use qdrant/qdrant:latest image. All settings by default. Only one node.

**Comment by timvisee** [comment]
In that case I don't understand why you're only seeing 'collection does not exist' half of the time.

Are you sure you're not accidentally running two separate instances over which requests are load balanced? If not - I have not seen this behavior before.

Does it look fine if inspecting the collection with the web UI dashboard?

**Comment by zadolbaloi** [comment]
> In that case I don't understand why you're only seeing 'collection does not exist' half of the time.
> 
> Are you sure you're not accidentally running two separate instances over which requests are load balanced? If not - I have not seen this behavior before.
> 
> Does it look fine if inspecting the collection with the web UI dashboard?

Yep.  It looks fine if inspecting the collection with the web UI dashboard.
Now the problem was gone. 
I set up https and API_KEY. After that, the problem was gone.
