### ISSUE TITLE
Support passing the api key in the Authorization Bearer HTTP header

### ISSUE THREAD

**Issue by bashofmann** [qdrant/qdrant#2845]
**Is your feature request related to a problem? Please describe.**
Some software, notably Prometheus, don't support passing authorisation information in a custom header, but only allow to set a limited set of headers, like the standardised `Authorization` header. (see https://github.com/prometheus/prometheus/issues/2346, https://github.com/prometheus/prometheus/issues/1724).

This is a problem, when Qdrant is configured with an [API key](https://qdrant.tech/documentation/guides/security/#authentication), because then the Qdrant `/metrics` endpoint is also only accessible with authorisation. This means that you can't use Prometheus to scrape Qdrant metrics as soon as an API key is configured.

**Describe the solution you'd like**
As an alternative to the custom `Api-Key: <token>` header, it should also be possible to send the API key through the standardized ([RFC 6570](https://datatracker.ietf.org/doc/html/rfc6750)) `Authorization: Bearer <token>` header.

**Describe alternatives you've considered**
Alternatively, the `/metrics` endpoint could be made public, but this is bad in terms of security and leads to information disclosure.

**Additional context**
Other projects have been facing the same issue, e.g. Hashicorp Vault: https://github.com/hashicorp/vault/issues/5396.

This will make it possible to fix this issue https://github.com/qdrant/qdrant-helm/issues/97.

**Comment by timvisee** [comment]
> As an alternative to the custom `Api-Key: <token>` header, it should also be possible to send the API key through the standardized ([RFC 6570](https://datatracker.ietf.org/doc/html/rfc6750)) `Authorization: bearer <token>` header.

If I understand [RFC 6570](https://datatracker.ietf.org/doc/html/rfc6750) correctly the authorization value is case sensitive. The implementation in <https://github.com/qdrant/qdrant/pull/2855> follows this. So the above example must use a capital letter B. This likely isn't critical, but I wanted to mention it anyway.

```diff
-Authorization: bearer <token>
+Authorization: Bearer <token>
```

**Comment by bashofmann** [comment]
Yes, it is. Thank you for catching this!

**Comment by timvisee** [comment]
Implemented in https://github.com/qdrant/qdrant/pull/2855

I suggest to keep this open until we extend our test suite with an integration test for it.
