### ISSUE TITLE
Export latency as prometheus histogram

### ISSUE THREAD

**Issue by sergeyshevch** [qdrant/qdrant#2857]
**Is your feature request related to a problem? Please describe.**

For now qdrant export latencies as few summaries metrics `grpc_responses_avg_duration_seconds` etc. It has only aggregated information and I guess it's a more common way to export the Prometheus histogram instead. It allows us to aggregate latencies across multiple replicas and look at different quantities

It will also allow the calculation of SLO across qdrant metrics. Such as 99% of requests faster than 0.1s bucket

**Describe the solution you'd like**
Export HTTP/grpc latencies as Prometheus histograms. Add ability to configure histogram buckets

Also not include or cover by setting usage of native Prometheus histograms. It's still in beta stage and not supported by some storages

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MrBeeMovie** [comment]
This is a very important feature for me when gauging performance of my qdrant cluster. Is there any chance that this will be added soon?

**Comment by xzfc** [comment]
Opened a pull request #3552.

@sergeyshevch @MrBeeMovie Do you have any suggestions for predefined bucket configuration?

**Comment by xzfc** [comment]
Added in v1.8.0.
