### ISSUE TITLE
Test storage compatibility

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#286]
**Is your feature request related to a problem? Please describe.**

It is sometimes not clear what are the implication of a new features or updating a dependency regarding our storage format.

This means it is possible to break the storage compatibility so that data produced by the application in version `n` is not readable by the version `n+1`.

Breaking the storage compatibility cannot be done by accident as it severely impacts users.

**Describe the solution you'd like**

An automated solution (ideally part of CI) which validates the storage compatibility between two different versions of the application (tags or git commits).  

1 - build and start application in version `n`
2 - load collections/points 
3 - stop application in version `n`
4 - backup storage folder
5 - build app in version `n + 1`
6 - move previous storage folder to `n + 1` build location
5 - start application in version `n + 1`
6 - validate that the application starts properly
7 - validate that the application serves read queries

**Describe alternatives you've considered**

Save a storage snasphot and try to start all application with it on CI.

**Comment by generall** [comment]
I would prefer to use alternative approach with snapshots for the following reasons:

- Faster - no need to build application twice
- Easier to experiment with migration tools - no dependency on the service crate
- Possible to test version before previous

**Comment by agourlay** [comment]
I agree the alternative is easier to setup and execute :+1: 

The first solution is more like a stateful staging system that is gatekeeping a production rollout.

**Comment by agourlay** [comment]
Alternative strategy implemented in https://github.com/qdrant/qdrant/issues/286
