### ISSUE TITLE
Add Configuration to Generate Unique Id On Insert and Return Associated IDs for a Request

### ISSUE THREAD

**Issue by mcmah309** [qdrant/qdrant#2887]
**Is your feature request related to a problem? Please describe.**
When an entry is inserted into a collection, currently the only way to get associate an ID for the point is to to provide the ID on insert. This is problematic since this leaves the possibility of collisions and subsequently overwriting existing data.

**Describe the solution you'd like**
On collection creation, there should be a field to specify if an ID is autogenerated if not provided, such as `autogenerate_missing_ids: Option<bool>` or `auto_id_if_absent: Option<bool>`. Upsert, delete, etc. should also return the id's of modified fields if an option is set on the request parameters, such as `return_modified_ids: Option<bool>` or `return_associated_ids: Option<bool>`.

**Describe alternatives you've considered**
Id's are needed to link data outside the collection to the correct data in a collection. Generating the id on insert may result in collisions. A user solution would be to maintain this outside, such as using the `ulid` crate, which is less desirable. Additionally mutations based on payload alone, make it hard to identity which entries have been effected, and thus ensure consistency with an outside data source that references the entries Id. Returning the list of modified IDs when requested, would be ideal.

**Comment by generall** [comment]
> This is problematic since this leaves the possibility of collisions and subsequently overwriting existing data.

Using UUID on client side will minimize the possibility of collision to such a low level, that it is not even worth considering

**Comment by mcmah309** [comment]
@generall There is a big difference between having an incredibly small possibility of a collision and having zero possibility of collision. Having a built in auto-increment ID would be ideal, since it would actually make collisions impossible.

**Comment by generall** [comment]
@mcmah309 with this level of probability - there are no difference in observable universe. Please check your math

**Comment by generall** [comment]
Also discussed here: https://github.com/qdrant/qdrant/issues/1424#issuecomment-1486361733

**Comment by mcmah309** [comment]
@generall I know it's small, but still possible and even probable given time and a theoretical number of applications using qdrant. In financial applications, as is the company I work for need, and I know mission critical applications - things like eventual consistency and small chance are hard no's and will absolutely get shut down by compliance.

You don't seem to address the other aspect of the feature request - returning ids acted upon in operations. e.g. a delete operation based on a payload search. Yet this is marked as "wontfix".

I appreciate the prompt feedback, but the tone here has been slightly confrontational. I actually gave this chat to chapgt to see their thoughts, which I thought was a good excercise: https://chat.openai.com/share/33ff51be-2f6a-4640-9fe6-6ac9e8772956

We may need to look elsewhere for a solution. Thank you for your time.

**Comment by timvisee** [comment]
@mcmah309 

> For example, the number of random version-4 UUIDs which need to be generated in order to have a 50% probability of at least one collision is 2.71 quintillion. (...) This number is equivalent to generating 1 billion UUIDs per second for about 86 years. A file containing this many UUIDs, at 16 bytes per UUID, would be about 45 [exabytes](https://en.wikipedia.org/wiki/Exabyte).

Is this still not good enough?

For your information, while implementing some auto incrementing counter is definitely possible, it will have a significant effect on insertion throughput.
