### ISSUE TITLE
Distributed deployment

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#2917]
Hello.
I read documentation and can not understand.
https://qdrant.tech/documentation/guides/distributed_deployment/.

Can I write in more than 1 node in Distributed deployment mode?
Thanks.

**Comment by timvisee** [comment]
> Can I write in more than 1 node in Distributed deployment mode?

Yes. You can always send write requests to all nodes _(expect when in listener mode)_.

However, depending on 'write ordering' writes are handled on any node directly or through the cluster leader. `weak` is the default write ordering, in which case the receiving node handles it directly and propagates the write to other nodes. When using `medium` or `strong` write consistency writes are automatically routed through a leader.

Again, you can send your writes to all nodes as they're automatically rerouted internally if needed. `weak` ordering is the default, but you may choose `medium` or `strong` ordering if you want better consistency guarantees.

You can read more about this here: https://qdrant.tech/documentation/guides/distributed_deployment/#write-ordering
