### ISSUE TITLE
[geo] validate coordinates in API

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#294]
**Is your feature request related to a problem? Please describe.**
It is currently possible to same some impossible coordinates like 

```
{
  "lat": 1000,
  "lon": -223,
}
```

**Describe the solution you'd like**
Validate input using serde - https://github.com/serde-rs/serde/issues/642#issuecomment-683276351 for REST API.
And also implement some validation for protobuf

**Describe alternatives you've considered**
Validate during update operation.
Pros:
 - universal approach, does not depend on API
 
Cons:
 - user will not see the validation error until the update operation is awaited

**Additional context**
Validation required for proper geo-hash calculation

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/qdrant/releases/tag/v0.5.1
