### ISSUE TITLE
Run dashboard locally, connected to remote Qdrant over gRPC

### ISSUE THREAD

**Issue by o-agassizii** [qdrant/qdrant#2946]
**Is your feature request related to a problem? Please describe.**
We run Qdrant on one of our servers, but we expose only the gRPC port, not the REST API port and therefore not the dashboard.

I would like to run the Qdrant dashboard locally and have it show the databases and the console, etc, of the remote Qdrant database by using gRPC.

**Describe the solution you'd like**
Qdrant dashboard should be able to run locally, and connect over gRPC to a remote Qdrant database so that I can interact with the remote db using the Qdrant dashboard.

**Describe alternatives you've considered**
In our case there is no alternative.

**Additional context**

**Comment by timvisee** [comment]
I like the idea of running the Qdrant dashboard locally, probably in a separate container. But I don't think the Qdrant dashboard will support gRPC requests in the near future.

> but we expose only the gRPC port

Is there a good reason for doing this? What prevents you from exposing the REST API as well?

**Comment by o-agassizii** [comment]
Hi, we expose only the gRPC port because we try to minimize the number of open ports to the bare minimum that the applications in our data center need.

So for us it would be nice if the Qdrant dashboard running locally on dev computers could use gRPC to connect to the Qdrant db in our DC.

**Comment by timvisee** [comment]
> So for us it would be nice if the Qdrant dashboard running locally on dev computers could use gRPC to connect to the Qdrant db in our DC.

This would require significant changes to the web UI. In that case it won't be able to support HTTP/REST requests anymore, so you'd have to construct gRPC requests in the dashboard. That'd be a lot more difficult.

I don't think we'll support that in the near feature.

**Comment by generall** [comment]
Current dashboard required to access same domain+port as the one used to deliver static files, otherwise that would require cross-domain requests, which require completely different security privileges in browser.
So I don't think we will proceed with this feature request, unfortunately
