### ISSUE TITLE
Collection corrupt when during the crush

### ISSUE THREAD

**Issue by DaiZack** [qdrant/qdrant#2953]
I encountered a memory issue on the server and qdrant stopped. during this, I was loading data into collections. And seems some collections were corrupted during the outage. 
The issue is, that I was unable to start the qdrant container it stuck (more than one hour, other same size collection only loaded in 2 mins) at the step of loading the corrupted collection. And after I remove the collection folder from storage. Qdrant can load other collections properly.
During the bad loading, there is no error in the log, and I can not work on the DB.

Suggestion:
1. Enable the database when partiallly load collections, so even some collection cannot be loaded, others could still be used.
2. Identify loading issue, e.g. compare the size of the collection folder and the loading time, if it is too long, throw an error. (if possible skip it and load the rest collections)

![420a9ff6-d943-4f4d-ae06-44a87f631226](https://github.com/qdrant/qdrant/assets/45176371/5f72aa05-79df-432c-b97c-c2d096a3f2a7)
ns)

![62f3e0e1-9209-4107-a71a-d097974c9b14](https://github.com/qdrant/qdrant/assets/45176371/1563156c-05ea-4143-a37a-740bc9477ccc)

**Comment by generall** [comment]
I would consider it as resolved. However, we will continue to looking for a more smooth handling of resource exhaustion

**Comment by DaiZack** [comment]
I think they are not going to change this. The situation is only when the hnsw indexing in progress and the qdrant stop accidentally. Once the indexing finished, it starts fine just take a little bit long time when the total number of vectors is large.
