### ISSUE TITLE
Searching with multiple vectors

### ISSUE THREAD

**Issue by vishalnayak108** [qdrant/qdrant#2971]
Hi,

I'm curious about whether it's possible to perform a search using multiple vectors simultaneously. Can I utilize two distinct text embeddings for searching concurrently, or is it required to use only one of them for vector search? The idea behind employing multiple vectors simultaneously is to utilize them as filters in a hierarchical manner.

**Comment by generall** [comment]
https://qdrant.tech/documentation/concepts/search/#recommendation-api

**Comment by timvisee** [comment]
Closing now assuming the above solution is fitting.

Feel free to open this again if you have further questions.
