### ISSUE TITLE
Cancel shard transfer if shard is locally disabled

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2975]
**Is your feature request related to a problem? Please describe.**
There is a situation possible in consensus:

- we have 2 replicas
- there is a currently running transfer from A(Active) -> B(Partial)
- Node A is killed
- Update is coming and it is written to B, but not to A
- A is reported as locally disabled and this change is actively propagated to consensus, but always declined due to "can't disable last active".
- reports to consensus generate a lot of spam in consensus WAL

Some limitations:

- If only `Partial` node receives the update, we can't ignore it. If the error is transient, the consistency of replicas will be compromised.
- We can't force disable A, cause in this case we won't have any active replicas

**Describe the solution you'd like**

If we, in addition to reporting disabled state, will try to cancel all outbound transfers from the reported-as-dead replica,
the following scenario should happen:

- Node B reporting to the consensus 2 operations: cancel transfer and disable replica A
- First operation should be accepted, as there are no reason to not abort transfer
- Second operation will be rejected, as we can't disable last Active
- While shard transfer is aborted - it will change state of B from Partial -> Dead, that will clean the `locally_disabled` state and prevent further consensus spam 

Also this solution doesn't look too hacky, as cancelling transfer from dead shard is nothing but reasonable.

**Comment by mdnfiras** [comment]
awesome, this works.

our transfer-er pod had a `consensus_thread_status` error and some shard transfers were stuck, resulting in other nodes failing to startup and sync their shards.

after restarting the transfer-er node, all shard transfers that were stuck got restarted and finished properly. other nodes that were stuck on startup finally worked.
