### ISSUE TITLE
Using large numbers for point IDs seem to cause 404s

### ISSUE THREAD

**Issue by rand0m-cloud** [qdrant/qdrant#3002]
Version 1.6.1 (docker)

## Current Behavior

I inserted points with an ID of 177 and 13811189083039875000 into my collection. Both appear in the dashboard's point listing but clicking on find similiar on the large point ID causes a not found error, repeating the same for the smaller ID works. My code was using the lower u64 half of a UUID v4 as a point ID but it was causing the API to 404 on payload edits and recommendations. Chopping the u64 to u8 fixed the problem.

## Steps to Reproduce

1. Create a collection (vector size of 1536, cosine distance, ..default)
2. Upsert a point with ID 177 from the Rust client
3. Upsert a point with ID 13811189083039875000 from the Rust client
4. Use the dashboard and attempt using the find similiar button on the 13811189083039875000 point

![image](https://github.com/qdrant/qdrant/assets/6750326/269de9ba-6870-4897-9175-82343d228570)
![image](https://github.com/qdrant/qdrant/assets/6750326/2ffa3d35-db79-4427-b74d-125485494264)

```
2023-11-13T19:13:53.230757Z  WARN collection::collection_manager::collection_updater: Update operation declined: No point with id 13811189083039875000 found    
2023-11-13T19:13:53.231002Z  INFO actix_web::middleware::logger: 172.17.0.1 "PUT /collections/my_collection/points/payload?wait=true HTTP/1.1" 404 105 "http://localhost:6333/dashboard" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0" 0.009414    
```

**Comment by generall** [comment]
Hi @rand0m-cloud, this is a js/dashboard problem. Qdrant itself is processing large numbers fine.

referencing original issue here: https://github.com/qdrant/qdrant-web-ui/issues/87

**Comment by rand0m-cloud** [comment]
FWIW, 13811189083039875000 is greater than `Number.MAX_SAFE_INTEGER` (9007199254740991). Not a JS 32-bit number issue.

**Comment by generall** [comment]
Hi @rand0m-cloud, it is still JS problem, cause you are using `jq` in your example, which is following JS standart

**Comment by rand0m-cloud** [comment]
Yep! I feel bad for not doing more through inspection before commenting. Researching this issue has not been fun, I think it is issues in the UI's dependencies. Namely, the JS REST client is largely generated through the OpenAPI spec and the codegen doesn't support BigInt. Then the fetcher used in the REST client has to be patched with a JSON-BigInt library.
