### ISSUE TITLE
Filters + Is Empty condition returns incorrect results

### ISSUE THREAD

**Issue by nmklong** [qdrant/qdrant#3003]
When applying Is Empty condition together with a payload filter, the filtering seem to ignore the Is Empty condition and only processed the filter

## Current Behavior

I have records looking like this:
```
     {
        "id": "123-345-568",
        "payload": {
          "TargetId": 149,
          "ParentTargetIds": [
            112
          ],
          "_partition": "partition_1"
        },
        "vector": null
      }
```

Then I try to filter:

```
POST collections/test-collection/points/scroll
{
  "limit": 1000,
  "filter": {
    "must": [
      {
        "key": "_partition",
        "match": {
          "value": "partition_1"
        }
      }
    ]
  },
  "is_empty": {
    "key": "ParentTargetIds"
  }
}
```

The returned results contain correctly records with `_partition` with value `partition_1`, however the `ParentTargetIds` in there are not empty

## Steps to Reproduce

1. Have a database with records having payload looking like above
2. Try to have a Is Empty condition on a payload's field together with a filter for another field in the payload
3. The results don't take into account for Is Empty condition

**Comment by generall** [comment]
hi @nmklong, could you pls double-check syntax of your query. `is_empty` appears to be outside of the filter.

**Comment by nmklong** [comment]
@generall  Thank you for pointing it out, I was confused at first because according [to the doc](https://qdrant.tech/documentation/concepts/filtering/#is-empty) it seems to be outside, If i update the JSON to below, it works perfectly

```
POST collections/test-collection/points/scroll
{
  "limit": 1000,
  "filter": {
    "must": [
      {
        "key": "_partition",
        "match": {
          "value": "partition_1"
        }
      },
      {
        "is_empty": {
          "key": "ParentTargetIds"
        }
      }
    ]
  }
}
```
