### ISSUE TITLE
Flaky test_shard_snapshot_transfer_cancel_during_updates

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#3006]
https://github.com/qdrant/qdrant/actions/runs/6859971045/job/18653061013?pr=3000#step:10:1269

```
=========================== short test summary info ============================
FAILED tests/consensus_tests/test_shard_snapshot_transfer_cancel.py::test_shard_snapshot_transfer_cancel_during_updates - assert 2 == 1
```

**Comment by timvisee** [comment]
Merged <https://github.com/qdrant/qdrant/pull/3009> in an attempt to fix this.

Let's leave this open for 3 days and see whether the issue persists before closing this.

**Comment by timvisee** [comment]
Failed again: https://github.com/qdrant/qdrant/actions/runs/6875240092/job/18698432683

I've attempted to fix it another time here: https://github.com/qdrant/qdrant/pull/3022
