### ISSUE TITLE
Flaky test_shard_snapshot_transfer_throttled_updates

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#3007]
https://github.com/qdrant/qdrant/actions/runs/6859971026/job/18653060742?pr=2999#step:10:4215

```
=========================== short test summary info ============================
FAILED tests/consensus_tests/test_shard_snapshot_transfer.py::test_shard_snapshot_transfer_throttled_updates - Exception: Timeout waiting for condition check_collection_shard_transfers_count to be satisfied in 30 seconds
```

**Comment by timvisee** [comment]
Merged <https://github.com/qdrant/qdrant/pull/3009> in an attempt to fix this.

Let's leave this open for 3 days and see whether the issue persists before closing this.
