### ISSUE TITLE
Flaky test_shard_snapshot_transfer_fast_burst

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#3008]
https://github.com/qdrant/qdrant/actions/runs/6860439387/job/18654272039?pr=2993#step:10:1501

```
 =========================== short test summary info ============================
FAILED tests/consensus_tests/test_shard_snapshot_transfer.py::test_shard_snapshot_transfer_fast_burst - assert 2805 == 2806
```

**Comment by timvisee** [comment]
Merged <https://github.com/qdrant/qdrant/pull/3009> in an attempt to fix this.

Let's leave this open for 3 days and see whether the issue persists before closing this.
