### ISSUE TITLE
Nice to have: Overwrite individual fields in payload

### ISSUE THREAD

**Issue by Tylersuard** [qdrant/qdrant#3042]
Right now I have to download the entire payload, modify one field, and then re-upload the entire payload.  It would be nice if I could only download one field from the payload, modify that one field, and then update only that one field in the payload in Qdrant.

**Comment by generall** [comment]
Hi @Tylersuard, Qdrant already allows you to do exactly as you described!

`with_payload` param allows you to select specific field in the result: https://qdrant.tech/documentation/concepts/search/#payload-and-vector-in-the-result

And https://qdrant.tech/documentation/concepts/points/#set-payload allows you to set individual payload values
