### ISSUE TITLE
Storage scalling

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#3046]
Hello

I would like to suggest adding the ability to save data in multiple directories
param `storage_path` in the config file

This can be useful when there is a lot of data and the speed of 1 SSD is no longer enough

Thanks.

**Comment by timvisee** [comment]
> This can be useful when there is a lot of data and the speed of 1 SSD is no longer enough

This is normally resolved with a RAID configuration.

**Comment by generall** [comment]
Altertatively, you can run qdrant in distributed mode on a single machine. It might be not as nice, but having multiple directories for storage also sounds problematic

**Comment by timvisee** [comment]
And in single-node deployment you _could_ use different disks mounted to collection directories directly, mapping different collections to different disks. I highly recommend against this though as it would require carefully managing this.

RAID would definitely be a lot more robust and scalable, and it would share available resources better.

**Comment by ava57r** [comment]
> Altertatively, you can run qdrant in distributed mode on a single machine. It might be not as nice, but having multiple directories for storage also sounds problematic

I tried =)
It's difficult.
