### ISSUE TITLE
io_uring compabilities with quantization

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#3075]
in https://github.com/qdrant/qdrant/issues/2948 I asked about quantization

not one of the parts of my collection does not fit by itself into RAM

I set
`hnsw.on_disk = true`
`vectors.on_disk = true`
`quantized_vectors.on_disk = true`

1. Why is quantized_vectors useless here?
2. how does oversampling work when quantized_vectors on disk? 
3. how does oversampling work when quantized_vectors not set(not use)?
4. it seems that searching by the source vector will lead to an increase in the number of disk I/O operations and this will lead to an increase in search time, as well as memmap, right?

Summary: how to combine the oversampling, quantization, oi_uring parameters correctly?

THANKS =)

**Comment by ava57r** [comment]
5. Are you planning to use io_using for the  `memmap` hnsw index?

**Comment by generall** [comment]
> Why is quantized_vectors useless here?

bottleneck is the disk IOPS, it doesn't matter if you read 1Kb or 4Kb of from disk, it will read the whole page anyway.
So quantization on-disk is indeed might only be useful in very specialized cases.


> how does oversampling work when quantized_vectors on disk?
Same way as in-ram

> how does oversampling work when quantized_vectors not set(not use)?
it doesn't

> it seems that searching by the source vector will lead to an increase in the number of disk I/O operations and this will lead to an increase in search time, as well as memmap, right?

partially, right. Number of operations would be the same, the effectiveness of disk cache will be better, as you have smaller storage with quantized.

> Are you planning to use io_using for the memmap hnsw index?

we are planning, but it might be quite complicated and we don't see clear advantage yet
