### ISSUE TITLE
payload is None when I do batch search 

### ISSUE THREAD

**Issue by sourabh-patil** [qdrant/qdrant#3077]
Hi,

When I do single query search using client.search, I do get payload as expected, but when I am trying batch search using client.search_batch, I get payload as None.

Following is the difference between single search and batch search 

Single search where each search is printed line by line 

```
[ScoredPoint(id=3295, version=3295, score=0.0, payload={'name': 'shabbir'}, vector=None)]
[ScoredPoint(id=9689, version=9689, score=0.0, payload={'name': 'sourabh'}, vector=None)]
[ScoredPoint(id=3862, version=3862, score=0.0, payload={'name': 'pankaj'}, vector=None)]
[ScoredPoint(id=9041, version=9041, score=0.0, payload={'name': 'veeru'}, vector=None)]
[ScoredPoint(id=2606, version=2606, score=0.0, payload={'name': 'rohan'}, vector=None)]
Time for single search :  0.2611043453216553 
```

Batch search where result is printed

```
[[ScoredPoint(id=2606, version=2606, score=0.0, payload=None, vector=None)], [ScoredPoint(id=9041, version=9041, score=0.0, payload=None, vector=None)], [ScoredPoint(id=3862, version=3862, score=0.0, payload=None, vector=None)], [ScoredPoint(id=9689, version=9689, score=0.0, payload=None, vector=None)], [ScoredPoint(id=3295, version=3295, score=0.0, payload=None, vector=None)]]
Time for batched search :  0.08774089813232422 
```

I create the collection using following code snippet

```python
from tqdm import tqdm
for idx, curr_emb in tqdm(enumerate(emb_bank)):
    client.upsert(
        collection_name = 'emb_bank_10k',
        points = [
            PointStruct(
                id = idx,
                vector = curr_emb.tolist(),
                payload = {'name':names[idx]}
            )
        ]
    )
```

here, names are the list of names I want to use as payload

Thanks!

**Comment by timvisee** [comment]
In each search item of your batch, you must provide `with_payload` with `true`. Does that work?

**Comment by sourabh-patil** [comment]
@timvisee Thank you for replying. I am using the search_batch definition, which apparently does not have the with_payload flag. But for search (which I am using for single vector query) and search_groups definitions, the with_payload flag is True by default. 
I need to query a varying size batch of vectors and get the corresponding payloads too. I am new to Qdrant, so any pointer would be really helpful. Thanks!

**Comment by timvisee** [comment]
Would you mind to share the code you use for the batch search?

**Comment by sourabh-patil** [comment]
@generall Thanks for the input. It worked! @timvisee Thanks for your assistance!
