### ISSUE TITLE
how indexing behave in the qdrant db when adding new records to the existing collection? does it need to re-index everytime we insert new records?

### ISSUE THREAD

**Issue by vishalnayak108** [qdrant/qdrant#3087]
Is it necessary to re-index the vector database when adding new records to the existing collection? Additionally, how can we accomplish this without impacting the production environment?

**Comment by timvisee** [comment]
> Is it necessary to re-index the vector database when adding new records to the existing collection?

Yes, but this is done automatically.

Basically, imagine that you're slowly inserting new points. Eventually you have enough 'plain' points and they'll be indexed together automatically. These 'plain' points are also searched. The indexing process will not cause downtime but it will temporarily cause high CPU load, so there might be slight delays in search timings. It is perfectly fine to do this on a production environment.
