### ISSUE TITLE
Wals files are corrupted after forced shutdown

### ISSUE THREAD

**Issue by Xredys-19** [qdrant/qdrant#3090]
I have a qdrant cluster with 5 nodes, and one of the nodes died because the server suddenly went down, and when the server came back on, the qdrant wals file became corrupt with the following error.

![image](https://github.com/qdrant/qdrant/assets/88485337/8bb65f70-613c-46e3-aec2-0035993db743)

Steps to Reproduce

1.Running qdrant node
2.Shutdown the server suddenly
3.Start Qdrant again and get corrupt wals files

**Comment by generall** [comment]
Hi @Xredys-19, could you please describe your setup in more details?

- How do you run qdrant? (docker? Which version?)
- What volumes/file system are you using?
- Potential out-of-disk problem?

**Comment by timvisee** [comment]
This has been resolved in Qdrant 1.7, which will be released very shortly.
