### ISSUE TITLE
Snapshot Size too big

### ISSUE THREAD

**Issue by zhenxi1** [qdrant/qdrant#3114]
**Is your feature request related to a problem? Please describe.**

Qdrant 1.6.1 version, with a distributed mode (3 nodes):

I created a collection with 6 shards and 3 replications and I added a point (768 vector size)

When I create a snapshot of the collection with only 1 point, the size of the created snapshot is around 400MB.

If I get the inserted point from the collection and save it in a file, the size of file is around 30KB.

The snapshot of the collection is so bigger than the point I inserted, is it right?

Is there a way to backup and recover only the points I inserted in the collection?

Thank you

**Comment by generall** [comment]
In addition to the point, snapshot also contains WAL and other files. By default, size of the one WAL segment is 32mb (configurable). 
When you create 6 shards, each one of them is going to have a separate WAL.

**Comment by generall** [comment]
> Can I update the "wal_capacity_mb" of a collection is already created?

unfortunately, no

> The old contents (old sequential number of operations) of WAL are removed automatically?

yes

> If I reduce the size of "wal_capacity_mb", and one day if there is no space in WAL, what will happen? The operations will be executed normally?


WAL is automatically truncated


> Would you give me some advice the "right size" to use for WAL, neither have too big size of snapshot nor the collection will not stop to work?

We didn't do any benchmarks on this and just use the default config everywhere.

**Comment by zhenxi1** [comment]
Thanks for your answer,

is it possible to do a logical database backup, to take a 'snapshot' without the WAL?

And we can restore the data from the backuped 'snapshot'.

Thank you

**Comment by generall** [comment]
> is it possible to do a logical database backup, to take a 'snapshot' without the WAL?

In this case consistency of the snapshot is not guaranteed

**Comment by fedecompa** [comment]
What are the drawbacks of configuring the single WAL segment size too low?

**Comment by timvisee** [comment]
> What are the drawbacks of configuring the single WAL segment size too low?

Having a small WAL size would mean that our WAL logic needs to reserve new WAL space more often. That _can_ be expensive, blocking incoming updates for a bit.

**Comment by fedecompa** [comment]
@timvisee which is the path in the container where is saved this WAL file ? Thanks

**Comment by timvisee** [comment]
@fedecompa Inside the container at: `/qdrant/storage/collections/*/*/wal`
