### ISSUE TITLE
Help: Running Qdrant as standalone application in Linux 

### ISSUE THREAD

**Issue by harshakhmk** [qdrant/qdrant#3141]
I am exploring the Qdrant database and was amazed with the features provided, and I am just wondering if there is an option to build and run Qdrant locally as I want to use it in my application

Any leads on this would be highly appreciated

**Comment by harshakhmk** [comment]
Could you mention the steps to do the same without docker 

Additionally could you mention the reason why it is not recommended to run without docker?

Thanks in Advance

**Comment by martyanov** [comment]
@harshakhmk where did you find that it is not recomended to run without docker?

Regarding build toolchain this is easy, excerpt from our `Makefile`:

```make

QDRANT_VERSION=1.6.1
QDRANT_RELEASE=1
QDRANT_ARCHIVE=v$(QDRANT_VERSION).tar.gz
QDRANT_URL=https://github.com/qdrant/qdrant/archive/refs/tags/$(QDRANT_ARCHIVE)

RUST_DIR=.rust
RUST_VERSION=1.72.1
RUSTUP_URL=https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
CARGO_BIN=$(RUST_DIR)/bin/cargo

PROTOBUF_VERSION=24.4
PROTOBUF_ARCHIVE=protoc-$(PROTOBUF_VERSION)-linux-x86_64.zip
PROTOBUF_URL=https://github.com/protocolbuffers/protobuf/releases/download/v$(PROTOBUF_VERSION)/$(PROTOBUF_ARCHIVE)

BUILD_DIR=.build

deps: $(CARGO_BIN)
$(CARGO_BIN):
	wget -c $(RUSTUP_URL) -P $(RUST_DIR)
	chmod +x $(RUST_DIR)/rustup-init
	CARGO_HOME=$(RUST_DIR) RUSTUP_HOME=$(RUST_DIR) \
		$(RUST_DIR)/rustup-init --no-modify-path --profile default --default-toolchain $(RUST_VERSION) -v -y

build: deps
	wget -c $(PROTOBUF_URL) -P $(BUILD_DIR)
	unzip -n $(BUILD_DIR)/$(PROTOBUF_ARCHIVE) -d $(RUST_DIR)

	wget -c $(QDRANT_URL) -P $(BUILD_DIR)
	tar -xf $(BUILD_DIR)/$(QDRANT_ARCHIVE) -C $(BUILD_DIR)

	CPLUS_INCLUDE_PATH=$(RUST_DIR)/include CARGO_HOME=$(RUST_DIR) RUSTUP_HOME=$(RUST_DIR) PATH=$(RUST_DIR)/bin:$(PATH) \
		cargo build --release --bin qdrant --manifest-path $(BUILD_DIR)/qdrant-$(QDRANT_VERSION)/Cargo.toml
```

This way your even don't need any `Rust` toolchain to be installed, `Cargo` does everything for you. Also note that in addition to dependencies provided by @timvisee you probably need `perl-interpreter` package as it is required by `OpenSSL` related stuff. And we're using upstream version of `protobuf` because depending on your distribution it may be dated, in our case everything is working fine without it on `Fedora 35+`, but requires upstream version in `Rocky Linux 8`.

And the last one. There was an issue with `Rust` that prevented to build `Qdrant` on the latest toolchain https://github.com/qdrant/qdrant/issues/2819, seems it was fixed in upstream, but haven't checked since then.

**Comment by martyanov** [comment]
> > can it be done without docker as well with database as a standalone application running in my local machine?
> 
> Yes, though that is not recommended.

Interesting. Why is that? Being using everything without `Docker`, `Kubernetes`, all the stuff since forever, never had an issue. :) Sorry if it is off topic.

**Comment by timvisee** [comment]
> Additionally could you mention the reason why it is not recommended to run without docker?

> @harshakhmk where did you find that it is not recomended to run without docker? P.S. Oh, now I see where it came from.

We **do** recommend to run **with** Docker.

We do not recommend to run without Docker.

@martyanov Thank you for sharing your Makefile.

**Comment by harshakhmk** [comment]
@


> > Additionally could you mention the reason why it is not recommended to run without docker?
> 
> > @harshakhmk where did you find that it is not recomended to run without docker? P.S. Oh, now I see where it came from.
> 
> We **do** recommend to run **with** Docker.
> 
> We do not recommend to run without Docker.
> 
> @martyanov Thank you for sharing your Makefile.
@martyanov martyanov Thanks for the makefile it is working fine building with this approach

I was just curious if there will be any issues if we run without docker following the above steps

**Comment by timvisee** [comment]
> I was just curious if there will be any issues if we run without docker following the above steps

There should be no issues.

Our web UI is not in self-compiled builds by default though, while it is included in our Docker image.

If you'd like to use the web UI you can call `./tools/sync-web-ui.sh` to download it.

**Comment by generall** [comment]
Assuming this is resolved
