### ISSUE TITLE
Different points ID will have the same ID after inserting to qdrant

### ISSUE THREAD

**Issue by golangboy** [qdrant/qdrant#3170]
## Current Behavior
There are two points with same ID.
```json
{
  "result": {
    "points": [
      {
        "id": 1000001001111123100,
        "payload": {
          "name": "test122"
        },
        "vector": null
      },
      {
        "id": 1000001001111123100,
        "payload": {
          "name": "test12"
        },
        "vector": null
      }
    ],
    "next_page_offset": null
  },
  "status": "ok",
  "time": 0.000893462
}
```

## Steps to Reproduce
```python
import qdrant_client
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct

client = QdrantClient("10.131.7.124", port=6333)
client.create_collection(
    collection_name="test",
    vectors_config=VectorParams(size=4, distance=Distance.DOT),
)
client.upsert(
    collection_name="test",
    points=[
        PointStruct(
            id=1000001001111123112,
            vector=[1.0, 2.0, 3.0, 4.0],
            payload={"name": "test12"},
        ),
    ],
    wait=False,
)

client.upsert(
    collection_name="test",
    points=[
        PointStruct(
            id=1000001001111123111,
            vector=[1.0, 2.0, 3.0, 40.0],
            payload={"name": "test122"},
        ),
    ],
    wait=False,
)

```

## Expected Behavior
A point's ID is 1000001001111123112, and another points's ID is 1000001001111123111.

## Possible Solution
 Not obligatory, but suggest a fix/reason for the bug

## Context (Environment)
Qdrant v1.6.1

## Detailed Description
Provide a detailed description of the change or addition you are proposing 

## Possible Implementation
Not obligatory, but suggest an idea for implementing addition or change

**Comment by timvisee** [comment]
Question, what client are you using? Is it the JavaScript/TypeScript client by any chance?

**Comment by golangboy** [comment]
> Question, what client are you using? Is it the JavaScript/TypeScript client by any chance?

client: https://github.com/qdrant/qdrant-web-ui 

and open the url:
> http://127.0.0.1:6333/dashboard#/console

and run the post request!
```
POST collections/video/points/scroll
{
  "limit": 10,
  "filter": {
    "must": [
      {
     
      }
    ]
  }
}

```

**Comment by golangboy** [comment]
@timvisee maybe it is client' problem,because i post the request with postman, anything is ok!
this is the response!

```
{
    "result": {
        "points": [
            {
                "id": 1000001001111123111,
                "payload": {
                    "name": "test122"
                },
                "vector": null
            },
            {
                "id": 1000001001111123112,
                "payload": {
                    "name": "test12"
                },
                "vector": null
            }
        ],
        "next_page_offset": null
    },
    "status": "ok",
    "time": 0.0740577
}
```

**Comment by golangboy** [comment]
ok, i found it at https://github.com/qdrant/qdrant-web-ui/issues/87

**Comment by timvisee** [comment]
Wanted to point you to that issue indeed (<https://github.com/qdrant/qdrant-web-ui/issues/87>).

It's an annoying issue, but we should still take care of it. As you've likely figured out, our other clients (other than JavaScript) don't have this problem.
