### ISSUE TITLE
Is there a way to store arbitrary metadata at collection level?

### ISSUE THREAD

**Issue by ashishb** [qdrant/qdrant#3182]
**Is your feature request related to a problem? Please describe.**

Is there a way to store arbitrary metadata at collection level?
For example, last time the collection was updated.

**Describe the solution you'd like**
A way to attach metadata to collection (not points in the collection)

**Describe alternatives you've considered**
Storing metadata with points in the collection

**Comment by generall** [comment]
I would suggest to rather create a separate collection for metadata like this.
