### ISSUE TITLE
gRPC API should return AlreadyExists status code rather than InvalidArgument if collection already exists

### ISSUE THREAD

**Issue by fuine** [qdrant/qdrant#3217]
**Is your feature request related to a problem? Please describe.**
When you try to create a collection that already exists the gRPC API returns status with `tonic::Code::InvalidArgument` code variant and I think it should return `tonic::Code::AlreadyExists`.

**Describe the solution you'd like**
`tonic::Code::AlreadyExists` code is returned instead of `tonic::Code::InvalidArgument` when trying to create a collection that already exists.

**Describe alternatives you've considered**
The obvious alternative is using the current implementation, but I think that it is somewhat misleading to return `InvalidArgument` when the `AlreadyExists` code is also present in `tonic::Code`.

**Additional context**
I didn't dig very deep, but as far as I can tell [this is the place where the error is created](https://github.com/qdrant/qdrant/blob/97b2483660d9190835b8df13ee1b27873d370da5/lib/storage/src/content_manager/collections_ops.rs#L21), and my guess would be that there is some sort of conversion between `StorageError` and `tonic::Status`, and `StorageError` uses `BadInput` variant, as it doesn't have `AlreadyExists` equivalent.

**Comment by Doordashcon** [comment]
Hello @generall I am looking into this

**Comment by 2k4sm** [comment]
I would like to work on this issue can you please assign me on this.

**Comment by timvisee** [comment]
> I would like to work on this issue can you please assign me on this.

We don't assign issues in GitHub. But please feel free to pick it up and reference this issue. :smile:

**Comment by 2k4sm** [comment]
### What i have done to understand the problem.
- After Setting up the repository in my local machine,  i created a dummy python grpc client to test the API.
- I tried to create a collection that already existed which resulted in an error which was expected.
- Status of the returned error
   - status = StatusCode.INVALID_ARGUMENT.
![image](https://github.com/qdrant/qdrant/assets/101013814/f9672f86-b877-4c37-8c46-2cce0a609f3b)

### My Understanding to fix this.
- To fix this problem there is a need to change the StorageError::BadInput to tonic::Code::AlreadyExists.

### Question regarding the problem.
- Is my understanding to fix this problem correct ?
- Currently we are returning ```Result<(), StorageError>``` changing the error code will lead to change the return type of the error from `StorageError` to tonic::Code.

**Comment by coszio** [comment]
Fixed in #3423
