### ISSUE TITLE
Add documentation for the upload endpoint 

### ISSUE THREAD

**Issue by thesteve0** [qdrant/qdrant#3219]
just noticed there is a method missing from the snapshot API documentation. On this page it shows you how to use curl to upload a snapshot
https://qdrant.tech/documentation/concepts/snapshots/#recover-via-api

But I don't see the upload method on the snapshots endpoint in the API doc.

![image](https://github.com/qdrant/qdrant/assets/1404099/19167a0d-16d7-4f92-a01f-c14865350562)

It's a pretty important piece of functionality and I keep forgetting where I saw the instructions and get really frustrated when it's not in the API doc

**Comment by timvisee** [comment]
Correct. It is listed here: https://qdrant.github.io/qdrant/redoc/index.html#tag/snapshots/operation/recover_from_uploaded_snapshot

You can upload a file to it as `multipart/form-data`.
