### ISSUE TITLE
qdrant升级

### ISSUE THREAD

**Issue by zhangzf875** [qdrant/qdrant#3227]
现在因为qdrant恢复快照时，不能正常恢复，执行语句：
curl -X POST 'http://127.0.0.1:6333/collections/zzf_test/snapshots/upload' \
-H 'Content-Type:multipart/form-data' \
--header "api-key: d37c985d343b876f6b1bce8a03ea3ae5" \
-F 'snapshot=@/var/lib/docker/overlay2/12412ce79e8263d735d9136cb0c9dd9cf489be46566ae6cba5aa4e9c795333ea/merged/qdrant/snapshots/zzf_test/zzf_test-7552286958953378-2023-12-14-07-02-43.snapshot'
会报错误：
{"status":{"error":"Service internal error: File IO error: Invalid cross-device link (os error 18)"},"time":98.230508433}
现在想要升级qdrant版本，这个升级具体要怎么操作才能保持原来的数据和配置不变，请大佬提供一下方法

**Comment by generall** [comment]
Duplicate of https://github.com/qdrant/qdrant/issues/3220
