### ISSUE TITLE
qdrant升级

### ISSUE THREAD

**Issue by zhangzf875** [qdrant/qdrant#3228]
qdrant升级，是不是通过docker pull qdrant/qdrant下载最新的qdrant镜像，然后在用来的的启动命令和文件存储去重新启动，就算启动成功了，整个过程是不是这样子的呢

**Comment by generall** [comment]
> (auto-translation) To upgrade qdrant, do you download the latest qdrant image through docker pull qdrant/qdrant, and then use the startup command and file storage to restart? Even if the startup is successful, is the whole process like this?

To upgrade qdrant with docker you need to simply run container with the new tag: `docker run qdrant/qdrant:v1.7.2`. Make sure that the storage is mounter properly to the container. Full example:

```
docker run -p 6333:6333 -p 6334:6334 \
    -v $(pwd)/qdrant_storage:/qdrant/storage:z \
    qdrant/qdrant:v1.7.2
```

**Comment by zhangzf875** [comment]
如果要保留之前的数据和以及配置文件是不是只要
docker run --restart=always --ulimit nofile=1048576:1048576  -p 6333:6333 \
    -v /data/qdrant/conf/config.yaml:/qdrant/config/config.yaml \
    -v /data/qdrant/qdrant_storage:/qdrant/storage \
    qdrant/qdrant:v1.7.2 &
这样原来的数据会不会同样保存下来，原来的配置文件是不是也会生效
您提供的案例上面还有加-p 6334:6334，声明这个6334端口是做什么用的呢

**Comment by jhdxr** [comment]
-p 6334是用于grpc的，如果你不用可以不加。

在明知项目维护者都不会中文的情况下坚持用中文提问非常不礼貌，维护者已经提供了示范了，在有中文的情况下，请附上一个英文翻译，哪怕是用工具翻译的。
