### ISSUE TITLE
customizing Timeout

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#3277]
Hi,

I am unable to either reduce of increase the default REST query timeout of 60s even if I set the timeout=300 in the (search)query request or even in the constructor of the qdrant client.
## Current Behavior

The timeout remains unchanged at 60s
## Steps to Reproduce

1.
2.
3.
4.

## Expected Behavior

Timeout provided in request should override timeout provided in the constructor which should override the default timeout. That doesnt seem to be happening.

## Possible Solution

Should we be using grpc instead of REST api for our query request to get control over the timeout?
## Context (Environment)
We are using 1.7 qdrant server and 1.7 python client on a ubuntu 22 machine

**Comment by generall** [comment]
Hi @nairajay2k, could you please describe steps to reproduce the problem?

**Comment by nairajay2k** [comment]
client = QdrantClient("192.168.10.141", port=6333, timeout=300)
    search_results = client.search(
         offset=offset,
         limit=limit,
         with_vectors=True,
         with_payload=True,
         query_vector=patent_embedding,
         query_filter=field_condition,
         timeout=300,
         collection_name="us_fto_collection_v7",
         search_params=models.SearchParams(hnsw_ef=128, exact=False,indexed_only=True),
    )

The above still times out at 60 seconds for long running queries. We want to control and increase that timeout so queries can complete their execution.

**Comment by nairajay2k** [comment]
Sorry my bad..Our client is 1.7.0 and qdrant server is 1.6.1

**Comment by nairajay2k** [comment]
Why has this thread been closed?

**Comment by AreYouLoco** [comment]
@nairajay2k please do re-open this. Why it has been closed?
