### ISSUE TITLE
Delete all points in a collection

### ISSUE THREAD

**Issue by milosgajdos** [qdrant/qdrant#3298]
**Is your feature request related to a problem? Please describe.**
Just a query because I'm not sure where else I can ask it

**Describe the solution you'd like**
Is there a way to delete all points in a collection? In some use cases where I  want to reset the data stored in the collection. 

**Describe alternatives you've considered*
Deleting and then recreating a collection - this might work but I wonder if this is the most efficient way?

**Additional context**
N/A

**Comment by generall** [comment]
Deleting and then recreating a collection is usually more efficient, especially is the collection is large,
but if you don't have many vectors and you don't want to interrupt other users of the service, you can delete by empty filter: https://qdrant.tech/documentation/concepts/points/#delete-points

**Comment by generall** [comment]
Additionally, if you are using custom sharding, you can delete shards instead of collections. In this case search queries should not be interrupted and it will be as efficient as removing of the whole collection

**Comment by milosgajdos** [comment]
> you can delete by empty filter

You mean something like this?
```json
POST /collections/{collection_name}/points/delete
{
    "filter": {}
}
```

**Comment by generall** [comment]
yes

**Comment by milosgajdos** [comment]
Thanks,
