### ISSUE TITLE
Unable to update named vectors on a given point

### ISSUE THREAD

**Issue by milosgajdos** [qdrant/qdrant#3299]
Unable to update named vectors on a given point.

## Current Behavior

Updating named vectors on a point seemingly returns `200` but when querying the points no named vectors are returned.

## Steps to Reproduce

Create a collection. We've created one with the name that's a uuid: `741f28d2-e703-4f1d-807e-8d5affe20b00`

Create a point in the collection 
```shell
curl localhost:6333/collections/741f28d2-e703-4f1d-807e-8d5affe20b00/points \
  -X PUT \
 -H "Content-Type: application/json" \
 -d'{
  "batch": {
    "ids": [
      "e2f73d54-e7d6-4429-8e36-83812586bc4f"
    ],
    "vectors": [
      [ 0.1, 0.2, 0.3, 0.4]
    ]
  }
}'
```

According to docs: https://qdrant.tech/documentation/concepts/points/#retrieve-points this should work, alas, doesn't seem to:
```shell
curl localhost:6333/collections/741f28d2-e703-4f1d-807e-8d5affe20b00/points \
 -X POST \
 -H "Content-Type: application/json" 
{"status":{"error":"Format error in JSON body: EOF while parsing a value at line 1 column 0"},"time":0.0}%
```

When trying the above with `-X GET` I get `404`, which is strange because the scrolling seems to work and confirms the point did get created:
```shell
curl localhost:6333/collections/741f28d2-e703-4f1d-807e-8d5affe20b00/points/scroll \
-X POST \
-H "Content-Type: application/json" \
-d'{
    "filter": {},
    "with_payload": true,
    "with_vector": true
}'
{"result":{"points":[{"id":"e2f73d54-e7d6-4429-8e36-83812586bc4f","payload":{},"vector":[0.1,0.2,0.3,0.4]}],"next_page_offset":null},"status":"ok","time":0.000629448}
```

Now, let's update the point with _named vetors_ as per the docs https://qdrant.tech/documentation/concepts/points/#update-vectors (not the ID of the point we are updating is the same as the point we've created above: `e2f73d54-e7d6-4429-8e36-83812586bc4f`)
```shell
$ curl localhost:6333/collections/741f28d2-e703-4f1d-807e-8d5affe20b00/points/vectors \
> -X PUT \
> -H "Content-Type: application/json" \
> -d '{
    "points": [
        {
            "id": "e2f73d54-e7d6-4429-8e36-83812586bc4f",
            "vector": {
                "2d": [0.1, 0.2],
                "3d": [0.1, 0.2, 0.3]
            }
        }
    ]
}'
{"result":{"operation_id":3,"status":"acknowledged"},"status":"ok","time":0.000089613}
```

The above seems to suggest that the point has been updated with the named vectors, but if we tried to query the points none get returned:

```shell
$ curl localhost:6333/collections/741f28d2-e703-4f1d-807e-8d5affe20b00/points/scroll \
-X POST \
-H "Content-Type: application/json" \
-d'{
    "filter": {},
    "with_payload": true,
    "with_vector": true
}'
{"result":{"points":[{"id":"e2f73d54-e7d6-4429-8e36-83812586bc4f","payload":{},"vector":[0.1,0.2,0.3,0.4]}],"next_page_offset":null},"status":"ok","time":0.000708418}
```

Even when we try to literally query the point itself directly:
```shell
$ curl localhost:6333/collections/741f28d2-e703-4f1d-807e-8d5affe20b00/points/e2f73d54-e7d6-4429-8e36-83812586bc4f \
> -H "Content-Type: application/json"
{"result":{"id":"e2f73d54-e7d6-4429-8e36-83812586bc4f","payload":{},"vector":[0.1,0.2,0.3,0.4]},"status":"ok","time":0.000098061}
```

## Expected Behavior

I expect the named vectors to be returned when querying either the individual point or ALL points (with empty filter and vectors enabled)

## Possible Solution

I might be misunderstanding something in the docs or something is wrong with the docs. Either is possible.

## Context (Environment)

Trying to learn about qdrant so I'm adding named vectors to a point. Simple as that 😄 

## Detailed Description

Should be pretty clear from the description above - just copy paste the shell commands

## Possible Implementation

🤷‍♂️

**Comment by generall** [comment]
hi @milosgajdos! How do you create a collection? If you want to have named vectors, you should specify them on the collection creation step.

**Comment by milosgajdos** [comment]
I do a simple `PUT` into `/collections/{collection_name}` as per the docs:
* https://qdrant.tech/documentation/concepts/collections/#create-a-collection
* https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/get_collection

There doesn't seem be to be a way to specify named vectors. Am I overlooking anything?

**Comment by generall** [comment]
Probably this: https://qdrant.tech/documentation/concepts/collections/#collection-with-multiple-vectors ?

**Comment by generall** [comment]
@milosgajdos, please let us know if it solves your problem or it requires additional investigation.

**Comment by milosgajdos** [comment]
Will do. I will be looking into this tonight.

**Comment by milosgajdos** [comment]
Thanks @generall this worked like charm. I can't believe I've missed that. Maybe add a link to that section in here https://qdrant.tech/documentation/concepts/points/#update-vectors just to remind to the folks like myself to be careful 😄
