### ISSUE TITLE
Implement datetime support for the payload index

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3320]
**Is your feature request related to a problem? Please describe.**

Currently, if users wants to search for specific data / time range, it is required to convert dates into unix timestamps (or similar) and work with dates as integers. It might inconvenient and annoying to do.

**Describe the solution you'd like**

Create a special type of index, which could automatically parse dates and create appropriate index for them (it could be same integer index internally).
User should be able to filter requests using date as well (in the range queries).

For this to work properly, we would need to extend Range data structure with ability to specify dates.

In rest interface it should look like this:

```json
{
  "must": [
    {
      "key": "my-date",
      "range": {
          "lte": "2024-12-01"
       }
    }
  ]
}
```

**Describe alternatives you've considered**

Create a dedicated filtering condition for dates, but that might be confusing.

**Additional context**

We need to be extra careful with backward compatibility in gRPC interface. We can't simply change Range structure into enum. Most likely in gRPC the best option would be to create another type "RangeDates" and implement proper conversions on server side.

Additionally, it might make sense to do same in REST (but reuse the same key `range`), so that it would be impossible to use 
dates and numbers in a single range statement.

--- 

Note for contributors: Please consider this as tracking issue. If you think that it would be beneficial to split the task into multiple smaller PRs, please you are welcome to do so. Bounty will be rewarded for each PR independently

**Comment by xzfc** [comment]
Couldn't this use case be covered by providing a general-purpose index for strings instead? The lexicographical order of timestamps in a format like `2024-01-14 16:34:23` is the same as the chronological order, so range comparisons could be used for date strings as well.
Besides timestamps, this could be used for postal codes and so on.

**Comment by timvisee** [comment]
> Couldn't this use case be covered by providing a general-purpose index for strings instead? The lexicographical order of timestamps in a format like `2024-01-14 16:34:23` is the same as the chronological order, so range comparisons could be used for date strings as well.

Probably, or possibly even better, a timestamp in an integer index.

But a dedicated index would allow for further optimization (and parameterization) if possible and/or required.

**Comment by timvisee** [comment]
Implemented in <https://github.com/qdrant/qdrant/pull/3395>.

There are some follow-up issues, but these are handles separately:
- https://github.com/qdrant/qdrant/issues/3529
- https://github.com/qdrant/qdrant/issues/3531
