### ISSUE TITLE
Snapshot storage on S3

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3324]
**Is your feature request related to a problem? Please describe.**

Related issue: https://github.com/qdrant/qdrant/issues/1703

Currently qdrant can only store snapshots in local filesystem (even if it is a mounted s3 bucket), but it might be convenient to upload and download snapshots from S3 directly.

**Describe the solution you'd like**

Ability to configure snapshot directory as S3 bucket, specifying access credentials.
It should be possible to list snapshots saved on attached S3 bucket as well.

**Describe alternatives you've considered**

Our current recommendations are to mount s3 as local fs, but it might be non-trivial to do in some environments.

**Additional context**

Important qualities of the solution:

- Solution should not change default behavior and should be backward compatible
- Additional dependency to work with S3 should be have reasonable size, do not contribute significantly into qdrant compile time & binary size
- Should work with all types of S3-compatible storage, not only aws, but also google storage, minio, e.t.c.

---

Note for contributors: Please consider this as tracking issue. If you think that it would be beneficial to split the task into multiple smaller PRs, please you are welcome to do so. Bounty will be rewarded for each PR independently

**Comment by rajdip-b** [comment]
Won't take much time, would like to give it a shot in parallel! /attempt #3324

**Comment by rajdip-b** [comment]
@generall hey, I think we will have to make the updates in the grpc and rest implementations if im not wrong. My query is, how should I tell the API to use local/s3 snapshots? Some insights into the implementation would be really helpful!

**Comment by generall** [comment]
Hi @rajdip-b, no, this issue goesn't expect any API changes. S3 params should be configures with our standard configuration infra, and everything else is transparent for the user.

This issue is purely about storage backend for snapshots. Currently it assumes local finesystem and we need to make it work with s3

**Comment by rajdip-b** [comment]
Okay, so we just need to swap local storage with S3, correct?

**Comment by generall** [comment]
We need an ability to configure either local storage or S3.

**Comment by rajdip-b** [comment]
Alright, so where should this configuration exist?

**Comment by generall** [comment]
https://qdrant.tech/documentation/guides/configuration/

**Comment by generall** [comment]
FYI: this issue is not closed, merged PR was aimed to initial refactoring.

Bounty is still to be paid in full.

**Comment by gulshan-rs** [comment]
I guess it was done here https://github.com/qdrant/qdrant/pull/4150

**Comment by timvisee** [comment]
You'd be correct. Thanks for noting!

Here we elaborate on how to configure S3 storage: https://qdrant.tech/documentation/concepts/snapshots/#s3
