### ISSUE TITLE
API for checking collection exists

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3332]
**Is your feature request related to a problem? Please describe.**

Currently, there are 2 ways of checking if collection exists:

- list all collections and find name in the list
- query specific collection info and check if it is 404 or 200 response code

But in some clients if would be much more convenient to have a dedicated API which would return `true` or `false` without error http code.

**Describe the solution you'd like**

API `/collections/<collection-name>/check` and similar in gRPC

API should return `true` if collection exists and `false` if not (with all the usual result wrappers, of course)

**Describe alternatives you've considered**

Make more sophisticated and extendable API, which could return some additional information as well (but not as much as collection info)

Or make an API for batch request of collection info, so that you could specify multiple names and get results for all of them

**Additional context**

API should be consistent with our current set of endpoints

---

Note for contributors: Please consider this as tracking issue. If you think that it would be beneficial to split the task into multiple smaller PRs, please you are welcome to do so. Bounty will be rewarded for each PR independently

**Comment by timvisee** [comment]
To be fair, in true REST you should rely on 404 when requesting the object.

> API `/collections/<collection-name>/check` and similar in gRPC

What about `/exists`, or do you eventually want to extend this with more types of checks?
