### ISSUE TITLE
MUSL binary builds

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3334]
**Is your feature request related to a problem? Please describe.**

Currently qdrant CI builds binaries with `glibc` linked and other dynamically linked libraries, which create problems when running on the system with no correct version of those libraries installed.

But direct build into MUSL target is complicated, because some dependencies like `jemalloc` doesn't work with it.

**Describe the solution you'd like**

Create a special configuration for MUSL, which would disable incompatible updates (if possible) or somehow workaround the issue.

This special build should be included into CI step along with current binary builds.

MUSL version should not affect the default version and only disable features if related build target is used.

Provide MUSL builds for both x86_64 and Arm64 arches.

**Additional context**

Pay extra attention to dependencies like RocksDB and jemalloc.

Here is a related attempt to fix the same issue with additional context: https://github.com/qdrant/qdrant/issues/2656

In order to accept the solution we would need to have a link of a successful CI run in the fork and examples of packages to test

---

Note for contributors: Please consider this as tracking issue. If you think that it would be beneficial to split the task into multiple smaller PRs, please you are welcome to do so. Bounty will be rewarded for each PR independently

**Comment by PranayB003** [comment]
Would like to try this in parallel: /claim #3334

**Comment by timvisee** [comment]
Implemented in <https://github.com/qdrant/qdrant/pull/3342>.
