### ISSUE TITLE
Provide DEB package with release

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3335]
**Is your feature request related to a problem? Please describe.**

Currently qdrant distributed in Docker and binary versions, but for some env, there are more convenient ways of how to deploy the service. Debian package is one of them

**Describe the solution you'd like**

Implement a CI step, along with the current steps which build binary files, which would create a debian `*.deb` package with all required dependencies.

Debian package should be attached to the release by CI task in a similar way as it happens with binary files.

**Describe alternatives you've considered**

Other types of packages might be introduced by separate issues.

**Additional context**

Make sure that debian package specifies all required dependencies, like glibc and so on. Package should be possible to install and run on variety of debian-based OS

---

Note for contributors: Please consider this as tracking issue. If you think that it would be beneficial to split the task into multiple smaller PRs, please you are welcome to do so. Bounty will be rewarded for each PR independently

**Comment by generall** [comment]
In order to accept the solution we would need to have a link of a successful CI run in the fork and examples of packages to test

**Comment by timvisee** [comment]
Implemented in <https://github.com/qdrant/qdrant/pull/3344>.
