### ISSUE TITLE
Collection payload

### ISSUE THREAD

**Issue by lpi-tn** [qdrant/qdrant#3379]
**Is your feature request related to a problem? Please describe.**
We need to create separate data treatments according to their source collection.
We currently use the name of the collections with the information inside, but this makes the application code more complex and is very inflexible.

**Describe the solution you'd like**
What would be really useful would be to be able to push a JSON via the API, enabling the collection information to be stored.
This way, when the collection is created, it would be possible to enter information about it (for example, the model used for vectorisation) and then it would be possible to read it via a simple GET call to a dedicated endpoint.

**Comment by generall** [comment]
Discussed https://github.com/qdrant/qdrant/issues/3379
