### ISSUE TITLE
Sort query result

### ISSUE THREAD

**Issue by xtyDoge** [qdrant/qdrant#3391]
Can I sort my query result by one of field in payload?

**Comment by timvisee** [comment]
No, by design a vector search orders by similarity score.

But we are working on implementing 'order_by' for the [scroll](https://qdrant.tech/documentation/concepts/points/#scroll-points) API: https://github.com/qdrant/qdrant/issues/1763

**Comment by generall** [comment]
Released in 1.8

**Comment by haschu** [comment]
@generall What about searching for a batch of similar objects using a `score_threshold` (maybe in combination with `limit`), and then sorting the batch by a payload value? 🙂

For example searching for similar real estates by some user input, cutting off results by `score_threshold` and then sort by price.
