### ISSUE TITLE
Please update the ring crate to 17.x

### ISSUE THREAD

**Issue by yurivict** [qdrant/qdrant#3392]
This is needed to prevent failures like [this](https://github.com/briansmith/ring/issues/1904).

**Comment by timvisee** [comment]
This will require `actix-tls` in [actix/actix-net](https://github.com/actix/actix-net) to be updated.

Part of the dependency tree, where `actix-tls` is already at its latest version:

```
actix-http v3.5.1
├── actix-tls v3.1.1
│   ├── rustls v0.21.10
│   │   ├── ring v0.17.5
│   │   ├── rustls-webpki v0.101.7
│   │   │   ├── ring v0.17.5 (*)
│   │   └── sct v0.7.0
│   │       ├── ring v0.16.20
```

**Comment by yurivict** [comment]
I asked them  to update ring: https://github.com/actix/actix-net/issues/519

Thanks!
