### ISSUE TITLE
qdrant disk read io high

### ISSUE THREAD

**Issue by UchihaArk** [qdrant/qdrant#3405]
## Current Behavior
There will be a period of time every few hours where the disk read is very high. This will affect the queries at the same time. Is there any mechanism for reading disk data? How to avoid this problem?

**Comment by timvisee** [comment]
This could be indexing, which is a regular optimization process.

While a lot of disk reads are happening, is the collection status yellow? You can see this at `GET /collections/my_collection`.

In `GET /telemetry?details_level=3` you'll find a optimization log in each shard. It'll show you more details with a history of optimizations and their timestamps.

**Comment by UchihaArk** [comment]
> This could be indexing, which is a regular optimization process.
> 
> While a lot of disk reads are happening, is the collection status yellow? You can see this at `GET /collections/my_collection`.
> 
> In `GET /telemetry?details_level=3` you'll find a optimization log in each shard. It'll show you more details with a history of optimizations and their timestamps.

current status is green, I'll track the collection status
```
{
	"result": {
		"status": "green",
		"optimizer_status": "ok",
		"vectors_count": 593202,
		"indexed_vectors_count": 589500,
		"points_count": 593202,
		"segments_count": 2,
		"config": {
			"params": {
				"vectors": {
					"size": 512,
					"distance": "Cosine",
					"on_disk": true
				},
				"shard_number": 1,
				"replication_factor": 1,
				"write_consistency_factor": 1,
				"on_disk_payload": true
			},
			"hnsw_config": {
				"m": 16,
				"ef_construct": 100,
				"full_scan_threshold": 10000,
				"max_indexing_threads": 0,
				"on_disk": false
			},
			"optimizer_config": {
				"deleted_threshold": 0.2,
				"vacuum_min_vector_number": 1000,
				"default_segment_number": 2,
				"max_segment_size": null,
				"memmap_threshold": null,
				"indexing_threshold": 20000,
				"flush_interval_sec": 5,
				"max_optimization_threads": 1
			},
			"wal_config": {
				"wal_capacity_mb": 32,
				"wal_segments_ahead": 0
			},
			"quantization_config": null
		},
		"payload_schema": {
			"p_id": {
				"data_type": "integer",
				"points": 0
			},
			"content": {
				"data_type": "text",
				"points": 593202
			}
		}
	},
	"status": "ok",
	"time": 0.001177255
}
```

**Comment by timvisee** [comment]
You might already be aware, but I didn't mention this above: When the status is yellow, an optimization is running. When it is green, no optimizations are running. ([docs](https://qdrant.tech/documentation/concepts/collections/#collection-info))

**Comment by UchihaArk** [comment]
> You might already be aware, but I didn't mention this above: When the status is yellow, an optimization is running. When it is green, no optimizations are running. ([docs](https://qdrant.tech/documentation/concepts/collections/#collection-info))

this is ```GET /telemetry?details_level=3``` info, When the optimizations are running, io high is normal, but he search speed will be affected. How can I adjust the config to reduce the frequency of optimizer execution, as the writing of this collection is not frequent
```
{
					"id": "PolicyV3",
					"init_time_ms": 63899,
					"config": {
						"params": {
							"vectors": {
								"size": 512,
								"distance": "Cosine",
								"on_disk": true
							},
							"shard_number": 1,
							"replication_factor": 1,
							"write_consistency_factor": 1,
							"on_disk_payload": true
						},
						"hnsw_config": {
							"m": 16,
							"ef_construct": 100,
							"full_scan_threshold": 10000,
							"max_indexing_threads": 0,
							"on_disk": false
						},
						"optimizer_config": {
							"deleted_threshold": 0.2,
							"vacuum_min_vector_number": 1000,
							"default_segment_number": 2,
							"max_segment_size": null,
							"memmap_threshold": null,
							"indexing_threshold": 20000,
							"flush_interval_sec": 5,
							"max_optimization_threads": 1
						},
						"wal_config": {
							"wal_capacity_mb": 32,
							"wal_segments_ahead": 0
						},
						"quantization_config": null
					},
					"shards": [
						{
							"id": 0,
							"local": {
								"variant_name": "local shard",
								"segments": [
									{
										"info": {
											"segment_type": "plain",
											"num_vectors": 3702,
											"num_points": 3702,
											"num_deleted_vectors": 0,
											"ram_usage_bytes": 0,
											"disk_usage_bytes": 0,
											"is_appendable": true,
											"index_schema": {
												"content": {
													"data_type": "text",
													"points": 3702
												},
												"p_id": {
													"data_type": "integer",
													"points": 0
												}
											}
										},
										"config": {
											"vector_data": {
												"": {
													"size": 512,
													"distance": "Cosine",
													"storage_type": "ChunkedMmap",
													"index": {
														"type": "plain",
														"options": {}
													},
													"quantization_config": null
												}
											},
											"payload_storage_type": {
												"type": "on_disk"
											}
										},
										"vector_index_searches": [
											{
												"index_name": "",
												"unfiltered_plain": {
													"count": 134863,
													"avg_duration_micros": 846.9492,
													"min_duration_micros": 315,
													"max_duration_micros": 1816191,
													"last_responded": "2024-01-16T09:55:08.830Z"
												},
												"filtered_plain": {
													"count": 1117,
													"avg_duration_micros": 21.44538,
													"min_duration_micros": 2,
													"max_duration_micros": 12992,
													"last_responded": "2024-01-16T09:55:09.300Z"
												}
											}
										],
										"payload_field_indices": [
											{
												"field_name": "p_id",
												"points_values_count": 0,
												"points_count": 0
											},
											{
												"field_name": "p_id",
												"points_values_count": 0,
												"points_count": 0,
												"histogram_bucket_size": 10
											},
											{
												"field_name": "content",
												"points_values_count": 3702,
												"points_count": 3702
											}
										]
									},
									{
										"info": {
											"segment_type": "indexed",
											"num_vectors": 589500,
											"num_points": 589500,
											"num_deleted_vectors": 1314,
											"ram_usage_bytes": 0,
											"disk_usage_bytes": 0,
											"is_appendable": false,
											"index_schema": {
												"p_id": {
													"data_type": "integer",
													"points": 0
												},
												"content": {
													"data_type": "text",
													"points": 589500
												}
											}
										},
										"config": {
											"vector_data": {
												"": {
													"size": 512,
													"distance": "Cosine",
													"storage_type": "ChunkedMmap",
													"index": {
														"type": "hnsw",
														"options": {
															"m": 16,
															"ef_construct": 100,
															"full_scan_threshold": 10000,
															"max_indexing_threads": 0,
															"on_disk": false
														}
													},
													"quantization_config": null
												}
											},
											"payload_storage_type": {
												"type": "on_disk"
											}
										},
										"vector_index_searches": [
											{
												"index_name": "",
												"filtered_small_cardinality": {
													"count": 837,
													"avg_duration_micros": 9.913364,
													"min_duration_micros": 2,
													"max_duration_micros": 51460,
													"last_responded": "2024-01-16T09:38:30.660Z"
												},
												"filtered_exact": {
													"count": 280,
													"avg_duration_micros": 73.840416,
													"min_duration_micros": 42,
													"max_duration_micros": 60287,
													"last_responded": "2024-01-16T09:55:09.300Z"
												},
												"unfiltered_exact": {
													"count": 134863,
													"avg_duration_micros": 120373.305,
													"min_duration_micros": 105901,
													"max_duration_micros": 118682890,
													"last_responded": "2024-01-16T09:55:08.950Z"
												}
											}
										],
										"payload_field_indices": [
											{
												"field_name": "p_id",
												"points_values_count": 0,
												"points_count": 0
											},
											{
												"field_name": "p_id",
												"points_values_count": 0,
												"points_count": 0,
												"histogram_bucket_size": 10
											},
											{
												"field_name": "content",
												"points_values_count": 589500,
												"points_count": 589500
											}
										]
									}
								],
								"optimizations": {
									"status": "ok",
									"optimizations": {
										"count": 62,
										"avg_duration_micros": 187690820,
										"min_duration_micros": 1593457,
										"max_duration_micros": 696411460,
										"last_responded": "2024-01-05T13:42:15.420Z"
									}
								}
							},
							"remote": [],
							"replicate_states": {
								"1538978957481381": "Active"
							}
						}
					],
					"transfers": []
				}
```

**Comment by timvisee** [comment]
First of all, I mentioned a log of optimizations, but it's not included in your snippet. You might be running an older version. It's probably worth to upgrade to our latest version to get this, and many other improvements.

You can tweak optimization parameters to tune optimizations. But it looks like you're using the default, which is a good thing.

I recommend to invest in a better performing disk (if possible) to mitigate this, and leave optimizations as-is. That would likely result in the best overall performance.

If you don't want to do this and want to tune optimizations anyway, there are some things you can change. Take a look at the optimizer configuration here:

```
"optimizer_config": {
	"deleted_threshold": 0.2,
	"vacuum_min_vector_number": 1000,
	"default_segment_number": 2,
	"max_segment_size": null,
	"memmap_threshold": null,
	"indexing_threshold": 20000,
	"flush_interval_sec": 5,
	"max_optimization_threads": 1
},
```

Increase the desired number of segments by upping `default_segment_number`. You could increase `indexing_threshold` to do less indexing. You could increase `deleted_threshold` a bit to do less segment rebuilding if lots of points are deleted.

Could you elaborate on what your usage is like? You mention writing is not frequent, but could you put this in numbers? Are you updating existing vectors a lot? Are you doing a bunch of deletes? Or are there no updates (insert/update/delete) at all?

Also, could you elaborate what your hardware looks like? What CPU, memory and disk do you have? Are you using our Cloud offering?

**Comment by UchihaArk** [comment]
> 
> Could you elaborate on what your usage is like? You mention writing is not frequent, but could you put this in numbers? Are you updating existing vectors a lot? Are you doing a bunch of deletes? Or are there no updates (insert/update/delete) at all?
> 
> Also, could you elaborate what your hardware looks like? What CPU, memory and disk do you have? Are you using our Cloud offering?

ok, no deleting points operate, the upsert is done once a day, and the data volume is about 10k each time. The cloud is not used. I am using an aliyun instance, 4-core 16G memory, the hard disk is HDD, and the CPU is Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50 GHz

**Comment by timvisee** [comment]
> no deleting points operate

Sorry but I'm a bit confused with what you mean by this. Do you mean you don't delete points at all?

> the upsert is done once a day

Right! In that case optimizers should only trigger once a day, after the contents have changed.

Note that upserting points on IDs that already exists counts as deleting the old one and inserting the updated one as new point.

> the hard disk is HDD

For vector search we highly recommend to use at least an SSD, preferrably an NVMe SSD. That may be the culprit here. It is listed [here](https://qdrant.tech/documentation/guides/installation/#storage).

**Comment by UchihaArk** [comment]
Thank you for your help
