### ISSUE TITLE
Update collection in qdrant-langchain

### ISSUE THREAD

**Issue by happynls** [qdrant/qdrant#3406]
from langchain.vectorstores import Qdrant
from langchain.embeddings import HuggingFaceBgeEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import PyPDFLoader

loader = PyPDFLoader("gpt.pdf")
documents = loader.load()
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500,
                                                   chunk_overlap=50)
texts = text_splitter.split_documents(documents)

model_name = "BAAI/bge-large-en"
model_kwargs = {'device': 'cpu'}
encode_kwargs = {'normalize_embeddings': False}
embeddings = HuggingFaceBgeEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)

url = "http://localhost:6333"
qdrant = Qdrant.from_documents(
    texts,
    embeddings,
    url=url,
    prefer_grpc=False,
    collection_name="vector_db_2",
)

print("Vector DB Successfully Created!")
Output :
![Screenshot_4](https://github.com/qdrant/qdrant/assets/155633884/6d0b58c5-7ef2-4803-98c0-0f7645f266ee)

I have added vectors to my collection with this code. Now, I want to implement an update functionality for individual words in my collection. The condition is that only the vectors corresponding to the changed word should be updated, while the vectors for other words remain unchanged.
I used docker.
I tried many methods but couldn't solve this , please help me..

_Originally posted by @happynls in https://github.com/qdrant/qdrant/issues/1444#issuecomment-1893298554_

**Comment by KShivendu** [comment]
> Now, I want to implement an update functionality for individual words in my collection

One approach is to use our scroll API to find all the points (their ids) with your updated word "X" in `page_content` payload field. Once you have the point ids, you can update only those vectors. You should also use create a [full-text index](https://qdrant.tech/documentation/concepts/filtering/#full-text-match) on `page_content` to speed up finding these words if you have lots of vectors.

However, afaik Langchain's `RecursiveCharacterTextSplitter` is not very stable if the content changes. So you need a more stable splitting logic like one on a paragraph level. But that could slightly lower the accuracy depending on your LLM.

**Comment by timvisee** [comment]
Hi @happynls. This question is not related to Qdrant, but rather to LangChain. I'd recommend to look for solutions there.

**Comment by KShivendu** [comment]
Closing this for now. Feel free to ask us if you're facing any issues with Qdrant. We also have an active [discord server](https://qdrant.to/discord) :)

**Comment by happynls** [comment]
So i have to assign ids for individual word?
Sorry to interrupt you all but i am new in this topic.
