### ISSUE TITLE
Remove `method` from abort shard transfer operation

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3409]
![image](https://github.com/qdrant/qdrant/assets/1935623/4a058bb7-6769-44e5-acaa-cd7fcc80c473)

It looks like we reuse the same data structure, we should create a dedicated one

**Comment by ashiskumarnaik** [comment]
Hi I'm interested in working on this issue, removing the method and 
- Design and implement a dedicated data structure for the shard transfer abort operation.
If there are specific considerations or additional information I should be aware of, please let me know.

**Comment by Pegasis404** [comment]
Please let me know if my approach is correct or not, but we need to duplicate the data structure MoveShard, without "method" for abort shard transfer operation?
