### ISSUE TITLE
Scroll all points with no limit

### ISSUE THREAD

**Issue by zain-at-edensolutions** [qdrant/qdrant#3412]
**Is your feature request related to a problem? Please describe.**
I am trying to scroll **all** points that satisfy filter conditions, If I do not specify a limit it defaults to 10. I don't want to specify any limit and get all the points.

**Describe the solution you'd like**
Would be better if we can pass something like `limit: -1` to tell the endpoint to scroll all the points

**Describe alternatives you've considered**
Currently I am first getting the count and then setting the limit based on the count values. The problem with this approach is this force me to make 2 calls.

**Comment by timvisee** [comment]
This call can be extremely expensive with huge data sets, which is why it has a lot default limit. It is intended to use with some form of pagination/chunking.

To achieve what you describe above, you can set a limit that is much larger than what you like to receive. For example, [`u32::MAX`](https://doc.rust-lang.org/std/primitive.u32.html#associatedconstant.MAX):

```
POST /collections/{collection_name}/points/scroll
{
    "filter": {
        "must": [
            {
                "key": "color",
                "match": {
                    "value": "red"
                }
            }
        ]
    },
    "limit": 4294967295,
    "with_payload": true,
    "with_vector": false
}
```

**Comment by DXist** [comment]
Maybe an alternative feature to process all points is to support user defined functions or custom database extensions - this will allow to collocate computations with data.

**Comment by timvisee** [comment]
> Maybe an alternative feature to process all points is to support user defined functions or custom database extensions - this will allow to collocate computations with data.

We don't have any plans for this. This is very hard to achieve and will require significant work to have any significant gain.

Assuming the above issue is fixed, I'm closing this now.
