### ISSUE TITLE
Add last_seen to message_send_failures in cluster status info

### ISSUE THREAD

**Issue by bashofmann** [qdrant/qdrant#3417]
**Is your feature request related to a problem? Please describe.**
The `message_send_failures` in the cluster status info endpoint `/cluster` currently contains information about the error message `latest_error` and the error `count`. 
For easier debugging, the time when this error last occurred should be displayed. This allows to see if a specific error is an old, or a current one.

**Describe the solution you'd like**
Add a `last_seen` (or `last_timestamp` or similar) field to https://github.com/qdrant/qdrant/blob/master/lib/storage/src/types.rs#L159 with a human readable timestamp when this error has been last seen.

**Comment by melsonic** [comment]
> /attempt #3417
> can i get assigned?

**Comment by melsonic** [comment]
can I get assigned?

**Comment by generall** [comment]
hey @melsonic, we prefer to not assign external collaborators to issue, but you are still welcome to make your attempt

**Comment by melsonic** [comment]
hey @generall, is there any discord or slack community channel?

**Comment by timvisee** [comment]
> hey @generall, is there any discord or slack community channel?

Yes, please visit our Discord channel over at: https://qdrant.to/discord

**Comment by xzfc** [comment]
In which scenario `latest_error` would not be a recent error?

I did a quick test: temporarily stopped the follower node (using `SIGSTOP` signal), waited until `latest_error` in `message_send_failures` appeared, and enabled the follower node again. As a result, the entry in `message_send_failures` disappeared. This corresponds to the comment:
https://github.com/qdrant/qdrant/blob/c6a351c82d57eb786b75dac785de7b085c6f80ff/lib/storage/src/types.rs#L175-L177

If nodes ping each other every 100ms (the default value of `tick_period_ms`), and the entry is removed on successful ping, does that mean that `last_seen` never be older than 100ms?

**Comment by generall** [comment]
> If nodes ping each other every 100ms (the default value of tick_period_ms), and the entry is removed on successful ping, does that mean that last_seen never be older than 100ms?

Only leader-to-follower happens every 100ms, but communication between other peers might be old

**Comment by timvisee** [comment]
Fixed in <https://github.com/qdrant/qdrant/pull/3418>.
