### ISSUE TITLE
Report shard transfer progress

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#3433]
**Is your feature request related to a problem? Please describe.**
As an operator I have no idea if shard transfers are making good progress and when they will be done.

**Describe the solution you'd like**
I want to have:
- the progress of on-going shard transfers in percentage  
- an estimated time of completion assuming constant speed

**Describe alternatives you've considered**
Either print the progress in the logs every minute or even better output it in the shard transfers section of the cluster information.

**Comment by ima-attac-helikoptaaa** [comment]
Hey @agourlay. If no one is working currently on this, can I take a stab at it?

**Comment by agourlay** [comment]
@ima-attac-helikoptaaa Thank you for your interest but someone is already working for this internally.
Sorry for not tagging the issue properly.

Maybe you will find another task to tackle!

**Comment by xzfc** [comment]
Added in v1.8.0.
https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/collection_cluster_info
Check `.result.shard_transfers[].comment`.

**Comment by timvisee** [comment]
Hi @mdnfiras. It is only shown on the peer that is the source of the transfer, so that would be on peer `259608753608965`.
