### ISSUE TITLE
Using NAS device for Qdrant Storage

### ISSUE THREAD

**Issue by hturner08** [qdrant/qdrant#3442]
I've been running qdrant locally no issue on my M2 Mac when I use my local file system but I've been trying to set the qdrant storage folder path to my NAS and run into errors like the following:

qdrant: 2024-01-22T18:29:36.420972Z ERROR qdrant::tonic::logging: gRPC /qdrant.Collections/Create unexpectedly failed with Internal error "Service internal error: RocksDB open error: IO error: While lock file: /Volumes/Public/vector_db/storage/collections/QDRANT_DEFAULT_COLLECTION/0/segments/8504c83e-3595-48dd-83ba-cd1705b5341e/LOCK: Operation not supported" 0.211594 
Error 2:

Is this some sort of permissions issue?

**Comment by generall** [comment]
what kind of file system are you using?

**Comment by joein** [comment]
I believe the discussion has been proceeded in discord

https://discord.com/channels/907569970500743200/1199060425027891330

**Comment by bikeshedder** [comment]
This is not a problem of the EXT4 filesystem of your NAS but the network filesystem you are using.

SMB file locking is quite limited in comparison to NFS. Simply switching to NFS should do the trick.

If you happen to run into the same troubles with NFS you could try enabling local locks. See https://www.unix.com/man-page/osx/8/mount_nfs/

> :warning: **Local locks means that all filesystem locking only happens on the NFS client machine. e.g. if you were to start another Qdrant instance on a different machine accessing the same folder they would not know each other and you will almost instantly end up with destroyed database files. A single launch of a second instance could be enough to trash all your data.**
> 
> When adding this flag _ALL_ your future NFS mounts will use locallocks. This might not be what you want/expect. So use this option with care. A better way would be to pass this option at mount time and not make it the default.

There might even be a way to enable local logs for SMB mounts if you really can't use NFS.

**Comment by timvisee** [comment]
That makes a lot of sense. I assume the above comment resolves your issue. If not, feel free to open this again.

Thanks @bikeshedder!
