### ISSUE TITLE
Best way to contribute? Can anyone help with step by step?

### ISSUE THREAD

**Issue by tiagodavi** [qdrant/qdrant#3444]
I would like to contribute and start reading the `Contributing.md` file. Those were my steps:

1 - Forked the project 
2 - Cloned the forked project
3 - Fetched the dev branch
4 - Created my own branch from dev
5 - cargo build /cargo run 

`Access web UI at http://localhost:6333/dashboard` It does not work..

```
This localhost page can’t be foundNo webpage was found for the web address: http://localhost:6333/dashboard
HTTP ERROR 404 
```

I tried to use this tutorial:
https://github.com/qdrant/qdrant/blob/master/docs/DEVELOPMENT.md#api-changes

![Screenshot 2024-01-22 at 18 46 51](https://github.com/qdrant/qdrant/assets/1058350/90d3fc28-c93a-45b0-8ddd-9596f0188f8d)

What Am I missing here?

**Comment by generall** [comment]
web-ui is a separate project, if you want to use with dev build, you would need to run this script to install it: https://github.com/qdrant/qdrant/blob/master/tools/sync-web-ui.sh

**Comment by tiagodavi** [comment]
Thank you, I was about to talk about it.. I've figured it out by looking on how the project runs on Docker.

<img width="1441" alt="Screenshot 2024-01-23 at 15 17 34" src="https://github.com/qdrant/qdrant/assets/1058350/0884f2c9-bc58-4eab-a6e7-76c7cf00ef0c">
