### ISSUE TITLE
chore: Inheriting a dependency from a workspace

### ISSUE THREAD

**Issue by ben1009** [qdrant/qdrant#3453]
**Is your feature request related to a problem? Please describe.**
since we have introduced [wrokspace](https://github.com/qdrant/qdrant/blob/master/Cargo.toml#L131)  in cargo.toml, should inheriting the dependency in the members instead.

**Describe the solution you'd like**
FYI https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

**Comment by timvisee** [comment]
Thank you for the suggestion!

We've actually partially done this now in <https://github.com/qdrant/qdrant/pull/3490>.
