### ISSUE TITLE
Iterate records

### ISSUE THREAD

**Issue by aseifert** [qdrant/qdrant#35]
**Is your feature request related to a problem? Please describe.**

I want to test the performance of different encoders. To this end, I would like to create a collection containing payloads of a number of documents and then create different collections holding vectors created by different encoders. My life would be easier if there was a way to iterate all available records.

**Describe the solution you'd like**

Something like `collection.keys()`

I'm not too familiar with RocksDB, but I know that it provides a way to get all keys, see for example https://python-rocksdb.readthedocs.io/en/latest/tutorial/#iteration

**Comment by generall** [comment]
Hi @aseifert , scroll API added in the latest version v0.3.4 https://qdrant.github.io/qdrant/redoc/index.html#operation/scroll_points
