### ISSUE TITLE
[gRPC] Enable gRPC compilation, make switch in configuration 

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#350]
Add possibility to optionally enable gRPC without re-compilation through the configuration file

**Comment by agourlay** [comment]
Taking this one.

This means:
- removing the `gRPC` build feature
- introduce new configuration in the `ServiceConfig` to toggle `gRPC` (false by default)
- start `tonic` service based on new config flag
- update dev docs and Github actions
