### ISSUE TITLE
Avoid `unique` usage in geo filed index

### ISSUE THREAD

**Issue by IvanPleshkov** [qdrant/qdrant#3503]
We use `unique` iterator for geo index here:
https://github.com/qdrant/qdrant/blob/master/lib/segment/src/index/field_index/geo_index.rs#L538
It's expensive because it builds hashmap inside. I strongly believe we can avoid this `unique` and implement more effective iteration over geo index.

**Comment by IvanPleshkov** [comment]
Close this task. `unique` is fine here because it merges inside the point indices for each requested geo index. There may be intersections which we cannot predict or avoid in easy way

**Comment by timvisee** [comment]
Thank you for looking into it!
