### ISSUE TITLE
Can't report operation in log

### ISSUE THREAD

**Issue by xiaoxixxxx** [qdrant/qdrant#3507]
## Current Behavior

2024-02-01T06:59:36.213350677Z 2024-02-01T06:59:36.213253Z  INFO collection::update_handler: Can't report operation 23429 result. Assume already not required

## Detailed Description

Hey, I saw this error in qdrant logs.
what does it mean？

**Comment by agourlay** [comment]
This is not an error :)

If you look carefully you will see that the level of the log is `INFO`.

This log most likely mean that an update operation has been executed but the client that issued the operation has closed the connection.

**Comment by generall** [comment]
Should we demote it to debug level?

**Comment by agourlay** [comment]
Good idea :+1: 

Here it is https://github.com/qdrant/qdrant/pull/3523
