### ISSUE TITLE
AttributeError: 'ScoredPoint' object has no attribute 'collection_name'

### ISSUE THREAD

**Issue by AbrahimZaman360** [qdrant/qdrant#3517]
## Steps to Reproduce

1. langchain == 1.0.5
2. langchain-community == 0.0.17
3. relevant_docs = doc_store.similarity_search(question)

## Expected Behavior

it shouldn't give this error/warning

**Comment by joein** [comment]
Hi @AbrahimZaman360 

it’s actually not Qdrant bug, but langchain’s 

there is a PR in langchain to address it https://github.com/langchain-ai/langchain/pull/16920

**Comment by Anush008** [comment]
The patch is merged and this should be resolved in `v0.1.6` of Langchain.

**Comment by shaurya-nwse** [comment]
Hi @Anush008 That's great news. We're running into the same issue. Any idea on the timeline when `v0.1.6` would be published ? Thanks.

**Comment by Anush008** [comment]
> Hi @Anush008 That's great news. We're running into the same issue. Any idea on the timeline when `v0.1.6` would be published ? Thanks.

I am assuming in a day or two.
In the meantime, you can use Langchain `v0.1.4` to resolve this.

**Comment by AbrahimZaman360** [comment]
You can check the changes and apply them in Langchain source code directly

Ibrahim Zaman aka Mr Tux

**Comment by Anush008** [comment]
Resolved with https://github.com/langchain-ai/langchain/releases/tag/v0.1.6
