### ISSUE TITLE
Support JsonPath in update payload commands

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#3524]
**Is your feature request related to a problem? Please describe.**

There are currently two ways to update point's payload:
- [set_payload](https://qdrant.tech/documentation/concepts/payload/#set-payload) to change only the value of a top level key
- [overwrite_payload](https://qdrant.tech/documentation/concepts/payload/#overwrite-payload) replace all values under a top level key

Given the payload:

```json
 "my_property": {
    "a": "a",
    "b": "b"
  }
```

I would like to add a nested key so that I get the following payload:

```json
"my_property": {
    "a": "a",
    "b": "b",
    "c": "c"
  }
```

Currently it is necessary to perform two calls:
- delete `my_property`
- set fully `my_property`

**Describe the solution you'd like**

Perform the update in a single call by making the payload update API aware of nested key using JsonPath.

```json
{
    "key": "my_property",
    "payload": {
        "c": "c",
    },
    "points": [ 1 ]
}
```

For example, this should work as well to modify deeper objects:

```json
{
    "key": "some.deep.object",
    "payload": {
        "c": "c",
    },
    "points": [ 1 ]
}
```

**Additional context**

It should follow the JsonPath convention and infrastructure introduced when we [allowed JsonPath for PayloadSelector](https://github.com/qdrant/qdrant/pull/2756)

**Comment by agourlay** [comment]
@Shylock-Hg Thanks I fixed it :)

**Comment by agourlay** [comment]
shipped in https://github.com/qdrant/qdrant/releases/tag/v1.8.0

**Comment by lambda-science** [comment]
> shipped in https://github.com/qdrant/qdrant/releases/tag/v1.8.0

Hey @agourlay I wanted to use this feature you implemented but it doesn't seem's to work as I would expect. Could you point me what's the issue ? https://github.com/qdrant/qdrant-client/issues/780
