### ISSUE TITLE
Extend datetime formats in REST API

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant#3529]
**Is your feature request related to a problem? Please describe.**
We recently merged <https://github.com/qdrant/qdrant/pull/3395> which adds a datetime payload index.

Currently, the datetime parser is very strict, only allowing [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339) formats in our REST API. A common format such as `YYYY-MM-DD HH:MM:SS` is currently not accepted.

**Describe the solution you'd like**
We'd like to extend datetime parsing a bit, to accept a bit more predefined formats.

More specifically, we want to support these in our REST API:
- [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339) (already supported)
- `YYYY-MM-DD'T'HH:MM:SS` (without timezone or `Z`)
- `YYYY-MM-DD HH:MM:SS`
- `YYYY-MM-DD HH:MM`
- `YYYY-MM-DD`

The above list is open for discussion. But as general rule, we want to prevent ambiguity.

There's probably two bits to implement this:
- Accept these formats in the datetime index
- Accept these formats in the `datetime_range` filter

**Describe alternatives you've considered**
- Do not support extra formats  
  We decided to not take this route in an attempt to make the API more lenient.
- Support all [formats in ElasticSearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#built-in-date-formats)
  There's a lot of formats, some ambiguous and uncommon, so we decided not to include any others for now.
- Support custom formats:  
  We do not want to implement this right now because it makes the whole API a lot more complex. Maybe in the future.

**Additional context**
The following query must succeed after implementing the above formats. Currently it fails because the format is not accepted.

```json
POST collections/test_collection/points/scroll
{
  "limit": 10,
  "filter": {
    "must": [
      {
        "key": "updated",
        "datetime_range": {
          "gt": "2014-01-01T00:00:00"
        }
      }
    ]
  }
}
```

Related issue: <https://github.com/qdrant/qdrant/issues/3531>

**Comment by Okabe-Rintarou-0** [comment]
I think i can do this, plz assign it to me.

**Comment by timvisee** [comment]
> I think i can do this, plz assign it to me.

We don't assign issues to people specifically, but please feel free to give it a shot.

**Comment by timvisee** [comment]
This has been implemented by <https://github.com/qdrant/qdrant/pull/3549>.
