### ISSUE TITLE
Reduce snapshot size

### ISSUE THREAD

**Issue by metal-dev-spd** [qdrant/qdrant#3577]
Hi,
In my team we currently use qdrant v.1.7.2, but since minor versions we are "shocked" about the dimension of generated snapshots.
It's not possible to think a way to reduce them? In case of collections with a long history of operations but with very small vector size, we have to store very huge size snapshot, and this can be a problem. 

Also, is there a tool to explore the files inside a .snapshot file?

Thanks a lot

**Comment by timvisee** [comment]
> It's not possible to think a way to reduce them? In case of collections with a long history of operations but with very small vector size, we have to store very huge size snapshot, and this can be a problem.

A snapshot should only contain the current state of a collection, along with ~32 megabytes of history per shard. So, this should not grow forever.

Could you maybe define some numbers here?

- How many collections do you have?
- How many shards do your have?
- How big are your snapshots?

**Comment by metal-dev-spd** [comment]
For example, a take a snapshot of a collection with 
- 3 shards, 
- 3 vectors_count
- 1 points_count 

and I obtain a file of 67.6 MB.

This is the configuration of my collection:

{
  "params": {
    "vectors": {
      "size": 3,
      "distance": "Cosine"
    },
    "shard_number": 3,
    "replication_factor": 1,
    "write_consistency_factor": 1,
    "on_disk_payload": true
  },
  "hnsw_config": {
    "m": 16,
    "ef_construct": 100,
    "full_scan_threshold": 10000,
    "max_indexing_threads": 0,
    "on_disk": false
  },
  "optimizer_config": {
    "deleted_threshold": 0.2,
    "vacuum_min_vector_number": 1000,
    "default_segment_number": 0,
    "max_segment_size": null,
    "memmap_threshold": null,
    "indexing_threshold": 20000,
    "flush_interval_sec": 5,
    "max_optimization_threads": 1
  },
  "wal_config": {
    "wal_capacity_mb": 32,
    "wal_segments_ahead": 0
  },
  "quantization_config": null
}

**Comment by timvisee** [comment]
A file of 67.6 MB sounds very reasonable for that configuration. Even if you'd do a billion more operations, without adding much more new points, it will not grow much bigger than that. Would it be fine in that case?

**Comment by metal-dev-spd** [comment]
There's a way to reduce the wal capacity file for an existing collection and preserve data?

Thank you

**Comment by metal-dev-spd** [comment]
Thank for your support for now, but i think i will no able to reduce number of collection or avoid increasing the number of new points in my existing collections due to functional context.

**Comment by generall** [comment]
Maybe just to be on the safe side, I will leave it here: https://qdrant.tech/documentation/guides/multiple-partitions/

**Comment by generall** [comment]
going to close this issue. Feel free to re-open it is there is any additional context
