### ISSUE TITLE
Overwrite/set payload changes to a point wont reflect in filter/scroll queries if the key contains a period or dot

### ISSUE THREAD

**Issue by cn-mayank** [qdrant/qdrant#3613]
I updated payload of few points with key tb_9.6.1-1 and then tried to get count of points with the key which showed 0 points.
This was unexpected so i created a new collection and tested the same behavior and it worked fine.

The only difference between the two collection was the size of the collection itself and the key that i used to update the payload.
So in the new collection i introduced the same key with dot, underscore and hyphen and the issue reproduced.
Eliminating period from the key solved this in the new collection too.

## Current Behavior
Updated payload of points dont reflect in scroll/count with filters. The count of points with above key comes 0 even though that is not the case

## Steps to Reproduce
1. set up qdrant container as per env described below
2. create a test collection and add a dummy point to it with payload {'init': 'init'}
3. update payload by {"init":"init",  "tb_9.6.11": "f5a1166b-6ca3-4070-b57b-931bed1e1201"}
4. POST collections/test_payload/points/count
{  "filter": {
    "must_not": [
     {
        "is_empty": 
            { "key": "tb_9.6.11" }
      }
    
    ]
  }
}
5. you will get count as 0
6. change the key in payload to something without period and run above query again and count will be 1

## Expected Behavior
The count should be appropriate

## Context (Environment)
 running latest qdrant docker v1.7.4 locally on a windows machine

**Comment by generall** [comment]
Hi @cn-mayank, thanks for reporting. We will see how we can fix that, but for this time I can only recommend to avoid using payload keys with dots
