### ISSUE TITLE
Sudden increase in query times

### ISSUE THREAD

**Issue by marcortr** [qdrant/qdrant#3614]
Hello,

I was currently testing how many vectors i can store on a single node. In my setup i am uploading 100k vectors per step and then sending 100 queries and measuring their average time. All vectors are randomly generated and the collection i created is set as `on_disk` and is stored on a ssd.

I would have expected the query and indexing times to slowly rise, but instead at some time the query times just suddenly rise and get infeasible. This always happens at around 50M vectors with dimension 768.

![grafik](https://github.com/qdrant/qdrant/assets/143508795/8cbcf16a-5cff-4d61-bd22-1dc29ada1258)

I am aware that there is optimization happening in the background and already modified my code to wait for collection status `green` before querying. I also tried what happens with 10 shards, which led to this happening much earlier at around 25M vectors.

My questions now are:
Why are the query times increasing so suddenly?
Are there config parameters that would enable me to store more vectors on a single node?
Might the random vectors in the test setup be responsible for the behaviour and it could work better with real ones?

**Comment by timvisee** [comment]
Could you tell us a bit about your hardware configuration? How much RAM do you have available? What IOPS do you get on this SSD? Is it locally, or network attached?

Vector data is notoriously large, you may very well be reaching system limitations.

**Comment by marcortr** [comment]
1 Billion on a single Machine would be awesome.

The machine i am using has 64GB RAM.

I just measured the IOPS with `fio`:
```
test1: (groupid=0, jobs=1): err= 0: pid=744756: Wed Feb 14 11:07:37 2024
  read: IOPS=15.8k, BW=61.9MiB/s (64.9MB/s)(3070MiB/49603msec)
   bw (  KiB/s): min=39184, max=156800, per=99.87%, avg=63295.53, stdev=26435.43, samples=99
   iops        : min= 9796, max=39200, avg=15823.85, stdev=6608.85, samples=99
  write: IOPS=5295, BW=20.7MiB/s (21.7MB/s)(1026MiB/49603msec); 0 zone resets
   bw (  KiB/s): min=13984, max=52456, per=99.88%, avg=21154.61, stdev=8825.42, samples=99
   iops        : min= 3496, max=13114, avg=5288.62, stdev=2206.33, samples=99
  cpu          : usr=2.38%, sys=35.80%, ctx=199535, majf=0, minf=8
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=785920,262656,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=61.9MiB/s (64.9MB/s), 61.9MiB/s-61.9MiB/s (64.9MB/s-64.9MB/s), io=3070MiB (3219MB), run=49603-49603msec
  WRITE: bw=20.7MiB/s (21.7MB/s), 20.7MiB/s-20.7MiB/s (21.7MB/s-21.7MB/s), io=1026MiB (1076MB), run=49603-49603msec
  ```

**Comment by generall** [comment]
This is not SSD, this looks like gp3 network mounted disk.

**Comment by marcortr** [comment]
Hello,
thanks already for your answers and help.
So i just tried it again and changed to test for sequentiel instead of random read and write and it looks faster:
```
test1: (groupid=0, jobs=1): err= 0: pid=337294: Thu Feb 15 08:42:07 2024
  read: IOPS=118k, BW=461MiB/s (483MB/s)(3070MiB/6662msec)
   bw (  KiB/s): min=157936, max=682752, per=99.04%, avg=467332.69, stdev=238262.46, samples=13
   iops        : min=39484, max=170688, avg=116833.15, stdev=59565.61, samples=13
  write: IOPS=39.4k, BW=154MiB/s (161MB/s)(1026MiB/6662msec); 0 zone resets
   bw (  KiB/s): min=52240, max=228536, per=99.09%, avg=156268.15, stdev=79771.03, samples=13
   iops        : min=13060, max=57134, avg=39067.00, stdev=19942.74, samples=13
  cpu          : usr=13.17%, sys=1.41%, ctx=34368, majf=0, minf=45
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=4.5%, 16=23.4%, 32=61.6%, >=64=10.5%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=97.4%, 8=0.8%, 16=0.4%, 32=0.1%, 64=1.4%, >=64=0.0%
     issued rwts: total=785920,262656,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=461MiB/s (483MB/s), 461MiB/s-461MiB/s (483MB/s-483MB/s), io=3070MiB (3219MB), run=6662-6662msec
  WRITE: bw=154MiB/s (161MB/s), 154MiB/s-154MiB/s (161MB/s-161MB/s), io=1026MiB (1076MB), run=6662-6662msec
```
Is the bandwidth the important value here? 
What specs would be needed to serve 1 billion vectors?
And is there a way to estimate how many vectors a machine can serve given its specs?

**Comment by generall** [comment]
> Is the bandwidth the important value here?

yes, but IOPS is more important

> What specs would be needed to serve 1 billion vectors?

Yeah, this disk should be fast enough

> is there a way to estimate how many vectors a machine can serve given its specs?

There are no single answer to this question, it depends on the config options you want to use. Basically you need to balance RAM, latency and accuracy all together
