### ISSUE TITLE
Qdrant DSPY Integration

### ISSUE THREAD

**Issue by Dyke-F** [qdrant/qdrant#3616]
I have created a Qdrant vector store via LLama-index including metadata. This is stored correctly to disc including a collection name and storage.sqlite; .lock and meta.json file.

Following the code from https://qdrant.tech/documentation/frameworks/dspy/

to use the DSPY framework for retrieval; i run into: "ValueError: Dense vector fast-bge-small-en is not found in the collection".
I created the embeddings using OpenAI embedding model.

Any way to fix this?

**Comment by Anush008** [comment]
https://github.com/qdrant/landing_page/issues/616
