### ISSUE TITLE
WAL environment variable does not override the default value and the size of the snapshots is enormous 

### ISSUE THREAD

**Issue by fedecompa** [qdrant/qdrant#3628]
The environment variable QDRANT__WAL__WAL_CAPACITY_MB=8  passed in the docker-compose does not override the default value of 32MB. 

In addiction, taking a snapshot of a collection of just 4 Kbyte (with a "wal_capacity_mb=8" passed through API at creation time) creates a file of 17 MB!!

Since it is not recommended to set a lower value for the WAL size, in a production cluster with 3 nodes I would have snapshots of size 17x3 MB. If I have 1000 collections I will have 50 GB of snapshots, even if I have only saved 4 MB of useful information. This seems like a shocking thing to me, never seen in any database!

**Comment by generall** [comment]
> The environment variable QDRANT__WAL__WAL_CAPACITY_MB=8 passed in the docker-compose does not override the default value of 32MB.

the correct env is `QDRANT__STORAGE__WAL__WAL_CAPACITY_MB`

> In addiction, taking a snapshot of a collection of just 4 Kbyte (with a "wal_capacity_mb=8" passed through API at creation time) creates a file of 17 MB!!

as expected, cause WAL is always pre-allocated

> I have 1000 collections

Creating 1000 collection is an anti-pattern and is highly not recommended.

Please consider reading documentation on this: https://qdrant.tech/documentation/guides/multiple-partitions/
