### ISSUE TITLE
Flaky integration test `tests/consensus_tests/test_shard_snapshot_transfer.py`

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3634]
```
>       assert counts[0] == counts[1] == counts[2]
E       assert 11599 == 11598
tests/consensus_tests/test_shard_snapshot_transfer.py:241: AssertionError
```

**Comment by generall** [comment]
https://github.com/qdrant/qdrant/actions/runs/7929275180/job/21649169236

**Comment by generall** [comment]
Brute-force reproduction: https://github.com/qdrant/qdrant/pull/3635

**Comment by timvisee** [comment]
I think this can be closed since <https://github.com/qdrant/qdrant/pull/3642> is merged.
