### ISSUE TITLE
Help: Is it possible to compile Qdrant to a statically linked binary?

### ISSUE THREAD

**Issue by apepkuss** [qdrant/qdrant#3656]
I am new to Qdrant. I just wonder if Qdrant could be compiled to a statically linked binary? and run it on Linux (x86 and ARM). Thanks a lot!

**Comment by timvisee** [comment]
Yes, it definitely can! 

With our upcoming 1.8 release we'll provide a statically linked (MUSL) binary for x86_64.

Though, we generally recommend to use our provided Docker images instead.

**Comment by apepkuss** [comment]
Great! Do you have any plan for arm64?

**Comment by timvisee** [comment]
We don't have immediate plans, but I've opened an issue here to keep track of this idea: https://github.com/qdrant/qdrant/issues/3714

Please feel free to give it a shot yourself if you like.

**Comment by apepkuss** [comment]
Thanks a lot!

**Comment by timvisee** [comment]
ARM64 MUSL binaries are now part of the latest releases: https://github.com/qdrant/qdrant/releases/
