### ISSUE TITLE
Help needed - Unable to build qdrant from source

### ISSUE THREAD

**Issue by shandou** [qdrant/qdrant#3675]
I have a special use case that need to install qdrant inside a docker container. I have a base image look like this:
```
# Use Python 3.9 image based on Debian Buster as the base
FROM python:3.9-buster AS base

# Avoid interactive dialog during the build
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages for building Qdrant and other dependencies
RUN apt-get update && apt-get install -y \
  curl \
  build-essential \
  cmake \
  pkg-config \
  git \
  clang \
  lld \
  libssl-dev \
  libc6-dev \
  libunwind-dev \
  protobuf-compiler \
  jq \
  && rm -rf /var/lib/apt/lists/*

# Install Rust using rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Add Rust to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

# Clone Qdrant repository and build it
WORKDIR /usr/src/qdrant
# RUN git clone https://github.com/qdrant/qdrant.git . \
#   && cargo build --release --bin qdrant

# Expose the port Qdrant uses
EXPOSE 6333

# Set up the working directory for your application
WORKDIR /app

# Copy the script that starts your application into the container
COPY application_starter.sh ./

# Make sure the script is executable
RUN chmod +x application_starter.sh

# Use the script as the entrypoint to start your container
ENTRYPOINT ["./application_starter.sh"]
```

I tried to manually run the commented out build-from-source lines but the build fails:

```
 Compiling console v0.15.2
   Compiling anstyle-parse v0.2.0
   Compiling tikv-jemalloc-sys v0.5.2+5.3.0-patched
error: failed to run custom build command for `api v1.7.4 (/usr/src/qdrant/lib/api)`

Caused by:
  process didn't exit successfully: `/usr/src/qdrant/target/release/build/api-cb40f1468a8a3562/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=src/grpc/proto/qdrant.proto
  cargo:rerun-if-changed=src/grpc/proto

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: collections.proto:8:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. 
...
```

Could I be missing some key libraries in the base image?

Thank you.

**Comment by shandou** [comment]
Thank you @timvisee! Your suggestion about protocol buffer compiler version was spot on. It took me some path tinkering, but just managed to make the build work :)

Building from source does take a fairly long time, however. This is a somewhat unusual use case on my end, but wonder if it is possible to have pre-compiled binaries for qdrant going forward.

The updated dockerfile that works looks like this:
```docker
# Use Python 3.9 image based on Debian Buster as the base
FROM python:3.9-buster AS base

# Avoid interactive dialog during the build
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages for building Qdrant and other dependencies
#   NOTE: protobuf-compiler is excluded from this list;
#   higher version is installed separately
RUN apt-get update && apt-get install -y \
  curl \
  build-essential \
  cmake \
  pkg-config \
  git \
  clang \
  lld \
  libssl-dev \
  libc6-dev \
  libunwind-dev \
  jq \
  && rm -rf /var/lib/apt/lists/*

# Debian buster's default protobuf-compiler version is too low
#  Install 3.15+ specifically for qdrant build
#   following steps in https://grpc.io/docs/protoc-installation/
#   but replace $HOME/.local with /usr/.local
ENV PROTOC_VERSION=3.15.8
ENV PB_REL="https://github.com/protocolbuffers/protobuf/releases"
RUN curl -LO ${PB_REL}/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip \
  && unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/.local \
  && rm protoc-${PROTOC_VERSION}-linux-x86_64.zip
# # Add path to the protoc executable to PATH
ENV PATH="${PATH}:/usr/.local/bin"

# Install Rust using rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Add Rust to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

# Clone Qdrant repository and build it
#   Warning: building qdrant from source is very time consuing
#   This step could take 1,200+ s to complete
WORKDIR /usr/src/qdrant
RUN git clone https://github.com/qdrant/qdrant.git . \
  && cargo build --release --bin qdrant \
  && cp /usr/src/qdrant/target/release/qdrant /usr/local/bin/qdrant

# Expose the port Qdrant uses
EXPOSE 6333 6334

# Set up the working directory for the application
WORKDIR /app

# Copy the script that starts the application into the container
COPY application_starter.sh ./

# Make sure the script is executable
RUN chmod +x application_starter.sh

# Use the script as the entrypoint to start the container
ENTRYPOINT ["./application_starter.sh"]
```

**Comment by timvisee** [comment]
> This is a somewhat unusual use case on my end, but wonder if it is possible to have pre-compiled binaries for qdrant going forward.

Definitely! We provide precompiled binaries along with our releases, see the artifacts here: https://github.com/qdrant/qdrant/releases/tag/v1.7.4

Thank you for sharing your updated Dockerfile.

I'll close this issue now as I think the main issue is now resolved.

Let me know if you have a wish for a specific binary. In the next release we'll also include an x86_64 MUSL based binary, which is statically linked.

**Comment by shandou** [comment]
@timvisee Thank you. I just tried using `https://github.com/qdrant/qdrant/releases/download/v1.7.4/qdrant-x86_64-unknown-linux-gnu.tar.gz` with python base image running Debian-buster (python:3.9-buster), but the binary is directly compatible. I see the following error messages and wonder if we could have a binary specific to this specific debian release.

```
root@99f5ba5a483d:/app# qdrant
qdrant: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by qdrant)
qdrant: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by qdrant)
qdrant: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by qdrant)
qdrant: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by qdrant)
qdrant: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by qdrant)
qdrant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by qdrant)
qdrant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by qdrant)
qdrant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by qdrant)
qdrant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by qdrant)
```

**Comment by shandou** [comment]
Awesome! I tried https://github.com/qdrant/qdrant/releases/download/v1.8.1/qdrant-x86_64-unknown-linux-musl.tar.gz as suggested and it works! Thank you very much :)

**Comment by shandou** [comment]
@timvisee Apologies, one more question:

I was able to successfully curl the endpoint inside the container once qdrant is started. But I do get some warning messages that I want to double check with you. some of them might be related to dashboard, but are there critical ones that I should address? Thank you!

```bash
2024-03-13T23:03:45.637580Z  WARN qdrant::settings: Config file not found: config/config    
2024-03-13T23:03:45.637661Z  WARN qdrant::settings: Config file not found: config/development    
2024-03-13T23:03:45.637714Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json    
2024-03-13T23:03:45.678123Z  INFO qdrant: Distributed mode disabled    
2024-03-13T23:03:45.678256Z  INFO qdrant: Telemetry reporting enabled, id: b8738c9a-e33e-4160-b4a5-8253762346b2    
2024-03-13T23:03:45.707581Z  WARN qdrant::actix: Static content folder for Web UI './static' does not exist    
2024-03-13T23:03:45.708691Z  INFO qdrant::actix: TLS disabled for REST API    
2024-03-13T23:03:45.708831Z  INFO qdrant::actix: Qdrant HTTP listening on 6333    
2024-03-13T23:03:45.708853Z  INFO actix_server::builder: Starting 15 workers
2024-03-13T23:03:45.708872Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
2024-03-13T23:03:45.714412Z  INFO qdrant::tonic: Qdrant gRPC listening on 6334    
2024-03-13T23:03:45.714450Z  INFO qdrant::tonic: TLS disabled for gRPC API    

root@1db6f623ce60:/app# 
root@1db6f623ce60:/app# 
root@1db6f623ce60:/app# curl http://localhost:6333
{"title":"qdrant - vector search engine","version":"1.8.1","commit":"3fbe1cae6cb7f51a0c5bb4b45cfe6749ac76ed59"}
```

**Comment by shandou** [comment]
Thanks & very good to know! Assuming those warnings are mostly for the dashboard, then it should not affect anything I want to do at the moment.

**Comment by timvisee** [comment]
>     2024-03-13T23:03:45.637580Z  WARN qdrant::settings: Config file not found: config/config    
>     2024-03-13T23:03:45.637661Z  WARN qdrant::settings: Config file not found: config/development 

If you don't have a configuration file with custom values, these are fine.

>     2024-03-13T23:03:45.707581Z  WARN qdrant::actix: Static content folder for Web UI './static' does not exist    

These are indeed for the web UI. Inside the repository, you can run `./tools/sync-web-ui.sh` to download the appropriate files into the `static` folder.

**Comment by shandou** [comment]
@timvisee I have been testing multiprocessor runs but noticed something that appear to differ between batch runtime obtained by running locally-run qdrant container (via qdrant image) versus qdrant binary. Would like to better understand the unlying reason, and plausible ways for improving the runtime when I must use precompiled binary in my use case at the moment--

For example, for a batch of 1000 queries, 
- if my endpoint comes from qdrant docker, a sequential run takes 1.89 minutes
- if my endpoint comes from precompiled binary, the same sequential run takes 7+ minutes

My machine information looks like the following:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

The precompiled binary I use is: https://github.com/qdrant/qdrant/releases/download/v1.8.1/qdrant-x86_64-unknown-linux-musl.tar.gz

**Comment by timvisee** [comment]
That is a significant difference!

I assume that the biggest difference here is running the GNU vs MUSL binary. Could you give the precompiled GNU binary a try instead, and see if the results are similar?

It is this one: https://github.com/qdrant/qdrant/releases/download/v1.8.1/qdrant-x86_64-unknown-linux-gnu.tar.gz

**Comment by shandou** [comment]
Thank you.

> Our Docker image does not have any magic to make it run faster. It's effectively the same, or at least a very similar, binary.

Interesting. Could configuration lead to resource usage differences?

I tried the GNU counterpart but seeing the following error messages that I have seen before:
```
./qdrant: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./qdrant)
./qdrant: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./qdrant)
./qdrant: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./qdrant)
./qdrant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./qdrant)
./qdrant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./qdrant)
./qdrant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./qdrant)
[1]+  Exit 1                  ./qdran
```
