### ISSUE TITLE
wii we have a API to recover from a full storage snapshot  in 3-node Distributed deployment for Qdrant

### ISSUE THREAD

**Issue by kimmy-github** [qdrant/qdrant#3686]
I can see we do have a collection snapshot recovered in Distributed deployment ,but from https://qdrant.tech/documentation/concepts/snapshots/#recover-during-start-up. I see "This method cannot be used in a multi-node deployment and cannot be used in Qdrant Cloud."

So if I want to recover a full storage snapshot for three-node, how can I do with this?

**Comment by generall** [comment]
We do not plan to extend full-storage snapshot functionality. 

But here is an example of how to create and restore collection snapshots in the distributed mode: https://qdrant.tech/documentation/tutorials/create-snapshot/
