### ISSUE TITLE
.so Support for Qdrant Source code 

### ISSUE THREAD

**Issue by harshakhmk** [qdrant/qdrant#3710]
Is there  .so Support for Qdrant Source to run on Andriod OS

**Comment by timvisee** [comment]
What do you mean with .so support? Do you mean whether Qdrant has a shared object file you could use as library? To that the answer is no.

**Comment by harshakhmk** [comment]
Yes, building Qdrant as a shared object file and use it as a library with .so & .h files, so that we can use it in Andriod projects

**Comment by timvisee** [comment]
No, this is not supported.

With regards to Android, you can attempt to compile yourself for Android. But we cannot provide any support for that at this time.

**Comment by harshakhmk** [comment]
How do we attempt to compile for Andriod
