### ISSUE TITLE
Feature Request: Add ability to have properties/metadata for a collection 

### ISSUE THREAD

**Issue by Waffleboy** [qdrant/qdrant#3711]
**Is your feature request related to a problem? Please describe.**
I would like to add metadata to a Collection itself (so it applied table wide). 

**Describe the solution you'd like**
Add a properties/metadata input argument to Collection object which enables you to input data in key pair form

**Describe alternatives you've considered**

1. Config file. Sure we could use a config file etc but its cleaner if we could just add properties to the table itself
2. Add to every row instead. This is possible but wasteful

**Comment by generall** [comment]
Also discussed here: https://github.com/qdrant/qdrant/issues/3957
