### ISSUE TITLE
Build and release ARM64 MUSL binary

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant#3714]
**Is your feature request related to a problem? Please describe.**
Many users want to run a Qdrant binary on ARM64 hardware. We don't have such binary available.

**Describe the solution you'd like**
We would like to build a Qdrant MUSL binary for ARM64 and publish it as part of our release pipeline.

**Describe alternatives you've considered**
None.

**Additional context**
- https://github.com/qdrant/qdrant/issues/3334: MUSL build for x86_64
- https://github.com/qdrant/qdrant/issues/2656: release MUSL build for x86_64
- https://github.com/qdrant/qdrant/issues/3056: question about ARM64 binary
- https://github.com/qdrant/qdrant/issues/3656: question about ARM64 binary

**Comment by Dhanus3133** [comment]
@timvisee , is that GNU? I want to clarify more on what target architectures to add.

**Comment by timvisee** [comment]
Whoops! It looks like it is already part of our release pipeline. :wow:

https://github.com/qdrant/qdrant/releases/tag/v1.8.3

It lists: `qdrant-aarch64-unknown-linux-musl.tar.gz`

That would mean this issue is already implemented.
