### ISSUE TITLE
Docker Example In README Does Not Work

### ISSUE THREAD

**Issue by argentini** [qdrant/qdrant#3727]
The docker example is incorrect. It's missing the gRPC port which prevents it from working.

The example should be:

`docker run -p 6333:6333 -p 6334:6334 qdrant/qdrant`

**Comment by kacperlukawski** [comment]
Hey @argentini, The example should work fine if you use HTTP, not gRPC to communicate with Qdrant.

**Comment by argentini** [comment]
> Hey @argentini, The example should work fine if you use HTTP, not gRPC to communicate with Qdrant.

I believe it uses gRPC by default so for me it did not work out of the box, so to speak. Perhaps I missed something. Follow the examples and see if it works for you.

**Comment by generall** [comment]
I believe this is fixed now. At least I can't find a place where gRPC is used but not exposed
