### ISSUE TITLE
Just importing QdrantClient in Python immediately produces a deprecation warning 

### ISSUE THREAD

**Issue by bob-ros2** [qdrant/qdrant#3743]
## Current Behavior
Immediatly after importing QdrantClient in Python a warning message will be printed to stderr.
Following message will be shown:

`2024-03-01 22:39:20.921 | WARNING  | fastembed.embedding:<module>:7 - DefaultEmbedding, FlagEmbedding, JinaEmbedding are deprecated.Use from fastembed import TextEmbedding instead.`

## Steps to Reproduce

```
import sys
from qdrant_client import QdrantClient
sys.exit(0)
```

## Expected Behavior
The warning should not be dropped if the deprecated objects are not used

## Possible Solution
None provided

## Context (Environment)
qdrant-client==1.7.3
Linux 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

## Detailed Description
see Current Behavior

## Possible Implementation
None provided

**Comment by joein** [comment]
Hi @bob-ros2 

Could you please check your fastembed version?

It should be 0.1.1, however I think that you have 0.2.1

**Comment by bob-ros2** [comment]
Hey @joein 
you are right. Thanks! This fixed it:
```
$ pip freeze | grep fastembe
fastembed==0.2.2

$ pip install fastembed==0.1.1
```
