### ISSUE TITLE
Downsides of creating lot of vectors in a collection.

### ISSUE THREAD

**Issue by Sailendrakc** [qdrant/qdrant#3744]
Hello, this is more of a question than bug. 

When serving to lof of clients, It is generally not advised to create multiple collection and rather use multitenacy. And that involves indexing a field in payload and using that as filter during query. For me, it looks like we are storing same information in multiple places as below where group_id is repeated:

```
client.upsert(
    collection_name="{collection_name}",
    points=[
        models.PointStruct(
            id=1,
            payload={"group_id": "client1"},
            vector=[0.9, 0.1, 0.1],
        ),
        models.PointStruct(
            id=2,
            payload={"group_id": "client2"},
            vector=[0.1, 0.9, 0.1],
        ),
        models.PointStruct(
            id=3,
            payload={"group_id": "uclient3"},
            vector=[0.1, 0.1, 0.9],
        ),
    ],
)
```

Now what happens if we create multiple vectors in a collection per client, even though they are of same dimention. We can change from creation of global HNSW graph to per vector HNSW graph creation. And when quering, my application will always pass the name of vector to search on. This design will prevent storing of same information in multiple places and it looks like good practice to me as it kinda seperates client data from each other (based on the information I have atm).

```
from qdrant_client import QdrantClient
from qdrant_client.http import models

client = QdrantClient("localhost", port=6333)

client.create_collection(
    collection_name="clientRAG",
    vectors_config={
        "client1": models.VectorParams(size=1024, distance=models.Distance.COSINE),
        "client2": models.VectorParams(size=1024, distance=models.Distance.COSINE),
        "client3": models.VectorParams(size=1024, distance=models.Distance.COSINE),
        "client4": models.VectorParams(size=1024, distance=models.Distance.COSINE),
        "client5": models.VectorParams(size=1024, distance=models.Distance.COSINE),
        "....." :  .............,
        "client1000": models.VectorParams(size=1024, distance=models.Distance.COSINE),
    },
)
```

1. Is the downside of creation of multiple collection same as downside of creation of multiple vectors in a collection?
2. Are there any downsides of creating like 500s or 1000s of vectors (like above code) in a collection in terms of memory, efficiency and retrival speed etc as compared to using multitenacy?

**Comment by timvisee** [comment]
I don't think this is possible. The reason is that the named vectors are fixed, and must all be defined on collection creation. You cannot dynamically create these.

Also, it won't be very storage efficient either.

So, your first snippet is definitely the correct way of doing things. Defining `group_id` multiple times is perfectly fine, and definitely a lot more efficient than other options. Please make sure to define an index on the `group_id` as well to ensure fast searches.

Closing this now as I think it is answered. Please feel free to open it again if you have further questions.
