### ISSUE TITLE
Add version to startup log

### ISSUE THREAD

**Issue by superseb** [qdrant/qdrant#3752]
**Is your feature request related to a problem? Please describe.**
When running the application, the startup/application logging does not contain the version. While this is easily retrievable by checking the container image tag/inspect the container image/using the Qdrant API, when debugging/collecting logs, it is convenient to have the version number in the log to make sure what version is running.

**Describe the solution you'd like**
Include the version in the application startup log

**Describe alternatives you've considered**
You can check the container image tag, inspect the container image, and can query the API to get the version, but when provided with a log it is convenient to have the version in the log.

**Additional context**
We can use `CARGO_PKG_VERSION` for this, I haven't found any problems with this approach but I'm a Rust beginner. We can also take it a step further and include commit hash but this requires a bit more work as it is not part of Cargo's default environment variables.

**Comment by generall** [comment]
this is already resolved in dev

**Comment by superseb** [comment]
Got it, I only searched issues apparently. For reference, the PR is https://github.com/qdrant/qdrant/pull/3581.
