### ISSUE TITLE
Qdrant become very slow when filter all points using filters

### ISSUE THREAD

**Issue by ChenXiaoTemp** [qdrant/qdrant#3805]
Qdrant become very slow when filter all points using filters

## Current Behavior
I import about 100w points into qdrant and each contains a payload, like following:

![image](https://github.com/qdrant/qdrant/assets/5827720/3bc15236-a2bc-4de7-a39f-2e3e9221fe0c)

It costs about 30ms to query a point without filter , or there exist at least one point queried using filter. I think it is expected.

But, if I use a filter filter filter out all points, then it will cost 6seconds to get the result.

## Steps to Reproduce

1. build a collection 
2. import about 100w points with payload, echo payload contains a event time field(datetime)
3. query with filter (filter out all points)
4. you will find it is slow

## Expected Behavior

The speed should not  become so slow.

## Context (Environment)

qdrant v1.8.0

**Comment by ChenXiaoTemp** [comment]
b.t.w. I build a datetime index for the event_time field, and use equal operator to filter it, then it also be very slow(cost about 6seconds to get the response)

**Comment by generall** [comment]
Hey @ChenXiaoTemp, could you please share collection info, example of the payload you store and the example of filter you use. Most likely there is something not aligned there

**Comment by timvisee** [comment]
> I build a datetime index for the event_time field, and use equal operator to filter it

You mention filtering on date time equality. Our date time index currently does not support equality, but only ranges.

**Comment by ChenXiaoTemp** [comment]
> Hey @ChenXiaoTemp, could you please share collection info, example of the payload you store and the example of filter you use. Most likely there is something not aligned there

Attechment is some data I queried out from qdrant
[res.json](https://github.com/qdrant/qdrant/files/14567111/res.json)

**Comment by ChenXiaoTemp** [comment]
> > I build a datetime index for the event_time field, and use equal operator to filter it
> 
> You mention filtering on date time equality. Our date time index currently does not support equality, but only ranges.
> 
> We made that choice because we didn't have a good use case for matching date time values exactly.
> 
> Could you elaborate on how you're using these filters, and why it makes sense to use it in this way in your case?
> 
> So again, because we don't support equality (lookups) in date time ranges, it accepts the filter but simply ignores the index. As a temporary workaround you may use a date time range filter instead, in which you define your exact value as `lte` and `gte`, essentially matching the exact date time value. Could you validate what results you get using that approach?

In out case, we use `yyyy-MM-dd` date format, and we want to filter the data whose datetime is 2024-03-12.

I think you advise is OK for me, we can use lte and gte to filter it, I just find this problem~

**Comment by generall** [comment]
Will put this improvement into our backlog
