### ISSUE TITLE
Flaky consensus test test_peer_snapshot_bootstrap

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#3821]
```
FAILED tests/consensus_tests/test_peer_snapshot_bootstrap.py::test_peer_snapshot_bootstrap - Exception: Timeout waiting for condition check_cluster_size to be satisfied in 30 seconds
````

Example of logs [logs.txt](https://github.com/qdrant/qdrant/files/14591342/logs.txt)

Most likely as side effect of https://github.com/qdrant/qdrant/pull/2831/files#diff-145ca2abd049013480a4bdacf8978d5324b7cb6d0586d286ae129e050f42b44cL26

**Comment by generall** [comment]
Reproducible locally (from the second try)

**Comment by timvisee** [comment]
I think this is fixed in <https://github.com/qdrant/qdrant/pull/3824>.
