### ISSUE TITLE
how to know when indexing is finished?

### ISSUE THREAD

**Issue by raulcarlomagno** [qdrant/qdrant#3844]
When i create a new collection for 60 million vectors, with 12 shards and replication factor of 2. Before uploading vectors, i disable indexing by setting indexing_threshold to zero. Then, after all vectors have been uploaded, I set indexing_threshold  back to 20000 (default).
When indexing process begins i would like to know when it is finished.
Before, when using no shards neither replication factor, i was querying collection info one time per minute to compare 'indexed_vectors_count' to 'vectors_count', when these matched, all my vectors were finally indexed.

But now, having shards and replication factors, i get different values for 'indexed_vectors_count' and 'vectors_count', depending of the shard and node.

So the question is, how can i know when indexation did finish?

**Comment by agourlay** [comment]
You need to fetch the collection information and check if the status field is `green`
https://qdrant.tech/documentation/concepts/collections/#collection-info

The number of vectors is approximate https://qdrant.tech/documentation/concepts/collections/#approximate-point-and-vector-counts

**Comment by raulcarlomagno** [comment]
yes, i have read about 
🟡 yellow: collection is optimizing

but i dont know if optimizing == indexing....

thank you for answering

**Comment by raulcarlomagno** [comment]
sorry for reopening 
but, i would to know if it is possible to know when the whole indexing process is finished, because having in my case 12 nodes, when i query collection info, depending of the node which responses it could have green status or yellow
it is not consistent
thank you

**Comment by raulcarlomagno** [comment]
@agourlay could you re open it?
thank you

**Comment by timvisee** [comment]
>  depending of the node which responses it could have green status or yellow
it is not consistent

Indexing is a local process, and happens on each node separately.

So if you'd like to know when indexing is done on all of them, all should report a green status.

**Comment by agourlay** [comment]
One precision to add.

If you have shards in your collection, we do check all shards info statuses across the cluster and merge them to reflect the highest value.

**Comment by raulcarlomagno** [comment]
> > depending of the node which responses it could have green status or yellow
> > it is not consistent
> 
> Indexing is a local process, and happens on each node separately.
> 
> So if you'd like to know when indexing is done on all of them, all should report a green status.

but i can't read all of them, it is 'random', i cannot query each node collection, i just query the main uri and it distpatches
anyways
i know what i am asking is not possible in qdrant

**Comment by raulcarlomagno** [comment]
> One precision to add.
> 
> If you have shards in your collection, we do check all shards info statuses across the cluster and merge them to reflect the highest value.

i think that would be good that collection info return each shard status, all of them in the collection info response, not a global highest one

thank you anyways

**Comment by timvisee** [comment]
> i think that would be good that collection info return each shard status, all of them in the collection info response, not a global highest one

That isn't really doable in a distributed system like this. Or at least, it may not be very reliable as the number of nodes grow.

Question: why would you like to know whether indexing has finished? It is a relatively transparent process, in the sense that every vector is immediately available from the moment you insert it, even if indexing is going on. You probably should not have to care about indexing happening.
