### ISSUE TITLE
Using qdrant vectore store created in llamaindex for dspy 

### ISSUE THREAD

**Issue by BlueKiji77** [qdrant/qdrant#3886]
Trying to use a vectore store created with llamaindex but the dspy QdrantRM can't find the embedding model used to initially create the vectore store.

## Current Behavior
When running `dspy.Retrieve(k=3)(query)` I get `ValueError: Dense vector fast-bge-small-en is not found in the collection`
ERROR TRACE:
`100%|██████████| 77.7M/77.7M [00:03<00:00, 22.5MiB/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 3
      1 import dspy
      2 dspy.settings.configure(lm=llm, rm=retriever_model)
----> 3 dspy.Retrieve(k=3)("What is level design?")

File /opt/conda/lib/python3.10/site-packages/dspy/retrieve/retrieve.py:30, in Retrieve.__call__(self, *args, **kwargs)
     29 def __call__(self, *args, **kwargs):
---> 30     return self.forward(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/dspy/retrieve/retrieve.py:39, in Retrieve.forward(self, query_or_queries, k)
     36 # print(queries)
     37 # TODO: Consider removing any quote-like markers that surround the query too.
     38 k = k if k is not None else self.k
---> 39 passages = dsp.retrieveEnsemble(queries, k=k)
     40 return Prediction(passages=passages)

File /opt/conda/lib/python3.10/site-packages/dsp/primitives/search.py:57, in retrieveEnsemble(queries, k, by_prob)
     54 queries = [q for q in queries if q]
     56 if len(queries) == 1:
---> 57     return retrieve(queries[0], k)
     59 passages = {}
     60 for q in queries:

File /opt/conda/lib/python3.10/site-packages/dsp/primitives/search.py:12, in retrieve(query, k, **kwargs)
     10 if not dsp.settings.rm:
     11     raise AssertionError("No RM is loaded.")
---> 12 passages = dsp.settings.rm(query, k=k, **kwargs)
     13 if not isinstance(passages, Iterable):
     14     # it's not an iterable yet; make it one.
     15     # TODO: we should unify the type signatures of dspy.Retriever
     16     passages = [passages]

File /opt/conda/lib/python3.10/site-packages/dspy/retrieve/retrieve.py:30, in Retrieve.__call__(self, *args, **kwargs)
     29 def __call__(self, *args, **kwargs):
---> 30     return self.forward(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/dspy/retrieve/qdrant_rm.py:73, in QdrantRM.forward(self, query_or_queries, k)
     70 queries = [q for q in queries if q]  # Filter empty queries
     72 k = k if k is not None else self.k
---> 73 batch_results = self._qdrant_client.query_batch(
     74     self._qdrant_collection_name, query_texts=queries, limit=k)
     76 passages_scores = defaultdict(float)
     77 for batch in batch_results:

File /opt/conda/lib/python3.10/site-packages/qdrant_client/qdrant_fastembed.py:444, in QdrantFastembedMixin.query_batch(self, collection_name, query_texts, query_filter, limit, **kwargs)
    430     request = models.SearchRequest(
    431         vector=models.NamedVector(
    432             name=self.get_vector_field_name(), vector=vector.tolist()
   (...)
    437         **kwargs,
    438     )
    440     requests.append(request)
    442 return [
    443     self._scored_points_to_query_responses(response)
--> 444     for response in self.search_batch(
    445         collection_name=collection_name,
    446         requests=requests,
    447     )
    448 ]

File /opt/conda/lib/python3.10/site-packages/qdrant_client/qdrant_client.py:234, in QdrantClient.search_batch(self, collection_name, requests, timeout, consistency, **kwargs)
    214 """Search for points in multiple collections
    215 
    216 Args:
   (...)
    230     List of search responses
    231 """
    232 assert len(kwargs) == 0, f"Unknown arguments: {list(kwargs.keys())}"
--> 234 return self._client.search_batch(
    235     collection_name=collection_name,
    236     requests=requests,
    237     consistency=consistency,
    238     timeout=timeout,
    239     **kwargs,
    240 )

File /opt/conda/lib/python3.10/site-packages/qdrant_client/local/qdrant_local.py:155, in QdrantLocal.search_batch(self, collection_name, requests, **kwargs)
    147 def search_batch(
    148     self,
    149     collection_name: str,
    150     requests: Sequence[types.SearchRequest],
    151     **kwargs: Any,
    152 ) -> List[List[types.ScoredPoint]]:
    153     collection = self._get_collection(collection_name)
--> 155     return [
    156         collection.search(
    157             query_vector=request.vector,
    158             query_filter=request.filter,
    159             limit=request.limit,
    160             offset=request.offset,
    161             with_payload=request.with_payload,
    162             with_vectors=request.with_vector,
    163             score_threshold=request.score_threshold,
    164         )
    165         for request in requests
    166     ]

File /opt/conda/lib/python3.10/site-packages/qdrant_client/local/qdrant_local.py:156, in <listcomp>(.0)
    147 def search_batch(
    148     self,
    149     collection_name: str,
    150     requests: Sequence[types.SearchRequest],
    151     **kwargs: Any,
    152 ) -> List[List[types.ScoredPoint]]:
    153     collection = self._get_collection(collection_name)
    155     return [
--> 156         collection.search(
    157             query_vector=request.vector,
    158             query_filter=request.filter,
    159             limit=request.limit,
    160             offset=request.offset,
    161             with_payload=request.with_payload,
    162             with_vectors=request.with_vector,
    163             score_threshold=request.score_threshold,
    164         )
    165         for request in requests
    166     ]

File /opt/conda/lib/python3.10/site-packages/qdrant_client/local/local_collection.py:408, in LocalCollection.search(self, query_vector, query_filter, limit, offset, with_payload, with_vectors, score_threshold)
    405 else:
    406     # it must be dense vector
    407     if name not in self.vectors:
--> 408         raise ValueError(f"Dense vector {name} is not found in the collection")
    409     vectors = self.vectors[name]
    410     distance = self.get_vector_params(name).distance

ValueError: Dense vector fast-bge-small-en is not found in the collection`

## Steps to Reproduce
-
### 1. Qdrant vectore store creation in llamaindex
`
import chromadb
import qdrant_client
from llama_index.core import VectorStoreIndex, load_index_from_storage
from llama_index.core.storage.docstore import SimpleDocumentStore
from llama_index.core.storage.index_store import SimpleIndexStore
from llama_index.vector_stores.qdrant import QdrantVectorStore
from llama_index.core.storage.storage_context import StorageContext

import torch
from llama_index.core import Settings
from llama_index.core import PromptTemplate
from llama_index.llms.huggingface import HuggingFaceLLM
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

alpha_monarch = "mlabonne/AlphaMonarch-7B"
huggingface_llm = HuggingFaceLLM(
    context_window=model_params["context_window"],
    max_new_tokens=model_params["max_new_tokens"],
    generate_kwargs=model_params["generate_kwargs"],
    tokenizer_name=alpha_monarch,
    model_name=alpha_monarch,
    device_map="auto",
    tokenizer_kwargs=tokenizer_params,
    # uncomment this if using CUDA to reduce memory usage
    model_kwargs={"torch_dtype": torch.float16}
)

# Setting up llm and huggingface embedding model
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en")
Settings.llm = huggingface_llm
Settings.embed_model = embed_model

print("Setting up qdrant store...")
client = qdrant_client.QdrantClient(
    path="/kaggle/working/"
)
qdrant_vector_store = QdrantVectorStore(client=client, collection_name="game_design_qdrant_store")

# create storage context using default stores
storage_context = StorageContext.from_defaults(
    docstore=SimpleDocumentStore(),
    vector_store=qdrant_vector_store,
    index_store=SimpleIndexStore(),
)

# create (or load) docstore and add nodes
# nodes are from previously uploaded documents with various transformation applied
storage_context.docstore.add_documents(nodes)

# build index
index = VectorStoreIndex(nodes, storage_context=storage_context)

# save index
output_dir = "/kaggle/working/"
index_persist_dir = os.path.join(output_dir)
os.makedirs(index_persist_dir, exist_ok=True)
index_name = "game_design_qdrant_index"
index.set_index_id(index_name)
# index.storage_context.persist(persist_dir=index_persist_dir)`

## Querying vectore store in dspy
`import dspy
import qdrant_client
from dspy.retrieve.qdrant_rm import QdrantRM

alpha_monarch = "mlabonne/AlphaMonarch-7B"
llm = dspy.HFModel(alpha_monarch)
collection_name = "game_design_qdrant_store"
index_store_path= "/kaggle/working/storytelling-gamedesign-qdrantindexstore"

qdrant_client = qdrant_client.QdrantClient(path=index_store_path)

retriever_model = QdrantRM(qdrant_collection_name=collection_name,
                         qdrant_client=qdrant_client)

qdrant_client.get_collections(collection_name="game_design_qdrant_store")

dspy.settings.configure(lm=llm, rm=retriever_model)
dspy.Retrieve(k=3)("What is level design?")
`

## Expected Behavior
Documents similar to the query 

## Possible Solution
Executing `dspy.Retrieve(k=3)("What is level design?")` downloads the embedding model ` HuggingFaceEmbedding(model_name="BAAI/bge-small-en")`
`100%|██████████| 77.7M/77.7M` before giving the error. A solution might be to redirect `LocalCollection.search` to wherever the embedding model has been downloaded.

## Context (Environment)
I want to leverage dspy on the qdrant vectore store backend I am building with llamaindex framework. For this I first create the vectore store with lamaindex and now need to connect it to dspy.

**Comment by generall** [comment]
I am not sure this is the right place to ask this question. Could you please move it to DSPy / llamaindex repo?

**Comment by Anush008** [comment]
Hi @BlueKiji77. The Dspy integration expects the documents to be added to Qdrant using `qdrant_clients`'s `QdrantClient#add()` method. It configures and adds appropriate named vectors that are later used by the `QdrantClient#query()` method which Dspy internally uses.

Since you're adding the embeddings separately, the expected named vectors are not created, thereby causing this issue.

**Comment by Anush008** [comment]
Due to these compatibility requirements, your approach to connect frameworks is not recommended and not guaranteed to work.

**Comment by Anush008** [comment]
Due to these compatibility requirements, your approach to connect frameworks is not recommended and not guaranteed to work.

**Comment by BlueKiji77** [comment]
What approach do you recommend I take to do this then considering I have the text to be embedded and the metadata? Using QdrantClient#add() did not work either.

**Comment by Anush008** [comment]
`QdranrClient#add()` should work.

Could you move this issue to DSpy and share a traceback or error you're running into if any?

**Comment by Anush008** [comment]
`QdrantClient#add()` should work.

Could you please move this issue to DSPy the repo and share a traceback or error you're running into if any?

**Comment by BlueKiji77** [comment]
Got it working, thank you!
