### ISSUE TITLE
Method to rename qdrant collection in API and dashboard

### ISSUE THREAD

**Issue by Waffleboy** [qdrant/qdrant#3904]
**Is your feature request related to a problem? Please describe.**
I discovered theres no way to rename an existing collection. This is a basic feature and should be included.

**Describe the solution you'd like**
The above

**Describe alternatives you've considered**
None

**Additional context**
Self explanatory

**Comment by Waffleboy** [comment]
Hey @generall , Yes i saw, but i need to swap the names of 2 tables so I'd rather rename rather than alias it which could lead to confusion

**Comment by timvisee** [comment]
At this stage there's no call to rename an existing collection, other than using [aliases](https://qdrant.tech/documentation/concepts/collections/#collection-aliases) as suggested above.

Could you elaborate your use case a bit more? That might help my understand on why it may be confusing to use aliases.

**Comment by almostimplemented** [comment]
What is the rationale for not allowing users to rename a collection? I cannot think of a DBMS that would not allow users to rename tables / databases.

**Comment by generall** [comment]
> What is the rationale for not allowing users to rename a collection? I cannot think of a DBMS that would not allow users to rename tables / databases.

This is not as easy operation as you might expect. Qdrant storage structure is pretty straightforward, we simply create a folder with collection name and put everything there. This helps navigating and overall very convenient.
But if you want to rename this folder while having the collection running, you are going to have problems.

For that reason we have a production-oriented mechanism of aliases. Our understanding is, if you are running qdrant in prod - aliases are the best option for you, as it is an atomic switch. If you are developing and just want to fix a typo in a name of the collection, creating a new one should not be a big deal.

For those reasons I don't think we are going to implement the renaming API any time soon. Please feel free to re-open this issue if you have any additional arguments for the change or suggestions how this renaming API can be easily implemented.

**Comment by almostimplemented** [comment]
Naively, I would think (part of) the "simple" solution would be to decouple internal storage mechanisms from external, user-provided information, for instance by using immutable UUIDs for each collection. That might also preclude the need for the concept of aliases (can just switch names as currently done for aliases).

I can understand that this may be difficult to introduce in a compatible manner.

**Comment by timvisee** [comment]
At the same time, that would make it a lot more annoying to work with on the file system level. We made a compromise here.

Note that if you really want to change your collection name, what you can do is this:
1. shut down your Qdrant instance
2. rename the collection directory to whatever you prefer
3. restart your Qdrant instance

**Comment by generall** [comment]
> Note that if you really want to change your collection name, what you can do is this:

This will only work for single-node cluster, and overall not recommended

**Comment by Enolerobotti** [comment]
I've got a use case where renaming might be convenient. I need to constantly update a huge collection, literally re-creating it. The update takes time and users should be able to access to old collection during the update. In an SQL database I would create a schema with suffix "_new", fill this schema with data. Once it is ready, I drop old schema and rename the new one removing the suffix.

**Comment by michelkluger** [comment]
+1 for a rename feature

**Comment by demony** [comment]
Guys, I don't get how you look at these GUIDs in the Qdrant DB and know it's your specific database. Is this specified somewhere in the kilo configs?
