### ISSUE TITLE
[Help] Regarding binary size of Qdrant Service

### ISSUE THREAD

**Issue by jay11ca39** [qdrant/qdrant#3920]
Hello All, 
I am experimenting Qdrant. 
- I built from source using `cargo build `

But size of Qdrant executable is **~900 MB** which is huge. 
Is it possible to reduce it: 
- With disabling some features during build
- Enable minimum functionalities like create/insert/search(query)/delete 

Or any other mechanism is there to reduce binary size.

**Comment by timvisee** [comment]
`cargo build` produces a debug build, which is indeed very large.

Instead I recommend to do a release build, which won't just be a lot smaller, but also a lot faster at runtime. You can use `cargo build --release` for that.

We do have some _heavy_ compile time features, but they are disabled by default. I therefore recommend to use the default feature set.

The latest Rust version (1.77) also made changes helping with reducing release binary size. So I'd recommend to update that as well.

Note that we do provide pre-built binaries here with our releases [here](https://github.com/qdrant/qdrant/releases/tag/v1.8.3). They are about 64 MB uncompressed.

**Comment by jay11ca39** [comment]
Hello @timvisee ,
Thanks for reply. 

I did release build.. with that binary size is: 61 MB 
With rust 1.77

But I am more greedy to reduce binary size...:)
Just want to know is there any room for reducing it further by disabling any features or ..?

**Comment by timvisee** [comment]
It'll be hard to strip it further. Qdrant is a big project with a lot going on internally.

At this time, it is not really possible to disable more features in Qdrant. There are some toggles to disable the REST API for example, but doing so currently fails to compile.

There are some guides on how to reduce the binary size of Rust projects, but we don't explicitly support that. Such as: https://github.com/johnthagen/min-sized-rust

What binary size are you actually looking for? I may be able to give an insight on whether that is possible.

**Comment by jay11ca39** [comment]
Hi, 
I am looking for somewhere around 30-35 MB..
Like you said disabling Rest API or grpc or both may be good support to reduce binary.. 
Also apart from reducing core binary size, people can have their own communication model as per their requirement.

**Comment by timvisee** [comment]
> I am looking for somewhere around 30-35 MB..

I don't think that's possible without significant work and code base changes. We currently don't have the bandwidth to do this ourselves because we have a lot of other tasks with higher priority, while storage is relatively cheap these days.

>  Like you said disabling Rest API or grpc or both may be good support to reduce binary..

Yes, though I don't know the significance of the effect this will have on binary size. It may very well be reducing binary size by 0.5 MBs.

> people can have their own communication model as per their requirement.

What do you mean with this?

**Comment by jay11ca39** [comment]
> > I am looking for somewhere around 30-35 MB..
> 
> I don't think that's possible without significant work and code base changes. We currently don't have the bandwidth to do this ourselves because we have a lot of other tasks with higher priority, while storage is relatively cheap these days.
> 
> > Like you said disabling Rest API or grpc or both may be good support to reduce binary..
> 
> Yes, though I don't know the significance of the effect this will have on binary size. It may very well be reducing binary size by 0.5 MBs.
> 
> > people can have their own communication model as per their requirement.
> 
> What do you mean with this?

 ..


By other communication: 
I mean if people don't want to use rest or grpc for communication and  want to some other protocols like mqtt or any other ..but that is just other benefit .. 

As you said rest API or grpc will not significantly reduce binary size..

Which components you think are majorly contributing to binary size ?

**Comment by timvisee** [comment]
> By other communication:
> I mean if people don't want to use rest or grpc for communication and want to some other protocols like mqtt or any other ..but that is just other benefit ..

Qdrant support a REST and gRPC API, along with that we provide a bunch of clients.

I understand that some users may desire a different API interface they may be more familiar with, but Qdrant will very likely not be supporting that. We may only consider that if there's a very good use case for it. Otherwise it requires significant work and only makes the project more complex to work with and harder to maintain.

You mention MQTT, but such protocol is not suitable for a vector database/search engine.

> Which components you think are majorly contributing to binary size ?

That is very hard to say, as it requires thorough binary inspection.

The top contenders for binary size according to [`cargo bloat`](https://github.com/RazrFalcon/cargo-bloat) are:

```
File  .text     Size             Crate Name
0.0%   0.3% 266.3KiB        actix_http brotli::enc::prior_eval::PriorEval<Alloc>::update_cost_base
0.0%   0.3% 218.5KiB tikv_jemalloc_sys _rjem_realloc
0.0%   0.3% 217.9KiB tikv_jemalloc_sys _rjem_mallocx
0.0%   0.3% 217.7KiB tikv_jemalloc_sys _rjem_calloc
0.0%   0.3% 217.3KiB tikv_jemalloc_sys _rjem_je_malloc_default
0.0%   0.2% 172.2KiB        blake2_rfc blake2_rfc::blake2b::Blake2b::compress
0.0%   0.2% 160.7KiB             regex <regex::exec::ExecNoSync as regex::re_trait::RegularExpression>::captures_read_at
0.0%   0.1%  79.3KiB         [Unknown] do_rallocx
0.0%   0.1%  73.7KiB tikv_jemalloc_sys _rjem_je_sdallocx_default
0.0%   0.1%  69.5KiB                h2 h2::codec::framed_read::decode_frame
0.0%   0.1%  59.9KiB                h2 h2::frame::headers::HeaderBlock::load::{{closure}}
0.0%   0.1%  53.9KiB             regex <regex::re_trait::Matches<R> as core::iter::traits::iterator::Iterator>::next
0.0%   0.1%  52.1KiB      aho_corasick <aho_corasick::packed::teddy::builder::x86_64::SlimAVX2<4_usize> as aho_corasick::packed::teddy::builder::SearcherT>::find
0.0%   0.1%  49.0KiB      aho_corasick <aho_corasick::packed::teddy::builder::x86_64::SlimAVX2<3_usize> as aho_corasick::packed::teddy::builder::SearcherT>::find
0.0%   0.1%  48.4KiB         [Unknown] stats_arena_bins_print
0.0%   0.1%  45.9KiB      aho_corasick <aho_corasick::packed::teddy::builder::x86_64::SlimAVX2<2_usize> as aho_corasick::packed::teddy::builder::SearcherT>::find
0.0%   0.1%  42.5KiB      aho_corasick <aho_corasick::packed::teddy::builder::x86_64::SlimAVX2<1_usize> as aho_corasick::packed::teddy::builder::SearcherT>::find
0.0%   0.0%  41.7KiB         [Unknown] HUF_compress1X_usingCTable_internal_default
0.0%   0.0%  41.4KiB         [Unknown] HUF_compress1X_usingCTable_internal_bmi2
0.0%   0.0%  40.6KiB      aho_corasick aho_corasick::automaton::try_find_fwd
8.3%  94.9%  77.4MiB                   And 351671 smaller methods. Use -n N to show more.
8.7% 100.0%  81.6MiB                   .text section size, the file size is 935.3MiB
```

But none of these can be removed, nor do they have any significant effect on binary size.

Please refer to the resource I [linked](https://github.com/johnthagen/min-sized-rust) above to dive further into making binaries smaller yourself.

Feel free to open a pull request with your contribution if some change helps with final binary size.
