### ISSUE TITLE
Help needed - Can search_batch and search_groups work together?

### ISSUE THREAD

**Issue by shandou** [qdrant/qdrant#3954]
Greetings! I am looking for ways to speed up similarity search, and I work with document index that has a nested structure and thus must rely on `search_groups` API to return a singular item per group. I just read through [2022 article Batch vector search with Qdrant](https://qdrant.tech/blog/batch-vector-search-with-qdrant/) and keen to experiment with the option "Multiprocessing batch search". However, it seems to me that search_groups does not yet have a batch search variant. Is my impression correct? Thank you!

**Comment by generall** [comment]
This is currently not supported.
Do you see that the networking is a bottleneck in your application? If not, I presume having just two parallel requests should be good enough alternative to the batch request, as I don't think group requests could benefit from shared filter as regular batch requests do

**Comment by generall** [comment]
As we don't plan to introduce batched + grouped search for now, I am going to close this issue. Please feel free to open again it if you have additional context of why this API would make sense
