### ISSUE TITLE
[Question] change the default embedding dimension for new collections?

### ISSUE THREAD

**Issue by vik-rant** [qdrant/qdrant#3955]
Is there any way, via config or env vars, to set a different embedding size (say 384 or 1024) for all new collections by default, at the server-level?

**Comment by generall** [comment]
No, currently it is not supported. 

This functionality looks very niche, could you please describe what's your use case?

**Comment by vik-rant** [comment]
Understood.
After some digging, I found that some other component in the pipeline is setting a fixed size that is forwarded to qdrant server.
And I assume embedding size is a mandatory parameter for creating a collection, and qdrant has no default value for it.
Thank you for your prompt response.
