### ISSUE TITLE
how to start docker service from local qdrant collections

### ISSUE THREAD

**Issue by srikanthmalla** [qdrant/qdrant#3981]
Hi,
I have created a local collections (on disk using path=...) of qdrantDB using provided examples, it contains close to 100k points with both dense and sparse vectors. I observe around 5-6sec for a single retrieval query with top_k=4 for both dense and sparse vectors using search_batch. With chroma the retrieval is less than 1 sec with only dense vectors, but the quality of retrieval is very bad when compared to qdrant.

From other issues, few people mentioned that for large scale DB or collection, docker or production setup or serving is better. How can I start a docker using existing qdrant DB and collections. And also what are some configurations (beginner friendly) that are easy to play around to speedup and reduce the latency.

Thank you,
Srikanth

**Comment by srikanthmalla** [comment]
I was able to resolve by recreating the collection using the docker service. It looks like the organization of folders and meta data seems different with docker and local-client. Since this got resolved, I am closing this issue.

**Comment by Cshekar24** [comment]
I'm having similar issue. I'm not able to load the collections, it says collection folder not found. What are the steps you have taken to resolve the issue?

**Comment by generall** [comment]
Hey @Cshekar24, local mode is not a part of qdrant core. It is a python-specific implementation. If you have a reproducible pipeline which would demonstrate the problem, please feel free to open an issue here https://github.com/qdrant/qdrant-client/issues
