### ISSUE TITLE
while RAGGing fails happen

### ISSUE THREAD

**Issue by yangboz** [qdrant/qdrant#3983]
while using Quadrant for PDF chunking and split text for RAGGing, then insert token to DQdrant   error happen, may be encounter some reserved words[%d '] ?  but official site missing this chapter.

## Current Behavior

```
UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d '
```

## Steps to Reproduce

1.
2.
3.
4.

python3.9 ,maces13.5.2 (22G91) , by : https://github.com/Otman404/local-rag-llamaindex
 
## Expected Behavior

 RAGing success.

**Comment by generall** [comment]
I don't think this is a right place for this issue. @yangboz please create it in the related repo
