### ISSUE TITLE
Feature request to control the flow of data in ALIAS feature

### ISSUE THREAD

**Issue by sarathsurpur** [qdrant/qdrant#3993]
**Is your feature request related to a problem? Please describe.**
I am maintaining a common collection and dedicated collections for specific groups. When I do incremental loading, is there a feature for updating the common collection that should replicate in all dedicated collections? I should be able to insert documents only in the dedicated collections. For fresh ingestion, the 'initiate the collection from common collection' feature helped me save time, but for incremental ingestion, I couldn't find an optimal way.

**Describe the solution you'd like**
In the alias feature, it would be helpful if we can control the flow of data

**Comment by timvisee** [comment]
We're introducing [RBAC](https://en.wikipedia.org/wiki/Role-based_access_control) soon, probably in Qdrant 1.9. It'll probably be sufficient to control the data flow like you describe above.

**Comment by generall** [comment]
RBAC is released in v1.9.0 now. @sarathsurpur I am going to close this issue, but please feel free to re-open it is you think RBAC doesn't solve your problem
