### ISSUE TITLE
Failing example from qdrant documentation

### ISSUE THREAD

**Issue by matthieudelaro** [qdrant/qdrant#3994]
In [Qdrant documentation](https://qdrant.tech/blog/qdrant-n8n/), the Workflow 1: GitHub Repository Ingestion into Qdrant, should run smoothly.

## Current Behavior
It fails with error
```
Problem in node ‘Qdrant Vector Store‘
400 Bad Request: Wrong input: Not existing vector name error:
```
[Screenshots and extra details](https://stackoverflow.com/questions/78297959/n8n-qdrant-working-example-in-the-documentation)

## Steps to Reproduce
[Detailed steps with full code and even screenshots](https://stackoverflow.com/questions/78297959/n8n-qdrant-working-example-in-the-documentation)

## Expected Behavior
https://qdrant.tech/blog/qdrant-n8n/

## Context (Environment)
What are you trying to accomplish? Same as in qdrant documentation : https://qdrant.tech/blog/qdrant-n8n/

## Detailed Description
[Detailed description, with full code and even screenshots](https://stackoverflow.com/questions/78297959/n8n-qdrant-working-example-in-the-documentation)

**Comment by Anush008** [comment]
Hi @matthieudelaro. It seems the collection is misconfigured. You don't need to explicitly create a collection.

The node automatically does so based on the embeddings.

You can try specifying a different collection name, which will be created by the node and data will be added into it.

**Comment by matthieudelaro** [comment]
Hi @Anush008,

thanks a lot for your answer, it solves the issue :)

So for the record, for future readers : a name of collection is required in the settings of the node.
Solution : choosing a name of collection which doesn’t exist yet

![grafik](https://github.com/qdrant/qdrant/assets/2452725/92b9714b-7d19-498b-aada-6faa7131807f)
![grafik](https://github.com/qdrant/qdrant/assets/2452725/7ca5007f-f3ba-4da2-9620-e91e7ad4abb4)

**Comment by CrustyData** [comment]
I'm doing exactly as you said: fill in a non existing collection and i receive the following error: 400 Bad Request: Wrong input: Not existing vector name error:. What could be the issue here? Also, i have one qdrant vector store node running with the exact same settings and that one works, now im trying to create another one and it doesnt.
