### ISSUE TITLE
Add deletion protection for collections

### ISSUE THREAD

**Issue by jdew89** [qdrant/qdrant#4009]
**Is your feature request related to a problem? Please describe.**
We would like to prevent accidental deletions of collections.

**Describe the solution you'd like**
Create a new config option on the collection like:
```
deletion_protection: true (default: false)
or
protected: true (default: false)
```
This would cause Qdrant to return a 403 on the deletion call if the collection is protected.

**Describe alternatives you've considered**
Being more careful with code.

**Additional context**
Why do we need this? We had a rogue `client.recreate_collection` still in our code and it deleted a collection due to an unfortunate sequence of events that ended up triggering it. Would love to prevent accidental deletions like this.

**Comment by generall** [comment]
![](https://i.imgflip.com/8mdziv.jpg)

**Comment by generall** [comment]
Seriously though, we will deprecate `recreate_collection` for good

**Comment by generall** [comment]
recreate_collection is deprecated in the latest version f qdrant client
