### ISSUE TITLE
Metrics endpoint doesn't expose all metrics

### ISSUE THREAD

**Issue by bbkgh** [qdrant/qdrant#4010]
Hi. According to this [docs link](https://qdrant.tech/documentation/guides/monitoring/) metrics like `rest_responses_total` are mentioned but they are not exposed in our environment. Is there another configuration to set?

`curl localhost:6339/metrics -H "api-key: KEY"` results to
```
# HELP app_info information about qdrant server
# TYPE app_info counter
app_info{name="qdrant",version="1.8.4"} 1
# HELP app_status_recovery_mode features enabled in qdrant server
# TYPE app_status_recovery_mode counter
app_status_recovery_mode 0
# HELP collections_total number of collections
# TYPE collections_total gauge
collections_total 2
# HELP collections_vector_total total number of vectors in all collections
# TYPE collections_vector_total gauge
collections_vector_total 16
# HELP cluster_enabled is cluster support enabled
# TYPE cluster_enabled counter
cluster_enabled 0

```

docker image: qdrant/qdrant:v1.8.4

**Comment by timvisee** [comment]
The above mentioned metric is only shown if it is at least one. What that means is that you'd have to send a REST request for it to show up. I believe `GET /collections` should be good enough.

**Comment by generall** [comment]
Hey @bbkgh, please feel free to re-open the issue if your problem is still not solved
