### ISSUE TITLE
Filtering by Distance

### ISSUE THREAD

**Issue by sujayrittikar** [qdrant/qdrant#4035]
**Is your feature request related to a problem? Please describe.**
Currently, we can't find distance between 2 points (ex: COSINE) through any API in Qdrant.
With a massive database that we have, just finding similar points doesn't do justice since there's also a necessity to set some threshold value of the distance to retrieve the vectors. This is specifically important for Classification or Clustering tasks.

For ex: If I just want to retrieve points that have a cosine distance of <0.3 -> This can help avoid unnecessary retrievals and avoid the hurdle of keeping up with distance calculations by explicitly using other libraries.

**Describe the solution you'd like**
Provide an additional parameter: something like **distance_threshold** in Filtering Endpoints (scroll, filter etc.), which can be set only if required and can help filter out unnecessary similar points right when we retrieve them.

**Comment by Waffleboy** [comment]
@sujayrittikar 

If you view the API documentation, you'll find it under search points/`score_threshold`

![image](https://github.com/qdrant/qdrant/assets/12254813/526c60e0-649e-41bb-92a0-3f21e44c2592)
