### ISSUE TITLE
qdrant monitoring metric rest_responses_fail_total, not showing specific collections name

### ISSUE THREAD

**Issue by ojbkxiongdei** [qdrant/qdrant#4099]
version: qdarnt 1.8.3
deploy: use docker to deploy qdrant cluster
issue:qdrant monitoring metric rest_responses_fail_total, not showing specific collections name
how to fix it?
![Uploading monitoring.png…]()

**Comment by timvisee** [comment]
It currently does not show per-collection metrics. So this is expected.

Please see the following issue for when we might implement this: https://github.com/qdrant/qdrant/issues/3322

Assuming that answers your question, I'm closing this issue.
