### ISSUE TITLE
How can I upsert on a collection containing multiple vectors?

### ISSUE THREAD

**Issue by destpat** [qdrant/qdrant#4101]
Creating a collection with multiple vectors is straightforward in the [API reference](https://qdrant.github.io/qdrant/redoc/index.html?v=master#tag/collections/operation/create_collection). There's also an option to delete a named vector from a collection.

However, I'm unable to find a method to upsert points into a specific vector within a collection. It seems this should be possible and fairly simple using Qdrant Langchain, with the use of [named vectors](https://python.langchain.com/docs/integrations/vectorstores/qdrant/#named-vectors).

**Describe the solution you'd like**

I would like to see both the documentation and the Qdrant SDK updated to support upsert operations with `named_vectors` more explicitly.

**Comment by destpat** [comment]
I didn't read the documentation correctly, so here's how to add a point to a specific vector using the TypeScript Quadrant SDK:

```javascript
  const points = {
    id: uuid(),
    vector: {
      custom_vector_1: [0.32, 0.3243, 0.123],
      custom_vector_2: [0.12, 0.4243, 0.103],
    },
    payload: {},
  };

  await clientQdrant.upsert(collectionName, { points });
```

**Comment by sushant-samespace** [comment]
Hi @destpat . I had a question regarding this. Can we search on these multiple vectors at the same time ? If so, could you provide a sample query please. Thanks.
