### ISSUE TITLE
CPU usage rate is too high

### ISSUE THREAD

**Issue by lijing5227** [qdrant/qdrant#4128]
<img width="918" alt="image" src="https://github.com/qdrant/qdrant/assets/20733031/22324da5-4712-4ea7-93d3-f1a82343e489">

How to solve this ?
Can anyone help ?

**Comment by generall** [comment]
looks like indexing. But would need a bit more context to be sure

**Comment by lijing5227** [comment]
1. The current operation is a similarity query
2. vectors_count： 11973992 Length:1024
3. searchParam: 
SearchPoints {
                                    collection_name: text_collection_name.to_string(),
                                    vector: vector.data,
                                    limit: 101,
                                    filter: Some(filter),
                                    params: Some(SearchParams {
                                        hnsw_ef: Some(128),
                                        exact: Some(true),
                                        ..Default::default()
                                    }),
                                    score_threshold: TEXT_SCORE_THRESHOLD.into(),
                                    with_payload: Some(false.into()),
                                    with_vectors: Some(false.into()),
                                    ..Default::default()
                                };
5.  Single data consumption：：800ms

> looks like indexing. But would need a bit more context to be sure

**Comment by timvisee** [comment]
Has it settled since then?

If indexing is going on your collection info will show a yellow status: https://qdrant.tech/documentation/concepts/collections/#collection-info

Qdrant will use all CPU cores by default. If you'd like something else, you can configure it that way in the configuration file.

**Comment by lijing5227** [comment]
> Has it settled since then?
> 
> If indexing is going on your collection info will show a yellow status: https://qdrant.tech/documentation/concepts/collections/#collection-info
> 
> Qdrant will use all CPU cores by default. If you'd like something else, you can configure it that way in the configuration file.

status is green and I'll try limit CPU cores, Thanks!

**Comment by timvisee** [comment]
Closing since I now assume this is resolved. Feel free to open it again if you have further questions.
