### ISSUE TITLE
Transfers with method snapshot fail when api auth enabled

### ISSUE THREAD

**Issue by Brian-Williams** [qdrant/qdrant#4147]
## Current Behavior

When shard transfers happen with method [snapshot](https://qdrant.tech/documentation/guides/distributed_deployment/#shard-transfer-method) the REST API won't send [authentication](https://github.com/qdrant/qdrant/blob/b99d507496a40b0895fff76eb2fa7a5cfdb701a9/lib/collection/src/shards/transfer/snapshot.rs#L174C9-L174C27) and the transfer won't succeed.

## Steps to Reproduce

1. Enable api auth
2. POST a transfer with method snapshot to `/collections/{collection_name}/cluster`
3. Fails to transfer

## Expected Behavior

Snapshot method works with any auth options.

## Possible Solution

Accept API key in the transfer endpoint or replace http calls with grpc.

## Context (Environment)

This is the suggested transfer method for new shards, so is the most likely method to get called.

We disabled api auth to confirm that was the issue and the transfer did work in that case.

Tested in v1.7.

**Comment by timvisee** [comment]
This is released as part of [Qdrant 1.9.1](https://github.com/qdrant/qdrant/releases/tag/v1.9.1).
