### ISSUE TITLE
untagged enum WithPayloadInterface error.

### ISSUE THREAD

**Issue by nemesis00sam** [qdrant/qdrant#4152]
Hi;

Field names of Metadata in vectorDB includes empty space.

`([Record(id='00025746-8f91-41e0-8ea9-363d10ecab07', payload={'metadata': {'Authors': 'Abraham Fer', 'Date published': '07/17/2023', 'Title of this paper': 'Optimization ', 'URL': 'link', 'file_name': 'dsffrfwefew.pdf'}}, vector=None, shard_key=None)`

But when I try to run scroll command, I'm getting error. How can I pass Date published field without error.

Qdrant version is 1.8.2.

`client.scroll(
    collection_name="Arxiv_zkp", 
    limit = 3,
    with_payload = ["metadata.URL","metadata.Date published"],
    with_vectors=False,  # change to True to see the vectors
)`

I appreciate your help. Thanks.

**Comment by timvisee** [comment]
Dates must follow the RFC 3339 notation, such as: `2023-07-17`

You can read more about it here: https://qdrant.tech/documentation/concepts/payload/#datetime

Closing the issue because I assume that'll fix it. Please feel free to open it again otherwise.
