### ISSUE TITLE
I can't create or upload snapshot in Qdrant's cloud

### ISSUE THREAD

**Issue by ThanawanJopol** [qdrant/qdrant#4174]
I use this pattern to upload snapshot but it didnt works. So I try again with create snapshot(bc its more simple maybe it gonna work), it didnt work too. I was stuck at this part for 2 days(IDK why lol).

Im just beginner. Please explain more for me
![image](https://github.com/qdrant/qdrant/assets/134232813/9b8be203-e501-4ca5-8bdb-84094c469d3c)

**Comment by timvisee** [comment]
You're using the web UI. It does not support curl commands. Instead it supports requests like this:

```
POST /collections/{collection_name}/snapshots
```

**Comment by ThanawanJopol** [comment]
If I want to use the curl command where can I use? Vscode?

**Comment by timvisee** [comment]
> If I want to use the curl command where can I use? Vscode?

 It should be usable in any terminal.

Yes, you'd probably be able to use it in the VSCode terminal too.
