### ISSUE TITLE
Issue in search latency with filters

### ISSUE THREAD

**Issue by SSK-14** [qdrant/qdrant#4237]
Facing an very slow response from qdrant when searched with filters. 
Without filters its faster. 

## Current Behavior

When we apply filter based on meta details like: 
{
   must: [{ key: 'article_id', match: { value: "8251929" } }],
};

Search take approximately between 14 to 17 secs.

## Expected Behavior

Would expect an similar or slightly slower response compared to search without filters. Example: 1 or 2 secs. 

## Context (Environment)

Qdrant db details:
- Running in a VM
- vectors count: 3413900

**Comment by timvisee** [comment]
Please make sure you configure a payload index for the keys on which you filter.

https://qdrant.tech/documentation/concepts/indexing/#payload-index

**Comment by SSK-14** [comment]
Thanks, we missed that @timvisee
