### ISSUE TITLE
Creating collections is too expensive

### ISSUE THREAD

**Issue by moy2010** [qdrant/qdrant#4241]
I've just started working with Qdrant, and so far I have faced two issues related to the creation of collections:

1. As part of the setup for my integration tests I create all the necessary database collections, but after adding Qdrant my integration tests are flaky because sometimes the request for creating the Qdrant collection times out
2. During the integration with Qdrant, I run my integration tests before setting up the tear-down logic the the database collections mentioned above, and found what I think is a nasty bug: The Qdrant server would choke and die (running it on my dev machine as a Docker container), restart and then become completely irresponsive for several minutes. After inspecting the logs, I noticed that the server was having a very hard time trying to start due to the high number of collections (on the order of hundreds).

## Current Behavior
Creating collections is a very expensive task for the server, and chokes under heavy load

## Steps to Reproduce
1. Run Qdrant as a Docker container
2. Create a few hundred collections
3. Profit

## Expected Behavior
Creating collections should not to be as resource intensive

## Context (Environment)
Ubuntu 22.04
Qdrant server v1.9.2 running as a docker container
Rust Qdrant client v 1.9.0

**Comment by coszio** [comment]
Qdrant is not designed to have that many collections, we consider an anti-pattern to work with it this way. Although it might be choking due to hitting some resource limit.

Could you describe why you need that many collections?

**Comment by moy2010** [comment]
> Qdrant is not designed to have that many collections, we consider an anti-pattern to work with it this way. Although it might be choking due to hitting some resource limit.

That far I could see, but setup & teardown is the cornerstone for integration tests and seeing the Qdrant server having such a hard time got me thinking.

> Could you describe why you need that many collections?

I don't need that many collections. I just started integrating with Qdrant and noticed the issue.

**Comment by generall** [comment]
Please consider this as an alternative: https://qdrant.tech/documentation/guides/multiple-partitions/

**Comment by moy2010** [comment]
> Please consider this as an alternative: https://qdrant.tech/documentation/guides/multiple-partitions/

Sorry, but this is not related with the stated problem. As I said, I don't need that many collections, it's just that before I wrote the code for the teardown a lot of collections where created, and that's how I noticed the performance issue.

**Comment by generall** [comment]
Hey @moy2010, if it is just for integration tests, there are a few configs you can tweak:

- limit the size of WAL. The default one is 32mb, you can set it to 1
- limit initial number of segments. The default value for high CPU system is 8, you can set it to 1.

**Comment by moy2010** [comment]
> Hey @moy2010, if it is just for integration tests, there are a few configs you can tweak:
> 
> * limit the size of WAL. The default one is 32mb, you can set it to 1
> * limit initial number of segments. The default value for high CPU system is 8, you can set it to 1.

Thanks for the recommendations, @generall ! They really helped to lower the cost of creating collections :smiley: .
