### ISSUE TITLE
what should the embedding and path be to use an existing collection?

### ISSUE THREAD

**Issue by abrar-tericsoft** [qdrant/qdrant#4263]
![image](https://github.com/qdrant/qdrant/assets/159236680/3f790a3e-5f2b-4810-a496-7eec4ffbef9d)

**Comment by timvisee** [comment]
This is a question about LangChain.

In your above example, `embeddings` be the embeddings you're using.

I believe `path` is only required if using local mode, but you've already specified an URL.

See more here: https://qdrant.tech/documentation/frameworks/langchain/#using-an-existing-collection
