### ISSUE TITLE
Connect Qdrant client to multiple nodes

### ISSUE THREAD

**Issue by xiaoxiper** [qdrant/qdrant#4279]
Hello, I have a self-hosted 3-node Qdrant cluster. [ip1:port , ip2:port, ip3:port]

How can I connect to this cluster using the Python Qdrant client? I noticed the following code, which seems to allow connection to only a single IP.

![image](https://github.com/qdrant/qdrant/assets/58277734/52d649a4-ed5b-4321-9b4c-dd9aa79da8d0)

I would greatly appreciate your help.

**Comment by timvisee** [comment]
You're correct. The client accepts a single IP.

There are a few things you can do:
1. Most commonly, you can put a load balancer in front. All traffic would go through the load balancer. The load balancer would spread the traffic to all 3 nodes under the hood.
2. You can create a client instance for each IP you have, and pick a random client in your code base each time you do a Qdrant query.
3. Always talk to a single node, and let it spread some traffic internally. This probably is suboptimal though, and so I would not recommend it.

**Comment by xiaoxiper** [comment]
Understood. Thanks.

**Comment by buildgreatthings** [comment]
This is a pretty poor design if its expected for client to handle use a load balancer or guess on their own. Why is there no qdrant client efficient way in Redis or MongoDB? Can the Qdrant team make a fix for this?

https://stackoverflow.com/questions/59907831/connect-to-4-different-redis-server-createclient-without-using-cluster-on-node
https://stackoverflow.com/questions/69658590/mongoclient-to-connect-to-multiple-hosts-to-handle-failover
