### ISSUE TITLE
Payload field index on disk/memory setting

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#4389]
Hello.
I tried to add fields with index a lot
I did not know how these indexes work
on memory or on disk

How can I change location for a index of payload field?
Thanks.

**Comment by generall** [comment]
it is always in RAM. On-disk payload indexes are on the roadmap

**Comment by Vasniktel** [comment]
@generall Is there any estimate on when on-disk payload indices will be released?

**Comment by generall** [comment]
In v1.11

**Comment by Vasniktel** [comment]
@generall I'm curious - do you have any release schedule (e.g. minor version every n months etc)?

**Comment by generall** [comment]
no

**Comment by ava57r** [comment]
[[On disk payload index] Tracking issue](https://github.com/qdrant/qdrant/issues/4502)
