### ISSUE TITLE
Aborted when put collection with a large optimizers_config.default_segment_number

### ISSUE THREAD

**Issue by secreu** [qdrant/qdrant#4398]
## Current Behavior

When requesting PUT collection/{collection_name} with large optimizers_config.default_segment_number, system receives SIGABRT.
This may cause Denial of Service.

## Steps to Reproduce

version: 1.9.4
We set default_segment_number a large number, here is 16384.
```python
from qdrant_client import QdrantClient, models
client = QdrantClient(location="localhost", port=6333)

response = client.create_collection(
    collection_name = "test",
    vectors_config = models.VectorParams(size=4, distance="Cosine"),
    optimizers_config = models.OptimizersConfigDiff(default_segment_number=16384)
)

print(response)
```
Qdrant logs as below
```
2024-06-05T09:35:07.433198Z  INFO storage::content_manager::toc::collection_meta_ops: Creating collection test    
terminate called without an active exception
terminate called recursively
terminate called recursively
Aborted
```

## Expected Behavior

Though a large default_segment_number seldom occurs, Qdrant should handle the invalid parameter instead of crash.

## Possible Solution

Check the parameter before excute.

**Comment by secreu** [comment]
Hi, thank you for clearing this up.
But I think the running server should prompt me that it's not a appropriate or common value instead of crashing directly.

**Comment by generall** [comment]
I think we can add a validation there. Thanks for reporting anyway
