### ISSUE TITLE
Windows CI stopped working

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#4419]
It looks like rocksdb stopped working with `windows-latest` CI. 

Related issue in RocksDB repo: https://github.com/rust-rocksdb/rust-rocksdb/issues/896

Some symptoms we observe:

1. Binary built on CI can still work normally on another server
2. Binary built on another server fails on CI with segfault when you try to create collection
3. If test uses rocksdb in any form - it fails with segfault error
4. No packages except for `windows-latest` image were updated, running test on older versions of qdrant generates the same error

## Current Behavior

Whenever any rocksdb object is used, the CI machine crashed with `code 0xc0000005: Invalid access to memory location`. No matter if it is database object or just config.

## Steps to Reproduce

1. Run CI test on `windows-latest`

## Expected Behavior

No segfault

## Possible Solution

There is a suspicion, that the bug might be related to some kind of new security/runtime policies in latest windows updates. Or related to rocks

## Context (Environment)

Solving this issue might require fixing the original problem inside rocksdb repo

**Comment by generall** [comment]
related: https://github.com/actions/runner-images/issues/10004#issuecomment-2157555139

**Comment by generall** [comment]
Apparently, it is a global problem

**Comment by ezhil56x** [comment]
> Apparently, it is a global problem

Yeah, my PR can be good workaround, till the new release of `windows-latest`

**Comment by timvisee** [comment]
This has been fixed by <https://github.com/qdrant/qdrant/pull/4461>.

**Comment by ImBIOS** [comment]
Can someone please takedown this bounty in algora if it's already fixed?

![image](https://github.com/user-attachments/assets/f2608e6b-8c99-4da0-8a06-d061b795c0fb)
