### ISSUE TITLE
[performance] HNSW graph memory locality

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#442]
**Is your feature request related to a problem? Please describe.**
Try to improve data locality for HNSW graph.

Currently, all HNSW links are stored as vector of vectors. 
On the other hand, the original HNSW implementation uses plain array of memory for this.
The issue is that unlike original implementation, we cannot guarantee that the total amount of stored links won't exceed `M`.

**Describe the solution you'd like**
Try hybrid approach - store the first `M` links and if more links required - use extendable storage. 

**Describe alternatives you've considered**
TBD

**Comment by IvanPleshkov** [comment]
Done in https://github.com/qdrant/qdrant/pull/1171
