### ISSUE TITLE
Appending vector data without providing the ID

### ISSUE THREAD

**Issue by vincenthawke** [qdrant/qdrant#4438]
I am trying to add batches of vectors appended to my database every day. If I set an ID that already exist it will replace the vector. If I do not provide an ID for my upload, I get an error. Am I supposed to always check if the ID already exists before uploading?

**Describe the solution you'd like**
A way to append vectors without ID. In case of a duplicated vector it would just get saved again and ID would get incremented by 1.

**Comment by coszio** [comment]
You can use new uuids if you want to always upload a new point.

**Comment by vincenthawke** [comment]
Perhaps I misunderstand how uuids work. Will each one always be unique? I assume I need to use some sort of a seed from vector data to guarantee that.

**Comment by generall** [comment]
Auto-incrementing IDs will contradict the idempotent property of the API. We will not implement this. It is only make sense for single-machine deployments

> I assume I need to use some sort of a seed from vector data to guarantee that.

UUID is 128 bit long, it is not possible to generate same UUID randomly

**Comment by vincenthawke** [comment]
Oh I see. The reason why you don't want non-unique IDs like starting from 1, 2, etc... is because it represents a hassle when you want to combine several databases. Fair, I can work with UUID too. Thanks for explaining. 

I was confused, because here https://qdrant.tech/documentation/concepts/points you say "If ids are not provided, they will be generated automatically as UUIDs.", but I can't find any API in documentation that would not throw an error when I try to upload a point without an ID, so I'll just have to generate UUIDs locally.

**Comment by generall** [comment]
> you say "If ids are not provided, they will be generated automatically as UUIDs."

This is only specific to python client method. It will generate UUIDs on the client side

**Comment by vincenthawke** [comment]
This may not be the best place but could you recommend me a library/standard for generating UUIDs that fits best with your architecture, specifically for performance? NanoID, UUIDv7, KSUID?

**Comment by timvisee** [comment]
With regards to potential collisions, UUIDs are generally considered collision free. See: https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions
