### ISSUE TITLE
Cannot delete collection with long name

### ISSUE THREAD

**Issue by vyom-vora** [qdrant/qdrant#4568]
I'm able to create a collection with long name, but when i try to delete that collection, it throws an error saying "Unexpected Response: 500 (Internal Server Error)
Raw response content:
b'{"status":{"error":"Service internal error: File name too long (os error 36)"},"time":0.064506633}'".

**Comment by generall** [comment]
could you please provide more context about your issue:

- what versions are you using
- steps to reproduce

**Comment by superseb** [comment]
This seems to happen in https://github.com/qdrant/qdrant/blob/master/lib/storage/src/content_manager/toc/collection_meta_ops.rs#L193:

```
            // Move collection to ".deleted" folder to prevent accidental reuse
            let uuid = Uuid::new_v4().to_string();
            let removed_collections_path =
                Path::new(&self.storage_config.storage_path).join(".deleted");
            tokio::fs::create_dir_all(&removed_collections_path).await?;
            let deleted_path = removed_collections_path
                .join(collection_name)
                .with_extension(uuid);
            tokio::fs::rename(path, &deleted_path).await?;
```

Although we limit our collection name on max of 255, the deletion moves it to the `.deleted` folder with the extension of a UUID. The UUID is 36 characters, plus the extension dot (`.`) so any collection name over 218 characters will hit this issue. If you issue the DELETE request a second time, it won't respond with `result: true` but it will delete the collection as it is not currently loaded:

```
2024-07-02T09:24:24.552519Z  WARN storage::content_manager::toc::collection_meta_ops: Collection extremelylongnameextremelylongnameextremelylongnameextremelylongnameextremelylongnameextremelylongnameextremelylongnameextremelylongnameextremelylongnameextremelylongnameextremelyextremelyextremelyextremelyextremelyextr is not loaded, but its directory still exists. Deleting it.
```

**Comment by JojiiOfficial** [comment]
Here is a way to reproduce it:
```curl
PUT collections/38cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd
{
  "vectors": {
    "size": 4,
    "distance": "Dot"
  }
}

DELETE collections/38cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd1838cb23c5-d842-4319-bc38-6c68396dcd
```

**Comment by timvisee** [comment]
Fixed by <https://github.com/qdrant/qdrant/pull/5439>.
