### ISSUE TITLE
Missing results when invoke "search" api under certain filter conditions.

### ISSUE THREAD

**Issue by GoFcys** [qdrant/qdrant#4574]
## Current Behavior
I copied the vector of a saved point, and searched with the vector and filter like this:
```python
query_filter = models.Filter(
    must=[
        models.FieldCondition(key="knowledge_base_id", match=models.MatchAny(any=[x for x in kb_ids])),
        # models.FieldCondition(key="knowledge_item_id", match=models.MatchAny(any=[106482]))
    ]
)
res = client.search(
    collection_name="test",
    query_vector=("content", vector),
    query_filter=query_filter,
    limit=100,
)
```
but the target point which i copied vector from was not in the result list. 
When i uncomment the second search condition `models.FieldCondition(key="knowledge_item_id", match=models.MatchAny(any=[106482]))`, i got the result with one point i want. The point's `knowledge_item_id` is 106482.

This situation only occurs when `knowledge_base_id` is set to certain values. In most cases, the search results are normal.

If set the param `exact=True` i can get correct results. But I still want to know why this happens and how much impact the param `exact=True` has on performance.

**Comment by generall** [comment]
Hey @GoFcys, vector search is by-design approximate.
If search doesn't find some results - this is expected behavior. 
You can tune accuracy with `hnsw` params or even use `exact=True` https://qdrant.tech/documentation/tutorials/retrieval-quality/?q=hnsw#tweaking-the-hnsw-parameters . We can't predict performance for your use-case,as it depends on many factors.

If you think that the accuracy is too low for your use case, please share dataset and reproducible example, we will try to see if it is something we can change in qdrant to make it better

**Comment by GoFcys** [comment]
Thank you for your reply.
The problematic dataset was initially built on a VMware virtual machine, which lacked CPU instruction sets such as AVX. It is likely due to this reason that operations like searching can cause qdrant to crash. 
Later on, I exported a snapshot of this collection and imported it to another server without any issues. Although it won't crash again, the query results may encounter unexpected situations, as mentioned at the beginning. 
Finally, I re established a collection and re imported the data one by one, instead of using snapshots from the original collection. At this point, the query problem no longer occurred and everything became normal. 
So I suspect that the missing instruction set may have caused the dataset to be damaged, and even if the dataset is migrated to another server with no issues through a snapshot, it cannot be repaired.
I am sorry that I am currently unable to provide the dataset with the problem. If similar issues arise in the future, let's discuss them further.
