### ISSUE TITLE
Collection versions incompatability with recent update

### ISSUE THREAD

**Issue by marcoramosw** [qdrant/qdrant#4582]
I have been using qdrant:latest version since 2 weeks ago, using a persistent volume in my host machine,

about 2 days ago I started having problems whenever I started the container and it kept exiting with the error message:

![image](https://github.com/qdrant/qdrant/assets/64008308/f56d24d2-f066-4ade-aaf0-071aa6fca344)

So I did see that the version.info file of my "Germany" collection had 0.3.1 in it, and suddenly my latest image was probably updated to use version 0.4.2.

Ok, fine but when I look for a qdrant image version all I see is 1.9.x above, where does this 0.4.2 or 0.3.1 come from? what version is this?
I tried qdrant:v1.9.3 and still kept saying the collection needed to be version 0.4.2...

**Comment by timvisee** [comment]
Do you happen to know which version you used previously?

Also, could you give this another try by using `qdrant/qdrant:v1.9.7` explicitly?

**Comment by marcoramosw** [comment]
I was always using qdrant/qdrant:latest.

as of now I tried with v1.9.7, v1.9.6, v1.9.3

still same issue, it doesn't read collections that have version 0.3.1 as it expects them to be 0.4.2

**Comment by generall** [comment]
v0.4.2 refers to version of the internal crate https://github.com/qdrant/qdrant/blob/master/lib/collection/Cargo.toml#L3

It was released in 2022, looks like you are trying to upgrade from really old version.

Thanks for using qdrant for so long, btw

**Comment by timvisee** [comment]
And, assuming that is the case: the proper way to upgrade is a rolling update over each minor version. That'll take care of properly migration your collection.

**Comment by marcoramosw** [comment]
> v0.4.2 refers to version of the internal crate https://github.com/qdrant/qdrant/blob/master/lib/collection/Cargo.toml#L3
> 
> It was released in 2022, looks like you are trying to upgrade from really old version.
> 
> Thanks for using qdrant for so long, btw

But I have only been using qdrant for 2 weeks, that's the problem. the qdrant:latest image was using an internal crate version of 0.3.1 (at least for me)

**Comment by timvisee** [comment]
Maybe you already had the old version on your system. If you use `:latest` directly, Docker won't pull a new image unless you explicitly tell it to.

As mentioned, the version was changed on the 14th of July 2022: https://github.com/qdrant/qdrant/blame/d1dda7e7f6fb42ef2d27f8ec29cea651c51ff517/lib/collection/Cargo.toml#L3

Anyway. If you'd like to recover your collection the above procedure for upgrading is still the way it should be done.

**Comment by marcoramosw** [comment]
I have only been working on this PC since 2 months, and I have only been working on the project requiring qdrant since 2 weeks, so I am 100% sure I didn't have any previous versions of the image. But maybe there was something else going on. Anyway, thank you

**Comment by coszio** [comment]
Closing this issue as it seems to be resolved by updating minor by minor versions. Feel free to reopen if it is not the case
