### ISSUE TITLE
Update with strong/medium ordering might try to deactivate last active shard 

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#4629]
## Current Behavior

Currently, if update request fails with strong/medium ordering guarantee, it is always try to deactivate "leader" shard.
In case of this leader shard is the only one, it will create an inconsistency, where node will try to deactivate last peer,
but consensus won't allow it.

It will result in a following error, if locally deactivated peer is queried:

```
{
  "error": "Service internal error: 0 of 0 read operations failed"
}
```

## Steps to Reproduce

1. Run distributed cluster with 2 nodes
2. Create collection with 1 shard upload some data
3. Shut down the peer with local shard
4. Try to make an update with strong consistency guarantee (it will fail)
5. Bring peer back online
6. Try to read collection info from the peer which was not restarted

## Expected Behavior

Peer should not be locally deactivated.

## Possible Solution

Make additional checks in the logic of deactivation.

**Comment by timvisee** [comment]
This problem is resolved by <https://github.com/qdrant/qdrant/pull/4631>, which will be included in the upcoming patch release.
