### ISSUE TITLE
Shifting already created collections from in memory to disk

### ISSUE THREAD

**Issue by Faiee50** [qdrant/qdrant#4649]
I have created collections with default qdrant configurations , with on_disk param to false, now it is taking alot of system memory. Is there any way i can shift already created collection to disk with some memmap parameters to segements some data per segment in memory...
This is my docker configurations which i used

services:
  qdrant:
    image: qdrant/qdrant
    container_name: stagging_qdrant_crd
    ports:
      - "5000:6333"
    volumes:
      - /home/ubuntu/stagging_qdrant_cdr:/qdrant/storage
      - /home/ubuntu/stagging_qdrant_cdr_snapshots:/qdrant/snapshots
    restart: always
    mem_limit: 28g
    memswap_limit: 30g
    environment:
      RUST_LOG: "info"
      QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
      QDRANT__STORAGE__SNAPSHOTS_PATH: "/qdrant/snapshots"
      QDRANT__STORAGE__TEMP_PATH: "/qdrant/tmp"
      QDRANT__STORAGE__ON_DISK_PAYLOAD: "true"
      QDRANT__STORAGE__WAL__WAL_CAPACITY_MB: "128" # Increased WAL capacity
      QDRANT__STORAGE__WAL__WAL_SEGMENTS_AHEAD: "2" # Increased pre-allocation of WAL segments
      QDRANT__STORAGE__PERFORMANCE__MAX_SEARCH_THREADS: "0"
      QDRANT__STORAGE__PERFORMANCE__MAX_OPTIMIZATION_THREADS: "2" # Increased optimization threads
      QDRANT__STORAGE__OPTIMIZERS__DELETED_THRESHOLD: "0.2"
      QDRANT__STORAGE__OPTIMIZERS__VACUUM_MIN_VECTOR_NUMBER: "1000"
      QDRANT__STORAGE__OPTIMIZERS__DEFAULT_SEGMENT_NUMBER: "0"
      QDRANT__STORAGE__OPTIMIZERS__MAX_SEGMENT_SIZE_KB: "65536" # Increased max segment size
      QDRANT__STORAGE__OPTIMIZERS__MEMMAP_THRESHOLD_KB: "65536" # Set memmap threshold
      QDRANT__STORAGE__OPTIMIZERS__INDEXING_THRESHOLD_KB: "20000"
      QDRANT__STORAGE__OPTIMIZERS__FLUSH_INTERVAL_SEC: "5"
      QDRANT__STORAGE__OPTIMIZERS__MAX_OPTIMIZATION_THREADS: "2" # Ensure optimization threads match
      QDRANT__STORAGE__HNSW_INDEX__M: "16"
      QDRANT__STORAGE__HNSW_INDEX__EF_CONSTRUCT: "100"
      QDRANT__STORAGE__HNSW_INDEX__FULL_SCAN_THRESHOLD_KB: "10000"
      QDRANT__STORAGE__HNSW_INDEX__MAX_INDEXING_THREADS: "0"
      QDRANT__STORAGE__HNSW_INDEX__ON_DISK: "false"
      QDRANT__SERVICE__MAX_REQUEST_SIZE_MB: "32"
      QDRANT__SERVICE__MAX_WORKERS: "0"
      QDRANT__SERVICE__HOST: "0.0.0.0"
      QDRANT__SERVICE__HTTP_PORT: "6333"
      QDRANT__SERVICE__GRPC_PORT: "6334"
      QDRANT__SERVICE__ENABLE_CORS: "true"
      QDRANT__SERVICE__ENABLE_TLS: "false"
      QDRANT__SERVICE__VERIFY_HTTPS_CLIENT_CERTIFICATE: "false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

**Comment by joein** [comment]
hi @Faiee50 

you can update collection parameters with 

https://qdrant.tech/documentation/concepts/collections/?q=update_collec#update-collection-parameters

or you can put particular vectors on disk with 

https://qdrant.tech/documentation/concepts/collections/?q=update_collec#update-vector-parameters

I would also recommend considering quantization https://qdrant.tech/documentation/guides/quantization/?q=scalar#scalar-quantization

**Comment by timvisee** [comment]
Note that when you change this, all your data will be optimized again.

That means that it might take a while for all of it to be moved to disk.

During this period your collection status will be yellow :yellow_circle:. Once it's done it's green :green_circle: .

**Comment by Faiee50** [comment]
Thanks @joein and @timvisee .. can i do the same configuration in docker compose file? If you can look my above docker compose file what configurations i do need to set.

**Comment by lyoot** [comment]
curl -X PATCH "http://localhost:6333/collections/NameYourCollections" \
     -H "Content-Type: application/json" \
     -d '{
           "vectors": {
             "": {
               "on_disk": true
             }
           }
