### ISSUE TITLE
Add details to the collection overview

### ISSUE THREAD

**Issue by azayarni** [qdrant/qdrant#4651]
**Is your feature request related to a problem? Please describe.**
 Currently, the dashboard-collection view is not very helpful.

**Describe the solution you'd like**
It will be more convenient if there is a list view of basic information of all collections like: number of points, status, shards number, etc.
**Describe alternatives you've considered**

FYI. Requested by a user.

**Comment by Fuelinger** [comment]
Since the Web UI (dashboard) is a separate project, your post would be probably better adressed here --> https://github.com/qdrant/qdrant-web-ui
