### ISSUE TITLE
Filtering: Support for Subset Matching in Array Fields

### ISSUE THREAD

**Issue by mautini** [qdrant/qdrant#4679]
Hello,

**Is your feature request related to a problem? Please describe.**
Today, I encountered a use case that seems not to be covered by the current filtering capabilities of Qdrant: I would like to express something like: "Given a match query for a field with an array, match all the points that have a subset of the array query for this field."

For example, let's consider I have the following points in my collection:
```
[
  { "id": 1, "city": "London", "colors": ["green", "blue"] },
  { "id": 2, "city": "London", "colors": ["red", "blue"] },
  { "id": 3, "city": "London", "colors": ["blue", "yellow"] },
  { "id": 4, "city": "Berlin", "colors": ["red"] },
  { "id": 5, "city": "Moscow", "colors": ["green", "yellow"] },
  { "id": 6, "city": "Moscow", "colors": ["blue"] }
]
```

Now considering a query like this (which does not exist in Qdrant):
```
POST /collections/{collection_name}/points/scroll
{
    "filter": {
        "must": [
            { "key": "colors", "match_subset": { "value": ["blue", "green", "yellow"] } }
        ]
    }
    ...
}
```

The result would be:
```
[
  { "id": 1, "city": "London", "colors": ["green", "blue"] },
  { "id": 3, "city": "London", "color": ["blue", "yellow"] },
  { "id": 5, "city": "Moscow", "color": ["green", "yellow"] },
  { "id": 6, "city": "Moscow", "color": ["blue"] }
]
```

**Describe the solution you'd like**
Add a new filtering clause that allows filtering as shown in the example above. Alternatively, add an argument to the match clause to support this use case (cf. how Elasticsearch handles it below).

**Describe alternatives you've considered**
- **Compute all possible combinations and combine them with exact matches**. However, this approach has two issues:
    - It could be expensive if we have many elements in the query (10 elements in the query produce 1023 combinations).
    - It seems it is not possible to exact match a query array with a point field array (maybe by combining MUST with a simple match clause?).
- **Apply post-filtering**, but this would require retrieving more points from Qdrant (or performing more queries if we don't get any points in the first call). Also, the built-in filtering is one of the main reasons we chose Qdrant.
- **Switch to another engine**; [it seems Elasticsearch supports this use case](https://stackoverflow.com/questions/72004393/how-to-return-all-documents-that-has-a-subset-of-input-array-in-opensearch).

**Additional context**
/

**Comment by coszio** [comment]
Isn't this already covered by MatchAny?

**Comment by mautini** [comment]
No, in the provided example, `match any` will also return `id 2`, which is not expected. I want only the points where all the values in the payload are in the match query, or "all the points where the `colors` value is a subset of the match query value."

**Comment by coszio** [comment]
You're right, I missed that, sorry!

However, (and fortunately for you), I think that [`MatchExcept`](https://qdrant.tech/documentation/concepts/filtering/#match-except) inside a `must_not` is what you are looking for.

From the docs:
> In this example, the condition will be satisfied if the stored value is neither black nor yellow.
>
> If the stored value is an array, it should have at least one value not matching any of the given values. E.g. if the stored value is ["black", "green"], the condition will be satisfied, because "green" does not match "black" nor "yellow".

So, by negating it, we get the behavior that you are requesting. i. e. Points that don't have any value that is not in the list.

I just confirmed that this filter will get the points you described:
```
POST /collections/{collection_name}/points/scroll
{
  "filter": {
    "must_not": {
      "key": "colors",
      "match": {
        "except": ["blue", "green", "yellow"]
      }
    }
  },
  ...
}
```

**Comment by mautini** [comment]
Wow, you're right! I didn't realize this behavior with `except` on arrays. Thanks a lot, and sorry for this unnecessary issue. I'll close the related PR too.
