### ISSUE TITLE
Out Of Memory with on_disk = true

### ISSUE THREAD

**Issue by pvictorlv** [qdrant/qdrant#4689]
I'm facing out of memory near ~2k collections with 3 records each. I've configured my qdrant server with storage.on_disk_payload = true, hnsw_index.on_disk = true and vectors.on_disk = true but qdrant still uses all of server memory on boot. I also can't perform new insert/search after a out of memory crash.

## Current Behavior
The qdrant instance just crashes when restart loads all collections on memory.

## Steps to Reproduce
1. Set all on_disk properties to true
2. Insert lots of collections untill your RAM goes to 100%
3. Restart qdrant
4. Try to insert/search

## Expected Behavior
The server should work without loading all collections on RAM

## Context (Environment)
Dedicated Linode Instance 32GB / 16C with SSD/NVMe

## Detailed Description
Config file
```
log_level: INFO
debug: false

service:
  host: 0.0.0.0
  http_port: 6333
  # Uncomment to enable gRPC:
  #grpc_port: 6334
  telemetry_disabled: true

storage:
  storage_path: ./storage

  snapshots_path: ./snapshots

  snapshots_config:
    snapshots_storage: local

  temp_path: null

  on_disk_payload: true

  update_concurrency: null

  wal:
    wal_capacity_mb: 32

    wal_segments_ahead: 0

  node_type: "Normal"

  performance:
    max_search_threads: 16
    max_optimization_threads: 8
    optimizer_cpu_budget: 0
    update_rate_limit: null

  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size_kb: 512
    memmap_threshold_kb: null
    indexing_threshold_kb: 10000
    flush_interval_sec: 10
    max_optimization_threads: 9
  hnsw_index:
    m: 16
    ef_construct: 100
    full_scan_threshold_kb: 10000
    max_indexing_threads: 8
    on_disk: true
    payload_m: null

  shard_transfer_method: null
  collection:
    replication_factor: 1
    write_consistency_factor: 1
    vectors:
      on_disk: true
    quantization:
      scalar:
        type: "int8"
        quantile: 0.99
        always_ram: true

telemetry_disabled: true
```

**Comment by pvictorlv** [comment]
Also, sometimes i'm getting this log:

terminate called without an active exception
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively

**Comment by timvisee** [comment]
We **strongly recommend against** creating that many collections. We recommend to have a few at most.

Collections have quite a bit of overhead, which is why you're likely seeing OOM.

Instead we recommend to store everything in a single collection and apply multitenancy/partitioning based on payload filters. That will be both faster and smaller in terms of memory and storage.

Documentation: https://qdrant.tech/documentation/guides/multiple-partitions/

**Comment by pvictorlv** [comment]
The problem was caused by multi collection. Using a single collection solved the issue.
Thanks.
