### ISSUE TITLE
S3 snapshots storage feature: missing endpoint_url parameter in documentation, credentials not picked up from env vars

### ISSUE THREAD

**Issue by mdnfiras** [qdrant/qdrant#4701]
## Current Behavior
Cannot create snapshots after setting S3 config

## Steps to Reproduce
1. Set the following S3 configuration + env vars `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`:
```yaml
storage:
  snapshots_config:
    snapshots_storage: s3
    s3_config:
      bucket: my-bucket
      endpoint_url: https://storage.googleapis.com # this option is not in the documentation, but is supported here.
```
2. Grant the associated service account proper permissions on the bucket
3. Run `curl -s -X POST http://localhost:6333/snapshots?wait=true` from within the qdrant pod (sidecar container, or port-forwarding, etc...)
4. Get error:
```
{"status":{"error":"Service internal error: failed to store snapshot archive to /qdrant/./storage/tmp/mycollection-1607136923954491-2024-07-18-19-08-00.snapshot-arc-3kbVmU: Service internal error: Failed to put multipart: Generic S3 error: Client error with status 405 Method Not Allowed: <!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 405 (Method Not Allowed)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>405.</b> <ins>That’s an error.</ins>\n  <p>The request method <code>PUT</code> is inappropriate for the URL <code>/latest/api/token</code>.  <ins>That’s all we know.</ins>\n"},"time":2.489350417}
```

## Expected Behavior

Snapshot creation works

## Possible Solution

use [AmazonS3Builder::from_env()](https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.from_env) to get configs from environment variables

## Context (Environment)
Qdrant v1.10.0 on Kubernetes

**Comment by mdnfiras** [comment]
Actually there should be support for endpoint_url [here](https://github.com/kemkemG0/qdrant/blob/bd5ac780d8450a141814db2a9815d884758cf26d/lib/collection/src/common/snapshots_manager.rs#L40) and [here](https://github.com/kemkemG0/qdrant/blob/bd5ac780d8450a141814db2a9815d884758cf26d/lib/collection/src/common/snapshots_manager.rs#L80). It's just [not mentioned in the docs](https://qdrant.tech/documentation/concepts/snapshots/#s3).

But I'm still getting the same error even after setting `endpoint_url` to `https://storage.googleapis.com`. I also tried setting `access_key` and `secret_key` in the config (rather than env vars).

**Comment by generall** [comment]
I don't think qdrant should use AWS-specific env variables. You should try regular ones like this:

`QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__ACCESS_KEY=...`

**Comment by generall** [comment]
I consider this resolved, please feel free to re-open if there is any additional context

**Comment by mdnfiras** [comment]
thanks @generall , env vars `QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__ACCESS_KEY` and `QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__SECRET_KEY` work!

The [documentation](https://qdrant.tech/documentation/concepts/snapshots/#s3) is still misleading though:
* it says that credentials could be set in `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env vars.
* it doesn't mention the `storage.snapshots_config.s3_config.endpoint_url` setting.
