### ISSUE TITLE
Unexpected Response: 404 (Not Found)  on localhost

### ISSUE THREAD

**Issue by widarr** [qdrant/qdrant#4739]
## Current Behavior
getting this error in PyCharm: 

qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 404 (Not Found)
Raw response content:
b''

getting this error in the qdrant console:

2024-07-23T19:41:47.818065Z  INFO actix_web::middleware::logger: 127.0.0.1 "POST /collections/My_Collection/points/query HTTP/1.1" 404 0 "-" "python-httpx/0.27.0" 0.000072    

## Steps to Reproduce
Followed the langchain Qdrant tutorial: https://python.langchain.com/v0.2/docs/integrations/vectorstores/qdrant/
Started qdrant from console:

qdrant --config-path ./config.yaml

(attached config.yaml)

My Code:

qdrant_url = "http://localhost:6333"
qdrant = QdrantVectorStore.from_documents(
    documents=splitted_docs,
    embedding=ollama_embeddings,
    url=qdrant_url,
    prefer_grpc=False,
    collection_name="My_Collection",
    retrieval_mode=RetrievalMode.DENSE,
    force_recreate=False,
)

The interesting thing is, that the vectorstore seems to be successfully created under ./storage

## Expected Behavior
Just connect to the local qdrant instance and post a query, get response

[config.yaml.zip](https://github.com/user-attachments/files/16353756/config.yaml.zip)

**Comment by generall** [comment]
which version of qdrant are you running?

**Comment by widarr** [comment]
qdrant: 1.9.4-1
langchain: 0.2.11
langchain-qdrant: 0.1.2

**Comment by timvisee** [comment]
You're using the query API, which requires at least Qdrant server 1.10.

I'd recommend to upgrade.

I assume using `location=":memory:"` works fine because the Qdrant client you're using is already up to date.

**Comment by hdotking** [comment]
For anyone else with this issue, I fixed this error by pulling the latest version of qdrant's docker image via `qdrant/qdrant:latest`
