### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by zhangzf875** [qdrant/qdrant#4761]
There are more than 4900 collections on qdrant, have tried to optimize the memory in the following ways, but the memory has not come down, how can this be improved.So far, 24 gigabytes of memory have been used
https://qdrant.tech/documentation/guides/quantization/?q=scalar#scalar-quantization
https://qdrant.tech/documentation/guides/optimize/
Please take a look at the configuration of each set
Set configuration
{
  "result": {
    "status": "green",
    "optimizer_status": "ok",
    "vectors_count": 1549,
    "indexed_vectors_count": 0,
    "points_count": 1548,
    "segments_count": 2,
    "config": {
      "params": {
        "vectors": {
          "size": 1536,
          "distance": "Cosine",
          "on_disk": true
        },
        "shard_number": 1,
        "replication_factor": 1,
        "write_consistency_factor": 1,
        "on_disk_payload": true
      },
      "hnsw_config": {
        "m": 16,
        "ef_construct": 100,
        "full_scan_threshold": 10000,
        "max_indexing_threads": 0,
        "on_disk": true
      },
      "optimizer_config": {
        "deleted_threshold": 0.2,
        "vacuum_min_vector_number": 1000,
        "default_segment_number": 0,
        "max_segment_size": null,
        "memmap_threshold": 20000,
        "indexing_threshold": 20000,
        "flush_interval_sec": 5,
        "max_optimization_threads": 1
      },
      "wal_config": {
        "wal_capacity_mb": 32,
        "wal_segments_ahead": 0
      },
      "quantization_config": {
        "scalar": {
          "type": "int8",
          "always_ram": false
        }
      }
    },
    "payload_schema": {}
  },
  "status": "ok",
  "time": 0.00002937
}

**Comment by JojiiOfficial** [comment]
You have way too many collections. Each collection has quite some overhead and using this much is bad practice, which we strongly recommend against.
Please reduce the amount of collections. You can do this for example by putting the vectors in the same collection and use payloads with indices.
 
If you still experience memory issues after reducing your collections to maximum a few, reopen this issue with more details on your configuration.

**Comment by zhangzf875** [comment]
Ok, I really feel your prompt

**Comment by timvisee** [comment]
For reference, we document that here: https://qdrant.tech/documentation/guides/multiple-partitions/
