### ISSUE TITLE
Snapshot Creation Under Yellow(optimizing) Status

### ISSUE THREAD

**Issue by pleomax0730** [qdrant/qdrant#4853]
What are the implications of creating a snapshot while the collection is still under yellow(optimizing) status? 

Specifically, will a collection recovered from this snapshot exhibit different behavior or results compared to a snapshot created when the collection is in green status?

**Comment by timvisee** [comment]
Snapshotting a yellow status is fine.

Yellow means that optimizations are happening, and that the current state isn't fully optimized yet. You'd be snapshotting this non-optimized state.

Once you recover such snapshot optimizations may start again to eventually get into the green state.
