### ISSUE TITLE
Error searching for points. RocksDB get_pinned_cf error.

### ISSUE THREAD

**Issue by danielebonfanti** [qdrant/qdrant#4866]
I have a qdrant instance deployed on Azure Container Apps (ACA), with a collection called "technicalreports". 
When I search points in that collection I get an error _RocksDB get_pinned_cf error_.

## Current Behavior
Searching for points in qdrant using the python client I get the following error:

![image](https://github.com/user-attachments/assets/7b152d5c-a165-46af-bb27-f73d96cb77a7)

Same error using the HTTP client.

![image](https://github.com/user-attachments/assets/0f8fb5dd-a9ac-4beb-97e1-dbf44d5e107c)

But it looks like that the file exists:

![image](https://github.com/user-attachments/assets/59d5dab6-e0d0-4654-ac71-13ab13227ce0)

## Steps to Reproduce
In order to reproduce the issue in the simplest way we have created the following jupiter notebook:
1. Instantiate the qdrant client:
`qdrant_client = QdrantClient(
    url = qdrant_base_url,
    timeout = qdrant_kwargs.get("timeout", 1000),
    api_key = qdrant_api_key)`
2. Query point with payload set to **true**
![image](https://github.com/user-attachments/assets/6fec27e6-1f84-4998-bb31-b7eba9f0e560)
the error is not present anymore if we set the payload to **false**
![image](https://github.com/user-attachments/assets/679effd9-44ee-4a90-a419-fc9ad04098e6)

## Expected Behavior
We expect that the behavior is the same with payload flag set to true or set to false.

**Comment by generall** [comment]
Is it very likely, that Azure Container Apps uses some strange file system or treat qdrant as if it is stateless microserver. We can't provide support for those types of deployments.

**Comment by johschmidt42** [comment]
@danielebonfanti Did you find a solution? Or did you move to a managed deployment? I'm experiencing the same issue. Qdrant runs as a docker container in Azure Container Apps with a premium Azure File Share mount. After some time, we get this error message and need to restart the container.

**Comment by danielebonfanti** [comment]
Hi @johschmidt42, unfortunately not, we tried different solution without a fix.
Because we are at the beginning of our project, we have chosen to switch to Azure AI Search.

**Comment by timvisee** [comment]
> a premium Azure File Share mount

Running Qdrant storage on a file share is not supported. It does not provide the strict control over disks that is needed.

Please see the requirements here: https://qdrant.tech/documentation/guides/installation/

**Comment by johschmidt42** [comment]
@timvisee 

You're right. Azure File Shares uses file-level access (SMB or NFS), not block-level access. 

> [For persistent storage, Qdrant requires block-level access to storage devices with a POSIX-compatible file system. Network systems such as iSCSI that provide block-level access are also acceptable. Qdrant won’t work with Network file systems such as NFS, or Object storage systems such as S3.](https://qdrant.tech/documentation/guides/installation/#storage)

Out of curiosity, how does one use Azure Kubernetes to persist the data if Azure File Shares can't be used? Or in other words what's the recommended storage solution for Azure?
