### ISSUE TITLE
Ask a question about index insertion

### ISSUE THREAD

**Issue by pengxin233** [qdrant/qdrant#4900]
I would like to ask qdrant when will the data be merged into the index when it is inserted?

**Comment by timvisee** [comment]
If talking about a payload index, then new insertions are indexed immediately. For vector indexing it is a bit different:

Newly inserted data will be inserted in non-indexed segments first. When the data in that segment exceeds the indexing threshold, it'll be optimized and indexed.

In practice this means newly inserted data is not indexed right away. It'll be indexed once there is enough non-indexed data.

Note that we do this on purpose. It's much more efficient than immediately indexing vector data.

**Comment by pengxin233** [comment]
Thank you very much for your answer. I have another question for you. How is filterable implemented in qdrant's hnsw index?

**Comment by pengxin233** [comment]
![企业微信截图_17240352769693](https://github.com/user-attachments/assets/3a19989f-5e8b-43cc-878a-80a90c724924)
This is what the document mentions

**Comment by timvisee** [comment]
This article describes it pretty well: https://qdrant.tech/articles/filtrable-hnsw/

**Comment by pengxin233** [comment]
Thank you very much for your help. Where is the code for filterable? I want to see its data structure.

**Comment by timvisee** [comment]
I'm not sure what you're asking about exactly, but all HNSW code can be found here: https://github.com/qdrant/qdrant/tree/master/lib/segment/src/index/hnsw_index

**Comment by coszio** [comment]
@manfredwang093 Any payload index you create will interact in this way with hnsw during construction

**Comment by manfredwang093** [comment]
> @manfredwang093 Any payload index you create will interact in this way with hnsw during construction

Thank you for your quick response, Luis, so as long as I creates a payload index, and during query time if there are filters passed to the query, it will invoke automatically? Thank you.

**Comment by manfredwang093** [comment]
Thank you! @coszio
