### ISSUE TITLE
`MAX_UPLOAD_SIZE` for multipart upload to object storage should be 5TiB

### ISSUE THREAD

**Issue by ShrubinS** [qdrant/qdrant#4908]
This is [defined](https://github.com/qdrant/qdrant/blob/6336395685187dffdcd786e1b3f6f5233541195a/lib/collection/src/operations/snapshot_storage_ops.rs#L76) as
```
const MAX_UPLOAD_SIZE: usize = 5 * 1024 * 1024 * 1024;
```
when it should be 

```
const MAX_UPLOAD_SIZE: usize = 5 * 1024 * 1024 * 1024 * 1024;
```

This seems like a simple mistake, because linked documents from S3 and Google Cloud Storage show 5TiB max size

## Current Behavior

Snapshot creation fails for snapshot file sizes > 5GiB

## Steps to Reproduce

1. setup s3 storage config
2. take snapshot
3. Snapshots > 5GiB fails with the error `024-08-19T09:39:24.175972Z ERROR qdrant::actix::helpers: error processing request: failed to store snapshot archive to /qdrant/./storage/tmp/<collection>-<peer_id>-2024-08-19-09-34-38.snapshot-arc-6AKyoO: Service internal error: File size exceeds the maximum upload size: 5368709120  `

**Comment by timvisee** [comment]
You seem to be right: https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html

The maximum size of an object is 5TB, while the maximum for a part is 5GB.

**Comment by ShrubinS** [comment]
@timvisee thank you for the quick turnaround here! Do you think we can get a hotfix release out for this? IMO large collections benefit the most from having snapshot recovery in place by being able to reduce TTR significantly compared to other options, and this is exactly what this bug doesn't allow.
