### ISSUE TITLE
UnexpectedResponse: Unexpected Response: 404 (Not Found) on client.search_points()

### ISSUE THREAD

**Issue by said-rasidin** [qdrant/qdrant#5016]
Utilize similarity search using search_points using IDs, but return always 404. other method works ok with IDs (retrieve, recommend)
 
## Current Behavior

```
File ~/miniconda3/envs/load/lib/python3.9/site-packages/qdrant_client/qdrant_client.py:560, in QdrantClient.query_points(self, collection_name, query, using, prefetch, query_filter, search_params, limit, offset, with_payload, with_vectors, score_threshold, lookup_from, consistency, shard_key_selector, timeout, **kwargs)
    556 # If the query contains unprocessed documents, we need to embed them and
    557 # replace the original query with the embedded vectors.
    558 query, prefetch = self._resolve_query_to_embedding_embeddings_and_prefetch(query, prefetch)
--> 560 return self._client.query_points(
    561     collection_name=collection_name,
    562     query=query,
    563     prefetch=prefetch,
    564     query_filter=query_filter,
    565     search_params=search_params,
    566     limit=limit,
    567     offset=offset,
    568     with_payload=with_payload,
    569     with_vectors=with_vectors,
    570     score_threshold=score_threshold,
...
--> 102 raise UnexpectedResponse.for_response(response)
```

## Steps to Reproduce
1. initiate connection
qdrant_client = QdrantClient(url="localhost:6333", timeout=120,)

2. search vector
qdrant_client.query_points(
    collection_name = qdrant_collection,
    query = 123,
    with_payload = True,
    with_vectors = True
)

## Expected Behavior
return similarity search data points

## Context (Environment)
similarity search with existing IDs while it exists in my database, it is very useful for latency without embedding the search query

**Comment by mkhludnev** [comment]
@said-rasidin it seems I stuck the same problem. How did you manage to solve it?

**Comment by said-rasidin** [comment]
ya it is the same I thought it was the qdrant-client issue, It solved by updating my qdrant docker to the latest

**Comment by tlevyaleia** [comment]
I had the same issue when querying my Qdrant Cloud cluster (see https://github.com/langchain-ai/langchain/issues/27223) that I solved by upgrading the version of the cluster
