### ISSUE TITLE
(Not an actual bug) Wrong info in the API document

### ISSUE THREAD

**Issue by lazur5566** [qdrant/qdrant#5068]
## Current Behavior

for API `/collections/{collection_name}/points/search`
https://api.qdrant.tech/api-reference/search/points shows with_payload option's default value is false.
But actually calling that API, I noticed its default value is true.
## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

option `with_payload` is default true in the code

**Comment by Taym95** [comment]
Either we set value to false(don't knew the implications) in code or change the doc:

https://github.com/qdrant/qdrant/blob/9fa86106e85d734765efe2c686a3ce975e53fb38/lib/collection/src/operations/types.rs#L381

**Comment by beanqi** [comment]
> Either we set value to false(don't knew the implications) in code or change the doc:
> 
> https://github.com/qdrant/qdrant/blob/9fa86106e85d734765efe2c686a3ce975e53fb38/lib/collection/src/operations/types.rs#L381

This struct is not used by `/collections/{collection_name}/points/search`. 
The Default value is false, [the code is here](https://github.com/qdrant/qdrant/blob/9fa86106e85d734765efe2c686a3ce975e53fb38/lib/segment/src/types.rs#L2091) , I think you have wrong param.

**Comment by coszio** [comment]
`with_payload`'s default for `search` and `query` is false, while for `scroll` it is true.

@Taym95 The code you shared is only for `scroll` requests.

@lazur5566 I'm going to close this for now, but feel free to reopen with a reproducible example :)
