### ISSUE TITLE
Installing qdrant in a cluster setup. qdrant instances out of sync. 

### ISSUE THREAD

**Issue by dingusagar** [qdrant/qdrant#510]
In order to make the qdrant instance highly available, I installed qdrant on two VMs and mounted an AWS EFS to store the qdrant collections and index files on both nodes. So any updates on collections files will be synced across both the nodes because of the mounted EFS.

But while testing this, found that the two qdrant instances in these nodes don't sync. A collection created in one node is not found when we try to query from the second node. 

Is there something I am doing wrong here? Are there any guidelines on how to setup qdrant in muliple nodes.

**Comment by generall** [comment]
Hi @dingusagar, as I have already answered you here https://github.com/qdrant/qdrant/discussions/60#discussioncomment-2593480, AWS EFS setup you are trying to do is not expected to work. 

We are currently working on proper distributed setup, I will let you know as soon as we get some the first release candidate ready for alpha testing.

And thanks for your interest in using Qdrant in highly available environment!

**Comment by dingusagar** [comment]
from your https://github.com/qdrant/qdrant/discussions/60#discussioncomment-2593480, 
`As a temporary workaround, you can try to implement your own proxy which will route requests among independent instances.
`

by this do you mean something like the following?  If I have 2 instances, for create collection and upsert APIs, i programmatically hit the requests to both the nodes from the proxy, and for search API this proxy can hit to any of the nodes.
