### ISSUE TITLE
Data inconsistent after migration

### ISSUE THREAD

**Issue by glorinli** [qdrant/qdrant#5101]
## Qdrant version
v1.10.1

I have 2 collections in a 2-node cluster, and I wrote a python script to migrate data from collection 1 to collection 2, after migration, when I performing search on collection 2, I got inconsistency result when request deliver to different node.

### Collection 1 configuration:
1. Sharding method: auto
2. Shard number: 2
### Collection 2 configuration
1. Sharding method: custom
2. Sharding number: 1
3. Shard keys: [shard_0 to shard_29], total 30 shard keys.
4. Replica factor: 2

I wrote a python script to read points from collection 1 and transform the format of payload, then write to collection 2 (by batch, batch size 15).

After migration, I got some issue when searching collection 2:
1. Some data cannot be searched, but when scroll it, we can find the data, we compared the vectors, they are same. If add exact param, we can get the result.
2. Some data are consistent in 2 nodes, when search comes to node 1, it works fine, but when comes to node 2, it return empty result.
3. Some data are consistent in 2 nodes, when search comes to node 1, it return some result, but when comes to node 2, it return different results. If I set consistency=2 for searching, it return empty results.

I checked the cluster API, raft term/commit are same on 2 nodes.

## Steps to Reproduce
1. Migrate data from old collection to new collection.
2. Perform search.

Since it's a internal data, I can't send it here.

## Expected Behavior
Expect same result when searching, expect searching works well after data migration.

## Possible Solution
We try to migrate data again, with following change:
1. Change write_consistency_factor to 2
2. When migration data, wait the batch upsert success.
3. Sleep some time between batches.

## Context (Environment)
N/A

Looking forward for your response, since we can't find much information about it.

Our new collection configuration:
```
{
  "result": {
    "status": "green",
    "optimizer_status": "ok",
    "indexed_vectors_count": 56205,
    "points_count": 56931,
    "segments_count": 60,
    "config": {
      "params": {
        "vectors": {
          "size": 1536,
          "distance": "Cosine",
          "on_disk": true
        },
        "shard_number": 1,
        "sharding_method": "custom",
        "replication_factor": 2,
        "write_consistency_factor": 1,
        "on_disk_payload": true
      },
      "hnsw_config": {
        "m": 0,
        "ef_construct": 128,
        "full_scan_threshold": 10000,
        "max_indexing_threads": 0,
        "on_disk": false,
        "payload_m": 16
      },
      "optimizer_config": {
        "deleted_threshold": 0.2,
        "vacuum_min_vector_number": 1000,
        "default_segment_number": 2,
        "max_segment_size": null,
        "memmap_threshold": 20000,
        "indexing_threshold": 20000,
        "flush_interval_sec": 5,
        "max_optimization_threads": null
      },
      "wal_config": {
        "wal_capacity_mb": 32,
        "wal_segments_ahead": 0
      },
      "quantization_config": {
        "scalar": {
          "type": "int8",
          "always_ram": true
        }
      }
    },
    "payload_schema": {
      "account_id": {
        "data_type": "keyword",
        "points": 56931
      },
      "type": {
        "data_type": "keyword",
        "points": 56931
      },
      "extension_id": {
        "data_type": "keyword",
        "points": 0
      },
      "indexing_type": {
        "data_type": "keyword",
        "points": 56931
      }
    }
  },
  "status": "ok",
  "time": 0.000557056
}
```

**Comment by timvisee** [comment]
Vector search is approximate by design. Results not entirely matching may be expected if not using exact search. This is especially true if spreading data across separate collections.

**Comment by glorinli** [comment]
Yes, I understand that the result may difer slightly in each search. But seems my case is not only in accurate.

I just tried to re-migrate the data, and it works now.
The change is:
1. Change write_consistency_factor to 2.
2. Use wait=True when batch upsert.
3. Sleep 1 second between each batch insert.

For this case:
> Some data are consistent in 2 nodes, when search comes to node 1, it works fine, but when comes to node 2, it return empty result.

My request is:
`
POST /collections/<collection_name>/points/search
{
    "limit": 3,
    "score_threshold": 0,
    "with_payload": true,
    "shard_key": "shard_29",
    "filter": {
        "must": [
            {
                "key": "group_id",
                "match": {
                    "value": "GROUP_ID"
                }
            },
            {
                "key": "account_id",
                "match": {
                    "value": "ACCOUNT_ID"
                }
            },
            {
                "key": "type",
                "match": {
                    "value": "article"
                }
            },
            {
                "key": "indexing_type",
                "match": {
                    "value": "default"
                }
            }
        ]
    },
    "vector": [The vector, 1536 dimension]
}
`

But I can't reproduce it now, it does not reproduce now, for same data, seems it's fixed automatically.

**Comment by glorinli** [comment]
I find that for some filter, I can only use exact search to get results, otherwise it will return empty result.

`
{
    "limit": 3,
    "score_threshold": 0,
    "with_payload": true,
    "shard_key": "shard_29",
    "filter": {
        "must": [
            {
                "key": "group_id",
                "match": {
                    "value": "GROUP_ID"
                }
            },
            {
                "key": "account_id",
                "match": {
                    "value": "ACCOUNT_ID"
                }
            },
            {
                "key": "type",
                "match": {
                    "value": "article"
                }
            },
            {
                "key": "indexing_type",
                "match": {
                    "value": "default"
                }
            }
        ]
    },
    "vector": [The 1536 vector]
}
`

Above is my query, and I have some testing results:
1. Some group_id works, and some doesn't.
2. If I use exact search, it works.

Could you please help to investigate:
1. I have 30 shard keys and shard_number is 1, replica is 2, are there too much shards?
2. I have 4 fields as filter, and I have created index for them, are there too much filters?
3. Some shard works fine, but when I insert some data to another shard, the other shard may suffer from same issue.

**Comment by glorinli** [comment]
Additional Info: Our group_id field is in UUID format.

**Comment by glorinli** [comment]
Updated to v1.11.4, still not working, and I try to change group_id field to uuid index, but when I use match uuid in query, it fails:

`
{
  "error": "Format error in JSON body: data did not match any variant of untagged enum Condition at line 1 column 33175"
}
`

**Comment by timvisee** [comment]
> I find that for some filter, I can only use exact search to get results, otherwise it will return empty result.
> 
> `{ "limit": 3, "score_threshold": 0, "with_payload": true, "shard_key": "shard_29", "filter": { "must": [ { "key": "group_id", "match": { "value": "GROUP_ID" } }, { "key": "account_id", "match": { "value": "ACCOUNT_ID" } }, { "key": "type", "match": { "value": "article" } }, { "key": "indexing_type", "match": { "value": "default" } } ] }, "vector": [The 1536 vector] }`
> 
> Above is my query, and I have some testing results:
> 
>   1. Some group_id works, and some doesn't.
>   2. If I use exact search, it works.

According to your above collection info snippet, you don't have a payload configured on `group_id`. Could you add this and retrigger indexation to see if it changes the result?

If it doesn't you may want to tune your HNSW configuration, likely increasing `payload_m`

> Could you please help to investigate:
> 
>   1. I have 30 shard keys and shard_number is 1, replica is 2, are there too much shards?
>   2. I have 4 fields as filter, and I have created index for them, are there too much filters?
>   3. Some shard works fine, but when I insert some data to another shard, the other shard may suffer from same issue.

1. Could you elaborate on how you partition these shards? Do you plan to add more in the future, and what for? Also, how many points does each shard have on average?
2. 4 should be fine.
3. I don't understand what you're saying here. I assume you're saying some shards (by key) work, some don't. Since shards are completely isolated I think that makes sense.

> (...) but when I use match uuid in query, it fails:

Could you show your exact query? We expect a specific format, like [this](https://qdrant.tech/documentation/concepts/payload/#uuid).

> I change the quantization to binary, and then change back to scalar, then I can retrieve some points now, but still in consistency, One request have result, and next result is empty.

Doing this forces recreation of the HNSW graphs because it reoptimizes all shards.

**Comment by glorinli** [comment]
Hi, I tried and the result is:
> 1. you don't have a payload configured on group_id

Yes I missed it, now I added it but still not working.
> 2. Increase payload_m

I didn't try it because seems it require a recreation of collection? I will try it later.
> 3. About shards

We define 30 shards, and we don't expected to add more in future, we just want to add nodes and move shards to new nodes if there are too many data.
About the data scale: in lab env, we have 10 shard key and shardnumber is 2 and replica factor is 2 so we have 40 shards in total, and the point count is currently 426405.

> About the unclear one: Some shard works fine, but when I insert some data to another shard, the other shard may suffer from same issue.

What I mean is that some shard works well at some time, but after some time, it's broken, we can't query for some filters that is OK before.

> About the match uuid query.

Please refer to below screenshot.
<img width="1581" alt="image" src="https://github.com/user-attachments/assets/6b550834-851f-40d7-9af4-da17c00d8d4e">

**Comment by glorinli** [comment]
I think we can narrow down to one specific case, I can reproduce now in my lab env.

## First one, when I disable exact search, I can get nothing, but when exact is enabled, I am able to get results:
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/3b264d75-3e12-4eff-aa4a-14a1e95c7ef9">
<img width="1368" alt="image" src="https://github.com/user-attachments/assets/1ff19eb4-0746-4556-900d-d5ebcd21621c">


## Then I modify the quantization config as I said above

Then I can get results without exact search, but only 1 instance, if query goes to another instance, the result is still empty.

## BUT, today, for same query

I can get result from both node, but the results is not the same.
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/45d03d1f-7d0d-4282-9f15-2dab121b9eed">
<img width="1305" alt="image" src="https://github.com/user-attachments/assets/37a9ee2d-031c-4046-b929-01d4ea08a255">

### When I add read consitency, I can get nothing: 
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/55f4de8b-ee06-477e-8b13-778951099261">

**Comment by timvisee** [comment]
> I didn't try it because seems it require a recreation of collection? I will try it later.

Recreating the HNSW graphs is enough, but it sometimes it a bit tricky to trigger. So that's why we've also suggested recreating the whole collection.

> We define 30 shards, and we don't expected to add more in future, we just want to add nodes and move shards to new nodes if there are too many data.
About the data scale: in lab env, we have 10 shard key and shardnumber is 2 and replica factor is 2 so we have 40 shards in total, and the point count is currently 426405.

Makes sense.

Though, do you just want to spread your points over 10 or 30 shards? In that case I'd recommend not to use shard keys because it may have some caveats. Using shard keys should only be necessary if you explicitly want to define the distribution across shards, because you want to partition your data.

Note that if using shard keys during search, you'll only be able to find points within that specific shard key.

> I think we can narrow down to one specific case, I can reproduce now in my lab env. (...)

Do you not see any problems at all when not using quantization?

If that is the case I wonder if quantization reduces the resolution by too much causing inconsistent results. If I recall correctly exact search will still use quantization. It's only the final stage where we rescore the quantized vectors to properly order results.

**Comment by glorinli** [comment]
Hi @timvisee , after some tests I found how to reproduce the EMPTY result issue:
1. Only create account_id, type, indexing_type indices, no group_id index.
2. Write lots of points to qdrant.

Then when I do the searching, I will get empty result for some group_id.

If I create the index after upserting data, it won't work, unless I change the quantization (according to previous discussion, it will recreate HNSW graph).

Could you please provide me more information? Is this behavior as expected?

**Comment by timvisee** [comment]
I think it does make sense, and is explainable.

When the HNSW graph is built, it considers the configured payload indexes. It takes them into account while generating graph links to prevent the exact situation you're describing.

I agree that in this case we might want to regenerate the HNSW graph for you, so you don't have to trigger it with some workaround.

Generally speaking we do recommend to create your payload indices right at the start when creating your collection, because building those is fast enough during bulk upsertion. That'll also prevent the above mentioned issue.

**Comment by glorinli** [comment]
Thank you verfy much for explanation.

We will create index before upserting data.

> I agree that in this case we might want to regenerate the HNSW graph for you, so you don't have to trigger it with some workaround.

It will be great if this change will can included in your future releases.

**Comment by timvisee** [comment]
> We will create index before upserting data.

Just to be specific: create the payload index before upserting data.

If you're doing bulk uploads and disable the HNSW index, then you still want to enable the HNSW index after uploading.

Happy to help!
