### ISSUE TITLE
The latest v1.11.4 tag on master branch fails to compile the 'memory' lib

### ISSUE THREAD

**Issue by agentzh** [qdrant/qdrant#5109]
The latest v1.11.4 tag on the master branch fails to compile its `memory` lib on Linux x64 with rustc/cargo 1.79.0.

## Current Behavior

I'm getting the following build errors:

```
   Compiling memory v0.0.0 (/home/agentzh/git/qdrant/lib/common/memory)
error[E0658]: use of unstable library feature 'lazy_cell'
   --> lib/common/memory/src/madvise.rs:146:36
    |
146 | static POPULATE_READ_IS_SUPPORTED: std::sync::LazyLock<bool> =
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> lib/common/memory/src/madvise.rs:147:5
    |
147 |     std::sync::LazyLock::new(|| memmap2::Advice::PopulateRead.is_supported());
    |     ^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> lib/common/memory/src/madvise.rs:147:5
    |
147 |     std::sync::LazyLock::new(|| memmap2::Advice::PopulateRead.is_supported());
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `memory` (lib) due to 3 previous errors
```

## Steps to Reproduce

Just clone the latest master branch of this repo, and run the command on a Linux x86_64 system with rustc/cargo 1.79.0:

```bash
cargo build --release --features multiling-chinese,multiling-japanese -j$(nproc)
```

No data is required.

## Expected Behavior

The previous v1.11.3 tag builds fine on the same system using the same Rust toolchain.

## Possible Solution

Maybe you should enable the unstable feature explicitly in the config file?

## Context (Environment)

I cannot build the latest version and have to roll back to the previous v1.11.3 version.

**Comment by agentzh** [comment]
BTW, I also tried `cargo clean` before `cargo build`. Same problem.

**Comment by generall** [comment]
hey @agentzh, please try to use latest stable rust. We currectly use `1.81.0`

**Comment by timvisee** [comment]
Note that, because this isn't exposed as library, we always pick the latest stable Rust version to make use of the latest features.

**Comment by agentzh** [comment]
@timvisee rustc 1.81.0 makes it build again. Thanks!
