### ISSUE TITLE
[sharding] Enable consensus via runtime configuration

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#511]
**Is your feature request related to a problem? Please describe.**
The consensus feature is currently gated by a cargo feature.

As the system becomes gradually consensus-aware, we see the spreading of conditional compilation blocks which add complexity to the code.

e.g. from https://github.com/qdrant/qdrant/pull/505

```rust
        #[cfg(feature = "consensus")]
        {
            return collection
                .retrieve(
                    request,
                    self.segment_searcher.as_ref(),
                    shard_selection,
                    &self.peer_address_by_id()?,
                )
                .await
                .map_err(|err| err.into());
        }

        #[cfg(not(feature = "consensus"))]
        {
            collection
                .retrieve(
                    request,
                    self.segment_searcher.as_ref(),
                    shard_selection,
                    &HashMap::new(),
                )
                .await
                .map_err(|err| err.into())
        }
```

**Describe the solution you'd like**
Compilation time with the consensus feature is not an actual problem.

Given that the consensus is expected to take over the whole codebase eventually, we could use a runtime configuration instead to toggle it more naturally.

**Describe alternatives you've considered**
Removing the switch it entirely but it could have performance implications.

**Comment by e-ivkov** [comment]
I agree with the proposed solution and it would be good to address it soon.
