### ISSUE TITLE
Keep Calculation Going if one or few points if not found in `recommend` positive or negative

### ISSUE THREAD

**Issue by said-rasidin** [qdrant/qdrant#5115]
I am using `.recommend` method, but if a point not exist in database it will raise error.

````
qdrant_client.recommend(   
 collection_name = "my_collection",
        positive = [18395, 1231037918],
        negative = [],
        query_filter = None,
        limit = 8,
        with_payload = True,
        with_vectors = False)
````

**Error:**

```
UnexpectedResponse: Unexpected Response: 404 (Not Found)
Raw response content:
b'{"status":{"error":"Not found: No point with id 18395 found"},"time":0.000158034}'
```

**The scenario:**
ID: 18395 does not exist but the rest is exist

**Ideal For My Case:**
what I want to control is just finding positive or negative points that exist in the data, keeping the calculation going, raising error if only all data points are not found in the data

**Comment by timvisee** [comment]
This is expected behavior because a missing point could result in unexpected results.

Could you elaborate on your use case? Why do you provide a point ID that may not exist?

**Comment by said-rasidin** [comment]
I am looking the vector in qdrant by mapping string payload to qdrant integer id, I cant do on the fly embedding due to latency. But my document is only partial inside qdrant that's why it raised that error. 

But it's Oke now, Done work around by using .scroll and np.mean for found document
