### ISSUE TITLE
Range filter is not working in version 0.7.0. works on 0.6.0

### ISSUE THREAD

**Issue by dingusagar** [qdrant/qdrant#512]
```curl
curl --location --request POST 'http://localhost:6333/collections/products_collection_1/points/search' \
--header 'Content-Type: application/json' \
--data-raw '{
    "filter": {
        "must": [
            {
                "key": "price",
                "range": {
                    "gt": null,
                    "gte": 100.0,
                    "lt": null,
                    "lte": 5450.0
                }
            }
        ]
    },
    "params": {
        "hnsw_ef": 0
    },
    "top": 5,
    "vector": [
        -0.049965106,
        0.0818114,
        0.018237809,
        0.06501494,
        -0.02273129,
        0.033985473,
        -0.08426942,
        -0.087136604,
        -0.06589177,
        0.030776124,
        -0.069842316,
        0.066270754,
        0.05512795,
        0.030017026
    ],
    "with_payload": true,
    "with_vector": false
}'
```

tried inserting the same data to both versions (0.6.0 and 0.7.0), but the following search api with filter works only in the 0.6.0 version. 
In 0.7.0, it gave an empty response. But when i removed the filter it started giving responses.

Are there any breaking changes on the range filter for version 0.7.0?

**Comment by generall** [comment]
Hi @dingusagar, in version 0.7.0 we changed the storage format, so it is no longer required to explicitly define data types.
Maybe you are uploading data with something like

```
{
   "price": { "value": 100.0, "type": "float" }
}
```

If so, could you please try change it to just `{ "price": 100.0 }`.

**Comment by generall** [comment]
@dingusagar could you please confirm if it worked for you or not?

**Comment by dingusagar** [comment]
hi @generall, sorry for the late reply,

yes, this seems to be working now after I created a fresh collection via the REST API. 

I guess the previous time it did not work because I was using an older version of the python client (qdrant-client==0.5.0). So maybe that was explicitly defining the data type as you mentioned. Will update the client. 

Anyways thanks for the response.
