### ISSUE TITLE
Vectors mysteriously gone in recent version 1.11.4

### ISSUE THREAD

**Issue by agentzh** [qdrant/qdrant#5134]
We've noted a possible regression with qdrant 1.11.4 that some of the vectors might just be gone even though insertion requests never had any errors. What we see is that some vectors are just cannot be found in search. And we have to reinsert those vectors to make it searchable again. We ran into two cases just today. We never saw such things with earlier versions like 1.11.1 ~ 1.11.3 before.

How to troubleshoot and debug such things? We might sometimes forcibly shut down the qdrant server with SIGINT or SIGQUIT signals. Will that be a potential cause here?

Today we ugpraded the database to the latest 1.11.5 version and will keep an eye on it...

For each new qdrant version, we always destroy the old collections' vectors and insert all the vectors all over again (just to make sure it's clean).

It's on Linux x86_64 system without containers (just a local build of qdrant with rustc/cargo 1.81.0).

**Comment by agentzh** [comment]
Oh, forgot to mention that the database was in the status "green" when the issues happen. And I tried both the index query and exact query, some thing: nothing can be found.

**Comment by agentzh** [comment]
And it's a single server instance: no clusters, no shardings.

**Comment by timvisee** [comment]
> How to troubleshoot and debug such things? We might sometimes forcibly shut down the qdrant server with SIGINT or SIGQUIT signals. Will that be a potential cause here?

Though this shouldn't be a problem, please use graceful shutdowns when possible.

> For each new qdrant version, we always destroy the old collections' vectors and insert all the vectors all over again (just to make sure it's clean).

Is that just to ensure everything is there? Because normally, that should not be necessary.

> Oh, I forgot to mention that the database was in the status "green" when the issues happened. I tried both the "index" query and the "exact" query, and the same thing happened: nothing could be found.

Did you check to explicitly [retrieve](https://qdrant.tech/documentation/concepts/points/#retrieve-points) the points you thought were missing?

You can use `GET /collections/my_collection/points/123`.

I assume you have been searching by exact vector to check whether a point still exists. With regular search it may be possible for it not being found. Though, when using exact search you should always see it.

**Comment by agentzh** [comment]
@timvisee Thanks for your suggestion! We'll try that GET request to check the points the next ime. The crime scene is already gone since it is a production server and we had to reinsert all the vectors to bring it back ASAP.

**Comment by timvisee** [comment]
Thanks!

I don't want to state the obvious, but, we definitely don't expect this with restarts or version upgrades.

**Comment by agentzh** [comment]
We ran into the same problem with qdrant 1.11.5 yesterday again. Deleting all the data and re-importing the data makes the issue go away. The symptom is that the sometimes some data cannot be found in vector search even when `exact` flag is set. We'll keep an eye on this.

And I saw there's a newer version, 1.12.1. Maybe we should upgrade to the latest version?

**Comment by agentzh** [comment]
Just upgraded qdrant to the latest 1.11.5 and also upgraded rustc/cargo to the latest 1.82.0 version and will keep watching.

**Comment by agentzh** [comment]
@timvisee yes! we've been using a lot of payload indexes on string and number typed fields. Glad you pin the bug down! May I ask which version has this issue fixed? Thanks a lot!

**Comment by agentzh** [comment]
And yes, we are using indexes during mass deletion since we re-import existing data and any new data every couple of days.

**Comment by timvisee** [comment]
Thanks for confirming.

We fixed it in <https://github.com/qdrant/qdrant/pull/5346>. It is not released yet, but we'll do so shortly. We now have a test in place that ensures the same problem doesn't happen in the future.

Sorry for the inconvenience.
