### ISSUE TITLE
Support: Multi-channel search？？？

### ISSUE THREAD

**Issue by SevenMpp** [qdrant/qdrant#5136]
There are many kinds of data. 
1、If we put them into a collection, how can we search them at the same time? The expected result is to get the top K of each kind of data.
2、If they are placed in different collections, is it possible to search for multiple items at the same time?

**Comment by timvisee** [comment]
> 1、If we put them into a collection, how can we search them at the same time? The expected result is to get the top K of each kind of data.

This can be done through batching. Please see our documentation here: https://qdrant.tech/documentation/concepts/search/#batch-search-api

Note that you can also use multiple requests concurrently to achieve something similar.

>  2、If they are placed in different collections, is it possible to search for multiple items at the same time?

While you cannot use batching for this, you can use multiple requests concurrently.

**Comment by SevenMpp** [comment]
@timvisee Thanks for your reply

**Comment by timvisee** [comment]
Closing this assuming the above resolves your questions. If you still have questions, please feel free to open this again.
