### ISSUE TITLE
Can't recover a small snapshot

### ISSUE THREAD

**Issue by DavidOsparks** [qdrant/qdrant#5151]
I have a qdrant instance on Qdrant Cloud, and another on my own server created by docker image. Both of them are version 1.9.7. I make a snapshot of a collection on Qdrant Cloud, where the size is only 100MB.
I try to recover it on my server by GUI, the uploading seems good, but when upload 100% it stucks without any further action.

![螢幕擷取畫面 2024-09-30 113612](https://github.com/user-attachments/assets/77ec0bdf-936d-4e4f-aa56-050cbc7965e8)

I check the log of qdrant on my server, there isn't any PUT /collections/{collection_name}/snapshots/recover or other logs. It just does nothing after upload 100%.

I also try to import the example datasets like Qdrant Web Documentation or Midjourney Styles. This works well, and I can actually see the logs appear.

```
2024-09-30T03:50:39.933236Z  INFO storage::content_manager::toc::collection_meta_ops: Creating collection 123
2024-09-30T03:50:40.738960Z  INFO collection::shards::local_shard: Recovering collection 123: 0/1 (0%)
2024-09-30T03:50:40.746168Z  INFO collection::shards::local_shard: Recovered collection 123: 1/1 (100%)
2024-09-30T03:50:40.782042Z  INFO actix_web::middleware::logger: 172.18.0.1 "PUT /collections/123/snapshots/recover HTTP/1.0" 200 54 "https://qdrant-stg.tribes.vip/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" 3.380208
```

later I may try to upgrade to qdrant 1.11.5, but still want to make sure why this happens.

**Comment by timvisee** [comment]
That's definitely not what should be happening.

I wonder, could it be some kind of permission error where it fails to store the snapshot you upload?

Since you're testing locally anyway, would you mind to give our latest version a quick try just to see if it does work there.
At this time I don't recall us fixing anything on snapshot recovery since then.

**Comment by DavidOsparks** [comment]
Ok, I check the console output:

![image](https://github.com/user-attachments/assets/7bb0cb5b-3db3-44e4-a84d-d1dcd65d82db)

It shows a 413 (Payload Too Large) and a parse error. However, this is my data size (only 96 points) and payload schema (only single short keywords) which is impossible to be too large.

![image](https://github.com/user-attachments/assets/a3047606-7e9d-4cc8-bb38-287c84bf1e45)

Hope these info helps. Thanks!

**Comment by JojiiOfficial** [comment]
Is your Qdrant instance deployed behind a reverse proxy or something else proxying the connection?

**Comment by DavidOsparks** [comment]
> Is your Qdrant instance deployed behind a reverse proxy or something else proxying the connection?

Thanks! I found that I have to modify the `client_max_body_size` settings of Nginx to a value which is larger than file size.

**Comment by timvisee** [comment]
Nice! Thanks for checking. Happy to see you were able to resolve it.

Now, I do think it shouldn't silently fail. Instead it should report a proper error. I'll open an issue for it so we can improve on the side.
