### ISSUE TITLE
Add some method to clear the qsrant cache

### ISSUE THREAD

**Issue by chrishart0** [qdrant/qdrant#5167]
**Is your feature request related to a problem? Please describe.**
We modified the metadata of a set of nodes, but we still see the old data being returned from qdrant. Qdrant appears to be caching our query.

**Describe the solution you'd like**
There should be some method to trigger a cache clear, either for all of qdrant or for just 1 collection. 

**Describe alternatives you've considered**
We've considered restarting our qdrant service to get a clean cache.

**Additional context**
N/A

**Comment by chrishart0** [comment]
Actually, looks like the issue is on our side. Using the qdrant GUI, we deleted the piece of metadata, we did not notice we also needed to delete that piece of metadata from the _node_content. Closing this out.

**Comment by timvisee** [comment]
Happy to see you found the solution.

Yes, once an operation is processed the new data is immediately reflected and available.
