### ISSUE TITLE
[sharding] Handle remote shards during collection creation

### ISSUE THREAD

**Issue by e-ivkov** [qdrant/qdrant#519]
Currently on collection creation all shards are created as local. This obviously presents a problem for multi-peer setup.

We need:
1. Algorithm to distribute shards on peers
2. Propagate the knowledge of which shards are local on collection creation

**Comment by agourlay** [comment]
> 1. Algorithm to distribute shards on peers

Are we able to detect the peer with the least amount of shards to distribute equally?

**Comment by e-ivkov** [comment]
> > 1. Algorithm to distribute shards on peers
> 
> Are we able to detect the peer with the least amount of shards to distribute equally?

Yes, essentially each peer is/(should be) aware of the shard distribution as it is a part of global state.

My initial idea is that the peer which receives the CreateCollection request from client - inserts the suggestions on how to most evenly distribute shards and then proposes this to consensus along the CreateCollection operation. The on commit the collection object will be initialized on each of the peers accordingly - accounting for the distribution.

**Comment by e-ivkov** [comment]
> Currently on collection creation all shards are created as local.

Same is on collection load - the shards are also assumed all to be local.
