### ISSUE TITLE
Delete operation not work in multiple thread program

### ISSUE THREAD

**Issue by 18lalala** [qdrant/qdrant#5210]
Hi, In my program, sometimes I need to delete point with id, while when running, the delete operation not work, I printed the output: `delete status:  b42b9f9b-4ff8-47e6-a3bc-02c7b67e58ed     completed`, but after running I can still retrieve this point with its id. When I run delete function in a test script, it just worked, so I think it is due to multiple thread. Do you have any advice?

**Comment by timvisee** [comment]
I don't expect any problems here. If you delete a point it should not be retrievable anymore from the moment it's processed.

Could it be that your retrieve happens before the delete? Or, could it be that the delete is still processing while you're doing the retrieve check? I'd recommend to specify `wait=true` on the delete operations to ensure it's fully processed.

If the above doesn't help, would you mind to share the code snippet you use to delete and to check whether the point is still retrievable?

**Comment by 18lalala** [comment]
It turned out to be a coding mistake, sorry for bothering you. Thanks again.

**Comment by timvisee** [comment]
No problem. Happy to see you were able to resolve this.
