### ISSUE TITLE
Database returning empty payload

### ISSUE THREAD

**Issue by F42J** [qdrant/qdrant#5225]
## Current Behavior
While querying the database, the correct points are returned. However, they do not have the payload passed on creation along them.

## Steps to Reproduce

Code for reference
Upsert:

```
let payload: Payload = json!(
            {"patient_id": entry.patient_id}
        )
            .try_into()
            .unwrap();
        let point = PointStruct::new(id, vectors, payload);
        upsert_point(&vectordb, point).await?;
```
        
Search:

```
qdrant
        .search_points(&SearchPoints {
            collection_name: "patientdata".to_string(),
            filter: None,
            params: Some(SearchParams {
                hnsw_ef: Some(128),
                exact: Some(false),
                ..Default::default()
            }),
            vector: queryvector.clone(),
            score_threshold: Some(0.665),
            limit: 1000000,
            ..Default::default()
        })
        .await;        
```

## Context (Environment)

Docker compose environment

**Comment by timvisee** [comment]
To include payloads in the search response you must set `with_payload`: https://docs.rs/qdrant-client/latest/qdrant_client/qdrant/struct.SearchPoints.html#structfield.with_payload

Note that doing this through the new [`SearchPointsBuilder`](https://docs.rs/qdrant-client/latest/qdrant_client/qdrant/struct.SearchPointsBuilder.html) will make this a lot easier.

For example (untested):

```rust
qdrant
    .search_points(SearchPointsBuilder::new("patientdata", queryvector.clone(), 1_000_000)
        .params(SearchParamsBuilder::default()
            .hnsw_ef(128)
            .exact(false)
        )
        .score_threshold(0.665)
    )
    .await;
```
