### ISSUE TITLE
 RUSTSEC-2022-0006 in time 0.1.43

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#525]
Cargo audit reports a vulnerability in time 0.1.43

```
Crate:         time
Version:       0.1.43
Title:         Potential segfault in the time crate
Date:          2020-11-18
ID:            RUSTSEC-2020-0071
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:      Upgrade to >=0.2.23
Dependency tree: 
time 0.1.43
```

The dependency is pulled by

```
cargo tree --invert time:0.1.43
time v0.1.43
├── eventual v0.1.7
│   └── wal v0.1.2 (https://github.com/generall/wal.git#ac3a1238)
│       ├── collection v0.3.1 (/home/agourlay/Workspace/qdrant/lib/collection)
│       │   ├── qdrant v0.7.0 (/home/agourlay/Workspace/qdrant)
│       │   └── storage v0.2.0 (/home/agourlay/Workspace/qdrant/lib/storage)
│       │       └── qdrant v0.7.0 (/home/agourlay/Workspace/qdrant)
│       └── storage v0.2.0 (/home/agourlay/Workspace/qdrant/lib/storage) (*)
├── syncbox v0.2.4
│   └── eventual v0.1.7 (*)
└── wal v0.1.2 (https://github.com/generall/wal.git#ac3a1238) (*)
```

**Comment by agourlay** [comment]
https://github.com/qdrant/wal/issues/23

**Comment by generall** [comment]
https://github.com/chronotope/chrono/issues/602#issuecomment-1075915577

**Comment by agourlay** [comment]
I am fine with closing this issue given the comment you found and that we have addressed what we could in our codebase :+1:

**Comment by ffuugoo** [comment]
It's possible to [ignore advisories in `.cargo/audit.toml` config file][cargo-audit-ignoring-advisories].
@generall @agourlay

[cargo-audit-ignoring-advisories]: https://github.com/RustSec/rustsec/tree/main/cargo-audit#ignoring-advisories

**Comment by ffuugoo** [comment]
BTW, seems like the wrong advisory is mentioned in the issue title. (:

**Comment by agourlay** [comment]
@ffuugoo  Thanks for the info :+1: 

We do not run cargo audit as part of the CI process, it was a one off thing.
Let's close this issue given the previous comments and the wrong title!
