### ISSUE TITLE
Pod Failure with Qdrant v1.11.3

### ISSUE THREAD

**Issue by shubham-kharche** [qdrant/qdrant#5260]
### Description
There are two pods associated with Qdrant with config of around 2.8 vCPU and 12 GB RAM each. All the collections, metadata, payload and indexes are stored with on_disk=True settings. One pod is running fine with less than 70 % resource utilization. While the other pod has started crashing and getting restarted with the issues. 
The Qdrant pod failed to start due to a panic error during the initialization process while loading a collection. Below are the relevant logs for the failing pod. 
### Logs:
Defaulted container "qdrant" out of: qdrant, ensure-dir-ownership (init)
Starting initializing for pod 1
           _                 _
  __ _  __| |_ __ __ _ _ __ | |_
 / _` |/ _` | '__/ _` | '_ \| __|
| (_| | (_| | | | (_| | | | | |_
 \__,_|\__,_|_|  \__,_|_| |_|\__|

Version: 1.11.3, build: 9fa86106
Access web UI at http://localhost:6333/dashboard

2024-10-18T06:18:05.804638Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json
2024-10-18T06:18:05.814014Z  INFO storage::content_manager::toc: Loading collection: tenant2
2024-10-18T06:18:13.845486Z ERROR qdrant::startup: Panic backtrace:
   0: qdrant::startup::setup_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: collection::shards::shard_holder::ShardHolder::load_shards::{{closure}}
   7: collection::collection::Collection::load::{{closure}}
   8: storage::content_manager::toc::TableOfContent::new
   9: qdrant::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: main
  12: <unknown>
  13: __libc_start_main
  14: _start

2024-10-18T06:18:13.845505Z ERROR qdrant::startup: Panic occurred in file /qdrant/lib/collection/src/shards/replica_set/mod.rs at line 277: Failed to load local shard "./storage/collections/tenant2/0": Service internal error: IO Error: failed to fill whole buffer

### Expected Behavior
The Qdrant pod should start successfully and load all collections without errors.

### Actual Behavior
The pod fails to start, and an error occurs when loading the tenant2 collection shard due to an internal I/O error.

Any guidance on debugging or resolving this issue would be greatly appreciated.

**Comment by timvisee** [comment]
> 2024-10-18T06:18:13.845505Z ERROR qdrant::startup: Panic occurred in file /qdrant/lib/collection/src/shards/replica_set/mod.rs at line 277: Failed to load local shard "./storage/collections/tenant2/0": Service internal error: IO Error: failed to fill whole buffer

This looks like an IO problem.

Are you sure you meet the installation requirements, especially in the storage area?
https://qdrant.tech/documentation/guides/installation/

**Comment by shubham-kharche** [comment]
We are using SSD of 512 GB

**Comment by timvisee** [comment]
> We are using SSD of 512 GB

Could you give a little bit more detail. Is it a locally mounted SSD, is it a file share, is it block storage?

**Comment by shubham-kharche** [comment]
We are using Azure managed disks, which are block-level storage volumes. These disks are provisioned automatically through AKS storage classes. We use the default storage class in AKS, which uses Standard_SSD. Standard SSDs generally offer a throughput of up to 60 MB/second, but with the one we use (512GB) it goes up to 100MB/second.

**Comment by generall** [comment]
it is likely that storage class is configured wrong

**Comment by shubham-kharche** [comment]
But wouldn't that have affected the other pod as well? Since they have similar storage classes.
The other pod is running fine and also serving the search requests successfully.

**Comment by dhruv-clootrack** [comment]
> it is likely that storage class is configured wrong

I'm from same team as @shubham-kharche

@generall Please can you give more details on how to configure storage class better or can reference to doc will also help

**Comment by shubham-kharche** [comment]
The issue got fixed after:
- removing PVC attached to the pod (which was failing) and restoring the data using snapshot on newer PVC
- reinstalling the qdrant using helm

Closing this.
