### ISSUE TITLE
Memory consumption always zero in API response

### ISSUE THREAD

**Issue by Teagum** [qdrant/qdrant#528]
I have a qdrant instance running on AWS with a single collection of about 3.5 GB in size (on my local machine). I tried to check out the actual memory consumption on the server, however, those values are always zero in the API response of the following snippet:

```
from qdrant_client import QdrantClient

client = QdrantClient(host="my_host.com", port=6333)
rsp = client.http.collections_api.get_collection("my_collection") 

print(rsp.result.disk_data_size, rsp.result.ram_data_size)    # -> 0 0
```

Could you give me any hint on what's going on here?

**Comment by generall** [comment]
Hi @Teagum, ram usage data is currently not implemented - https://github.com/qdrant/qdrant/issues/5

It turned out to be a much harder challenge than is looks like, so most likely this field will be removed in upcoming versions.
