### ISSUE TITLE
Be able to filter text by prefix

### ISSUE THREAD

**Issue by hugo-ijw** [qdrant/qdrant#5300]
Hey,
I've seen there are a [few ways to filter keyword payload](https://qdrant.tech/documentation/concepts/filtering)
However, could the text payload be filtered based on a specific prefix?

For instance, what if I would like to store my points within a folder structure and retrieve points lying in a specific folder:  
```json
{
  "key": "folder",
  "startsWith": {
    "value": "/a/b/c/"
  }
}
```

Thank you!

**Comment by generall** [comment]
https://qdrant.tech/documentation/concepts/indexing/?q=prefix#full-text-index

> prefix - splits the string into words, separated by spaces, punctuation marks, and special characters, and then creates a prefix index for each word. For example: hello will be indexed as h, he, hel, hell, hello.
