### ISSUE TITLE
REST API: params for payload indexes

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#5304]
Hello.

I did not find here https://api.qdrant.tech/api-reference/indexes/create-field-index how add params for index
via on_disk, lookup, range and etc.

Protobuf API contains this functionality.

Could You add this into REST API, please?
Thanks.

**Comment by generall** [comment]
https://api.qdrant.tech/api-reference/indexes/create-field-index#request.body.field_schema.Payload%20Field%20Schema.Payload%20Schema%20Params.keyword.on_disk

https://qdrant.tech/documentation/concepts/indexing/?q=on+disk+index#on-disk-payload-index

**Comment by ava57r** [comment]
Oh! Thanks!
