### ISSUE TITLE
How to implement Partial Matching for Facets Using Keywords in Qdrant

### ISSUE THREAD

**Issue by manish-eclat** [qdrant/qdrant#5335]
- Currently, the facets feature in Qdrant only returns results for exact matches in filters. However, we need the ability to retrieve facets based on partial matching of strings when using search keywords.

- For example, with the current setup:

```
import { QdrantClient } from "@qdrant/js-client-rest";

const client = new QdrantClient({ host: "localhost", port: 6333 });

client.facet("{collection_name}", {
    filter: {
        must: [
            {
                key: "color",
                match: {
                    value: "red",
                },
            },
        ],
    },
    key: "size",
});
```

- The facet can be fetched for exact matches (e.g., "red").
- However, there is no support for partial matching (e.g., matching "re" to "red")

**Comment by generall** [comment]
i think you need to use full-text index with prefix tokenizer for that https://qdrant.tech/documentation/concepts/indexing/?q=prefix+#full-text-index

**Comment by generall** [comment]
Does it resolve you problem, @manish-eclat ?

**Comment by manish-eclat** [comment]
Thanks, @generall, for your answer! I have a follow-up question.

Here's what we're aiming to implement: we want to display some facets on the left side of the interface. When a user performs a search, we want the facets to update dynamically based on the search keyword.

My question is, how can we pass the vector representation of the search keyword to retrieve the facets? The goal is to perform a semantic search and get the updated facets accordingly.

**Comment by generall** [comment]
facets with vector search are not possible, as vectors will match with any other vector in the collection. Usage of the score threshold won't help either, because this request will be as expensive as search with unbound limit.
