### ISSUE TITLE
Feature Request: JSON logging option

### ISSUE THREAD

**Issue by freinold** [qdrant/qdrant#5347]
Currently, logs are only produced as a semi-structured string.
Due to this, Tools like Kibana are not able to automatically parse the log into more detailed insights.

To fix this, JSON logging and a configuration option to enable it should be enabled.
This would enable qdrant users to build more intricate dashboards and analyze their logs better in Tools like Kibana.

**Comment by thundersparkf** [comment]
Hey! I'm new to this space and I'd like to pick this up. Would that be cool?

**Comment by freinold** [comment]
Thanks a lot @timvisee and @gulshan-rs!

**Comment by timvisee** [comment]
We've just released [Qdrant 1.12.6](https://github.com/qdrant/qdrant/releases/tag/v1.12.6) which includes JSON logging.
