### ISSUE TITLE
QDrant on Windows 11 system crashes while creating collections

### ISSUE THREAD

**Issue by cv-msan** [qdrant/qdrant#5388]
## Steps to Reproduce

1.I downloaded the latest version of qdrant for Windows
2.Double click the mouse to run qdrant.exe
3.After running, the terminal output is as follows

4.When running the web UI to create collections, the terminal will crash

**Comment by cv-msan** [comment]
![image](https://github.com/user-attachments/assets/2716de8d-db6b-411a-ab7f-5b835a5712f7)

**Comment by timvisee** [comment]
Could it be a disk permission problem?

I don't see any logs attached. Please provide these if you have them, because I assume a reason for the crash will be stated in there.

**Comment by cv-msan** [comment]
Yes, there were no error message logs and the terminal was closed directly. I also tried running it with an administrator and the result was the same

**Comment by Fuelinger** [comment]
Had a similar Error on Windows Server. Installing the latest Microsoft Visual C++ redistributables solved it. Give it a try --> https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by timvisee** [comment]
> Yes, there were no error message logs and the terminal was closed directly. I also tried running it with an administrator and the result was the same

Qdrant is not meant to be ran directly by double clicking the binary.

Please open a terminal in that directory instead, and start it with `.\qdrant.exe`.

@Fuelinger Thanks! Yes, installing recent Microsoft Visual C++ redistributables is required.

**Comment by cv-msan** [comment]
@Fuelinger thank you！I solved it according to what you said

**Comment by nicolab28** [comment]
Thank you! 
Same incomprehensible error.
After having tested an application on two development PCs, fairly recently, without any problems, I wanted to deploy it as a test on an old development PC running win10.
Qdrant.exe kept crashing, with no messages. Impossible to do anything.
On this PC, I must have had the msvc-1700, I think, but an old version.
Since the update, it works perfectly!
