### ISSUE TITLE
search_groups could support DENSE+SPARSE

### ISSUE THREAD

**Issue by sglebs** [qdrant/qdrant#5397]
Hi,

 I am getting some slowness due to the need to make 2 calls into search_groups - the API below.

```python
def search_groups(
    self,
    collection_name: str,
    query_vector: Union[
        Sequence[float],
        Tuple[str, List[float]],
        types.NamedVector,
        types.NamedSparseVector,
        types.NumpyArray,
    ],
```

I have to call it once with a DENSE vector (representing the sentence), then again with a SPARSE vector (representing the same sentence), and merge the 2 results myself. But query_points API is smart and allows a combined usage of DENSE+SPARSE: https://qdrant.tech/blog/qdrant-1.10.x/#native-hybrid-search-support

Can this “mixed mode” please be added to search_groups? I would think that it would make my query run significantly faster.

Maybe “query_vector” could also take a list of vectors?

   Thanks,

Marcio

**Comment by generall** [comment]
Why not query groups? https://api.qdrant.tech/master/api-reference/search/query-points-groups

**Comment by sglebs** [comment]
> Why not query groups? https://api.qdrant.tech/master/api-reference/search/query-points-groups

Thanks for pitching in!

Simply put, I was not aware of this alternate form, for whatever reason.
