### ISSUE TITLE
Expose gRPC API

### ISSUE THREAD

**Issue by kgrech** [qdrant/qdrant#54]
**Is your feature request related to a problem? Please describe.**
Right now the only way to interact with the system is by using JSON API. It enforces the data to be encoded as a human-readable text format, which is not the most effective approarch. Having the binary encoded protocol like GRPc would be a big win for the project in my option

**Describe the solution you'd like**
- Add 2 features to the project: web and grpc. Enable web by default, disable grpc by default until ready. They way we could merge the code during dev without affecting the production binary. Once ready we could potentially disable/enable the given type of API at the compile time.
-  Use [tonic](https://github.com/hyperium/tonic) crate
- Refactor the app crate to have 2 submodules under the API modules: web and grpc. Also, add a ``common`` submodule.
- The common module would contain the functions like this:
```
fn get_collections(toc: TableOfContent) -> CollectionsResponse {
    let collections = toc
        .all_collections()
        .into_iter()
        .map(|name| CollectionDescription { name })
        .collect_vec();

    CollectionsResponse { collections }
}
```
- Common module is to be used by web and grpc modules 

**Describe alternatives you've considered**
- There is also the [grpc-rus](https://github.com/stepancheg/grpc-rust) create, but as per a few [blogs](https://blog.logrocket.com/rust-and-grpc-a-complete-guide/) I've read it is not production-ready yet
- We could use other binary protocols, but I think the grpc is the most popular

**Additional context**
N/A

**Comment by generall** [comment]
Released in https://github.com/qdrant/qdrant/releases/tag/v0.6.0
