### ISSUE TITLE
Wasteful storage, please add dot search for packed bits

### ISSUE THREAD

**Issue by beviah** [qdrant/qdrant#5442]
If I want to store a binary vector directly into Qdrant, i can only use uint8 datatype, so have to pack bits. Then in order for dot product to work, you need to add an option to handle packed bits. 

# Original bits
bits_a = np.array([1,1,0,0,1,0,1,0], dtype=np.uint8)
bits_b = np.array([1,1,0,1,1,0,0,0], dtype=np.uint8)

# Packed version
packed_a = np.packbits(bits_a)
packed_b = np.packbits(bits_b)

# Similarities
original_dot = np.dot(bits_a, bits_b)
packed_dot = np.unpackbits(np.bitwise_and(packed_a, packed_b)).sum()

assert original_dot == packed_dot

Not sure if this can be trivial change or there's more going on under the hood..

**Comment by generall** [comment]
hey @beviah, qdrant doesn't use np or even python to store vectors, but we do have limitation of the minimal data type. Currently you can have binary compressed vectors in RAM, but you still would need to have at least int8 stored on disk.

**Comment by beviah** [comment]
Above solution is illustration, it should be doable in RUST as well..

**Comment by timvisee** [comment]
> Above solution is illustration, it should be doable in RUST as well..

Rust is not a limitation here. It's about the storage infrastructure we already have. It'd require significant changes to make bit-level storage work. 

The suggestion by Andrey is a valid alternative if the concern is about memory usage.

**Comment by beviah** [comment]
Again, this is not about changing storage type, but adding similarity for packed bits:

Again, LLM generated, so needs verification by someone who knows Rust. 

```
use std::arch::x86_64::*;

/// SIMD-optimized batch similarity computation
/// Processes 16 bytes at once using SSE2
#[cfg(target_arch = "x86_64")]
unsafe fn batch_similarity_simd(query: &[u8], vectors: &[Vec<u8>]) -> Vec<u32> {
    let chunks_16 = query.len() / 16;
    let remainder = query.len() % 16;
    
    vectors.iter()
        .map(|vec| {
            let mut sum = 0u32;
            
            // Process 16 bytes at a time using SIMD
            for i in 0..chunks_16 {
                let offset = i * 16;
                let q = _mm_loadu_si128(query[offset..].as_ptr() as *const __m128i);
                let v = _mm_loadu_si128(vec[offset..].as_ptr() as *const __m128i);
                
                // AND operation and population count
                let matched = _mm_and_si128(q, v);
                sum += popcnt_16_bytes(matched);
            }
            
            // Handle remaining bytes
            if remainder > 0 {
                let offset = chunks_16 * 16;
                sum += query[offset..]
                    .iter()
                    .zip(&vec[offset..])
                    .map(|(&q, &v)| (q & v).count_ones())
                    .sum::<u32>();
            }
            
            sum
        })
        .collect()
}

/// Count bits in 16 bytes using POPCNT instruction
#[cfg(target_arch = "x86_64")]
#[inline]
unsafe fn popcnt_16_bytes(v: __m128i) -> u32 {
    let mut counts = 0u32;
    let ptr = &v as *const _ as *const u64;
    
    // Process two 64-bit integers
    for i in 0..2 {
        counts += _popcnt64(*ptr.add(i));
    }
    
    counts
}

/// Safe wrapper for SIMD operations
fn batch_similarity_safe(query: &[u8], vectors: &[Vec<u8>]) -> Vec<u32> {
    if is_x86_feature_detected!("sse2") && is_x86_feature_detected!("popcnt") {
        unsafe { batch_similarity_simd(query, vectors) }
    } else {
        batch_similarity(query, vectors)  // Fall back to scalar version
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_simd_batch_similarity() {
        // Create test vectors that are multiple of 16 bytes
        let query = vec![1u8; 32];
        let vectors = vec![
            vec![1u8; 32],     // Should match all bits
            vec![0u8; 32],     // Should match no bits
            vec![1, 0].repeat(16)  // Should match half bits
        ];
        
        let similarities = batch_similarity_safe(&query, &vectors);
        assert_eq!(similarities, vec![32, 0, 16]);
    }
}
```

**Comment by timvisee** [comment]
> Again, this is not about changing storage type, but adding similarity for packed bits:

Support that does in turn require changing storage type. It is not as simple as just adding your snippet in the code base.

**Comment by beviah** [comment]
Ah, ok.. not sure I get it but seems storage is optimized in some way not quite obvious from `lib/segment/src/spaces/metric_uint/avx2/dot.rs`

**Comment by beviah** [comment]
also, in my use case, I would actually feed Qdrant with already packed bits, so Qdrant would see uint8 only, only custom similarity function would know it is dealing with packed bits.

**Comment by timvisee** [comment]
But once again, what is the concern here? Is it about memory consumption or persisted (disk) storage usage? We consider disk storage to be relatively cheap.

**Comment by beviah** [comment]
My current tests show that searching on-disk vectors is super slow, in fact timeouts with <20M vectors, and I am aiming at 1B+. This renders current setup of Qdrant unusable :(

**Comment by beviah** [comment]
And hard for me to understand how you can consider 8x storage savings a non-issue, even if it is relatively cheap..

**Comment by generall** [comment]
search through billions of vectors on disk, even if there are binary compressed, won't be much fast anyway. We highly recommend to keep binary quantized vectors in RAM. In conbination with matriyoshka-style cut off of the vectors it should give relatively small memory footprint.

**Comment by timvisee** [comment]
> And hard for me to understand how you can consider 8x storage savings a non-issue, even if it is relatively cheap..

We don't consider it a non-issue, we never said that. That's why we're still evaluating on whats possible.

**Comment by beviah** [comment]
Thanks for responses.. I'll see what I can do to achieve my goals..

**Comment by beviah** [comment]
https://github.com/unum-cloud/usearch

USearch solved my problem. on-disk sharded finds results in a second from 10M vectors (where qdrant is timing out with 20M, so >60 seconds). and i can store compressed vectors and have custom similarity functions..

**Comment by beviah** [comment]
millisecond for on-disk or RAM? my vectors wont fit in ram, not even quantized.

**Comment by generall** [comment]
quantized vectors can be configured on-disk as well. Glad that you found a solution for your problem
