### ISSUE TITLE
Example search with filter gives 422 response

### ISSUE THREAD

**Issue by regstuff** [qdrant/qdrant#553]
I'm trying out the examples here: https://qdrant.github.io/qdrant/redoc/index.html

The collection gets created and search without any filters returns results as expected.

Here's what I get WITHOUT using filters: 
`'{'result': [{'id': 4, 'version': 0, 'score': 1.362, 'payload': None, 'vector': None}, {'id': 1, 'version': 0, 'score': 1.273, 'payload': None, 'vector': None}, {'id': 3, 'version': 0, 'score': 1.208, 'payload': None, 'vector': None}], 'status': 'ok', 'time': 0.000127168}`

However, upon executing the next step in the example, where we search with filters, I get a 422 error for the request.

Here's the curl command I issue for search WITH filters, which returns the 422 response:

```
curl -L -X POST 'http://localhost:6333/collections/test_collection/points/search' \ -H 'Content-Type: application/json' \ --data-raw '{
    "filter": {
        "should": [
            {
                "key": "city",
                "match": {
                    "value": "London"
                }
            }
        ]
    },
    "vector": [0.2, 0.1, 0.9, 0.7],
    "top": 3
}'
```

Can anyone let me know what I'm doing wrong.

**Comment by generall** [comment]
Discussed issue in the community chat: https://discord.qdrant.tech/

The problem was related to version mismatch - example expects v0.7.0+
