### ISSUE TITLE
Search with should filters return no results for empty list 

### ISSUE THREAD

**Issue by kacperlukawski** [qdrant/qdrant#554]
## Steps to Reproduce

1. Create a new collection
```
curl -X PUT 'http://localhost:6333/collections/test_collection' \
  -H 'Content-Type: application/json' \
  --data-raw '{
        "vector_size": 4,
        "distance": "Dot"
    }'
```
2. Put some vectors with payloads
```
curl -L -X PUT 'http://localhost:6333/collections/test_collection/points?wait=true' \
  -H 'Content-Type: application/json' \
  --data-raw '{
        "points": [
          {"id": 1, "vector": [0.05, 0.61, 0.76, 0.74], "payload": {"city": "Berlin"}},
          {"id": 2, "vector": [0.19, 0.81, 0.75, 0.11], "payload": {"city": ["Berlin", "London"] }},
          {"id": 3, "vector": [0.36, 0.55, 0.47, 0.94], "payload": {"city": ["Berlin", "Moscow"] }},
          {"id": 4, "vector": [0.18, 0.01, 0.85, 0.80], "payload": {"city": ["London", "Moscow"] }},
          {"id": 5, "vector": [0.24, 0.18, 0.22, 0.44], "payload": {"count": [0] }},
          {"id": 6, "vector": [0.35, 0.08, 0.11, 0.44]}
        ]
    }'
```
3. Search for the closest vectors with an empty list of "should" filters
```
curl -L -X POST 'http://localhost:6333/collections/test_collection/points/search' \
  -H 'Content-Type: application/json' \
  --data-raw '{
      "filter": {
          "should": []
      },
      "vector": [0.2, 0.1, 0.9, 0.7],
      "top": 3
  }'
```

The response doesn't contain any results:
`{"result":[],"status":"ok","time":0.000218003}`

However, if we provided `null` instead of an empty list, the results are returned properly:
`{"result":[{"id":4,"version":4,"score":1.362,"payload":null,"vector":null},{"id":1,"version":4,"score":1.273,"payload":null,"vector":null},{"id":3,"version":4,"score":1.208,"payload":null,"vector":null}],"status":"ok","time":0.000217165}`

## Expected Behavior

I would expect an empty list of should filters will return with the same results as if there was `null` value provided.

## Context (Environment)

I was incrementally building the filtering criteria, and started with an empty list.

**Comment by generall** [comment]
> I was incrementally building the filtering criteria, and started with an empty list.

but in case of `should` condition - more criteria you add, more results you would get. 
In this scenario the behavior of `should` condition matches the specification of https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.any
Maybe you could expect this from `must` condition instead?

**Comment by kacperlukawski** [comment]
Elasticsearch had a similar discussion, but they finally decided to treat the empty _should_ filter as a _match_all_ scenario:
https://github.com/elastic/elasticsearch/issues/8676

I don't claim this is the intended behaviour, but I faced that issue once while using Elasticsearch ;) Just thought it would be good to be consistent with the other systems.

**Comment by generall** [comment]
I have also discovered, that gRPC version does not allow to specify the difference between empty array and None.
So I would prefer to keep current behavior
