### ISSUE TITLE
Qdrant creates many directories even if no snapshot is created. 

### ISSUE THREAD

**Issue by zenxme** [qdrant/qdrant#5558]
## Current Behavior
Qdrant creates many directories even if no snapshot is created. 

## Steps to Reproduce
1. create 100 collections.
2. delete them.

```python
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams


client = QdrantClient("localhost", port=6333, grpc_port=6334, prefer_grpc=True)


for i in range(100):
    name = f'tmp_{i}'
    client.create_collection(
        collection_name=name,
        vectors_config=VectorParams(size=4, distance=Distance.DOT),
        shard_number=1,
        replication_factor=1,
    )
    client.delete_collection(collection_name=name)
    print(name)

```

## Expected Behavior
The snapshots directories should be deleted when the collection is deleted. But after the code runs, they are still there. 

A cluster that has been running for a long time may have many empty directories.

**Comment by timvisee** [comment]
> But after the code runs, they are still there.

It is kept because in some cases they may function as backup. You don't want to lose your backups when deleting a collection.

A better solution may be this:
1. do not create collection snapshot directory on collection creation
2. create collection snapshot directory when creating snapshot if it doesn't exist yet

In that case snapshot directories will still remain if they're there if you delete the collection. But, they won't be created in the first place if you don't create any snapshots.

**Comment by zenxme** [comment]
> > But after the code runs, they are still there.但代码运行后，它们仍然存在。
> 
> It is kept because in some cases they may function as backup. You don't want to lose your backups when deleting a collection.保留它是因为在某些情况下它们可以充当备份。您不想在删除集合时丢失备份。
> 
> A better solution may be this:更好的解决方案可能是这样的：
> 
> 1. do not create collection snapshot directory on collection creation创建集合时不要创建集合快照目录
> 2. create collection snapshot directory when creating snapshot if it doesn't exist yet创建快照时创建集合快照目录（如果尚不存在）
> 
> In that case snapshot directories will still remain if they're there if you delete the collection. But, they won't be created in the first place if you don't create any snapshots.在这种情况下，如果您删除集合，快照目录仍然会保留（如果它们在那里）。但是，如果您不创建任何快照，则首先不会创建它们。

Thank you for your response. Yes, they will solve the problems. I wish it would be fixed in the future.

**Comment by gulshan-rs** [comment]
> A better solution may be this:

>  do not create collection snapshot directory on collection creation
>  create collection snapshot directory when creating snapshot if it doesn't exist yet


@timvisee let me know if you think we should attempt to make this better. I can work on a PR.

**Comment by timvisee** [comment]
> > A better solution may be this:
> 
> >  do not create collection snapshot directory on collection creation
> >  create collection snapshot directory when creating snapshot if it doesn't exist yet
> 
> 
> @timvisee let me know if you think we should work on the above suggestion(you posted earlier). I can work on a PR. 

Feel free to give it a shot based on that suggested alternative!

**Comment by timvisee** [comment]
Fixed by <https://github.com/qdrant/qdrant/pull/5574>
