### ISSUE TITLE
Expose a method to duplicate the collection with a different distance function

### ISSUE THREAD

**Issue by kacperlukawski** [qdrant/qdrant#560]
**Describe the solution you'd like**
I'd like to be able to duplicate a collection of points, but with a different distance function. Together with aliases, they might be a powerful combo allowing to switch the distance function seamlessly.

**Describe alternatives you've considered**
Right now I need to use CLI or qdrant-client to recreate the collection with the same vectors but select a different function. Thus, I need to keep the vectors outside of qdrant or recreate them (which may take a lot of time).

**Comment by generall** [comment]
That would require full index re-building and non-trivial architecture changes. Also usually the distance function is known in advance from the training process.
