### ISSUE TITLE
内存占用很大

### ISSUE THREAD

**Issue by zhang19523zhao** [qdrant/qdrant#5607]
![QQ_1733738084811](https://github.com/user-attachments/assets/72937bae-975d-4211-ad2b-e7db4eb2fefb)

![QQ_1733738095149](https://github.com/user-attachments/assets/825d41c5-2a90-4199-8bbb-1011a222d041)

![QQ_1733738111858](https://github.com/user-attachments/assets/da785764-78c8-4e18-ba22-3490cda58ef0)
每个节点都去到了50g

**Comment by timvisee** [comment]
Based on your configuration you put the HNSW index and the payload on disk. However, vectors are still in memory.

Please set `on_disk: true` inside the vectors configuration using the [update](https://qdrant.tech/documentation/concepts/collections/#update-collection-parameters) API to also put those on disk.

Note that even then, Qdrant will still try to consume all memory available because that'll be the most efficient way to run it. The difference is that it will not crash if the memory limit is reached, because it'll automatically release memory if something else needs it.

**Comment by zhang19523zhao** [comment]
> Based on your configuration you put the HNSW index and the payload on disk. However, vectors are still in memory.
> 
> Please set `on_disk: true` inside the vectors configuration using the [update](https://qdrant.tech/documentation/concepts/collections/#update-collection-parameters) API to also put those on disk.
> 
> Note that even then, Qdrant will still try to consume all memory available because that'll be the most efficient way to run it. The difference is that it will not crash if the memory limit is reached, because it'll automatically release memory if something else needs it.



curl --location --request PATCH 'http://10.0.0.18:6343/collections/qa_embedding_point' \
--header 'Content-Type: application/json' \
--data '{
    "vectors": {
        "": {
            "on_disk": true
        }
    }
}'
After I set it up, restarted the qdrant cluster and waited for him to finish loading the memory was still directing 50gb per node. is it because of this config?

```txt
“quantization_config": {
    “scalar": {
      “type": ‘int8’, ‘always_ram’: { ‘always_ram’: { ‘always_ram’: {
      “always_ram": true
    }
```
![QQ_1733747941388](https://github.com/user-attachments/assets/2bf3f002-a3d3-43d4-a095-721f778d1366)

But if I don't add this configuration, the query is almost 1.5 to 2 seconds, is there something I set wrong?

```python
    start = datetime.datetime.now()
    similary = requests.post("http://10.0.0.18:6343/collections/qa_embedding_point/points/search",json={ "with_payload":["id","content"],"vector":get_embedding(question),"limit":size}).json()
    print("qdrant查询耗时: ", datetime.datetime.now() - start)
    return similary
````


Here is my configuration
# config 
{
  "params": {
    "vectors": {
      "size": 1024,
      "distance": "Cosine",
      "on_disk": true
    },
    "shard_number": 6,
    "replication_factor": 2,
    "write_consistency_factor": 1,
    "on_disk_payload": true
  },
  "hnsw_config": {
    "m": 16,
    "ef_construct": 100,
    "full_scan_threshold": 10000,
    "max_indexing_threads": 0,
    "on_disk": true
  },
  "optimizer_config": {
    "deleted_threshold": 0.2,
    "vacuum_min_vector_number": 1000,
    "default_segment_number": 2,
    "max_segment_size": null,
    "memmap_threshold": null,
    "indexing_threshold": 20000,
    "flush_interval_sec": 5,
    "max_optimization_threads": null
  },
  "wal_config": {
    "wal_capacity_mb": 32,
    "wal_segments_ahead": 0
  },
  "quantization_config": {
    "scalar": {
      "type": "int8",
      "always_ram": true
    }
  },
  "strict_mode_config": {
    "enabled": false
  }
}

# payload_schema

{
  "judgementDate": {
    "data_type": "keyword",
    "points": 37539045
  },
  "full_crime_reason": {
    "data_type": "keyword",
    "points": 37491799
  },
  "authority": {
    "data_type": "keyword",
    "points": 37877
  }
}

**Comment by timvisee** [comment]
Your configuration change (moving vectors on disk) is correctly applied.

Again, even though data is moved on disk it may still consume all available memory. There normally is nothing to be concerned about though.

Checking just the memory usage is not reliable, because it includes caches and memory mapped pages.

**Comment by zhang19523zhao** [comment]
> Your configuration change (moving vectors on disk) is correctly applied.
> 
> Again, even though data is moved on disk it may still consume all available memory. There normally is nothing to be concerned about though.
> 
> Checking just the memory usage is not reliable, because it includes caches and memory mapped pages.
Okay, is it possible to limit the memory usage directly, because I just imported more than 30 million data into now qdrant cluster used 150gb memory, I import 140 million data later I am afraid that the memory will be very large. I'm afraid that the memory will be too big when I import 140 million data later on.

**Comment by zhang19523zhao** [comment]
> > Okay, is it possible to limit the memory usage directly, because I just imported more than 30 million data into now qdrant cluster used 150gb memory
> 
> Limit the usage to what? Do you not want to use more than 50% of memory (for example) at any point in time because you need to share it with other applications, or something like that? It now uses a more than you might expect just because that memory is there. Unused memory is wasted memory.
> 
> Again, if more memory is needed Qdrant will automatically release memory as needed. I therefore have no concerns about memory usage, even if you're about to upload 140 million points later on.
> 
> See the following in our calculator: https://cloud.qdrant.io/calculator?provider=aws&region=us-east-1&vectors=140000000&dimension=1024&storageOptimized=true&replicas=2&quantization=Scalar
> 
> It estimates roughly needing 76 GB per replica, that's 152 GB with a replication factor of two. I have no concerns of this being problematic.
> 
> I'd recommend to upload the 140 million points with the current configuration to see if it behaves as expected.

Ok, since I'm importing over 30 million data now 3 nodes totaling over 160+gb of memory, I'm afraid that 140 million data might take a very large amount of memory before using it

**Comment by timvisee** [comment]
> Ok, since I'm importing over 30 million data now 3 nodes totaling over 160+gb of memory, I'm afraid that 140 million data might take a very large amount of memory before using it

Are you afraid of it crashing, because it goes out of memory?

As I said above, I don't think that is a valid concern and it should run totally fine. Even if growing your data by about 5 times.

**Comment by zhang19523zhao** [comment]
> Are you afraid of it crashing, because it goes out of memory?
> 
> As I said above, I don't think that is a valid concern and it should run totally fine. Even if growing your data by about 5 times.

Ok thanks, I am afraid that if I import so much data memory is too large, if you get 3 nodes of qdrant server 300gb memory memory is not enough to start

**Comment by timvisee** [comment]
It will be fine due to the on-disk flags.

Please give uploading all your data a try and come back if problems appear. :smile:

**Comment by zhang19523zhao** [comment]
> It will be fine due to the on-disk flags.
> 
> Please give uploading all your data a try and come back if problems actually appear. 😄

Okay. Thank you very much.
