### ISSUE TITLE
Datetime filtering not working as expected.

### ISSUE THREAD

**Issue by manish-eclat** [qdrant/qdrant#5641]
### Title:
Datetime filtering not working as expected.

### Description:
I have a collection named `oacontent` which contains payloads with the following format (**FYI**):

```json
{
  "id": 4319297759,
  "payload": {
    "type": "article",
    "language": "en",
    "publication_date": "2023-01-01T00:00:00",
    "created_date": "2023-01-01T00:00:00",
    "version": "2",
    "subject": "Materials Chemistry",
    "title": "Correction: Increased photocorrosion resistance of ZnO foams <i>via</i> transition metal doping",
    "keywords": ["Ferromagnetism"]
  }
}
```

- Please note that the publication_date is an ISO string.
- Payload Schema: 

![{3DE62C9C-B5A8-4E88-940E-F20FE9844F1D}](https://github.com/user-attachments/assets/689812c8-bc96-4d44-8b81-f8f18164ebb0)

- When I try to count records using the following filter:

```js
import { QdrantClient } from "@qdrant/js-client-grpc";

const client = new QdrantClient({ host: "127.0.0.1", port: 6334 });

const res = await client.api("points").count({
  collectionName: "oacontent",
  filter: {
    must: [
      {
        conditionOneOf: {
          case: "field",
          value: {
            key: "publication_date",
            datetimeRange: {
              lte: "2024-12-13T00:00:00",
              gte: "2023-12-13T00:00:00",
            },
          },
        },
      },
    ],
  },
});
```

- The result always returns 307 documents, irrespective of the filter values. Changing the filter range does not affect the result.

### Issue:
The count API does not seem to apply the datetimeRange filter correctly. It always returns the total number of documents (307), ignoring the provided date range filters.

### Additional Information:
Library: @qdrant/js-client-grpc (v1.12.0)
Qdrant Version: (v1.12.5)

**Comment by generall** [comment]
Could you please try `exact: true` option in count api and let us know here.

**Comment by Waffleboy** [comment]
@manish-eclat see https://github.com/qdrant/qdrant/issues/5595

**Comment by manish-eclat** [comment]
- @generall @Waffleboy  I also checked with the **exact: true** option. But I am getting the same results.

```js
const res = await client.api("points").count({
  collectionName: "oacontent",
  **exact: true**,
  filter: {
    must: [
      {
        conditionOneOf: {
          case: "hasId",
          value: {
            hasId: [
              {
                pointIdOptions: {
                  case: "num",
                  value: BigInt(4319297759),
                },
              },
            ],
          },
        },
      },
      {
        conditionOneOf: {
          case: "field",
          value: {
            key: "publication_date",
            range: {
              gte: "2023-01-01T10:00:00",
              gte: null,
              lt: null,
              lte: "2024-01-31T10:14:31",
            },
          },
        },
      },
    ],
  },
});
```

- If I try to query with the same filter in the Qdrant dashboard I get the correct results.

```js
POST collections/oacontent/points/scroll
{
    "filter": {
        "must": [
            { "has_id": [4319297759] },
            {
              "key": "publication_date",
              "range": {
                "gte": "2023-01-01T10:00:00",
                "gte": null,
                "lt": null,
                "lte": "2024-01-31T10:14:31"
              }
            }
        ]
    },
    "with_payload": true,
    "with_vector": false
}
```

![{652A8A14-3B00-4D5F-A59D-4755E3A217BA}](https://github.com/user-attachments/assets/808676fe-07f1-4037-b6de-005ece56d18c)

**Comment by manish-eclat** [comment]
- There was an issue with how the date was being passed in the filter for the count API.
- Previously, the date range was passed in the following incorrect format:

```json
{
  "conditionOneOf": {
    "case": "field",
    "value": {
      "key": "publication_date",
      "datetimeRange": {
        "gt": "2023-01-01T00:00:00",
        "gte": null,
        "lt": null,
        "lte": "2024-01-31T10:14:31"
      }
    }
  }
}
```

- Instead, the date should be passed in the correct format using datetimeRange with seconds, as shown below (**FYI**), and it works as expected:

```json
{
  "conditionOneOf": {
    "case": "field",
    "value": {
      "key": "publication_date",
      "datetimeRange": {
        "lte": {
          "seconds": 1704047400
        },
        "gte": {
          "seconds": 1734460200
        }
      }
    }
  }
}
```
- This resolves the issue with the date filter not being applied correctly.
