### ISSUE TITLE
search_batch has not performence improve

### ISSUE THREAD

**Issue by moonmon** [qdrant/qdrant#5668]
**Is your feature request related to a problem? Please describe.**
use query_batch_points or search_batch func has not performence increase, this is a restrict. is a spurious batch?

**Describe the solution you'd like**
what can i  do for authentic batch

**Describe alternatives you've considered**
It's not supposed to be like this

**Additional context**

<img width="1100" alt="qdrant_batch2" src="https://github.com/user-attachments/assets/1cf95473-8ac7-4cd0-b4cb-c37b70c82afe" />
<img width="1112" alt="qdrant_batch1" src="https://github.com/user-attachments/assets/15e5cf58-b60b-46e1-bff9-b79952fcf4bc" />

**Comment by generall** [comment]
Batch request has performance boost in some specific cases (like re-usable filtering condition). It won't magically make CPU-intensive search faster.

**Comment by moonmon** [comment]
Thanks for getting back to me and saving me time 😊
