### ISSUE TITLE
Optimization taking too long 

### ISSUE THREAD

**Issue by AlterHoodie** [qdrant/qdrant#5681]
Have a few doubts regarding qdrant's optimization 
The collection currently has 10005 points and below is the collection configuration
```
{
  "params": {
    "vectors": {
      "colbertv2.0": {
        "size": 128,
        "distance": "Cosine",
        "on_disk": true,
        "multivector_config": {
          "comparator": "max_sim"
        }
      },
      "nomic-embed-text-v1": {
        "size": 768,
        "distance": "Cosine",
        "on_disk": true
      }
    },
    "shard_number": 1,
    "replication_factor": 1,
    "write_consistency_factor": 1,
    "on_disk_payload": true,
    "sparse_vectors": {
      "bm25": {
        "index": {
          "on_disk": true
        },
        "modifier": "idf"
      },
      "splade": {
        "index": {
          "on_disk": true
        },
        "modifier": "idf"
      }
    }
  },
  "hnsw_config": {
    "m": 16,
    "ef_construct": 100,
    "full_scan_threshold": 10000,
    "max_indexing_threads": 0,
    "on_disk": false
  },
  "optimizer_config": {
    "deleted_threshold": 0.2,
    "vacuum_min_vector_number": 1000,
    "default_segment_number": 0,
    "max_segment_size": null,
    "memmap_threshold": null,
    "indexing_threshold": 20000,
    "flush_interval_sec": 5,
    "max_optimization_threads": null
  },
  "wal_config": {
    "wal_capacity_mb": 32,
    "wal_segments_ahead": 0
  },
  "quantization_config": null,
  "strict_mode_config": {
    "enabled": false
  }
}
```
1) How long does it usually take to optimize the above collection, since the collection status has been in yellow for quite a few days
2) What all parameters I can change to reduce the optimization time and the tradeoffs associated with it
3) Will the optimization resume, if I restart the docker container

**Comment by timvisee** [comment]
> How long does it usually take to optimize the above collection

That is not easy to answer, because it depends on a lot of variables. But I'm quite confident that for 10005 it should always complete within a few minutes, even on limited hardware.

> since the collection status has been in yellow for quite a few days

That definitely sounds like something is off.

Out of curiosity, are you constantly changing this set of points? Or has it been yellow for a long time without doing any update operations at all?

Also, do you have any other collections on this instance?

> What all parameters I can change to reduce the optimization time and the tradeoffs associated with it

I'd rather dive into why it seems to be stuck first and fix that. Then we can dive into tuning it further if you think it's too slow.

> Will the optimization resume, if I restart the docker container

Normally it does not, and we do that on purpose to prevent crash loops. You can send an update operation to trigger it again.

There's a 'trigger optimizers' button in the web UI next to the grey collection status. Or you can send an empty update as described here: https://qdrant.tech/documentation/concepts/collections/#grey-collection-status

Please give restarting and triggering the optimizers again like described above a shot.

**Comment by AlterHoodie** [comment]
It has been yellow for a long time without doing any update operations.
There are other collections in the instance, but all of them have been optimized
Is it because there are 4 different embeddings attached to a particular point?
It has currently indexed 38214 vectors, 
will give restarting a shot.

**Comment by timvisee** [comment]
>  Is it because there are 4 different embeddings attached to a particular point?

If it's just 4 it should not increase indexing time in a very significant way.

>  There are other collections in the instance, but all of them have been optimized

Okay! I'm asking because resources are shared. If some collection is doing heavy optimizations, other collections may be waiting for resources to be released showing a yellow state.

>  will give restarting a shot.

Thanks!

**Comment by generall** [comment]
Indexing time for multivectors is heavily affected by the amount of sub-vectors. Keep in mind that complexity of `max_sim` is quadratic to the number of those sub-vectors. If needed, disable HNSW completely for multivectors and only use them for re-scoring

**Comment by AlterHoodie** [comment]
Ahh yes, that could be the problem. Will disable it and check it out.

**Comment by nauyan** [comment]
Hi @AlterHoodie , I hope you are doing well
have you checked it out yet? Did it resolve the issue?

**Comment by nauyan** [comment]
@timvisee @generall 
Is there any way, I can turn off hnsw_config for the whole collection? and then update the hnsw_config for only selected named_vectors that I need to index? 


currently I have tried hnsw_config=None and  hnsw_config=models.HnswConfigDiff() while creating collection but it is not working! I managed to change hnsw_config for selected vectors but I want to turn it off completely on the collection level. Is this possible or not?

**Comment by AlterHoodie** [comment]
Nope, I haven't tried disabling HNSW since my collection is now optimized(did take a few days). But I think you can set indexing_threshold=0 in the optimizer's config of the collection.
```from qdrant_client import QdrantClient, models

client = QdrantClient(url="http://localhost:6333")

client.update_collection(
    collection_name="{collection_name}",
    optimizer_config=models.OptimizersConfigDiff(indexing_threshold=0),
)
```
source : https://qdrant.tech/documentation/database-tutorials/bulk-upload/
