### ISSUE TITLE
[sharding] cluster status API

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#605]
**Is your feature request related to a problem? Please describe.**
There is no way to see what is the current cluster status is, except for logs.
It would be nice to have `/cluster` rest API with status information.

**Describe the solution you'd like**
Create a REST API endpoint `GET /cluster` which will return the following information:

- what machines are in the cluster, their URI, ports, status

**Describe alternatives you've considered**
Also implement version of this API for grpc, but I think it would be an overkill for now.

**Additional context**
debugging distributed deployment is expected to be a pain-point, so we need to make it as flawless as possible

**Comment by e-ivkov** [comment]
About their status - in particular raft state is interesting:
- term
- commit
- role of this peer in consensus (harder to get, but can be done from consensus module)

**Comment by e-ivkov** [comment]
Having a Prometheus endpoint might also help, but I am not sure - it might be an overkill at this stage

**Comment by generall** [comment]
> Having a Prometheus endpoint might also help, but I am not sure - it might be an overkill at this stage

It would be nice, but as a part of more global telemetry epic
