### ISSUE TITLE
[real-time index] keyword index on disk

### ISSUE THREAD

**Issue by IvanPleshkov** [qdrant/qdrant#616]
RocksDB supports searching by first symbols of string. We can use it for removing `HashMap` from `OnDiskMapIndex`. This feature will reduce RAM usage but will increase search performance. Field `point_to_values` contains searching by value. It is possible to build this map while loading from DB or keep it in a separate column family of RocksDB.
By this proposition, we can keep maps on RAM or use search in DB as index option.

**Comment by generall** [comment]
Released in https://github.com/qdrant/qdrant/releases/tag/v0.8.0
