### ISSUE TITLE
[distributed-deployment][refactor] Refactor consensus in ToC

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#639]
Currently `TableOfContent` is overwhelmed with consensus-related methods, which are not actually required in there.

Proposal:

Move consensus-related methods and structures out of `TableOfContent`, create a new entity to hold
```
    consensus_op_wal: Arc<std::sync::Mutex<Wal>>,
    raft_state: Arc<std::sync::Mutex<PersistentRaftState>>,
    propose_sender: Option<std::sync::Mutex<std::sync::mpsc::Sender<Vec<u8>>>>,
    on_consensus_op_apply: std::sync::Mutex<HashMap<ConsensusOperations, oneshot::Sender<Result<bool, StorageError>>>>,
    transport_channel_pool: Arc<TransportChannelPool>,
    this_peer_id: PeerId,
```

Make an independent initialization

**Comment by e-ivkov** [comment]
After this refactor we will no longer need to store `r#new`, but can return it as a bool in a tuple on state initialization - relates to https://github.com/qdrant/qdrant/pull/638
