### ISSUE TITLE
Is there an easy way to break out the indexing/search to embed it?

### ISSUE THREAD

**Issue by spullara** [qdrant/qdrant#670]
I'd like to use this in an iOS application but I don't want to run it as a service. I would like to embed it directly.

**Comment by generall** [comment]
Hi @spullara! Unfortunately no, Qdrant is not intended to be used as library. I would suggest to take a look at https://github.com/facebookresearch/faiss for this

**Comment by spullara** [comment]
Oh I have, I used several but none of them are incremental and don't include other facet type searching. Thanks though!
