### ISSUE TITLE
Delete collection does not work with Container instances on Azure

### ISSUE THREAD

**Issue by Teagum** [qdrant/qdrant#701]
I have a qdrant instance deployed on Microsoft Azure using their Container Instance service. In order to allow the container to persist data it is required to attach a file share to it. If I try to delete any existing collection, the client receives a 500 response code with the message

>  Service internal error: Can\'t delete collection mycoolcollection, error: Directory not empty (os error 39)

Obviously, on Azure file shares your are not allowed to remove non-empty directories. So, the command that qdrant uses internally  to delete a collection, crashes because it probably tries to delete the whole collection folder. 

## Current Behavior
Client Receives 500, collection is not deleted.

## Steps to Reproduce
Create any collection and then try to delete it
```
from qdrant_client import QudrantClient, models

host = "your.container.ip.address"
client = QdrantClient(host)

col_conf = models.CreateCollection(distance=models.Distance.DOT, vector_size=10)
client.http.collections_api.create_collection(collection_name='mycoolcollection',  create_collection=col_conf)

client.delete_collection('mycoolcollection')
```

## Expected Behavior
Instance should properly delete collection.

## Possible Solution
A possible solution could be to iterate over each file in the collection's directory and delete them one by one.

See [here](https://stackoverflow.com/questions/63887143/unable-to-delete-a-directory-in-azure) for a possible solution to delete non-empty folders in Azure file shares using external tools.

## Full error message

> UnexpectedResponse                        Traceback (most recent call last)
> Input In [41], in <cell line: 1>()
> ----> 1 client.delete_collection("mycoolcollection")
> 
> File ~/python3.10/site-packages/qdrant_client/qdrant_client.py:197, in QdrantClient.delete_collection(self, collection_name)
>     187 def delete_collection(self, collection_name: str):
>     188     """Removes collection and all it's data
>     189 
>     190     Args:
>    (...)
>     194         Operation result
>     195     """
> --> 197     return self.http.collections_api.delete_collection(collection_name)
> 
> File ~/python3.10/site-packages/qdrant_client/http/api/collections_api.py:464, in SyncCollectionsApi.delete_collection(self, collection_name)
>     457 def delete_collection(
>     458     self,
>     459     collection_name: str,
>     460 ) -> m.InlineResponse2001:
>     461     """
>     462     Drop collection and all associated data
>     463     """
> --> 464     return self._build_for_delete_collection(
>     465         collection_name=collection_name,
>     466     )
> 
> File ~/python3.10/site-packages/qdrant_client/http/api/collections_api.py:216, in _CollectionsApi._build_for_delete_collection(self, collection_name)
>     209 """
>     210 Drop collection and all associated data
>     211 """
>     212 path_params = {
>     213     "collection_name": str(collection_name),
>     214 }
> --> 216 return self.api_client.request(
>     217     type_=m.InlineResponse2001,
>     218     method="DELETE",
>     219     url="/collections/{collection_name}",
>     220     path_params=path_params,
>     221 )
> 
> File ~/python3.10/site-packages/qdrant_client/http/api_client.py:59, in ApiClient.request(self, type_, method, url, path_params, **kwargs)
>      57 url = (self.host or "") + url.format(**path_params)
>      58 request = Request(method, url, **kwargs)
> ---> 59 return self.send(request, type_)
> 
> File ~/python3.10/site-packages/qdrant_client/http/api_client.py:82, in ApiClient.send(self, request, type_)
>      80     except ValidationError as e:
>      81         raise ResponseHandlingException(e)
> ---> 82 raise UnexpectedResponse.for_response(response)
> 
> UnexpectedResponse: Unexpected Response: 500 (Internal Server Error)
> Raw response content:
> b'{"result":null,"status":{"error":"Service internal error: Can\'t delete collection mycoolcollection, error: Directory not empty (os error 39)"},"time":0.7265154}'

**Comment by generall** [comment]
Hi @Teagum, thanks for reporting! I will try to reproduce the issue.

> A possible solution could be to iterate over each file in the collection's directory and delete them one by one.

That is what we actually are doing. So I would suspect something more relater to the permissions
