### ISSUE TITLE
[distributed-deployment] try to remove sleeps during consensus establishing

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#702]
In tests, polling cluster API to find out the leader was used to determine if peer has successfully joined the network and proceed with adding another peer.

But it seems that a peer agrees on leader some time before network is able to process another AddPeer request. So `sleep` was added there. Ideally we want to be able to add peers asynchronously - not waiting for the previous to be added - so that no `sleep` or cluster status polling will be required.

**Comment by agourlay** [comment]
Trying to remove the `sleep` to have a full polling solution for the time being https://github.com/qdrant/qdrant/pull/720
