### ISSUE TITLE
Error while restarting the qdrant docker container. 

### ISSUE THREAD

**Issue by dingusagar** [qdrant/qdrant#721]
Qdrant was running in a docker container. we wanted to change the storage directory to a different volume. So we backed up the data folder and copied it to the new volume and restarted the container with the path to the new volume. 

But got this error on restarting. 

`thread 'main' panicked at 'Can't read WAL: InitWalError("Custom { kind: InvalidData, error: \"missing segment(s) containing wal entries 8250 to 8419\" }")', lib/collection/src/shard.rs:135:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Is it because while we copied the data, there were uncommitted transactions to the Write ahead Log? If so what is the ideal way to change the directory where qdrant data is present?

**Comment by generall** [comment]
Hi @dingusagar, copying data of running container is an unsafe operation - there are a lot of moving parts and while you are copying one file - others might be updated. One thing you could try, if it is possible, is to use btrfs - https://btrfs.wiki.kernel.org/index.php/Main_Page. It is a copy-on-write filesystem, which have a built-in snapshot capabilities.

From our side, we are working on snapshot API, it should allow us to create reliable snapshots by locking the collection during the copy. It should be available in one of the next releases.

**Comment by dingusagar** [comment]
Hi @generall 
Okay got it. 
Can I stop the container and copy the data and then restart the container with the new path? will stopping the container flush uncompleted writes to the disk gracefully so that there are no corrupt data on the disk?

**Comment by generall** [comment]
> will stopping the container flush uncompleted writes to the disk gracefully so that there are no corrupt data on the disk?

yes, that should work
