### ISSUE TITLE
Test Storage impl for ConsensusState

### ISSUE THREAD

**Issue by e-ivkov** [qdrant/qdrant#730]
As our lengthy investigation with https://github.com/qdrant/qdrant/pull/710 shows - we need to carefully check all the invariants by ourselves in our implementation. 

It is suggested to:
1. Abstract ToC functions needed for ConsensusState with a trait
2. Test Storage impl for ConsensusState (as close as possible to raft MemStorage tests https://github.com/tikv/raft-rs/blob/master/src/storage.rs#L523) 

We might use property testing libraries for better coverage - https://crates.io/crates/proptest

**Comment by agourlay** [comment]
We also do a bit of model testing by generating a sequence of storage operations and then verify that tikv's `MemStorage` and our storage yield the same raft log back.

**Comment by agourlay** [comment]
Exactly :+1:
