### ISSUE TITLE
[snapshot] segment-level snapshot

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#744]
An Internal function which would create a file from the existing segment:

- lock the segment for read
- flush everything
- make a copy & archive of all files into specified location
- implement function to restore segment from the archive

**Comment by agourlay** [comment]
> lock the segment for read

AFAIR this is accomplished by using a proxy wrapper segment right?

> make a copy & archive of all files into specified location

I assume this `location` is a local file system path provided by the user through a new HTTP internal API.

> implement function to restore segment from the archive

Same as above, introduce a new HTTP internal API that restores an archiving based a local file system path.

**Comment by generall** [comment]
> AFAIR this is accomplished by using a proxy wrapper segment right?

I think a simple read lock should be enough

> I assume this location is a local file system path provided by the user through a new HTTP internal API.

Thats a segment-level option, I don't think we should expose it to HTTP API. Internal gPRC maybe. HTTP should have collection-level snapshoting

**Comment by agourlay** [comment]
We cleared up some confusions I had offline.

This is a low level infrastructure that will be used by the users only though the future collection-level snapshot.

The expected outcome here is to be able to archive each segment directories using something like `tar`.

We need to keep the read lock in place for the whole during to avoid updates from happening but this should be only for a very short time hopefully.

**Comment by agourlay** [comment]
Not completely done.

Still missing a basic restore.

**Comment by agourlay** [comment]
Performing the snapshot of a proxy segment is more complicated than we initially thought https://github.com/qdrant/qdrant/pull/759#issuecomment-1169690313
