### ISSUE TITLE
[Question] is there any doc. to set distributed setup in kubernetes

### ISSUE THREAD

**Issue by sivaguru-pat** [qdrant/qdrant#749]
i have seen your distributed setup using raft.  i am curious to use this in kubernetes if you provide any info or doc regarding this will be helpfull 
thank you!

**Comment by generall** [comment]
@fabriziobonavita

**Comment by fabriziobonavita** [comment]
Hi @sivaguru-pat
we are currently adding support for distributed clusters to our helm chart.
I'll come back to you asap after we merged it and will provide you with an example.

**Comment by sivaguru-pat** [comment]
@fabriziobonavita thank you! can you tell me the approximate time for that

**Comment by sivaguru-pat** [comment]
@fabriziobonavita cool thanks

**Comment by fabriziobonavita** [comment]
@sivaguru-pat The last issues were resolved quickly and the distributed version should now be available in the latest helm release. 
For the installation in general - [Installation with Kubernetes](https://qdrant.tech/documentation/install/#with-kubernetes)
As of per default it is starting a single node, to activate cluster mode please refer to [Helm distributed setup](https://github.com/qdrant/qdrant-helm#distributed-setup)
Thank you and please let us know if we can help you any further

**Comment by sivaguru-pat** [comment]
hey @fabriziobonavita thank you, its works well!
