### ISSUE TITLE
[sharding] shard transfer - sending end

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#790]
**Is your feature request related to a problem? Please describe.**
We need a way for nodes to initiate shard transfer.

**Describe the solution you'd like**
A worker based transfer mechanism (Thread or Tokio).

1. The worker is responsible for transferring a local shard to a remote peer.
2. The worker handles the lifecycle of the local shard via a proxy shard
3. The worker respect the back pressure when pushing batches of records 
4. The worker handles network issues
5. The worker handles `too-many-changes` in proxy shard abort/restart
6. The worker survives a node restart

**Comment by generall** [comment]
What do we understand by

> The worker survives a node restart

?

I suggest to assume, that it should be enough to 
1. Do not loose any committed data
2. Do not corrupt the state of the storage
