### ISSUE TITLE
Geo Filtering by Polygon and/or MultiPolygon

### ISSUE THREAD

**Issue by zstatmanweil** [qdrant/qdrant#795]
Edit from Qdrant admin: this issue has been tackled as part of the GSoC 2023.
A description of the contribution can be found at the bottom https://github.com/qdrant/qdrant/issues/795#issuecomment-1705505987

**Is your feature request related to a problem? Please describe.**
It would be great to be able to geo filter by a region (aka polygon or multipolygon), in addition to by radius and bounding box. 

**Describe the solution you'd like**
I would love to be able to geo filter by a more complex geometry (polygon or multipolygon). A common format used for other geo API queries is the GeoJSON geometry format, the spec of which can be found here: https://datatracker.ietf.org/doc/html/rfc7946#section-3.1

**Describe alternatives you've considered**
We can use the existing geo filters by choosing a radius or bounding box that covers our region of interest and then do post-filtering after retrieving our points. This would be quite slow for large regions and qouls require us to managed our location data in another database. Alternatively, we can tag all vector payloads with regions, like countries for example, so we can use different fields to filter and not rely on the geo filter.

**Comment by do-me** [comment]
Additionally it would be nice to have (multi-)polygons added to the [Geo Payload](https://qdrant.tech/documentation/payload/#geo), so one could perform complex geospatial queries (and get a step closer to PostGIS).

For the moment, the only solution for heavy geospatial operations seems to be Postgres + PostGIS + [pgvector](https://github.com/pgvector/pgvector) (or any other vector search enabling plugin).

**Comment by agourlay** [comment]
Happy to report that Qdrant is participating in the [GSoC 2023](https://summerofcode.withgoogle.com/) and that this very issue will tackled as part of it.

https://qdrant.notion.site/Ideas-for-GSoC-at-Qdrant-99a10bcc68634d459de94408e38c233e

**Comment by zzzz-vincent** [comment]
This is for Google Summer of Code 2023. As for now, we have completed following tasks:
1. design doc to validate the concept and key functions([https://docs.google.com/document/d/156lYQPbOqDhVCmjomQXNgByaX9t919gV-bGNPfYgkdU/edit?usp=sharing](https://docs.google.com/document/d/156lYQPbOqDhVCmjomQXNgByaX9t919gV-bGNPfYgkdU/edit?usp=sharing&authuser=2))
2. merged #2139, which introduces GeoPolygon struct
3. merged #2162, which introduces `polygon_hashes` function to get geo hashes regarding to given polygon
4. merged #2188, which complete a initial version of Polygon Filter

Things in review:
1. #2315 which extend current implementation to support interiors. The PR scope is expanding as we have some back and forth for RPC/Rest API interface design.
2. [add geopolygon local mode and congruence test #272](https://github.com/qdrant/qdrant-client/pull/272) which is waiting for the first PR to be merged.
Other than that, nothing are left to complete this Issue.

Things to do:
1. Fill Polygon section in the [documentation](https://qdrant.tech/documentation/concepts/filtering/)

To notice that, multi-polygon is not explicitly implemented as it is able to be created as multiple polygon filters. We intentionally to do this to align with the level of consistency with other filter.

**Comment by agourlay** [comment]
Fixed in https://github.com/qdrant/qdrant/releases/tag/v1.6.0

**Comment by agourlay** [comment]
FYI https://qdrant.tech/articles/geo-polygon-filter-gsoc/
