### ISSUE TITLE
string identifier (string point IDs)

### ISSUE THREAD

**Issue by raulcarlomagno** [qdrant/qdrant#810]
As documentation says "Qdrant supports using both 64-bit unsigned integers and UUID as identifiers for points."

It is a good feature to have a string identifier, for example "JNO112", "PLASTICAR", "myStringId" or whatever

At least with 0.8.4 version and python client, when i try to send as id a list of string, it returns this error:

`UnexpectedResponse: Unexpected Response: 422 (Unprocessable Entity)
Raw response content:
b'{"result":null,"status":{"error":"Json deserialize error: data did not match any variant of untagged enum ExtendedPointId at line 1 column 26"},"time":0.0}'`

**Comment by generall** [comment]
Hi @raulcarlomagno, thanks for suggestion! Unfortunately we decided to not support arbitrary sting IDs for performance reasons. In our experience, if there is a string you want to associated with the vector - it is more flexible to store this string in the payload. You can use index payload for faster retrieving and use it in a similar way as IDs - by using scroll API. If you don't have explicit IDs in your collection, we recommend to simply generate random UUIDs. 

Please let me know if you think that in your use-case it is especially important to have string IDs

**Comment by ncoder** [comment]
please update the documentation to reflect this.

"ids" in the get indicate that strings are okay,

and the python types say:

```py
ExtendedPointId = Union[
    StrictInt,
    StrictStr,
]

```
