### ISSUE TITLE
Recreate channel to peer after several failures to send

### ISSUE THREAD

**Issue by e-ivkov** [qdrant/qdrant#832]
This is needed to account for the case where ip changed but domain stayed the same, so address needs to be resolved again.

**Comment by agourlay** [comment]
Been doing some investigations and now I wonder if this could be done via a contribution to either `hyper` or `tonic`.

This means the DNS re-lookup concern would not leak through our pooling abstraction.

Something like having an extra builder field at the tonic transport level to configure the underlying `hyper::client::connect::HttpConnector` in

https://github.com/hyperium/tonic/blob/9ea03c2c44ad6bf76e4141e6fb40870b9b30ab63/tonic/src/transport/channel/endpoint.rs#L302-L321

For instance I found this issue https://github.com/hyperium/hyper/issues/2605 mentioning refreshing connections.

**Comment by e-ivkov** [comment]
I think the process in this kind of big projects for new features is rather slow. Maybe we should try both? Use our own solution for now and file an issue to them?

**Comment by agourlay** [comment]
The approach sounds good to me :+1:

**Comment by e-ivkov** [comment]
Solved in:
1. https://github.com/qdrant/qdrant/pull/851/files
2. https://github.com/qdrant/qdrant/pull/845
