### ISSUE TITLE
Airflow Qdrant hook 

### ISSUE THREAD

**Issue by raulcarlomagno** [qdrant/qdrant#833]
Could be interesting in a future to have an Airflow Qdrant hook to be alined with airflow framework

**Comment by generall** [comment]
Contributions are welcome!

**Comment by kacperlukawski** [comment]
@raulcarlomagno, if you could please request that feature on Airlfow's Github, we can handle that together!

**Comment by raulcarlomagno** [comment]
> @raulcarlomagno, if you could please request that feature on Airlfow's Github, we can handle that together!

Done! @kacperlukawski 
https://github.com/apache/airflow/issues/25901
