### ISSUE TITLE
Point search too slow

### ISSUE THREAD

**Issue by YongWookHa** [qdrant/qdrant#834]
Hi, Thank you for this amazing project.
I am planning to get help in creating a vector search engine with qdrant.
I created a collection like below using docker container.

```python
url = f"{qdrant_host}/collections/{model_name}"
        data = {
            "name": model_name,
            "distance": "Cosine",
            "vector_size": 768
        }
        response = requests.put(url,
                                headers={'Content-Type':'application/json; charset=utf8'},
                                data=json.dumps(data))
```

I put points like below.

```python
batch = []
for payload, embedding in data:
  """
  payload = {
                  'short_str1': str,
                  'integer_format_date_1': integer,
                  'list_of_str1': list,
                  'integer_format_date_2': integer,
                  'short_str2': str,
                  'list_of_str2': list
              }
  """
  batch.append({
                                'id': cnt,
                                'payload': payload,
                                'vector': embedding
                            })
  cnt += 1

qd_url = f"{qdrant_host}/collections/{model_name}/points"
response = requests.put(qd_url,
                                        headers={'Content-Type':'application/json; charset=utf8'},
                                        data=json.dumps(data))
```

Loaded about 620,000 points. It takes about 10-20 seconds to search for a point as shown below.

```python
data = {
        'vector': embedding,
        'with_payload': True,
        'score_threshold': 0.8,
        'top': 10
    }
qd_url = f"{qdrant_host}/collections/{model_name}/points/search"
response = requests.post(qd_url,
                             headers={'Content-Type':'application/json; charset=utf8'},
                             data=json.dumps(data))
```

I think processing time increases linearly with the number of registered vectors. Is this normal?

**Comment by generall** [comment]
Hi @YongWookHa, please make sure that the indexes are created for your collection. You can use collection info API https://qdrant.github.io/qdrant/redoc/index.html#operation/get_collection to get he current status of the collection. If it is `green` - all indexes are ready.

**Comment by YongWookHa** [comment]
@generall , Thank you for the reply.

I checked the status and it is green. But I still get the result after 20sec~.
I want to know if I am doing something wrong.

**Comment by generall** [comment]
@YongWookHa that looks strange :thinking:
I might need some more information

- Do you use default configuration? 
- What machine are you using?
- Can you please provide an output of collection info API and some logs of requests?

It would also help if you could share a piece of data on which I could reproduce the issue.

**Comment by YongWookHa** [comment]
@generall 
Sorry for the late answer. 
- I used the default configuration
- I think the machine I'm using is fine. Here are short specs.
  ```
  Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
  128GiB System memory
  Nvidia RTX A6000 (x2)
  4TB SSD
  ...
   ```
- ```
  {
    "result": {
        "status": "green",
        "optimizer_status": "ok",
        "vectors_count": 12433923,
        "segments_count": 67,
        "disk_data_size": 0,
        "ram_data_size": 0,
        "config": {
            "params": {
                "vector_size": 768,
                "distance": "Cosine",
                "shard_number": 1
            },
            "hnsw_config": {
                "m": 16,
                "ef_construct": 100,
                "full_scan_threshold": 10000
            },
            "optimizer_config": {
                "deleted_threshold": 0.2,
                "vacuum_min_vector_number": 1000,
                "default_segment_number": 5,
                "max_segment_size": 200000,
                "memmap_threshold": 50000,
                "indexing_threshold": 20000,
                "payload_indexing_threshold": 10000,
                "flush_interval_sec": 1,
                "max_optimization_threads": 0
            },
            "wal_config": {
                "wal_capacity_mb": 32,
                "wal_segments_ahead": 0
            }
        },
        "payload_schema": {}
    },
    "status": "ok",
    "time": 0.002786322
}
  ```

**Comment by YongWookHa** [comment]
Now I got 12,433,923 vectors. And it takes 92 sec for a `collections/{model_name}/points/search` request.

**Comment by generall** [comment]
It looks like you are trying to use mmap vectors storage: `"memmap_threshold": 50000,` which was a default configuration for an old version. Can you please try to use latest version?

**Comment by YongWookHa** [comment]
@generall  
Okay I will set `"memmap_threshold": 50000` to `"memmap_threshold": 200000`.
And, I ran docker container with the command below.
```
docker run --rm -d \
    --name container_name \
    -p port:port \
    -v /data/qdrant:/qdrant/storage \
    qdrant/qdrant
```
And the `/data/qdrant` is a directory mounted in HDD not SSD.
Can this be a problem in this case?

**Comment by generall** [comment]
@YongWookHa , yeah, SSD is preferable, but once you are not using mmap it should be fine. Make sure you are using the latest version of the docker. Currently it's `0.8.4`. If it is still not enough, you cal also try to increase `"max_segment_size"`.

**Comment by YongWookHa** [comment]
How can I disable `mmap`?
I updated to the latest version of qdrant `0.8.4` and the default setting was still `"memmap_threshold": 200000`.
The collection was lost while updating. Because it's not backwards compatible.
It may take some time to load new points into the collection.
When done, we'll try sending a search query and leaving a comment.

**Comment by generall** [comment]
You can disable mmap by setting the `memmap_threshold` higher than the `max_segment_size`

**Comment by azayarni** [comment]
Hey, @YongWookHa is your issue solved now?

**Comment by YongWookHa** [comment]
My team and I are having trouble indexing new points. So retesting the settings is slow.
We think it will take a week to get back to this issue. Can you wait for us until then?

**Comment by azayarni** [comment]
Sure, no worries. Let us know.

**Comment by YongWookHa** [comment]
Hello, @azayarni 
Finally indexed all the points and tried searching with the new settings.

```
max_segment_size: 800000
memmap_threshold: 800000
```

The processing time is successfully reduced. It takes about 1 second to search for 15 million points.

Thank you for your help! Have a good day.
