### ISSUE TITLE
upload_collection error

### ISSUE THREAD

**Issue by microvnn** [qdrant/qdrant#857]
client.upload_collection(
    collection_name=collection_name,
    vectors=vectors,
    payload=payloads,
    ids=ids,
    batch_size=64
)

"Service internal error: 1 out of 5 shards failed to apply operation. First error captured: Service internal error: Tonic status error: The operation was cancelled"

**Comment by generall** [comment]
Hi @microvnn, can you please describe a bit more context for the issue?
- What version are you using?
- What is your setup?
- Are there any error logs on the server side related to the issue?
- Is this issue stable? Meaning that if it is possible to reproduce it, or it happens randomly?

**Comment by generall** [comment]
Also, there is a number of stability improvements in a new version https://github.com/qdrant/qdrant/releases/tag/v0.8.5

**Comment by microvnn** [comment]
I look problems  fixed in version "qdrant/qdrant • Updated 2 hours ago". i think version is [v0.8.5]
Thank you for support .
