### ISSUE TITLE
Search by ids

### ISSUE THREAD

**Issue by keotic** [qdrant/qdrant#859]
**Is your feature request related to a problem? Please describe.**
In some scenarios the client may have an array of vectors / records ids and not the vectors themselves.
A nearest neighbours search by ids instead of vectors will prevent the round trip of fetching the vectors and then query by them.
( consider a query of 5000 ids on a vectors space of 1024 fp32, the payload round trip is big) 

**Describe the solution you'd like**
Get top k vectors ids by search query by ids

**Comment by generall** [comment]
Hi @keotic, take a look at https://qdrant.tech/documentation/search/#recommendation-api - it might be the thing you are looking for

**Comment by keotic** [comment]
@generall 
Thanks for the reply, according to the recommend API, the ids vectors are merged ( and a negative vectors are also given)
The request is for a regular ANN search / batch search with ids instead vectors

**Comment by generall** [comment]
If you are specifying just one ID - it will be similar to search. If you want to search for multiple stored vectors - you would need, indeed, a batch API, which is currently under the development

**Comment by raulcarlomagno** [comment]
> **Is your feature request related to a problem? Please describe.** In some scenarios the client may have an array of vectors / records ids and not the vectors themselves. A nearest neighbours search by ids instead of vectors will prevent the round trip of fetching the vectors and then query by them. ( consider a query of 5000 ids on a vectors space of 1024 fp32, the payload round trip is big)
> 
> **Describe the solution you'd like** Get top k vectors ids by search query by ids

i think you need something like the retrieve() method

https://github.com/qdrant/qdrant_client/blob/master/qdrant_client/qdrant_client.py#L651
