### ISSUE TITLE
[filter] Substring payload filtering

### ISSUE THREAD

**Issue by qeumo** [qdrant/qdrant#871]
Hi everyone
I was wondering if Qdrant has ability to filter payload fields by substring besides full match filter like MatchValue
If not then can it store payload data in any database like PostgreSQL?

**Comment by generall** [comment]
Hi @qeumo, currently it is only possible to do a full match. We have a plan to extend it to the keyword-based filter, similar to full-text search. Can you please elaborate on your use-case, where do you need to use substring filters?

**Comment by qeumo** [comment]
The use-case is to implement real time text search based on substring. Search field should suggest relevant queries for user when he starts to type there. 
Do you plan to implement such feature in near future?

**Comment by generall** [comment]
This functionality is better solved m specialized full-text search engines. For example https://github.com/meilisearch/meilisearch
