### ISSUE TITLE
Request: Support explicit schema changes

### ISSUE THREAD

**Issue by tlack** [qdrant/qdrant#92]
**Is your feature request related to a problem? Please describe.**

As collections in Qdrant grow, it is sometimes necessary to add a new column/field to an existing collection's payload.

Right now this can be done by manually creating a new record with the new column added, including the `type` flag.

This works OK but it would be good if there was a way to change the schema without upserting a new record.

This feature is especially important when using a connector library that features migrations.

**Describe the solution you'd like**

Ideally:

```GET collections/mycoll/schema```
..would return the current schema (like we get from the `payload_schema` fields from the  `POST collections/mycoll` endpoint), and..

```POST collections/mycoll/schema``` 
..would allow us to add new fields.

On a secondary level, it would be killer if we could fill in a default for that new field in all existing point payloads.

**Additional context**

(Discussed 8/19/2021 on Qdrant Telegram group)

**Comment by generall** [comment]
Schema is no longer required, payload index type could be dynamically specified for each field. released in https://github.com/qdrant/qdrant/releases/tag/v0.7.0
