### ISSUE TITLE
Change in `max_request_size_mb` not reflected

### ISSUE THREAD

**Issue by MatejBabis** [qdrant/qdrant#935]
Editing the value of `max_request_size_mb` in `custom_config.yaml` does not change the behaviour.

## Current Behavior
I am experimenting with increasing request size to allow for upserting a larger set of points at once. Changing the maximum value in `custom_config.yaml` does not seem to be reflected in the container and the upsert fails.

## Detailed Description
In `custom_config.yaml`:
```
debug: true
log_level: DEBUG
...
service:
  # Maximum size of POST data in a single request in megabytes
  max_request_size_mb: 128
  ...
```
Run qdrant with the changed config:
```
$ docker run -p 6333:6333 \
    -v $(pwd)/qdrant/qdrant_storage:/qdrant/storage \
    -v $(pwd)/qdrant/custom_config.yaml:/qdrant/config/production.yaml \
    qdrant/qdrant
```
When trying to batch upsert a larger set of points (~64MB): ...
```
    client.upsert(
        collection_name="some_collection",
        points=models.Batch(
            ids=list_of_ids,
            vectors=list_of_vectors,
            payloads=list_of_payloads
        )
    )
```
...the operation never completes - hangs:
```
[2022-08-10T11:53:10.739Z DEBUG actix_web::types::json] Failed to deserialize Json from payload. Request path: /collections/some_collection/points
[2022-08-10T11:53:10.740Z DEBUG actix_web::middleware::logger] Error in response: OverflowKnownLength { length: 65991429, limit: 33554432 }
[2022-08-10T11:53:10.740Z INFO  actix_web::middleware::logger] 172.17.0.1 "PUT /collections/some_collection/points?wait=true HTTP/1.1" 400 125 "-" "-" 0.005954
```
Clearly, the limit is set still to 32MB. When running with a smaller set of points, the upsert call completes succesfully:
```
[2022-08-10T11:55:29.784Z INFO  actix_web::middleware::logger] 172.17.0.1 "PUT /collections/some_collection/points?wait=true HTTP/1.1" 200 90 "-" "-" 5.495906
```
## Expected Behavior
I can see that the config is loaded, given that I am getting debug logs. It seems that the value of `max_request_size_mb` is not handled properly. Based on the documentation, I would expect that this is how one would go on with increasing the size of the request.

If there is a workaround I can use (beside doing several upsert calls), please let me know. Thanks!

**Comment by agourlay** [comment]
Interesting finding :+1: 

It looks like the limit is hardcoded to 32MB

https://github.com/qdrant/qdrant/blob/fd5bb6be1cf221ed7973b065d1e4600fbccf1b8b/src/actix/mod.rs#L82-L84

We need to propagate properly `max_request_size_mb`

**Comment by generall** [comment]
Hi @MatejBabis thanks for pointing out, will fix soon! One thing you could do it to use gRPC interface, which does not have this limitation. Although, I would not recommend to send updates in this large queries. It might be better to use smaller batches in parallel - performance wise.
