### ISSUE TITLE
Any configs to optimise storage ? 

### ISSUE THREAD

**Issue by dingusagar** [qdrant/qdrant#962]
Have been using qdrant in production for some time. Looks like the storage space allocated to qdrant is growing at a good pace.
Wanted to check if there are any optimizations that can be configured to reduce the storage.

For eg, when I looked into the collection folder,  I could see a segments folder and wal folder. Does it make sense to have some kind of log rotation/compaction for wal?  

Any other guidelines for optimizing the overall disk space required by qdrant?

**Comment by generall** [comment]
Hi @dingusagar! Can you please list which files take the most space?

**Comment by dingusagar** [comment]
Hi @generall,

these are the file sizes for a few of the collections. we have many such collections.
```
du -sh image_embeddings__1/*

4.0K	image_embeddings__1/config.json
570M	image_embeddings__1/segments
97M	image_embeddings__1/wal


4.0K	text_embeddings__1/config.json
1.5G	text_embeddings__1/segments
97M	text_embeddings__1/wal

4.0K	text_embeddings__4/config.json
880M	text_embeddings__4/segments
65M	text_embeddings__4/wal


4.0K	text_embeddings__3/config.json
1.4G	text_embeddings__3/segments
97M	text_embeddings__3/wal
```

**Comment by generall** [comment]
That looks like an old version of qdrant, in the recent updates we fixed some log rotation-related isssues
