### ISSUE TITLE
Number of results

### ISSUE THREAD

**Issue by Mokto** [qdrant/qdrant#965]
**Is your feature request related to a problem? Please describe.**
It's always useful, when using score_threshold, to anticipate how many results there will be.

**Describe the solution you'd like**
Add an option to return the number of results (or at least an estimate or a max vlaue, I understand there might be some performances impact with HNSW)

Thanks!

**Comment by generall** [comment]
Hi!

We received this request multiple times, but unfortunately didn't find a suitable technical solution for the problem:

- Vector index doesn't provide any information about the count of records by any other means except for actually retrieving the vectors. It makes counting operation almost as expensive as the search itself, moreover, search with very high limit.
- Even if we will use exact counting to the `score_threshold`, the number of points may increase by order of magnitude with just a small change of the score_threshold parameter. 

The combination of this 2 factors makes this function unstable and potentially dangerous for production use case.

We are happy to reconsider as soon as there will be a way to provide number estimation avoiding the actual retrieval of the vectors
