### ISSUE TITLE
Change distance of existing collection

### ISSUE THREAD

**Issue by Teagum** [qdrant/qdrant#979]
I try to change the distance of a existing collection with

```
PUT /collections/{existing_collection}

{
    "name": "{existing_collection}",
    "distance": "new_distance",
    "vector_size": 300
}
```
This returns the following error:

```
{
'result': None,
 'status': {'error': 'Wrong input: Collection `{existing_collection}` already exists!'},
 'time': 1.271e-05
}
```

The [documentation](https://qdrant.tech/documentation/collections/#collections) however says that:

> In addition to metrics and vector size, each collection uses its own set of parameters that controls collection optimization, index construction, and vacuum. These settings can be changed at any time by a corresponding request.

Is there a way to change the distance of an existing collection?

**Comment by generall** [comment]
Hi @Teagum, no, distance can not be changed. There is a set of parameters which can be changed, it is specified in collection update API - https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/update_collection
