### ISSUE TITLE
[replication] `RemoteShard` should manage several remote peers

### ISSUE THREAD

**Issue by e-ivkov** [qdrant/qdrant#993]
This will be a big change for the remote peer logic so let's address it in a separate PR?

_Originally posted by @e-ivkov in https://github.com/qdrant/qdrant/pull/986#discussion_r963605824_

Updates and queries should go to all remote replicas - this is planned to be managed inside the `RemoteShard` struct which should contain all ids of the peers which contain a replica of this shard. On top of `RemoteShard` these updates will be aggregated together with a local replica updates inside of the `ReplicaSet` struct.

**Comment by generall** [comment]
pls update the task

**Comment by agourlay** [comment]
We have discussed the design of `ReplicaSet` and decided to follow a different design.

The initial design's goal was to optimize the performance by not having to perform the score conversion logic on each canceled replica search within the `RemoteShard`.

We will instead go with a more intuitive approach where the `ReplicaSet` holds a set of `RemoteShard` and is responsible for the coordination and cancellation of outbound queries.

In that case we always perform the score conversion even on discarded searches result but we assume the cost is negligible for the time being.
